### ISSUE TITLE
incorrect sql while deleting entity from collection, which is populated with LoadStrategy.JOINED

### ISSUE THREAD

**Issue by zarv1k** [mikro-orm/mikro-orm#1041]
**Describe the bug**
When I try to remove one entity from collection, which is populated with `LoadStratedy.JOINED` strategy, MikroORM produces insert statement with already existing rows into pivot table, instead of producing delete statement.

**Stack trace**
```
[query] begin
[query] insert into "user_apps" ("user_id", "app_id") values ('80a1eee9-df22-4b47-bc38-fc5cb6be1c79', 1) [took 4 ms]
[query] rollback
(node:90332) UnhandledPromiseRejectionWarning: UniqueConstraintViolationException: insert into "user_apps" ("user_id", "app_id") values ('80a1eee9-df22-4b47-bc38-fc5cb6be1c79', 1) - duplicate key value violates unique constraint "user_apps_pkey"
    at PostgreSqlExceptionConverter.convertException (/app/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:28:24)
    at PostgreSqlDriver.convertException (/app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:168:54)
    at /app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:172:24
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async PostgreSqlDriver.nativeInsertMany (/app/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:192:19)
    at async PostgreSqlDriver.updateCollectionDiff (/app/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:446:13)
    at async UnitOfWork.persistToDatabase (/app/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:439:13)

previous error: insert into "user_apps" ("user_id", "app_id") values ('80a1eee9-df22-4b47-bc38-fc5cb6be1c79', 1) - duplicate key value violates unique constraint "user_apps_pkey"
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
(node:90332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:90332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**To Reproduce**

```
@Entity()
export class App {

  @PrimaryKey()
  public id!: number;

  @ManyToMany('User', 'apps')
  public users = new Collection<User>(this);

}

@Entity()
export class User {

  @PrimaryKey({ type: 'uuid', defaultRaw: 'uuid_generate_v4()' })
  public id!: string;

  @ManyToMany(() => App, a => a.users, { owner: true })
  public apps = new Collection<App>(this);

}

...

const em = orm.em;
const repository = em.getRepository(User);
const user = await repository.findOne({ id }, { populate: { apps: LoadStrategy.JOINED } });
const app = user?.apps.getItems().find(i => i.id === 3);
user?.apps.remove(app!);
repository.flush()
```

**Expected behavior**
delete statement executes

**Additional context**
There is no issue if the collection is populated using `LoadStrategy.SELECT_IN`

**Versions**

| Dependency | Version |
| - | - |
| node | v12.14.1 |
| typescript | 4.0.3 |
| mikro-orm | 4.2.3 |
| your-driver | postgresql |

**Comment by zarv1k** [comment]
I've prepared [test](https://github.com/zarv1k/mikro-orm/blob/df152319a03e5023a7c078756dbf3c83b381c05e/tests/issues/GH1041.test.ts) reproducing the issue.
