### ISSUE TITLE
Hooks not working properly when using Entity Schema

### ISSUE THREAD

**Issue by bahdcoder** [mikro-orm/mikro-orm#1072]
**Describe the bug**
I defined an entity using the Entity Schema:

```js
const CustomerSchema = {
    ...,
   hooks: {
      onInit: [console.log]
   }
}

module.exports = new EntitySchema(CustomerSchema)
```

When I create a new customer with `em.create('Customer', {...})`, I get the following error below:

**Stack trace**
```
TypeError: listener[1][listener[0]] is not a function
    at /Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/core/events/EventManager.js:37:41
    at Array.forEach (<anonymous>)
    at EventManager.dispatchEvent (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/core/events/EventManager.js:35:30)
    at EntityFactory.create (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/core/entity/EntityFactory.js:40:31)
    at SqlEntityManager.create (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/core/EntityManager.js:330:40)
    at Auth.register (/Users/bahdcoder/Projects/tensei/packages/auth/build/index.js:42:34)
    at asyncUtilWrap (/Users/bahdcoder/Projects/tensei/node_modules/express-async-handler/index.js:3:20)
    at Layer.handle [as handle_request] (/Users/bahdcoder/Projects/tensei/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/bahdcoder/Projects/tensei/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/bahdcoder/Projects/tensei/node_modules/express/lib/router/route.js:112:3)
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an entity using entity schema
2. Add a hook
3. Invoke the hook

**Expected behavior**
Hooks should be dispatched and handled correctly when creating entities using entity schema

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | v12.17.0 |
| typescript | ^3.9.5 |
| mikro-orm | ^4.2.0 |
| your-driver | mysql |

**Comment by B4nan** [comment]
Hooks in metadata are method names, not function references.

https://github.com/mikro-orm/mikro-orm/blob/master/tests/entities-js/Author3.js#L113
