### ISSUE TITLE
`SchemaGenerator.updateSchema()` recreating indexes

### ISSUE THREAD

**Issue by bahdcoder** [mikro-orm/mikro-orm#1078]
**Describe the bug**
I ran create schema on a database, then immediately ran the update schema without making any change to the entities, and it attempted to drop all existing indexes even though I turned on safe mode. 

**Stack trace**
```sql
alter table `roles_permissions` modify `roles_id` int(11) unsigned, modify `permissions_id` int(11) unsigned;
alter table `roles_permissions` drop index `roles_permissions_roles_id_index`;
alter table `roles_permissions` add index `roles_permissions_roles_id_index`(`roles_id`);
alter table `roles_permissions` drop index `roles_permissions_permissions_id_index`;
```

**To Reproduce**
1. Create two entities: Role and Permission with a many to many association. 
2. Run create schema
3. Run update schema
4. Notice update schema tries to remove and recreate indexes.

**Expected behavior**
Update schema should not drop indexes existing in database because this will make queries slow for some time.

**Versions**

| Dependency | Version |
| - | - |
| node | v12.17.0 |
| typescript | ^3.9.5 |
| mikro-orm | ^4.2.0 |
| your-driver | mysql v8.0.22 |

**Comment by bahdcoder** [comment]
Please also notice update schema tries to modify the foreign keys on a pivot table for a many to many relationship even though there was no change to the properties of either entities.

**Comment by B4nan** [comment]
Safe mode have no effect here, it is safe because you will never loose data, that's it, nothing more. 

**I need a full reproduction for issues like this**, and please always upgrade to the latest version before reporting anything, there was a lot of bugfixes in `v4.3` (including something mysql8 related).

The problem will be most probably mysql8, there are quite a lot of small BC in how information schema tables work.

**Comment by bahdcoder** [comment]
@B4nan I can confirm that upgrading to 4.3 fixes the issues mentioned in this PR. Thank you very much for your hard work and timely response. 

I experience a new issue 


```js
TypeError: calc.discoverProperty is not a function
    at SchemaGenerator.getOrderedMetadata (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/mysql-base/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:472:22)
    at SchemaGenerator.getUpdateSchemaSQL (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/mysql-base/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:80:31)
    at SchemaGenerator.updateSchema (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/mysql-base/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:76:32)
    at Migrator.init (/Users/bahdcoder/Projects/tensei/packages/core/build/database/Migrator.js:14:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Database.init (/Users/bahdcoder/Projects/tensei/packages/core/build/database/index.js:43:9)
    at async Tensei.bootDatabase (/Users/bahdcoder/Projects/tensei/packages/core/build/Tensei.js:252:32)
    at async Tensei.registerDatabase (/Users/bahdcoder/Projects/tensei/packages/core/build/Tensei.js:260:9)
    at async Tensei.register (/Users/bahdcoder/Projects/tensei/packages/core/build/Tensei.js:163:9)
    at async Tensei.start (/Users/bahdcoder/Projects/tensei/packages/core/build/Tensei.js:178:13)
```

Can you please tell what this might be about ? I checked and I'm on the latest. Thanks.
