### ISSUE TITLE
transaction with nested insert

### ISSUE THREAD

**Issue by sptGabriel** [mikro-orm/mikro-orm#1080]
Hello I'm trying to do 3 transactions in a begin, where one depends on the insertion of the other, that is, when inserting a product_instance I need to create a record in the departament_has_equipaments table
but for some reason this is not working:

```
public create = async (
    instance: ProductInstance,
  ): Promise<ProductInstance> => {
    if (!(instance instanceof ProductInstance))
      throw new Error(`Invalid Data Type`);
    await this.em.begin();
    try {
      await this.em.persist(instance);
      const stockQueryBuilder = this.em.createQueryBuilder(ProductStocks);
      await stockQueryBuilder
        .update({ quantity: stockQueryBuilder.raw(`quantity - 1`) })
        .where({ id:instance.stock.id,product:instance.product.id })
      if (instance.departament) {
      await this.em
          .createQueryBuilder('departament_has_equipaments')
          .insert({
            departament_id: instance.departament.id,
            equipament_id: instance.id,
          }).getResult().catch((err)=> {console.log(err)})
      }
      await this.em.commit();
      return instance;
    } catch (e) {
      console.log(e);
      await this.em.rollback();
      throw e;
    }
  };
```
stacktrace:

```
[query] begin
[query] insert into "departament_has_equipaments" ("departament_id", "equipament_id") values ('17b0d12b-f3d6-4d13-9dc1-1f15ca8ae0bc', 'caa1733e-885c-4fd2-9e43-69a98fbd2054') [took 3 ms]
error: insert into "departament_has_equipaments" ("departament_id", "equipament_id") values ('17b0d12b-f3d6-4d13-9dc1-1f15ca8ae0bc', 'caa1733e-885c-4fd2-9e43-69a98fbd2054') - insert or update on table "departament_has_equipaments" violates foreign key constraint "departament_has_equipaments_equipament_id_foreign"
    at Parser.parseErrorMessage (C:\Users\spiriT\Documents\emasa\node_modules\pg-protocol\src\parser.ts:357:11)
    at Parser.handlePacket (C:\Users\spiriT\Documents\emasa\node_modules\pg-protocol\src\parser.ts:186:21)
    at Parser.parse (C:\Users\spiriT\Documents\emasa\node_modules\pg-protocol\src\parser.ts:101:30)
    at Socket.<anonymous> (C:\Users\spiriT\Documents\emasa\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
    at Socket.Readable.push (_stream_readable.js:221:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:129:14) {
  length: 401,
  severity: 'ERROR',
  code: '23503',
  detail: 'Key (equipament_id)=(caa1733e-885c-4fd2-9e43-69a98fbd2054) is not present in table "product_instances".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'departament_has_equipaments',
  column: undefined,
  dataType: undefined,
  constraint: 'departament_has_equipaments_equipament_id_foreign',
  file: 'ri_triggers.c',
  line: '2479',
  routine: 'ri_ReportViolation'
}
[query] insert into "product_instances" ("created_at", "employee_id", "id", "patrimony_code", "product_id", "serial_number", "stock_id", "type", "updated_at") values ('2020-11-15T13:53:54.903Z', 'f4f99256-e842-4932-b9ff-205cc73c1fbf', 'caa1733e-885c-4fd2-9e43-69a98fbd2054', 'aa', '6b757829-f93b-446c-99ce-45ba6dc01fa2', 'x', 'b41076bf-8283-45b6-842d-bcca904a738d', 'equipament', '2020-11-15T13:53:54.903Z') [took 2 ms]
DriverException: insert into "product_instances" ("created_at", "employee_id", "id", "patrimony_code", "product_id", "serial_number", "stock_id", "type", "updated_at") values ('2020-11-15T13:53:54.903Z', 'f4f99256-e842-4932-b9ff-205cc73c1fbf', 'caa1733e-885c-4fd2-9e43-69a98fbd2054', 'aa', '6b757829-f93b-446c-99ce-45ba6dc01fa2', 'x', 'b41076bf-8283-45b6-842d-bcca904a738d', 'equipament', '2020-11-15T13:53:54.903Z') - current transaction is aborted, commands ignored until end of transaction block   
    at PostgreSqlExceptionConverter.convertException (C:\Users\spiriT\Documents\emasa\node_modules\@mikro-orm\core\platforms\ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException (C:\Users\spiriT\Documents\emasa\node_modules\@mikro-orm\postgresql\PostgreSqlExceptionConverter.js:40:22)        
    at PostgreSqlDriver.convertException (C:\Users\spiriT\Documents\emasa\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:168:54)
    at C:\Users\spiriT\Documents\emasa\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:172:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at PostgreSqlDriver.nativeInsert (C:\Users\spiriT\Documents\emasa\node_modules\@mikro-orm\knex\AbstractSqlDriver.js:145:21)
    at ChangeSetPersister.persistNewEntity (C:\Users\spiriT\Documents\emasa\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:55:21)
    at ChangeSetPersister.executeInserts (C:\Users\spiriT\Documents\emasa\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:24:13)
    at UnitOfWork.commitCreateChangeSets (C:\Users\spiriT\Documents\emasa\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:455:9)
    at UnitOfWork.persistToDatabase (C:\Users\spiriT\Documents\emasa\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:417:13)
    at UnitOfWork.commit (C:\Users\spiriT\Documents\emasa\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:176:17)
    at SqlEntityManager.flush (C:\Users\spiriT\Documents\emasa\node_modules\@mikro-orm\core\EntityManager.js:452:9)
    at SqlEntityManager.commit (C:\Users\spiriT\Documents\emasa\node_modules\@mikro-orm\core\EntityManager.js:239:9)
    at ProductInstanceRepository.create (C:\Users\spiriT\Documents\emasa\src\modules\products\persistence\instanceRepositoryImpl.ts:40:7)
    at AssignProductUseCase.execute (C:\Users\spiriT\Documents\emasa\src\modules\products\application\useCases\assignProduct\assignProduct.ts:99:29)
    at ProductsController.assignProduct (C:\Users\spiriT\Documents\emasa\src\modules\products\ui\products.controller.ts:33:22)

previous error: insert into "product_instances" ("created_at", "employee_id", "id", "patrimony_code", "product_id", "serial_number", "stock_id", "type", "updated_at") 
values ('2020-11-15T13:53:54.903Z', 'f4f99256-e842-4932-b9ff-205cc73c1fbf', 'caa1733e-885c-4fd2-9e43-69a98fbd2054', 'aa', '6b757829-f93b-446c-99ce-45ba6dc01fa2', 'x', 
'b41076bf-8283-45b6-842d-bcca904a738d', 'equipament', '2020-11-15T13:53:54.903Z') - current transaction is aborted, commands ignored until end of transaction block    
    at Parser.parseErrorMessage (C:\Users\spiriT\Documents\emasa\node_modules\pg-protocol\src\parser.ts:357:11)
    at Parser.handlePacket (C:\Users\spiriT\Documents\emasa\node_modules\pg-protocol\src\parser.ts:186:21)
    at Parser.parse (C:\Users\spiriT\Documents\emasa\node_modules\pg-protocol\src\parser.ts:101:30)
    at Socket.<anonymous> (C:\Users\spiriT\Documents\emasa\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
    at Socket.Readable.push (_stream_readable.js:221:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:129:14) {
  length: 144,
  severity: 'ERROR',
  code: '25P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1105',
  routine: 'exec_simple_query'
}
[query] rollback
```

my entities:

```
@Entity({ tableName: 'product_instances' })
export class ProductInstance {
  @PrimaryKey()
  public readonly id: string;
  @PrimaryKey()
  public readonly serial_number: string;
  [PrimaryKeyType]: [string, string];
  @Property()
  public patrimony_code?: string;
  @Enum()
  public type: ProductTypes;
  @ManyToOne(() => Product, { fieldName: 'product_id' })
  public product!: Product;
  @ManyToOne(() => ProductStocks, { fieldName: 'stock_id' })
  public stock!: ProductStocks;
  @ManyToOne(() => Employee, { fieldName: 'employee_id' })
  public employee!: Employee;
  @Property({persist:false})
  public departament: Departament | null;
  @ManyToOne({ entity: () => ProductInstance, nullable:true })
  public parent!: ProductInstance | null;
  @OneToMany({
    entity: () => ProductInstance,
    mappedBy: 'parent',
    orphanRemoval: true,
  })
  public parents = new Collection<ProductInstance>(this);
  @Property()
  public created_at = new Date();
  @Property({ onUpdate: () => new Date() })
  public updated_at = new Date();
  @Property()
  public deleted_at?: Date;

  constructor(container: instanceContainer) {
    this.id = container.id ? container.id : v4();
    this.serial_number = container.serial_number;
    this.patrimony_code = container.patrimony_code;
    this.type = container.type;
    this.employee = container.employee;
    this.stock = container.stock;
    this.product = container.product;
    this.departament = container.departament
    this.parent = container.parent
  }

  static build = (container: instanceContainer): ProductInstance => {
    return new ProductInstance(container);
  };
}
```
it seems to me that inserting departmentament_has_equipaments always comes before inserting product_instances

**Comment by B4nan** [comment]
This is your problem:

```ts
await this.em.persist(instance);
```

`persist` is synchronous method that marks the entity, you need to `flush` to make it actually saved in your database.

**Comment by sptGabriel** [comment]
> Isso é problema seu:
> 
> ```ts
> aguarde  isso . em . persist ( instância ) ;
> ```
> 
> `persist`é o método síncrono que marca a entidade, você precisa `flush`para torná-la realmente salva em seu banco de dados.

but if any of the transactions fail it will not give an exact roolback?

**Comment by B4nan** [comment]
I dont follow, `em.persist` won't do anything, just mark it for the future `flush` call

**Comment by sptGabriel** [comment]
I understand, but if I use:

     await this.em.persist (instance) .flush ();

and one of my next failed transactions will not roolback my em.persist.flush?

**Comment by B4nan** [comment]
You are inside a transactions as you previously called `em.begin()` so the `flush` will rollback the whole tx if it fails.

**Comment by sptGabriel** [comment]
> Você está dentro de uma transação como a chamou anteriormente, `em.begin()`então o `flush`irá reverter todo o tx se ele falhar.

on this:

```
      const stockQueryBuilder = await this.em.createQueryBuilder(ProductStocks);
      await stockQueryBuilder
        .update({ quantity: stockQueryBuilder.raw(`quantity - 1`) })
        .where({ id:instance.stock.id,product:instance.product.id })
```

get this:
`[query] update "product_stocks" set "supply_id" = '1cd0d0ff-7694-479b-99a4-395128182c68', "product_id" = '6b757829-f93b-446c-99ce-45ba6dc01fa2', "updated_at" = '2020-11-15T15:58:18.106Z' where "id" = 'b41076bf-8283-45b6-842d-bcca904a738d' [took 2 ms]`

but it doesn't decrease the value, but now if I use getSingleResult (), the value updates.
I can't understand why

**Comment by B4nan** [comment]
You can't just await the QB, you need to use `qb.execute()` (for insert/update). `qb.getResult()` (and its variants) is for mapping back the results to entities.
