### ISSUE TITLE
 relation as pk and smart conditions

### ISSUE THREAD

**Issue by sptGabriel** [mikro-orm/mikro-orm#1095]
Hello I have 3 entities, components, equipments, an equipment is a component that can have one or more components.
so I created an equipments_has_components table:
**Equipment:**
```
@Entity({ tableName: 'equipments' })
export class EquipmentInstance {
  @Unique({ name: 'patrimony' })
  @Property()
  public patrimony_code: string;
  @ManyToOne({ entity: () => Employee, fieldName: 'employee_id' })
  public employee!: Employee;
  @OneToOne(() => ComponentInstance, component => component.equipment, {
    owner: true,
    primary:true,
    cascade: [],
    fieldName: 'equipment_id',
  })
  public component: ComponentInstance;
  @OneToMany(() => EquipmentHasComponents, equips => equips.equipment)
  public components = new Collection<EquipmentHasComponents>(this);
  @Property()
  public createdAt = new Date();
  @Property({ onUpdate: () => new Date() })
  public updatedAt = new Date();
  @Property()
  public deletedAt?: Date;
}
```
**Components**

```
@Entity({ tableName: 'components' })
export class ComponentInstance {
  @PrimaryKey()
  public readonly id: string;
  @Unique({ name: 'component' })
  @Property()
  public readonly serial_number: string;
  @ManyToOne(() => Product, { fieldName: 'product_id' })
  public product!: Product;
  @ManyToOne(() => ProductStocks, { fieldName: 'stock_id' })
  public stock!: ProductStocks;
  @OneToOne({
    entity: () => EquipmentInstance,
    cascade: [],
    mappedBy: 'component'
  })
  public equipment: EquipmentInstance;
  @OneToMany(() => EquipmentHasComponents, components => components.component)
  public equipments = new Collection<EquipmentHasComponents>(this);
  @Property({ persist: false })
  departament?: Departament;
  @Property()
  public created_at = new Date();
  @Property({ onUpdate: () => new Date() })
  public updated_at = new Date();
  @Property()
  public deleted_at?: Date;
}
```

**Equipments_has_Components**:

```
@Entity({ tableName: 'equipment_has_components' })
export class EquipmentHasComponents {
  @ManyToOne({
    entity: () => EquipmentInstance,
    fieldName: 'equipment_id',
    primary: true,
  })
  public equipment!: EquipmentInstance;
  @ManyToOne({
    entity: () => ComponentInstance,
    fieldName: 'component_id',
    primary: true,
  })
  public component!: ComponentInstance;
  [PrimaryKeyType]: [EquipmentInstance, ComponentInstance];
  @Property()
  public createdAt = new Date();
  @Property({ onUpdate: () => new Date() })
  public updatedAt = new Date();
  @Property()
  public deletedAt?: Date;
}
```

when trying to use a smart query, to get components a component by id, if it exists, or exists in the equipments table, or in the table, equipments_has_components:
```
    const instance = await this.em.find(ComponentInstance, { serial_number: sn , 
      $or: [
      { equipment: { component:{ serial_number:sn} } },
      { equipments: { component: { serial_number: sn } }}
    ] });
```

but i got this error:

```
Error: Trying to query by not existing property EquipmentInstance.serial_number
    at C:\Users\x\Documents\x\node_modules\@mikro-orm\knex\query\CriteriaNode.js:21:27
    at Array.forEach (<anonymous>)
    at new CriteriaNode (C:\Users\x\Documents\x\node_modules\@mikro-orm\knex\query\CriteriaNode.js:18:48)
    at new ScalarCriteriaNode (C:\Users\x\Documents\x\node_modules\@mikro-orm\knex\query\ScalarCriteriaNode.js:6:1)
    at Function.createScalarNode (C:\Users\x\Documents\emasa\node_modules\@mikro-orm\knex\query\CriteriaNodeFactory.js:22:22)
    at Function.createNode (C:\Users\x\Documents\emasa\node_modules\@mikro-orm\knex\query\CriteriaNodeFactory.js:19:21)
    at Function.createObjectItemNode (C:\Users\x\Documents\x\node_modules\@mikro-orm\knex\query\CriteriaNodeFactory.js:47:25)
    at C:\Users\x\Documents\x\node_modules\@mikro-orm\knex\query\CriteriaNodeFactory.js:38:28
    at Array.reduce (<anonymous>)
    at Function.createObjectNode (C:\Users\x\Documents\x\node_modules\@mikro-orm\knex\query\CriteriaNodeFactory.js:37:45)
    at Function.createNode (C:\Users\x\Documents\x\node_modules\@mikro-orm\knex\query\CriteriaNodeFactory.js:17:25)
    at Function.createObjectItemNode (C:\Users\x\Documents\x\node_modules\@mikro-orm\knex\query\CriteriaNodeFactory.js:47:25)
    at C:\Users\x\Documents\x\node_modules\@mikro-orm\knex\query\CriteriaNodeFactory.js:38:28
    at Array.reduce (<anonymous>)
    at Function.createObjectNode (C:\Users\x\Documents\x\node_modules\@mikro-orm\knex\query\CriteriaNodeFactory.js:37:45)
    at Function.createNode (C:\Users\x\Documents\x\node_modules\@mikro-orm\knex\query\CriteriaNodeFactory.js:17:25)
```

**Comment by ZilRahman** [comment]
How did you fix this issue?
