### ISSUE TITLE
Schema generator throws error with sqlite database

### ISSUE THREAD

**Issue by bahdcoder** [mikro-orm/mikro-orm#1098]
**Describe the bug**
When I run schema generator on sqlite database, it throws the following error:

**Stack trace**
```js
[query] create table `password_resets` (`id` integer not null primary key autoincrement, `email` varchar not null, `token` varchar not null, `expires_at` datetime not null, `created_at` timestamp(3) not null default current_timestamp(3), `updated_at` timestamp(3) not null default current_timestamp(3)); [took 0 ms]
SyntaxErrorException: create table `password_resets` (`id` integer not null primary key autoincrement, `email` varchar not null, `token` varchar not null, `expires_at` datetime not null, `created_at` timestamp(3) not null default current_timestamp(3), `updated_at` timestamp(3) not null default current_timestamp(3)); - SQLITE_ERROR: near "(": syntax error
    at SqliteExceptionConverter.convertException (/Users/bahdcoder/Projects/jwt-best-practices/api/node_modules/@mikro-orm/sqlite/SqliteExceptionConverter.js:38:20)
    at SqliteDriver.convertException (/Users/bahdcoder/Projects/jwt-best-practices/api/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:171:54)
    at /Users/bahdcoder/Projects/jwt-best-practices/api/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:175:24
    at async SchemaGenerator.execute (/Users/bahdcoder/Projects/jwt-best-practices/api/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:119:13)
    at async SchemaGenerator.updateSchema (/Users/bahdcoder/Projects/jwt-best-practices/api/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:77:9)
    at async Migrator.init (/Users/bahdcoder/Projects/jwt-best-practices/api/node_modules/@tensei/core/build/database/Migrator.js:14:9)
    at async Database.init (/Users/bahdcoder/Projects/jwt-best-practices/api/node_modules/@tensei/core/build/database/index.js:43:9)
    at async Tensei.bootDatabase (/Users/bahdcoder/Projects/jwt-best-practices/api/node_modules/@tensei/core/build/Tensei.js:236:32)
    at async Tensei.registerDatabase (/Users/bahdcoder/Projects/jwt-best-practices/api/node_modules/@tensei/core/build/Tensei.js:244:9)
    at async Tensei.boot (/Users/bahdcoder/Projects/jwt-best-practices/api/node_modules/@tensei/core/build/Tensei.js:147:9)

previous Error: create table `password_resets` (`id` integer not null primary key autoincrement, `email` varchar not null, `token` varchar not null, `expires_at` datetime not null, `created_at` timestamp(3) not null default current_timestamp(3), `updated_at` timestamp(3) not null default current_timestamp(3)); - SQLITE_ERROR: near "(": syntax error {
  errno: 1,
  code: 'SQLITE_ERROR'
}
```

**To Reproduce**
1. Run `schemaGenerator.updateSchema(true, true, false, false)` on an sqlite database

**Expected behavior**
Schema generator should run smoothly with no errors

**Versions**

| Dependency | Version |
| - | - |
| node | v12.17.0 |
| typescript | v3.9 |
| mikro-orm | v4.3.0 |
| your-driver | sqlite |

**Comment by B4nan** [comment]
First of all, if you report issue like this, you really need to provide entity definitions. 

But here it's quite obvious, you are setting length of some `Date` property, but sqlite does not support that.

**Comment by bahdcoder** [comment]
Hey @B4nan  thanks for having a look. Next time I'll correctly include entity definitions. 

You're right about the length, thanks for sharing ! 

closing this now
