### ISSUE TITLE
Sqlite: Executing a migration results in a knex timeout

### ISSUE THREAD

**Issue by rmuchall** [mikro-orm/mikro-orm#1102]
**Describe the bug**
When executing a migration using the sqlite driver the application appears to hang followed by the following error message:
```Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?```

**Stack trace**
```
 KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
        at Client_SQLite3.acquireConnection (C:\Work\TypeScript\orm-bug\node_modules\knex\lib\client.js:348:26)
        at Transaction.acquireConnection (C:\Work\TypeScript\orm-bug\node_modules\knex\lib\transaction.js:213:28)
        at UnitOfWork.commit (C:\Work\TypeScript\orm-bug\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:173:17)
        at SqlEntityManager.flush (C:\Work\TypeScript\orm-bug\node_modules\@mikro-orm\core\EntityManager.js:457:9)
        at SqlEntityManager.persistAndFlush (C:\Work\TypeScript\orm-bug\node_modules\@mikro-orm\core\EntityManager.js:409:9)
        at SqlEntityRepository.persistAndFlush (C:\Work\TypeScript\orm-bug\node_modules\@mikro-orm\core\entity\EntityRepository.js:21:9)
        at Migration20201120112502.up (C:\Work\TypeScript\orm-bug\src\migrations\Migration20201120112502.ts:14:5)
        at MigrationRunner.getQueries (C:\Work\TypeScript\orm-bug\node_modules\@mikro-orm\migrations\MigrationRunner.js:34:9)
        at C:\Work\TypeScript\orm-bug\node_modules\@mikro-orm\migrations\MigrationRunner.js:22:33
    From previous event:
        at C:\Work\TypeScript\orm-bug\node_modules\umzug\lib\index.js:116:62
        at processImmediate (internal/timers.js:461:21)
    From previous event:
        at C:\Work\TypeScript\orm-bug\node_modules\umzug\lib\index.js:112:43
    From previous event:
        at Umzug.execute (C:\Work\TypeScript\orm-bug\node_modules\umzug\lib\index.js:112:9)
        at Umzug._run (C:\Work\TypeScript\orm-bug\node_modules\umzug\lib\index.js:279:19)
        at Umzug.<anonymous> (C:\Work\TypeScript\orm-bug\node_modules\umzug\lib\index.js:307:21)
    From previous event:
        at Umzug._run (C:\Work\TypeScript\orm-bug\node_modules\umzug\lib\index.js:306:10)
        at Umzug.up (C:\Work\TypeScript\orm-bug\node_modules\umzug\lib\index.js:198:17)
        at Migrator.runInTransaction (C:\Work\TypeScript\orm-bug\node_modules\@mikro-orm\migrations\Migrator.js:207:45)
        at C:\Work\TypeScript\orm-bug\node_modules\@mikro-orm\migrations\Migrator.js:202:70
        at C:\Work\TypeScript\orm-bug\node_modules\knex\lib\transaction.js:184:22
```

**To Reproduce**
I have created a minimal-repository to reproduce this issue.
You can find it here: https://github.com/rmuchall/orm-bug
1.  npm install dependencies
2. run npm start script

**Expected behavior**
The migration should execute successfully without hanging.

**Additional context**
N/A

**Versions**

| Dependency | Version |
| - | - |
| node | v14.15.0 LTS |
| typescript | 4.1.2 |
| mikro-orm | 4.3.0 |
| your-driver | @mikro-orm/sqlite 4.3.0 |

**Comment by B4nan** [comment]
You should not use EM inside migrations, definitely not like this. Once #929 will be finished, this will be better suited for the seeder package.

What you can do is to use the driver provided in the `Migration` class:

```ts
async up(): Promise<void> {
  await this.driver.nativeInsert(User, { name: 'Rob' });
}
```

**Comment by rmuchall** [comment]
Thanks @B4nan!
I shall modify my code as per your suggestion :)

**Comment by rmuchall** [comment]
This has indeed fixed my problem. Many thanks for your assistance.
