### ISSUE TITLE
[bug] QB.raw Converting circular structure to JSON

### ISSUE THREAD

**Issue by Langstra** [mikro-orm/mikro-orm#1112]
**Description**
When updating a JSON field using the raw method of a queryBuilder an error is thrown.

**Stack trace**
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
    at JSON.stringify (<anonymous>)
    at JsonType.convertToDatabaseValue (/dir/mikro-orm-issue/node_modules/@mikro-orm/core/types/JsonType.js:11:21)
    at /dir/mikro-orm-issue/node_modules/@mikro-orm/knex/query/QueryBuilderHelper.js:62:43
    at Array.forEach (<anonymous>)
    at QueryBuilderHelper.processData (/dir/mikro-orm-issue/node_modules/@mikro-orm/knex/query/QueryBuilderHelper.js:50:27)
    at QueryBuilder.init (/dir/mikro-orm-issue/node_modules/@mikro-orm/knex/query/QueryBuilder.js:411:38)
    at QueryBuilder.update (/dir/mikro-orm-issue/node_modules/@mikro-orm/knex/query/QueryBuilder.js:55:21)
    at ProjectsController.createProject (/dir/mikro-orm-issue/src/projects/projects.controller.ts:25:8)
    at /dir/mikro-orm-issue/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**To Reproduce**
1. git clone git@github.com:RiskChallenger/mikro-orm-issue.git
2. cd mikro-orm-issue
3. yarn
4. yarn test:e2e

**Expected behavior**
json should be updated using the raw query

**Additional context**
-

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript |3.9.7 |
| mikro-orm | 4.3.1 |

**Comment by B4nan** [comment]
It does not make sense to me, even if it would work, it would produce `payload = jsonb_set(payload, '{consumed}', ${Math.floor(Date.now() / 1000)})`, but you do not want that `payload = ` prefix, right?

Btw you should `import { EntityManager } from '@mikro-orm/knex';` instead of that type casting, no need to use `SqlEntityManager` explicitly.

**Comment by Langstra** [comment]
`qb.unsetFlag(QueryFlag.CONVERT_CUSTOM_TYPES)` fixed the problem. Would that be the preferred solution to this problem, or should we mark this as a bug?

**Comment by B4nan** [comment]
I guess I know a way around this, the main issue is that to ignore knex instance when processing params, I can't simply use `instanceof` as this happens in the `core` package - there is no knex at that level. But we could add a method to the platform level that would allow checking it this way. 

Will try to come up with something, for this specific use case it should work.

**Comment by B4nan** [comment]
Should work with `4.3.2-dev.3`
