### ISSUE TITLE
Entity subscribe: before create.

### ISSUE THREAD

**Issue by sptGabriel** [mikro-orm/mikro-orm#1113]
Hello I would like to know if it is possible to do something like this in the subscribe?

```
  @BeforeInsert()
  async beforeInsert() {
    this.password = await bcrypt.hash(this.password, bcrypt.genSaltSync(10));
  }
```

i try this:

```
import { Employee } from './employee.entity';
import { hash, genSaltSync } from 'bcryptjs';
import { EventSubscriber, EventArgs, Subscriber } from '@mikro-orm/core';
@Subscriber()
export class EmployeeSubscriber implements EventSubscriber<Employee> {
  async beforeCreate(args: EventArgs<Employee>): Promise<void> {
    const password = args.entity.user.password;
    if (args.entity.user) {
      args.entity.user.password = await hash(password, genSaltSync(10));
    }
  }
}

```

everything seems to work, but it generates an error:

```
[query] insert into "employees" ("created_at", "departament_id", "first_name", "id", "last_name", "matricula", "position", "updated_at") values ('2020-11-23T14:50:12.079Z', '3adb6602-45b0-4052-b9c8-7ef6058668b3', 'a', 'ccd9b3f4-50d3-45f3-84c6-829ca262fe23', 'b', '111111', 'tecnico', '2020-11-23T14:50:12.079Z') returning "id" [took 3 ms]
[query] rollback
TypeError: Cannot read property 'password' of undefined
    at EmployeeSubscriber.beforeCreate (C:\Users\xd\Documents\xe-Management\src\modules\employees\domain\employee.subscriber.ts:7:39)
    at C:\Users\xd\Documents\xe-Management\node_modules\@mikro-orm\core\events\EventManager.js:36:87
    at Function.runSerial (C:\Users\xd\Documents\xe-Management\node_modules\@mikro-orm\core\utils\Utils.js:457:28)
    at EventManager.dispatchEvent (C:\Users\xd\Documents\xe-Management\node_modules\@mikro-orm\core\events\EventManager.js:36:30)
    at UnitOfWork.runHooks (C:\Users\xd\Documents\xe-Management\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:304:33)
    at UnitOfWork.commitCreateChangeSets (C:\Users\xd\Documents\xe-Management\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:453:24)
    at UnitOfWork.persistToDatabase (C:\Users\xd\Documents\xe-Management\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:417:24)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
TypeError: Cannot read property 'password' of undefined
    at EmployeeSubscriber.beforeCreate (C:\Users\xd\Documents\xe-Management\src\modules\employees\domain\employee.subscriber.ts:7:39)
    at C:\Users\xd\Documents\xe-Management\node_modules\@mikro-orm\core\events\EventManager.js:36:87
    at Function.runSerial (C:\Users\xd\Documents\xe-Management\node_modules\@mikro-orm\core\utils\Utils.js:457:28)
    at EventManager.dispatchEvent (C:\Users\xd\Documents\xe-Management\node_modules\@mikro-orm\core\events\EventManager.js:36:30)
    at UnitOfWork.runHooks (C:\Users\xd\Documents\xe-Management\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:304:33)
    at UnitOfWork.commitCreateChangeSets (C:\Users\xd\Documents\xe-Management\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:453:24)
    at UnitOfWork.persistToDatabase (C:\Users\xd\Documents\xe-Management\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:417:24)
```

I didn't find many examples about subcribes, so I apologize, if this isn't the ideal place to ask.

**Comment by B4nan** [comment]
Because your entity does not have `user` property defined.

    const password = args.entity.user.password; // this line fails, you need to move it inside the `if` statement

**Comment by sptGabriel** [comment]
> Because your entity does not have `user` property defined.
> 
> ```
> const password = args.entity.user.password; // this line fails, you need to move it inside the `if` statement
> ```

```
[query] begin
User {
  active: false,
  employee: Employee {
    createdAt: 2020-11-23T15:03:03.061Z,
    updatedAt: 2020-11-23T15:03:03.061Z,
    id: 'e7e882a5-1c88-4479-a64a-943112c23df2',
    matricula: '111111',
    first_name: 'a',
    last_name: 'b',
    departament: Departament {
      id: '3adb6602-45b0-4052-b9c8-7ef6058668b3',
      departament_name: 'x',
      employees: [Collection],
      createdAt: 2020-11-23T12:24:39.191Z,
      updatedAt: 2020-11-23T12:24:39.191Z,
      deletedAt: null
    },
    position: 'tecnico',
    user: User { active: false, employee: [Employee], login: 'x', password: 'x' }
  },
  login: 'x',
  password: 'x'
}
$2a$10$Va7rS0LHmqySmvkga6nPxO4CnpNtAqoR64uiKz6JzLd1Q3tzLgfzu
User {
  active: false,
  employee: Employee {
    createdAt: 2020-11-23T15:03:03.061Z,
    updatedAt: 2020-11-23T15:03:03.061Z,
    id: 'e7e882a5-1c88-4479-a64a-943112c23df2',
    matricula: '111111',
    first_name: 'a',
    last_name: 'b',
    departament: Departament {
      id: '3adb6602-45b0-4052-b9c8-7ef6058668b3',
      departament_name: 'x',
      employees: [Collection],
      createdAt: 2020-11-23T12:24:39.191Z,
      updatedAt: 2020-11-23T12:24:39.191Z,
      deletedAt: null
    },
    position: 'tecnico',
    user: User {
      active: false,
      employee: [Employee],
      login: 'x',
      password: '$2a$10$Va7rS0LHmqySmvkga6nPxO4CnpNtAqoR64uiKz6JzLd1Q3tzLgfzu'
    }
  },
  login: 'x',
  password: '$2a$10$Va7rS0LHmqySmvkga6nPxO4CnpNtAqoR64uiKz6JzLd1Q3tzLgfzu'
}
$2a$10$Q0xRluaXUyYYlAifDY85GuLQ1IljhIYPV6j1q5otywvCBS7m1fMtC
[query] insert into "employees" ("created_at", "departament_id", "first_name", "id", "last_name", "matricula", "position", "updated_at") values ('2020-11-23T15:03:03.061Z', '3adb6602-45b0-4052-b9c8-7ef6058668b3', 'a', 'e7e882a5-1c88-4479-a64a-943112c23df2', 'b', '111111', 'tecnico', '2020-11-23T15:03:03.061Z') returning "id" [took 3 ms]
undefined
```

My user exists, but then it appears as undefined.
