### ISSUE TITLE
Cannot read property '__helper' of undefined

### ISSUE THREAD

**Issue by sptGabriel** [mikro-orm/mikro-orm#1119]
i find user and change password:

```
const user = await this.userRepository.byMatricula(matricula);
user.password = await User.EncryptPassword(password)
const updatedUser = await this.userRepository.updatePassword(user);

```
repository:
```
  public updatePassword = async (user: User): Promise<User> => {
    await this.em.persistAndFlush(user).catch((err) => {console.log(err)})
    return user;
  };
```
user instance:
```
User {
  employee: Employee {
    id: '178ea2de-33e2-4c6e-8ff9-14414e76385a',
    matricula: '1',
    first_name: 'test',
    last_name: 'test2',
    position: 'tecnico',
    departament: Ref<Departament> { id: '59524956-d7b1-4337-8f73-e2b54ffe40c1' },
    createdAt: 2020-11-23T23:10:03.452Z,
    updatedAt: 2020-11-23T23:10:03.452Z,
    deletedAt: null,
    user: User {
      employee: [Employee],
      login: 'xd',
      password: '$2a$10$2Uoav2J1OGn0g3oxIvV8r.iJMLfGOJ5fLn2fdOok1jPh1cvpumkKa',
      active: false
    }
  },
  login: 'xd',
  password: '$2a$10$2Uoav2J1OGn0g3oxIvV8r.iJMLfGOJ5fLn2fdOok1jPh1cvpumkKa',
  active: false
}
```

error:
```
TypeError: Cannot read property '__helper' of undefined
    at UnitOfWork.remove (C:\Users\xmin\Documents\xmin-Management\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:149:20)
    at UnitOfWork.computeChangeSets (C:\Users\xmin\Documents\xmin-Management\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:218:18)
    at UnitOfWork.commit (C:\Users\xmin\Documents\xmin-Management\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:163:18)
    at SqlEntityManager.flush (C:\Users\xmin\Documents\xmin-Management\node_modules\@mikro-orm\core\EntityManager.js:452:9)
    at SqlEntityManager.persistAndFlush (C:\Users\xmin\Documents\xmin-Management\node_modules\@mikro-orm\core\EntityManager.js:404:9)
    at UserRepository.updatePassword (C:\Users\xmin\Documents\xmin-Management\src\modules\users\persistence\userRepositoryImpl.ts:24:5)
    at ChangePasswordUseCase.execute (C:\Users\xmin\Documents\xmin-Management\src\modules\users\application\useCases\changePassword\changeUserPassword.ts:37:25)    
    at EmployeeController.changePassword (C:\Users\xmin\Documents\xmin-Management\src\modules\employees\ui\employee.controller.ts:41:22)
```

My user exists with all properties, but I'm having a problem using em.persistAndFlush and I've had a similar problem with more entities

**Comment by B4nan** [comment]
I need a reproduction, executable one, this is not enough - how do you expect me to debug it? I don't mind if you create issue every single day, but please always provide executable reproductions, so it is clear what you are actually doing. There are many examples of reproductions here: https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues

The error, based on your stack trace, is caused by issued orphan removal of some entity, but apparently it is not an entity (as discovered entities do have the hidden `__helper` property that the error is about). Hard to say why, because you did not provide any details of what you are actually doing, or how your entities are defined. 

```ts
// btw there is always only one instance of the user, so `user` === `updatedUser`.
const updatedUser = await this.userRepository.updatePassword(user);
```
