### ISSUE TITLE
Attempting to run/create migrations, error with tsNode set to true.

### ISSUE THREAD

**Issue by jaketoolson** [mikro-orm/mikro-orm#1123]
**Describe the bug**
With `tsNode` set to true in the `package.json` settings, the below stack trace occurs.  When I set it to false, the migrations are created and run successfully.

**Stack trace**
```
(node:35117) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token } in JSON at position 590
    at JSON.parse (<anonymous>)
    at Function.getTsConfig (/Users/jake/www/oliver/server/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:71:21)
    at Function.registerTsNode (/Users/jake/www/oliver/server/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:58:30)
    at Function.configure (/Users/jake/www/oliver/server/node_modules/@mikro-orm/cli/CLIConfigurator.js:20:13)
    at /Users/jake/www/oliver/server/node_modules/@mikro-orm/cli/cli.js:16:19
...
```

**To Reproduce**
1. Set mikro-orm values from below in `package.json`
2. run `npx mikro-orm migration:create` 

**Expected behavior**

**Additional context**
from `package.json` :
```
  "mikro-orm": {
    "useTsNode": true,
    "configPaths": [
      "./src/config/mikro-orm-config.ts",
      "./dist/config/mikro-orm-config.js"
    ]
  }
```

ORM Config:
```
export default {
  entities: [
    './dist/models/BaseModel.js',
    './dist/models/**/*.*',
  ],
  entitiesTs: [
    './src/models/BaseModel.ts',
    './src/models/**/*.*',
  ],
  dbName: 'database/db.sqlite',
  type: 'sqlite',
  metadataProvider: TsMorphMetadataProvider,
  debug: true,
  migrations: {
    tableName: 'migrations', // migrations table name
    path: './database/migrations', // path to folder with migration files
    pattern: /^[\w-]+\d+\.ts$/, // how to match migration files
    transactional: true, // run each migration inside transaction
    disableForeignKeys: true, // try to disable foreign_key_checks (or equivalent)
    allOrNothing: true, // run all migrations in current batch in master transaction
    emit: 'ts', // migration generation mode
  },
}

```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.3.0 |
| typescript | 4.1.2 |
| mikro-orm | 4.3.0 |
| your-driver | sqlite |

**Comment by B4nan** [comment]
Your `tsconfig.json` is not a valid JSON, comments are supported, trailing commas not.

**Comment by jaketoolson** [comment]
🤦 Thanks!
