### ISSUE TITLE
Can't load config file

### ISSUE THREAD

**Issue by andnofence** [mikro-orm/mikro-orm#1127]
**Describe the bug**
I'm trying to use MikroORM together with Nest.js. When I run `nest start` it crashes because it can't load the mikro-orm config file:

**Stack trace**
```
[Nest] 20124   - 11/25/2020, 5:33:27 PM   [ExceptionHandler] MikroORM config file not found in ['./mikro-orm.config.js'] +3ms
Error: MikroORM config file not found in ['./mikro-orm.config.js']
    at Function.getConfiguration (/Users/andre/src/yukon/backend/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:24:15)
    at async InstanceWrapper.useFactory [as metatype] (/Users/andre/src/yukon/backend/node_modules/@mikro-orm/nestjs/mikro-orm.providers.js:17:28)
    at async Injector.instantiateClass (/Users/andre/src/yukon/backend/node_modules/@nestjs/core/injector/injector.js:294:37)
    at async callback (/Users/andre/src/yukon/backend/node_modules/@nestjs/core/injector/injector.js:77:30)
    at async Injector.resolveConstructorParams (/Users/andre/src/yukon/backend/node_modules/@nestjs/core/injector/injector.js:118:24)
    at async Injector.loadInstance (/Users/andre/src/yukon/backend/node_modules/@nestjs/core/injector/injector.js:81:9)
    at async Injector.loadProvider (/Users/andre/src/yukon/backend/node_modules/@nestjs/core/injector/injector.js:38:9)
    at async Promise.all (index 4)
    at async InstanceLoader.createInstancesOfProviders (/Users/andre/src/yukon/backend/node_modules/@nestjs/core/injector/instance-loader.js:43:9)
    at async /Users/andre/src/yukon/backend/node_modules/@nestjs/core/injector/instance-loader.js:28:13
```

**To Reproduce**
Follow the instructions on how to set up a nest.js project here: https://mikro-orm.io/docs/usage-with-nestjs

**Expected behavior**
I expect the app to start

**Additional context**
The one thing that may be unusual with my app is that I have a monorepo structure with a `backend` and `frontend` directory at the project root. The nest.js app is in the backend directory.

I've tried copying the config file from https://github.com/mikro-orm/nestjs-example-app/blob/master/src/mikro-orm.config.ts but this did not help. I also tried to configure the app using just `MikroORM.init` in the bootstrap() method, but it still tries to load the config file. Is there a way to turn that off?

**Versions**

| Dependency | Version |
| - | - |
| node | 12.18.2 |
| typescript | 4.1.2 |
| mikro-orm | 4.3.2 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Try running `mikro-orm debug` to see the absolute paths, you probably have the baseDir misconfigured. 

If you want more precise suggestion, you need to provide executable reproduction.

**Comment by andnofence** [comment]
Thanks, the `debug` command helped me. I'd forgotten to add the necessary `configPaths` to `package.json`.
