### ISSUE TITLE
Cannot read property 'adjustments' of undefined

### ISSUE THREAD

**Issue by kodeine** [mikro-orm/mikro-orm#1138]
**Describe the bug**

**Stack trace**
```
TypeError: Cannot read property 'adjustments' of undefined
    at eval (eval at createFunction (/Users/user/test/node_modules/@mikro-orm/core/utils/Utils.js:575:52), <anonymous>:33:45)
    at Function.callCompiledFunction (/Users/user/test/node_modules/@mikro-orm/core/utils/Utils.js:586:20)
    at ObjectHydrator.hydrate (/Users/user/test/node_modules/@mikro-orm/core/hydration/ObjectHydrator.js:23:23)
    at EntityFactory.hydrate (/Users/user/test/node_modules/@mikro-orm/core/entity/EntityFactory.js:81:27)
    at EntityFactory.create (/Users/user/test/node_modules/@mikro-orm/core/entity/EntityFactory.js:35:14)
    at SqlEntityManager.find (/Users/user/test/node_modules/@mikro-orm/core/EntityManager.js:95:52)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at QueryRunner.onQueryCatchEvent (/Users/user/test/src/strategies/runner.base.ts:114:23)
[ERROR] 19:43:39 TypeError: Cannot read property 'adjustments' of undefined
```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ^3.9.7 |
| mikro-orm | ^4.3.0 |
| mikro-orm/postgresql | ^4.2.3 |

**Comment by bahdcoder** [comment]
Hey can you please share some information about the entities you have in your application? That way we can help you figure out what's not working.

**Comment by B4nan** [comment]
I am sorry but I will close this right ahead, this is great example how you should not file bug reports. You literally ignored everything, and just copy pasted a stack trace, without even writing a single sentence. 

Don't ignore the issue template, if you don't know how to describe a bug in words, then prepare a reproduction in code.

And if you are really trying to use `@mikro-orm/core@^4.3.0` together with `@mikro-orm/postgresql@^4.2.3` then that will be almost certainly your issue. The versions needs to be aligned. And the last part of the issue template is for specific versions, so we can see what _exact_ version are you on, so nope, `^4.3.0` is not what you should put there.
