### ISSUE TITLE
Self-referencing OneToOne with STI 

### ISSUE THREAD

**Issue by elmpp** [mikro-orm/mikro-orm#1140]
**Describe the bug**
I cannot seem to find a combination of configuration to define a nullable self-referencing OneToOne relation with an Single Table Inherited abstract type

**Stack trace**
```
mikro-orm migration:create

Create new migration with current schema diff

Options:
  -b, --blank    Create blank migration                                [boolean]
  -i, --initial  Create initial migration                              [boolean]
  -d, --dump     Dumps all queries to console                          [boolean]
  -p, --path     Sets path to directory where to save entities          [string]
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]

MetadataError: Both RepoEntity.parentRepo and RepoEntity.parentRepo are defined as owning sides, use 'mappedBy' on one of them
    at Function.fromWrongOwnership (/Users/matt/dev/org-repo/.yarn/unplugged/@mikro-orm-core-virtual-603fa737fe/node_modules/@mikro-orm/core/errors.js:116:16)
    at MetadataValidator.validateOwningSide (/Users/matt/dev/org-repo/.yarn/unplugged/@mikro-orm-core-virtual-603fa737fe/node_modules/@mikro-orm/core/metadata/MetadataValidator.js:91:42)
    at MetadataValidator.validateBidirectional (/Users/matt/dev/org-repo/.yarn/unplugged/@mikro-orm-core-virtual-603fa737fe/node_modules/@mikro-orm/core/metadata/MetadataValidator.js:70:18)
    at MetadataValidator.validateEntityDefinition (/Users/matt/dev/org-repo/.yarn/unplugged/@mikro-orm-core-virtual-603fa737fe/node_modules/@mikro-orm/core/metadata/MetadataValidator.js:31:18)
    at MetadataDiscovery.processEntity (/Users/matt/dev/org-repo/.yarn/unplugged/@mikro-orm-core-virtual-603fa737fe/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:287:24)
    at /Users/matt/dev/org-repo/.yarn/unplugged/@mikro-orm-core-virtual-603fa737fe/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:52:63
    at Array.forEach (<anonymous>)
    at MetadataDiscovery.discover (/Users/matt/dev/org-repo/.yarn/unplugged/@mikro-orm-core-virtual-603fa737fe/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:52:18)
    at Function.init (/Users/matt/dev/org-repo/.yarn/unplugged/@mikro-orm-core-virtual-603fa737fe/node_modules/@mikro-orm/core/MikroORM.js:40:24)
    at Function.handleMigrationCommand (/Users/matt/dev/org-repo/.yarn/$$virtual/@mikro-orm-cli-virtual-581be499e6/3/.yarn/berry/cache/@mikro-orm-cli-npm-4.3.2-47b7ef8d92-7c0.zip/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:70:21) {
  entity: undefined
```

**To Reproduce**
 - Here is the offending set of entities - https://hastebin.com/ekurofudop
Note that i have also tried the various formats of relationship declaration for the `parentRepo?: RepoEntity`. including e.g.
```
@OneToOne(() => RepoEntity, (Repo) => Repo.parentRepo, {
   onDelete: 'cascade', // combinations of cascades don't affect
   cascade: [Cascade.PERSIST, Cascade.MERGE], // combinations of cascades don't affect
   nullable: true,
   mappedBy: "parentRepo", // have tried with/without mappedBy
   // owner: true, // have tried with/without owner
   joinColumn: 'parentId',
}) 
parentRepo?: RepoEntity
```
```
@OneToOne({
    mappedBy: "parentRepo",
  })
parentRepo?: RepoEntity
```

It *seems* that Mikro sees 2 sides?

**Expected behavior**
That i can declare a nullable self-referencing relationship on the base "entity" here that will by "inherited" by `RepoStandardEntity` and `RepoGithubEntity`

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.0 |
| typescript | 4.0.2 |
| mikro-orm | 4.3.2 |
| your-driver | sqlite |

**Comment by B4nan** [comment]
Owning side should use `inversedBy`, not `mappedBy`.

**Comment by B4nan** [comment]
You probably want just a uni directional relation:

```ts
@Entity(...)
export abstract class RepoEntity {

  @OneToOne({
    entity: () => RepoEntity,
    joinColumn: 'parentId',
    nullable: true,
  })
  parentRepo?: RepoEntity

}
```

Optionally you could model also the inverse side of that relation (in the very same entity):

```ts
  @OneToOne({
    entity: () => RepoEntity,
    mappedBy: 'parentRepo',
  })
  childRepo?: RepoEntity
```

Then (only then) you need to specify `mappedBy` or `inversedBy` (the side that is using `inverseBy` is considered as owner).

**Comment by elmpp** [comment]
Yes, the unidirectional form is what i'm after - looks like i need to use the options format to omit the inverse relationship then. Ah ok thanks

**Comment by B4nan** [comment]
As you want to pass additional options, its better to use it right ahead. You can also use the other way, passing `undefined` as the second param:

```ts
@OneToOne(() => RepoEntity, undefined, { nullable: true })
```

**Comment by elmpp** [comment]
Thanks for the help
