### ISSUE TITLE
how can I override foreign key constraint name?

### ISSUE THREAD

**Issue by SDAdham** [mikro-orm/mikro-orm#1202]
how can I override foreign key constraint name? I lookedup the code and it looks like there is no a specific config that allows me to override it...

The reason behind this request is because for some columns I am getting foreign key index name is too long. Please help about this. It's urgent.

A more detailed context of why I'ma sking for this:
```
UnhandledPromiseRejectionWarning: DriverException: alter table `table_name` add index `table_name_column_name_id_index`(`column_name_id`); - Identifier name 'table_name_column_name_id_index' is too long
    at MySqlExceptionConverter.convertException (\node_modules\@mikro-orm\core\platforms\ExceptionConverter.js:8:16)
    at MySqlExceptionConverter.convertException (\node_modules\@mikro-orm\mysql-base\MySqlExceptionConverter.js:78:22)
    at MySqlDriver.convertException (\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:171:54)
    at \node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:175:24
    at ZoneDelegate.invoke (\node_modules\zone.js\dist\zone-node.js:386:30)
    at Zone.run (\node_modules\zone.js\dist\zone-node.js:143:47)
    at \node_modules\zone.js\dist\zone-node.js:891:38
    at ZoneDelegate.invokeTask (\node_modules\zone.js\dist\zone-node.js:421:35)
    at Zone.runTask (\node_modules\zone.js\dist\zone-node.js:188:51)
    at drainMicroTaskQueue (\node_modules\zone.js\dist\zone-node.js:601:39)

previous Error: alter table `table_name` add index `table_name_column_name_id_index`(`column_name_id`); - Identifier name 'table_name_column_name_id_index' is too long
    at Packet.asError (\node_modules\mysql2\lib\packets\packet.js:712:17)
    at Query.execute (\node_modules\mysql2\lib\commands\command.js:28:26)
    at Connection.handlePacket (\node_modules\mysql2\lib\connection.js:425:32)
    at PacketParser.onPacket (\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (\node_modules\mysql2\lib\connection.js:82:25)
    at ZoneDelegate.invokeTask (\node_modules\zone.js\dist\zone-node.js:421:35)
    at Zone.runTask (\node_modules\zone.js\dist\zone-node.js:188:51)
    at ZoneTask.invokeTask (\node_modules\zone.js\dist\zone-node.js:503:38)
    at Socket.ZoneTask.invoke (\node_modules\zone.js\dist\zone-node.js:492:52)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by xeladejo** [comment]
Maybe you are referring to `joinColumn` or `inverseJoinColumn`:
  - https://mikro-orm.io/docs/decorators#onetoone
  - https://mikro-orm.io/docs/decorators#onetomany

Or to naming strategy:
  - https://mikro-orm.io/docs/naming-strategy/

**Comment by B4nan** [comment]
```ts
@ManyToOne({ index: 'custom_idx_name' })
```
