### ISSUE TITLE
UnhandledPromiseRejectionWarning when trying to create a migration

### ISSUE THREAD

**Issue by HippoBaguette** [mikro-orm/mikro-orm#1209]
**Describe the bug**
UnhandledPromiseRejectionWarning when running `npx mikro-orm migration:create` in gitpod terminal. Unsure if able to reproduce in other terminals/editors

**Stack trace**
```
gitpod /workspace/myworkspace $ npx mikro-orm migrations:create
(node:3487) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token } in JSON at position 714
    at JSON.parse (<anonymous>)
    at Function.getTsConfig (/workspace/myworkspace/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:71:21)
    at Function.registerTsNode (/workspace/myworkspace/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:58:30)
    at Function.configure (/workspace/myworkspace/node_modules/@mikro-orm/cli/CLIConfigurator.js:20:13)
    at /workspace/myworkspace/node_modules/@mikro-orm/cli/cli.js:16:19
(node:3487) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3487) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
1. Run `npx mikro-orm migration:create`

**Expected behavior**
A migration folder to be created, and "MigrationXXXXXXXXXXXXXX successfully created" to be printed.

**Additional context**
Installed mikro-orm via yarn
mikro-orm.config.ts:
```ts
import { Post } from "./entities/Post"
import { __prod__ } from "./constants"
import { MikroORM } from "@mikro-orm/core";
import path from 'path';

export default {
        migrations: {
            path: path.join(__dirname, "./migrations"),
            patter: /^[\w-]+\d+\.[tj]s$/,
        },
        entities: [Post],
        dbName: 'data',
        type: 'postgresql',
        debug: !__prod__
} as Parameters<typeof MikroORM.init>[0];
```

**Versions**

| Dependency | Version |
| - | - |
| node | 12.20.0 |
| typescript | 4.1.2 |
| mikro-orm | 4.3.4 |
| your-driver | gitpod |
| yarn | 1.22.10 |

**Comment by B4nan** [comment]
You have invalid `tsconfig.json` file, most probably trailing comma (as comments ara supported, but trailig commas not).
