### ISSUE TITLE
Metadata Discovery: Bug when running with node

### ISSUE THREAD

**Issue by eklam** [mikro-orm/mikro-orm#1214]
**Describe the bug**
When I run my project with mikro-orm with node after I compiled it. mikro-orm throws an exception at the Metadata Discover step.

I use ts-node on the dev environment and mikro-orm works as expected here. I only face the problem when I build with `tsc` and try to run with `node`. Check my configuration files below.

I tried several different configurations, like specifying `entities` and `entitiesTs`, either as a glob or array but I always get the same error. The `.d.ts` definitions are getting generated fine after I run `yarn tsc`

**Stack trace**
```
[discovery] - processing 15 files
(node:42404) UnhandledPromiseRejectionWarning: C:\Users\rmalk\Fables\fables\server\infrastructure\database\entities\Account.ts:1
import { User } from './User'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.patchedRequire [as require] (C:\Users\rmalk\Fables\fables\server\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:88:18)
    at MetadataDiscovery.getEntityClassOrSchema (C:\Users\rmalk\Fables\fables\server\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:643:25)     
    at MetadataDiscovery.discoverDirectories (C:\Users\rmalk\Fables\fables\server\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:95:34)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:42404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:42404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
1. Run the project with `node`
2. Wait for mikro-rom to break during Metadata Discovery step

**Expected behavior**
mikro-orm should run the same with node and ts-node, or throw an error message pointing me on how to fix my config.

**package.json**
```
    ...
    "mikro-orm": {
        "useTsNode": true,
        "configPaths": [
            "./src/mikro-orm.config.ts"
        ]
    }
    ...
```

**tsconfig.json**
```
{
  "compilerOptions": {
    "typeRoots": [
      "@types",
      "./node_modules/@types",
    ],
    "target": "es2018",
    "module": "commonjs",
    "lib": [
      "es2018",
      "esnext.asynciterable",
      "es2020.string"
    ],
    "outDir": "./dist",
    "strict": true,
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "declaration": true
  }
}
```

**mikro-orm.config.ts**
```
import { IDatabaseDriver, Options } from '@mikro-orm/core'

// Load .env file - needed when running MikroOrm CLI
require(`dotenv`).config()

export default {
    entities: [`./infrastructure/database/entities`],
    type: `postgresql`,
    clientUrl: process.env.DATABASE_URL,
    debug: true,
} as Options<IDatabaseDriver>

```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.1 |
| typescript | 3.9.3 |
| mikro-orm | 4.3.2 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
For folder based discovery you need both `entities` and `entitiesTs`:

```ts
export default {
    entities: [`./dist/infrastructure/database/entities`], // this needs to point to compiled JS entities
    entitiesTs: [`./infrastructure/database/entities`], // this needs to point to TS source files
    type: `postgresql`,
    clientUrl: process.env.DATABASE_URL,
    debug: true,
} as Options<IDatabaseDriver>
```
