### ISSUE TITLE
Error creating migrations 

### ISSUE THREAD

**Issue by mrsants** [mikro-orm/mikro-orm#1285]
when trying to create my migrations i am having the following error in mikro, i'm following the recommended configuration steps in the documentation

```
(node:3933) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token } in JSON at position 651
    at JSON.parse (<anonymous>)
    at Function.getTsConfig (/Users/marcelobatista/Documents/Github/lireddit-server/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:71:21)
    at Function.registerTsNode (/Users/marcelobatista/Documents/Github/lireddit-server/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:58:30)
    at Function.configure (/Users/marcelobatista/Documents/Github/lireddit-server/node_modules/@mikro-orm/cli/CLIConfigurator.js:20:13)
    at /Users/marcelobatista/Documents/Github/lireddit-server/node_modules/@mikro-orm/cli/cli.js:16:19
(node:3933) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3933) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Stack trace**
```
mikro-orm.config.ts

import { __prod__ } from "./constants";
import { Post } from "./entities/Post";
import { MikroORM } from "@mikro-orm/core";
import { TsMorphMetadataProvider } from '@mikro-orm/reflection';

import path from 'path';
export default {
  migrations: {
    path: path.join(__dirname + './migrations'), 
    pattern: /^[\w-]+\d+\.ts$/, 
  },
  entities: [Post],
  dbName: "lireddit",
  type: "postgresql",
  password: '123456',
  debug: !__prod__,
  metadataProvider: TsMorphMetadataProvider,
} as Parameters<typeof MikroORM.init>[0];

index.ts 

import { MikroORM } from "@mikro-orm/core";
import { __prod__ } from "./constants";
import mikroConfig from './mikro-orm.config';

const main = async () => {
  await MikroORM.init(mikroConfig);
};

main();

package.json

 "dependencies": {
    "@mikro-orm/cli": "^4.3.4",
    "@mikro-orm/core": "^4.3.4",
    "@mikro-orm/migrations": "^4.3.4",
    "@mikro-orm/postgresql": "^4.3.4",
    "@mikro-orm/reflection": "^4.3.4",
    "pg": "^8.5.1"
  },
  "devDependencies": {
    "@types/node": "^14.14.20",
    "nodemon": "^2.0.7",
    "ts-node": "^9.1.1",
    "typescript": "^4.1.3"
  },
  "scripts": {
    "start": "ts-node src/index.ts",
    "watch": "tsc -w",
    "dev": "nodemon --exec ts-node src/index.ts",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "mikro-orm": {
    "useTsNode": true,
    "configPaths": [
      "./src/mikro-orm.config.ts",
      "./dist/mikro-orm.config.js"
    ]
  },
...
```

**To Reproduce**

npx mikro-orm migration:create   

**Expected behavior**
I hope to create my migrations normally

**Versions**

| Dependency | Version |

mikro-orm 4.3.4
node 12.20.0
typescript 4.1.3
macos: 11.0.1

**Comment by B4nan** [comment]
Your `tsconfig.json` is not valid json - you cant have trailing commas there (comments are allowed).

**Comment by B4nan** [comment]
- [ ] Also note that `path.join(__dirname + './migrations')` looks wrong too. That method is used for joining path fragments, and you are feeing it wrongly (with a single parameter, that is btw also wrong - you will end up with path like `...curr-dir-name./migrations`, so drop the dot to make it valid).

**Comment by mrsants** [comment]
> Observe também que também `path.join(__dirname + './migrations')`parece errado. Esse método é usado para juntar fragmentos de caminho, e você o está alimentando incorretamente (com um único parâmetro, que também está errado - você acabará com um caminho como `...curr-dir-name./migrations`, portanto, solte o ponto para torná-lo válido).

I just checked it out, thanks

**Comment by B4nan** [comment]
Lastly, using `Parameters<typeof MikroORM.init>[0]` is wrong way too. Use just `Options` exported from the ORM.
