### ISSUE TITLE
[bug] unable to generate schema

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#130]
**Describe the bug**
I'm trying to create a really simple project to test how well this thing works.

So far I'm on my 4th ORM and the only one I could get to work was TypeORM and ugh with that one. This one looks very promising, but having troubles just getting the schema output...

**Stack trace**
```
ValidationError: No entities were discovered
    at Function.noEntityDiscovered (relations-mikro/node_modules/mikro-orm/dist/utils/ValidationError.js:81:16)
    at MetadataValidator.validateDiscovered (relations-mikro/node_modules/mikro-orm/dist/metadata/MetadataValidator.js:23:43)
    at MetadataDiscovery.discover (relations-mikro/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:40:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Function.init (relations-mikro/node_modules/mikro-orm/dist/MikroORM.js:18:28)
    at Function.handleSchemaCommand (relations-mikro/node_modules/mikro-orm/dist/cli/SchemaCommandFactory.js:42:21) {
  entity: undefined,
  name: 'ValidationError'
}
```

**To Reproduce**
Download this file:

[relations-mikro.zip](https://github.com/mikro-orm/mikro-orm/files/3631004/relations-mikro.zip)

Assuming that you have `./node_modules/.bin` in your PATH.

```
yarn
mikro-orm schema:create -d
```

**Expected behavior**
A 💩 

**Versions**

the latest release from next

**Comment by B4nan** [comment]
You are defining `entitiesDirs` and `entitiesDirsTs` not as directories, but as file globs. You need to provide directories there, then it works. 

```
export = {
	baseDir: __dirname, // defaults to `process.cwd()`,
	entitiesDirs: ['../build/model'],
	entitiesDirsTs: ['./model'],
	debug: true,
	type: 'sqlite',
	dbName: 'test.db',
	warnWhenNoEntities: true,
}
```

**Comment by lookfirst** [comment]
i knew it was something stupid. thanks!

**Comment by B4nan** [comment]
I will add validation for this in v3.

**Comment by B4nan** [comment]
Btw `warnWhenNoEntities` is by default `true`, this options is there only because of `EntityGenerator`, which can be executed even when no entities were discovered so it patches the options when you run it via CLI with this flag disabled.
