### ISSUE TITLE
Nested Insert Error

### ISSUE THREAD

**Issue by thekevinbrown** [mikro-orm/mikro-orm#1326]
**Describe the bug**
When attempting a nested insert, I receive the message:

```
NotNullConstraintViolationException: insert into `license` (`driver_id`, `expires_at`, `license_type_id`) values (1, '2050-01-01 00:00:00.000', NULL) - Column 'license_type_id' cannot be null
```

**Stack trace**
```
 at MySqlExceptionConverter.convertException (packages/mysql-base/src/MySqlExceptionConverter.ts:79:16)
      at MySqlDriver.convertException (packages/core/src/drivers/DatabaseDriver.ts:249:50)
      at packages/core/src/drivers/DatabaseDriver.ts:254:18
      at MySqlDriver.nativeInsert (packages/knex/src/AbstractSqlDriver.ts:189:17)
      at ChangeSetPersister.persistNewEntity (packages/core/src/unit-of-work/ChangeSetPersister.ts:68:17)
      at ChangeSetPersister.executeInserts (packages/core/src/unit-of-work/ChangeSetPersister.ts:29:7)
      at UnitOfWork.commitCreateChangeSets (packages/core/src/unit-of-work/UnitOfWork.ts:606:5)
      at UnitOfWork.persistToDatabase (packages/core/src/unit-of-work/UnitOfWork.ts:557:7)
      at MySqlConnection.transactional (packages/knex/src/AbstractSqlConnection.ts:46:19)
      at UnitOfWork.commit (packages/core/src/unit-of-work/UnitOfWork.ts:227:9)
      at SqlEntityManager.flush (packages/core/src/EntityManager.ts:685:5)
      at SqlEntityManager.persistAndFlush (packages/core/src/EntityManager.ts:629:5)
      at Object.<anonymous> (tests/issues/GHXXX.test.ts:85:5)
      previous Error: insert into `license` (`driver_id`, `expires_at`, `license_type_id`) values (1, '2050-01-01 00:00:00.000', NULL) - Column 'license_type_id' cannot be null
      at Packet.asError (node_modules/mysql2/lib/packets/packet.js:712:17)
      at Query.execute (node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (node_modules/mysql2/lib/connection.js:425:32)
      at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:75:12)
      at PacketParser.executeStart (node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (node_modules/mysql2/lib/connection.js:82:25)
```

**To Reproduce**
I added a unit test in this PR that reproduces the issue: https://github.com/mikro-orm/mikro-orm/pull/1327

**Expected behavior**
Expected the nested insert to succeed

**Additional context**
Suspect this is related to #1150.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.16.1 |
| typescript | 4.1.3 |
| mikro-orm | latest master |
| your-driver | MySQL or Postgres (does not reproduce on SQLite) |

**Comment by B4nan** [comment]
Interesting, the `LicenceType` entity is added to the ID map here, even if it does not have PK. On the other hand, this was never really supposed to work, `assign` never worked recursively (not by design), you should be using `em.create()` here anyway, the purpose of `assign` is to update existing entities, not to create new ones. 

Does this work? I believe it should:

```ts
    const newDriver = orm.em.create(Driver, {
      name: 'Martin Adámek',
      licenses: [{
        expiresAt: new Date(2050, 0, 1),
        licenseType: {
          name: 'Standard Driver License',
        },
      }],
    });
```

On the other hand, this is definitely fixable, the reason why `assign` has limited usage is mainly because it is not possible to tell what entity should be inserted and what updated (in general it will result in inserts for everything unless you provide just the PK of a relation, not an object). Here you actually want inserts, so fixable for sure.

Btw this issue is not bound to mysql/pg, the difference with sqlite that the FK is made nullable, regardless of how you define it (due to limitations of sqlite, added columns need to be nullable and schema generator is always adding FKs via alter query to support circular relations).

**Comment by thekevinbrown** [comment]
Thanks for looking into this so quickly!

It looks like the `persistAndFlush` with `create` behaves the same way. I updated the reproduction to see if there was a difference: https://github.com/mikro-orm/mikro-orm/pull/1327/checks?check_run_id=1738379536

Anything I can do to help fix?

**Comment by B4nan** [comment]
Mmmmm it might be actually different issue with the same outcome, with `em.create()` we even have two records in the ID map before the flush... 

Tried to use normal relations instead of wrapped references and that way it works fine - but I can see the same issue with entities without PK being addedd to ID map...

**Comment by thekevinbrown** [comment]
@B4nan can confirm this is now resolved, thank you very much for your help!
