### ISSUE TITLE
Cannot read property 'push' of undefined when populating ManyToMany relation

### ISSUE THREAD

**Issue by AlexandrosMelissas** [mikro-orm/mikro-orm#1357]
**Describe the bug**
Entity A has 3 relations : 1 OneToMany and 2 ManyToMany relations (owner side). Trying to populate the entity with the ManyToMany relations gives me this error:
` TypeError: Cannot read property 'push' of undefined
      at node_modules/@mikro-orm/knex/AbstractSqlDriver.js:325:22
          at Array.forEach (<anonymous>)
      at MySqlDriver.loadFromPivotTable (node_modules/@mikro-orm/knex/AbstractSqlDriver.js:323:15)
      at EntityLoader.findChildrenFromPivotTable (node_modules/@mikro-orm/core/entity/EntityLoader.js:226:21)
      at EntityLoader.populateField (node_modules/@mikro-orm/core/entity/EntityLoader.js:195:25)
      at EntityLoader.populate (node_modules/@mikro-orm/core/entity/EntityLoader.js:37:13)
      at EntityLoader.populateField (node_modules/@mikro-orm/core/entity/EntityLoader.js:212:9)
      at EntityLoader.populate (node_modules/@mikro-orm/core/entity/EntityLoader.js:37:13)
      at EntityLoader.populateField (node_modules/@mikro-orm/core/entity/EntityLoader.js:212:9)`

**To Reproduce**
1. Create an entity with 1 OneToMany relation and 2 ManyToMany relations (owner side) with other entities
2. Try to populate the entity using find method.

**Expected behavior**
The ManyToMany relations should be properly loaded.

**Versions**

| Dependency | Version |
| node | 12.18.4 |
| typescript | 4.0.5 |
| mikro-orm | 4.3.3 |

**Comment by B4nan** [comment]
Please provide full (executable) reproduction, ideally as a [single file test case](https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues), and test it on the latest version (4.4.0).
