### ISSUE TITLE
Finding by items in JsonType

### ISSUE THREAD

**Issue by sekaru** [mikro-orm/mikro-orm#1359]
Hey,

If you had a JsonType field that had this signature: `customProps: { [key: string]: any }`, is there a nice way to search for keys inside that object?

Currently to find a player with the specified `customProps` key I'm doing:
```
const player = await em.getRepository(Player).findOne({
  [expr(`json_extract(customProps, '$.${keyName}')`)]: id
})
```

Ideally I'd do something like this:
```
const player = await em.getRepository(Player).findOne({ customProps: { [keyName]: id } })
```

However that throws an error with the query helper:
``` 
TypeError: Cannot read property 'includes' of undefined
      at /node_modules/@mikro-orm/core/utils/QueryHelper.js:157:77
      at Array.reduce (<anonymous>)
      at Function.processCustomType (/node_modules/@mikro-orm/core/utils/QueryHelper.js:156:38)
      at /node_modules/@mikro-orm/core/utils/QueryHelper.js:92:37
      at Array.reduce (<anonymous>)
      at Function.processWhere (/node_modules/@mikro-orm/core/utils/QueryHelper.js:75:35)
      at SqlEntityManager.findOne (/node_modules/@mikro-orm/core/EntityManager.js:177:37)
      at SqlEntityRepository.findOne (/node_modules/@mikro-orm/core/entity/EntityRepository.js:36:24)
      at PlayersAPIService.<anonymous> (/src/services/api/players-api.service.ts:39:51)
      at Generator.next (<anonymous>)
```

Am I missing something or is there currently no way of finding by items inside a json column?

**Comment by B4nan** [comment]
Currently the only way to do this is via embeddables in object mode, but we could support this for JSON columns too (as well as object properties in mongo).

https://mikro-orm.io/docs/embeddables/#storing-embeddables-as-objects

**Comment by sekaru** [comment]
Ah okay I see, that makes sense. My main problem is that `customProps` can have any key/value pairs in it. I'll look into it, thanks!

**Comment by sekaru** [comment]
Thanks @B4nan !
