### ISSUE TITLE
problem persisting an object

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#139]
I am sure that I'm doing something stupid here. Latest beta.

```ts
import {Entity, IEntity, PrimaryKey, Property} from "mikro-orm";

@Entity()
export class Person {
	@PrimaryKey()
	id: string;

	@Property({columnType: 'varchar', nullable: true, default: null})
	displayName: string;
	@Property({columnType: 'varchar', nullable: false})
	email: string;
	@Property({columnType: 'varchar', nullable: true, default: null})
	photoURL: string;

	constructor(person: Partial<Person>) {
		this.id = person.id!;
		this.displayName = person.displayName!;
		this.email = person.email!;
		this.photoURL = person.photoURL!;
	}
}

export interface Person extends IEntity<string> {
}
```

```
	beforeEach(async () => {
		createdBy = new Person({id: PERSON_ID, email: 'email address'});
		await orm.em.persistAndFlush(createdBy);
	});

```

```
ValidationError: Trying to set Person.displayName of type 'string' to 'undefined' of type 'undefined'
    at Function.fromWrongPropertyType (node_modules/mikro-orm/dist/utils/ValidationError.js:18:16)
    at EntityValidator.validateProperty (node_modules/mikro-orm/dist/entity/EntityValidator.js:36:43)
    at /node_modules/mikro-orm/dist/entity/EntityValidator.js:21:49
    at Array.forEach (<anonymous>)
    at EntityValidator.validate (node_modules/mikro-orm/dist/entity/EntityValidator.js:16:30)
    at ChangeSetComputer.computeChangeSet (node_modules/mikro-orm/dist/unit-of-work/ChangeSetComputer.js:20:24)
    at UnitOfWork.findNewEntities (node_modules/mikro-orm/dist/unit-of-work/UnitOfWork.js:149:50)
    at UnitOfWork.computeChangeSets (node_modules/mikro-orm/dist/unit-of-work/UnitOfWork.js:117:18)
    at UnitOfWork.commit (node_modules/mikro-orm/dist/unit-of-work/UnitOfWork.js:75:14)
    at EntityManager.flush (node_modules/mikro-orm/dist/EntityManager.js:210:36)
    at EntityManager.persistAndFlush (node_modules/mikro-orm/dist/EntityManager.js:177:20)
    at Context.<anonymous> (test/db/index.spec.ts:23:16)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:131:23)
```

**Comment by B4nan** [comment]
This is actually the same as #132 I think, I just fixed it in the master and rebased to dev, but didn't publish new version. 

Please try v3.0.0-alpha.8, that includes the fix.

**Comment by lookfirst** [comment]
Fixed! Thanks!
