### ISSUE TITLE
Unknown column 'datetime_precision' in 'field list' (MySql 5.5)

### ISSUE THREAD

**Issue by theKHR3b** [mikro-orm/mikro-orm#1401]
Hello! Trying to generate entities on current database I found this error:

C:\projects\call_robot>npx mikro-orm generate-entities -d
mikro-orm generate-entities

Error: select column_name as column_name, column_default as column_default, is_nullable as is_nullable, data_type as data_type, column_key as column_key, ifnull(datetime_precision, character_maximum_length) length
      from information_schema.columns where table_schema = database() and table_name = '_worker_house' - Unknown column 'datetime_precision' in 'field list'
    at Packet.asError (C:\projects\call_robot\node_modules\mysql2\lib\packets\packet.js:712:17)
    at Query.execute (C:\projects\call_robot\node_modules\mysql2\lib\commands\command.js:28:26)
    at Connection.handlePacket (C:\projects\call_robot\node_modules\mysql2\lib\connection.js:425:32)
    at PacketParser.onPacket (C:\projects\call_robot\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (C:\projects\call_robot\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\projects\call_robot\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'datetime_precision' in 'field list'"
}

After some reserching I found that error produces this part of sql query in 
[link to MySqlSchemaHelper](https://github.com/mikro-orm/mikro-orm/blob/969d4229bd525d4172ebff5fe10cf1b0c32dbb96/packages/mysql-base/src/MySqlSchemaHelper.ts#L99)
"ifnull(datetime_precision, character_maximum_length) length". Copying the full query to mysql command prompt produces the error too. Because: datetime_precision option is available from MySQL 5.6.4. https://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html, but my version is 5.5. 

**Expected behavior**
So, fixing errored query is simple: just writing "character_maximum_length as length" without any datetime_precision will work as expected.

**Versions**
mysql  Ver 14.14 Distrib 5.5.55, for debian-linux-gnu (i686) using readline 6.3
        "@mikro-orm/core": "^4.4.2",
        "@mikro-orm/mysql": "^4.4.2",
        "@mikro-orm/cli": "^4.4.2",
        "ts-node": "^9.1.1",
        "ts-node-dev": "^1.1.1"

Yes, I will consider to switch for a new version mysql, but if anyone run in this trouble, hope this will help.

**Comment by B4nan** [comment]
Correct fix is to upgrade your mysql, 5.5 is really outdated (released more than 10 years ago).

I'd say the minimal is 5.7 also because of other features like json columns. 5.6 will reach end of life in the end of this month. No plans to support older and generally discontinued versions.
