### ISSUE TITLE
Dealing with undefined or null within collections

### ISSUE THREAD

**Issue by blelump** [mikro-orm/mikro-orm#1408]
**Describe the bug**
Consider such usage:
```
    let foundDevice = user.userDevices.getItems().find((ud) => ud.uuid === deviceUuid);
    user.userDevices.remove(foundDevice);
```
It is possible `foundDevice` will be `undefined` in such scenario, but then it fails with:
 
**Stack trace**
```
    TypeError: Cannot read property '__helper' of undefined

      at check (node_modules/@mikro-orm/core/entity/Collection.js:269:22)
      at node_modules/@mikro-orm/core/entity/Collection.js:275:32
          at Array.find (<anonymous>)
      at Collection.validateModification (node_modules/@mikro-orm/core/entity/Collection.js:275:19)
      at Collection.modify (node_modules/@mikro-orm/core/entity/Collection.js:232:14)
      at Collection.remove (node_modules/@mikro-orm/core/entity/Collection.js:106:14)
      at RemoveDevice.handle (src-ts/components/user/use_cases/remove_device.ts:20:22)
      at src-ts/app/lambda/remove_device.ts:15:12
      at Object.withDbConnection (src-ts/config/orm.ts:28:12)
```

**To Reproduce**

Run `root.collection.remove(undefined);` or `root.collection.remove(null);`

**Expected behavior**

It depends. It depends who should take the responsibility of handling `undefined` / `null`. Somehow initially expected that the method will just continue and some guard clause will catch, if provided entity to be removed is `undefined`. Probably that would be the answer to `expected behavior`.

**Versions**

| Dependency | Version |
| - | - |
| node | 12 |
| typescript | 3.9.3 |
| mikro-orm | 4.4.2 |
| your-driver | PSQL - 4.4.2 |

**Comment by B4nan** [comment]
Worth noting that this is something TS should catch... :] You should better use strict mode (`strictNullChecks` in particular).
