### ISSUE TITLE
ManyToMany relations throws TypeError on populate when using custom `inverseJoinColumn`

### ISSUE THREAD

**Issue by mukaschultze** [mikro-orm/mikro-orm#1429]
**Describe the bug**
Populating the inverse side of a `ManyToMany` relation when using a custom `inverseJoinColumn` throws an exception.
This is probably the same issue as #1357

**Stack trace**
```
TypeError: Cannot read property 'push' of undefined

      403 |     items.forEach((item: any) => {
      404 |       const key = Utils.getPrimaryKeyHash(prop.joinColumns.map(col => item[`fk__${col}`]));
    > 405 |       map[key].push(item);
          |                ^
      406 |       prop.joinColumns.forEach(col => delete item[`fk__${col}`]);
      407 |       prop.inverseJoinColumns.forEach(col => delete item[`fk__${col}`]);
      408 |     });

      at packages/knex/src/AbstractSqlDriver.ts:405:16
          at Array.forEach (<anonymous>)
      at PostgreSqlDriver.loadFromPivotTable (packages/knex/src/AbstractSqlDriver.ts:403:11)
      at EntityLoader.findChildrenFromPivotTable (packages/core/src/entity/EntityLoader.ts:290:17)
      at EntityLoader.populateField (packages/core/src/entity/EntityLoader.ts:246:19)
      at EntityLoader.populate (packages/core/src/entity/EntityLoader.ts:54:7)
      at SqlEntityManager.lockAndPopulate (packages/core/src/EntityManager.ts:859:5)
      at SqlEntityManager.findOneOrFail (packages/core/src/EntityManager.ts:359:20)
      at Object.<anonymous> (tests/issues/GH1357.test.ts:51:20)
```

**To Reproduce**
```ts
import { Collection, Entity, ManyToMany, MikroORM, PrimaryKey } from '@mikro-orm/core';
import { PostgreSqlDriver } from '@mikro-orm/postgresql';

@Entity()
class A {

  @PrimaryKey()
  id!: number;

  @ManyToMany(() => A, undefined, {
    joinColumn: 'a_to_b',
    inverseJoinColumn: 'b_to_a',
  })
  as = new Collection<A>(this);

  @ManyToMany(() => A, 'as')
  bs = new Collection<A>(this);

}

describe('GH issue 1357', () => {

  let orm: MikroORM<PostgreSqlDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [A],
      dbName: `mikro_orm_test_gh_1357`,
      type: 'postgresql',
    });
    await orm.getSchemaGenerator().ensureDatabase();
    await orm.getSchemaGenerator().dropSchema();
    await orm.getSchemaGenerator().createSchema();
  });

  afterAll(() => orm.close(true));

  test(`GH issue 1357`, async () => {
    const fixture1 = new A();
    const fixture2 = new A();

    fixture1.as.add(fixture2);

    await orm.em.persistAndFlush([fixture1, fixture2]);
    orm.em.clear();

    const found1 = await orm.em.findOneOrFail(A, fixture1.id, ['as', 'bs']);
    const found2 = await orm.em.findOneOrFail(A, fixture2.id, ['as', 'bs']);

    expect(found1.as.isInitialized()).toBe(true);
    expect(found1.bs.isInitialized()).toBe(true);
    expect(found1.as).toHaveLength(1);
    expect(found1.as[0].id).toEqual(fixture2.id);
    expect(found1.bs).toHaveLength(0);
    expect(found2.as.isInitialized()).toBe(true);
    expect(found2.bs.isInitialized()).toBe(true);
    expect(found2.as).toHaveLength(0);
    expect(found2.bs).toHaveLength(1);
    expect(found2.bs[0].id).toEqual(fixture1.id);
  });
});

```

**Expected behavior**
Populating the inverse side of a ManyToMany relation should not throw an exception.

**Additional context**
This test script does work if both the `as` **and** `bs` specify the `inverseJoinColumn: 'b_to_a'`, I don't know if this is by design, if it is I think it should be documented somewhere.

If the owning side omits but the inverse side declares the `inverseJoinColumn` then the test above does pass, but the wrong schema is generated (it uses the default naming strategy, instead of the custom column name).

A similar error is thrown if the inverse side is changed to:
```ts
@ManyToMany({ entity: () => A, inversedBy: 'as' })
bs = new Collection<A>(this);
```
```
InvalidFieldNameException: insert into "a_as" ("a_2_id", "a_1_id") values (2, 1) - column "a_2_id" of relation "a_as" does not exist

      36 |         return new NonUniqueFieldNameException(exception);
      37 |       case '42703':
    > 38 |         return new InvalidFieldNameException(exception);
         |                ^
      39 |       case '42P01':
      40 |         return new TableNotFoundException(exception);
      41 |       case '42P07':

      at PostgreSqlExceptionConverter.convertException (packages/postgresql/src/PostgreSqlExceptionConverter.ts:38:16)
      at PostgreSqlDriver.convertException (packages/core/src/drivers/DatabaseDriver.ts:249:50)
      at packages/core/src/drivers/DatabaseDriver.ts:254:18
      at PostgreSqlDriver.nativeInsertMany (packages/knex/src/AbstractSqlDriver.ts:241:13)
      at PostgreSqlDriver.updateCollectionDiff (packages/knex/src/AbstractSqlDriver.ts:573:7)
      at UnitOfWork.persistToDatabase (packages/core/src/unit-of-work/UnitOfWork.ts:591:7)
      at PostgreSqlConnection.transactional (packages/knex/src/AbstractSqlConnection.ts:46:19)
      at UnitOfWork.commit (packages/core/src/unit-of-work/UnitOfWork.ts:232:9)
      at SqlEntityManager.flush (packages/core/src/EntityManager.ts:695:5)
      at SqlEntityManager.persistAndFlush (packages/core/src/EntityManager.ts:639:5)
      at Object.<anonymous> (tests/issues/GH1357.test.ts:50:5)
      previous error: insert into "a_as" ("a_2_id", "a_1_id") values (2, 1) - column "a_2_id" of relation "a_as" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:357:11)
      at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:186:21)
      at Parser.parse (node_modules/pg-protocol/src/parser.ts:101:30)
      at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)
```

**Versions**

| Dependency | Version |
| - | - |
| node | v12.19.1 |
| typescript | 4.1.5 |
| mikro-orm | commit d98612ebfe4149073e354678d016aadde4929b68 |
| your-driver | ? |

**Comment by B4nan** [comment]
Thanks for the repro. Looks like the values are not correctly propagated to the inverse side.

> A similar error is thrown if the inverse side is changed to:
> 
> @ManyToMany({ entity: () => A, inversedBy: 'as' })
> bs = new Collection<A>(this);

By using `inversedBy`, you are making this the owning side. So you end up with two owning sides basically.
