### ISSUE TITLE
MetadataDiscovery - prop.customType.getColumnType is not a function

### ISSUE THREAD

**Issue by LazeKer** [mikro-orm/mikro-orm#1497]
**Describe the bug**
I encounter this error every time after cache generation using the TsMorphMetadataProvider for metadata discovery.

I logged the prop.customType during the first cache generation :
```javascript
 customType: EnumArrayType {
  hydrate: [Function: hydrate],
  owner: 'User.roles',
  items: [ 'USER', 'ADMIN' ]
}
```

The times after:
```javascript
customType: 'customType'
```

Source file: 
https://github.com/mikro-orm/mikro-orm/blob/57b605ccef8c8104db73270effa62d85fd1ed223/packages/core/src/metadata/MetadataDiscovery.ts#L751

**Stack trace**
```
TypeError: prop.customType.getColumnType is not a function
    at MetadataDiscovery.initCustomType (...\api\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:607:106)
    at ...\api\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:48:86
    at Array.forEach (<anonymous>)
    at ...\api\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:48:65
    at Array.forEach (<anonymous>)
    at MetadataDiscovery.discover (...\api\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:48:18)
    at Object.handler (...\api\node_modules\@mikro-orm\cli\commands\GenerateCacheCommand.js:26:9)
```

**Additional context**
The user entity file: 

```typescript
export enum UserRole {
	User = 'USER',
	Admin = 'ADMIN',
}

@Entity()
export class User extends MongoEntity {
	@Property({serializer: value => value.toLowerCase()})
	@IsEmail()
	email: string;

	@Property({serializer: value => value.toLowerCase()})
	@IsNotEmpty()
	firstname: string;

	@Property({serializer: value => value.toLowerCase()})
	@IsNotEmpty()
	lastname: string;

	@Property()
	@IsNotEmpty()
	@Exclude({toPlainOnly: true})
	password: string;

	@Enum({items: () => UserRole, array: true, default: [UserRole.User]})
	roles: UserRole[] = [UserRole.User];
}
```

mikro-orm.config.ts
```typescript
const config = {
  type: 'mongo',
  host: 'localhost',
  username: 'root',
  port: 27017,
  password: 'root',
  dbName: 'mikro',
  entities: ['dist/**/*.entity.js'],
  entitiesTs: ['src/**/*.entity.ts'],
  metadataProvider: TsMorphMetadataProvider,
} as Options;
```

package.json
```json
"mikro-orm": {
    "useTsNode": true,
    "configPaths": [
      "./src/mikro-orm.config.ts",
      "./dist/mikro-orm.config.js"
    ]
  }
```

**Versions**
4.4.4

| Dependency | Version |
| node | 12.2.0 |
| typescript | 4.1.3 |
| mikro-orm | 4.4.4 |
| mikro-orm/mongodb | 4.4.4 |

**Comment by B4nan** [comment]
To work this around you could specify the type yourself:

```ts
	@Enum({items: () => UserRole, array: true, default: [UserRole.User], customType: new EnumArrayType() })
	roles: UserRole[] = [UserRole.User];
```
