### ISSUE TITLE
Using entity manager in hooks for async operations

### ISSUE THREAD

**Issue by bahdcoder** [mikro-orm/mikro-orm#1503]
**Describe the bug**
Performing async operations such as `em.findOne` or `em.find`  in `afterCreate` / `beforeCreate` hooks result in a time out error shown below:

**Stack trace**
```
ERROR    (DriverException): Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    DriverException: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
        at SqliteExceptionConverter.convertException (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
        at SqliteExceptionConverter.convertException (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/sqlite/SqliteExceptionConverter.js:46:22)
        at SqliteDriver.convertException (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:171:54)
        at /Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:175:24
        at async SqliteDriver.find (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:42:24)
        at async SqliteDriver.findOne (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:56:21)
        at async SqlEntityManager.findOne (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/core/EntityManager.js:192:22)
        at async /Users/bahdcoder/Projects/tensei/examples/blog/index.js:71:36
        at async Promise.all (index 0)
        at async Function.runSerial (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/core/utils/Utils.js:458:22)
    
    previous KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
        at Client_SQLite3.acquireConnection (/Users/bahdcoder/Projects/tensei/node_modules/knex/lib/client.js:348:26)
        at async SqliteConnection.executeQuery (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/core/connections/Connection.js:56:25)
        at async SqliteConnection.execute (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:67:21)
        at async QueryBuilder.execute (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/knex/query/QueryBuilder.js:274:21)
        at async SqliteDriver.find (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:42:24)
        at async SqliteDriver.findOne (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:56:21)
        at async SqlEntityManager.findOne (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/core/EntityManager.js:192:22)
        at async /Users/bahdcoder/Projects/tensei/examples/blog/index.js:71:36
        at async Promise.all (index 0)
        at async Function.runSerial (/Users/bahdcoder/Projects/tensei/node_modules/@mikro-orm/core/utils/Utils.js:458:22)

```

**To Reproduce**
1. Create a model
2. Add a `beforeCreate` hook. 
3. Perform an operation with entity manager in the hook.

**Expected behavior**
I think this is supposed to be sync, but maybe a feature request would be to allow async operations in model hooks.

**Versions**

| Dependency | Version |
| - | - |
| node | 15.0 |
| mikro-orm | ^4.4.0 |
| your-driver | sqlite |

**Comment by B4nan** [comment]
Hooks can be async, and that itself works fine. This is sqlite related, other drivers work fine, probably because sqlite will have pool of size 1.
