### ISSUE TITLE
GraphQLError: cannot represent value on custom type nullable field

### ISSUE THREAD

**Issue by abelland** [mikro-orm/mikro-orm#1514]
**Describe the bug**
Given a custom type class:
```
import { EntityProperty, Type } from "@mikro-orm/core";

export class CustomString extends Type<StringValueObject, string> {
  private _value = "";

  get value(): string {
    return this._value;
  }

  private constructor(value: string) {
    super();
    this._value = value;
  }

  public static create(value: string): StringValueObject {
    return new StringValueObject(value);
  }

  convertToDatabaseValue(value: string | StringValueObject): string {
    return value instanceof StringValueObject ? value.value : value;
  }

  convertToJSValue(value: string): StringValueObject {
    return StringValueObject.create(value);
  }

  toJSON(value: StringValueObject): string | null {
    return value?.value || this.value;
  }

  getColumnType(prop: EntityProperty): string {
    return `varchar(${prop.length || 255})`;
  }
}

```

and used as a type in a property

```
  @Property({ type: CustomString, nullable: true })
  aNullableStringField: CustomString;
```

i have the following error when the value of the field is `null`:
```
GraphQLError: String cannot represent value: { _value: \"\" }
```

**Stack trace**
```
"GraphQLError: String cannot represent value: { _value: \"\" }",
            "    at GraphQLScalarType.serializeString [as serialize] (/app/node_modules/graphql/type/scalars.js:173:9)",
            "    at completeLeafValue (/app/node_modules/graphql/execution/execute.js:654:37)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:580:12)",
            "    at resolveField (/app/node_modules/graphql/execution/execute.js:474:19)",
            "    at executeFields (/app/node_modules/graphql/execution/execute.js:294:18)",
            "    at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:749:10)",
            "    at completeObjectValue (/app/node_modules/graphql/execution/execute.js:739:10)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:592:12)",
            "    at completeValue (/app/node_modules/graphql/execution/execute.js:558:21)",
            "    at /app/node_modules/graphql/execution/execute.js:471:16",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
            "    at async Promise.all (index 10)",
            "    at async Promise.all (index 0)"
          ]
```

**To Reproduce**
1. Create a custom type 
2. assign it to an entity field
3. run migrations
4. set `null` (if necessary) to the created field
5. query the field with graphql

**Expected behavior**
handle the `null` value on a nullable custom type property

**Versions**

| Dependency | Version |
| - | - |
| node | v14.15.4 |
| typescript |  3.9.7 |
| mikro-orm | 4.3.4 |
| your-driver | Postgresql |

**Comment by B4nan** [comment]
As you said, its GQL error, why are you reporting it here? 

If you want to report MikroORM issue, provide a repro (full repro, executable) that does not use GQL to proove its actually MikroORM issue.
