### ISSUE TITLE
Cannot destructure property className - NestJS, MongoDB

### ISSUE THREAD

**Issue by Beleren** [mikro-orm/mikro-orm#1543]
## Issue

Hello, I'm currently trying to use this ORM in a nest js application with docker, running the application locally doesn't throw any errors but it does when i build and run the project inside a container.

```
TypeError: Cannot destructure property 'className' of 'Configuration.PLATFORMS[this.options.type]' as it is undefined.
|     at Configuration.initDriver (/home/app/node_modules/@mikro-orm/core/utils/Configuration.js:151:21)
|     at new Configuration (/home/app/node_modules/@mikro-orm/core/utils/Configuration.js:25:28)
|     at new MikroORM (/home/app/node_modules/@mikro-orm/core/MikroORM.js:20:27)
|     at Function.init (/home/app/node_modules/@mikro-orm/core/MikroORM.js:38:21)
|     at InstanceWrapper.useFactory [as metatype] (/home/app/node_modules/@mikro-orm/nestjs/mikro-orm.providers.js:21:32)
|     at Injector.instantiateClass (/home/app/node_modules/@nestjs/core/injector/injector.js:289:55)
|     at callback (/home/app/node_modules/@nestjs/core/injector/injector.js:42:41)
|     at async Injector.resolveConstructorParams (/home/app/node_modules/@nestjs/core/injector/injector.js:114:24)
|     at async Injector.loadInstance (/home/app/node_modules/@nestjs/core/injector/injector.js:46:9)
|     at async Injector.loadProvider (/home/app/node_modules/@nestjs/core/injector/injector.js:68:9)
```

This error is similar to [documentation's circular dependency error](https://mikro-orm.io/docs/installation/#possible-issues-with-circular-dependencies). I tried to replace the MikroORM's Nest plugin config `entities` array items with the `entity` import but it logs the same error.

------

## Code

- **app.module.ts**
```typescript
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { MobileAppModule } from './mobile-app/mobile-app.module';
import { DatabaseModule } from './database/database.module';
import { ConfigModule } from '@nestjs/config';

@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true }),
    AppModule,
    DatabaseModule,
    MobileAppModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}

```

- **databse.module.ts**
```typescript
import { Module } from '@nestjs/common';
import { MikroOrmModule } from '@mikro-orm/nestjs';
import { ConfigModule, ConfigService } from '@nestjs/config';
import {
  DATABASE_NAME,
  DATABASE_TYPE,
  DATABASE_DNS,
} from './database.constants';

@Module({
  imports: [
    MikroOrmModule.forRootAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => ({
        entities: ['./dist/**/*.schema.js'],
        entitiesTs: ['./src/**/*.schema.ts'],
        dbName: configService.get(DATABASE_NAME),
        type: configService.get(DATABASE_TYPE),
        clientUrl: configService.get(DATABASE_DNS),
      }),
    }),
  ],
})
export class DatabaseModule {}

```

- **mobile-app.schema.ts**
```typescript
import {
  Entity,
  EntityRepositoryType,
  Enum,
  PrimaryKey,
  Property,
  SerializedPrimaryKey,
} from '@mikro-orm/core';
import { ObjectId } from '@mikro-orm/mongodb';
import { MobileAppRepository } from './mobile-app.repository';

export enum Platform {
  GOOGLE_ANDROID = 'Google Android',
  APPLE_IOS = 'Apple iOS',
}
@Entity({ collection: 'mobileapps' })
export class MobileApp {
  [EntityRepositoryType]?: MobileAppRepository;

  @PrimaryKey()
  _id!: ObjectId;

  @SerializedPrimaryKey()
  id!: string;

  @Property()
  name!: string;

  @Property()
  bundle!: string;

  @Property()
  storeLink!: string;

  @Enum(() => Platform)
  platform: Platform;

  @Property()
  category!: string;
}

```

- **Dockerfile**
```dockerfile
FROM node:12.16-alpine

WORKDIR /home/app

COPY package*.json yarn.lock ./

RUN yarn install --frozen-lockfile 
RUN yarn cache clean

COPY . .

RUN yarn build

CMD ["node", "dist/main.js"]
```

- **docker-compose.yml**
```yaml
version: '3'
services:
  ingest-v2:
    container_name: ingest-v2
    build: .
    env_file: .env
    ports:
      - '40001:40001'
      - '9229:9229'
    command: yarn start:dev
    volumes:
      - ./src:/home/app/src:cached
    depends_on:
      - ingest-v2-mongo

  ingest-v2-mongo:
    image: mongo:3.4
    container_name: ingest-v2-mongo
    restart: on-failure
    ports:
      - 3001:27017
    volumes:
      - ./.data/mongo:/data/db:cached
```

| Dependency         | Version |
|--------------------|---------|
| Node               | 12.16.1 |
| typescript         | ^3.7.4  |
| @mikro-orm/core    | ^4.4.4  |
| @mikro-orm/nestjs  | ^4.2.0  |
| @mikro-orm/mongodb | ^4.4.4  |

**Comment by B4nan** [comment]
Well this sounds like your `type` inside config is undefined or more probably invalid. You need to use one of the existing platform types.

**Comment by B4nan** [comment]
This is indeed invalid `type` in your config, I thought we had this validated, but apparently we only validate the value is set, but not whether it is a known type. 

Valid platform type are: `mongo`, `mysql`, `mariadb`, `postgresql`, `sqlite`

**Comment by Beleren** [comment]
> This is indeed invalid `type` in your config, I thought we had this validated, but apparently we only validate if the value is set, but not whether it is a known type.
> 
> Valid platform types are: `mongo`, `mysql`, `mariadb`, `postgresql`, `sqlite`

I much appreciate the replying speed you have with this repo's issues. I'll validate this case in my project. Would it be possible to have a more user friendly warning in this case? @B4nan

**Comment by B4nan** [comment]
Yes, already have a todo note in the code, I am all in for better validation.
