### ISSUE TITLE
Validate that inverse side of 1:m is a m:1 relation (not 1:1)

### ISSUE THREAD

**Issue by ceopaludetto** [mikro-orm/mikro-orm#1568]
**Describe the bug**
When I try to insert nested data with many to many relation the error below occurs:

**Stack trace**
```
err: {
      "type": "TypeError",
      "message": "collection.getItems is not a function",
      "stack":
          TypeError: collection.getItems is not a function
              at UnitOfWork.cascadeReference (/home/carlos/Documents/Projetos/Javascript/with-loadable-components/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:386:18)
              at UnitOfWork.cascade (/home/carlos/Documents/Projetos/Javascript/with-loadable-components/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:366:18)
              at UnitOfWork.cascadeReference (/home/carlos/Documents/Projetos/Javascript/with-loadable-components/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:377:25)
              at UnitOfWork.cascade (/home/carlos/Documents/Projetos/Javascript/with-loadable-components/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:366:18)
              at UnitOfWork.cascadeReference (/home/carlos/Documents/Projetos/Javascript/with-loadable-components/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:377:25)
              at UnitOfWork.cascade (/home/carlos/Documents/Projetos/Javascript/with-loadable-components/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:366:18)
              at /home/carlos/Documents/Projetos/Javascript/with-loadable-components/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:388:39
              at Array.forEach (<anonymous>)
              at UnitOfWork.cascadeReference (/home/carlos/Documents/Projetos/Javascript/with-loadable-components/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:388:18)
              at UnitOfWork.cascade (/home/carlos/Documents/Projetos/Javascript/with-loadable-components/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:366:18)
}
```

**To Reproduce**

My Condominium Model:
```ts
import { Entity, Property, ManyToMany, Collection, OneToMany, OneToOne } from "@mikro-orm/core";
import { ObjectType, Field } from "@nestjs/graphql";

import { CONDOMINIUM, PERSON_CONDOMINIUM } from "../utils/constants";
import { ModelRef } from "../utils/model-ref";
import type Address from "./address.model";
import BaseModel from "./base.model";
import type Block from "./block.model";
import type Local from "./local.model";
import type Person from "./person.model";

@ObjectType(CONDOMINIUM)
@Entity({ tableName: CONDOMINIUM })
export default class Condominium extends BaseModel {
  @Field()
  @Property()
  public companyName!: string;

  @Field()
  @Property({ unique: true })
  public cnpj!: string;

  @Field({ defaultValue: "#" })
  @Property({ default: "#" })
  public character!: string;

  @Field(() => [ModelRef("block.model")])
  @OneToMany({ entity: () => ModelRef("block.model"), mappedBy: (block: Block) => block.condominium })
  public blocks: Collection<Block> = new Collection<Block>(this);

  @Field(() => [ModelRef("local.model")])
  @OneToMany({ entity: () => ModelRef("local.model"), mappedBy: (local: Local) => local.condominium })
  public locals: Collection<Local> = new Collection<Local>(this);

  @Field(() => ModelRef("address.model"))
  @OneToOne({ entity: () => ModelRef("address.model"), mappedBy: (address: Address) => address.condominium })
  public address!: Address;

  @Field(() => [ModelRef("person.model")])
  @ManyToMany({
    entity: () => ModelRef("person.model"),
    pivotTable: PERSON_CONDOMINIUM,
    joinColumn: "condominium",
    inverseJoinColumn: "person",
    inversedBy: "condominiums",
  })
  public people: Collection<Person> = new Collection<Person>(this);
}
```

My Person Model:
```ts
import { Entity, Property, Enum, OneToOne, OneToMany, Collection, ManyToMany } from "@mikro-orm/core";
import { ObjectType, Field, registerEnumType } from "@nestjs/graphql";

import { PERSON } from "../utils/constants";
import { Gender } from "../utils/enums";
import { ModelRef } from "../utils/model-ref";
import BaseModel from "./base.model";
import type Condominium from "./condominium.model";
import type Phone from "./phone.model";
import type User from "./user.model";

function generateHexColor() {
  return `#${Math.floor(Math.random() * 16777215).toString(16)}`;
}

registerEnumType(Gender, {
  name: "Gender",
});

@ObjectType(PERSON)
@Entity({ tableName: PERSON })
export default class Person extends BaseModel {
  @Field()
  @Property()
  public name!: string;

  @Field()
  @Property()
  public lastName!: string;

  @Field()
  @Property({ unique: true })
  public email!: string;

  @Field(() => Gender)
  @Enum(() => Gender)
  public gender!: Gender;

  @Field()
  @Property()
  public cpf!: string;

  @Field()
  @Property()
  public color: string = generateHexColor();

  @Field()
  @Property()
  public birthdate!: Date;

  @Field(() => [ModelRef("phone.model")])
  @OneToMany({ entity: () => ModelRef("phone.model"), mappedBy: (phone: Phone) => phone.person, orphanRemoval: true })
  public phones: Collection<Phone> = new Collection<Phone>(this);

  @Field(() => ModelRef("user.model"))
  @OneToOne({ entity: () => ModelRef("user.model"), mappedBy: (user: User) => user.person })
  public user!: User;

  @Field(() => [ModelRef("condominium.model")])
  @ManyToMany({
    entity: () => ModelRef("condominium.model"),
    mappedBy: (condominium: Condominium) => condominium.people,
  })
  public condominiums: Collection<Condominium> = new Collection<Condominium>(this);
}

```

ModelRef Util(this util is needed to avoid cycle deps in webpack compilation, I've tried to change to string names in relations but @nestjs/graphql does not support this option in field decorator, then I've created this util):
```ts
import type { Type } from "@nestjs/common";

export function ModelRef<T>(path: string): Type<T> {
  if (module.hot) {
    return require(`@/server/models/${path}`).default as Type<T>;
  }

  return require(`../models/${path}`).default as Type<T>;
}

```

Test data:
```json
{
  "login":"userName",
  "password":"aPassword123#",
  "person":{
    "name":"Carlos Eduardo",
    "lastName":"de Oliveira Paludetto",
    "email":"stub@mail.com",
    "gender":"M",
    "cpf":"555.555.555-55",
    "birthdate":"some now date",
    "phones":[
      {
        "ddd":"11",
        "number":"95215-1529"
      }
    ],
    "condominiums":[
      {
        "companyName":"Edificio Itália",
        "cnpj":"55.555.555/5555-55",
        "address":{
          "zip":"55555-555",
          "address":"Rua Correia Barbosa",
          "number":"17",
          "city":"cityID"
        }
      }
    ]
  }
}
```

The service who run this mutation:
```ts
public async create(data: UserInsertInput) {
  const user = this.userModel.create(data);

  await this.flush(user);

  return user;
}
```

When I send an empty array in condominiums field, no error are thrown and flush runs correctly, but when i send condominiums inside array, mikro-orm throw the error.

**Expected behavior**
Should insert nested data

**Additional context**
I run this server in webpack using reflect-metadata and I followed https://mikro-orm.io/docs/deployment#running-webpack,  

**Versions**

| Dependency | Version |
| - | - |
| node | 12.16.2 |
| typescript | 4.2.3 |
| mikro-orm | 4.4.4 |
| pg | 8.5.1 |

**Comment by B4nan** [comment]
Please provide full repro, without GQL, and stripped from the irrelevant things (e.g. scalar properties or in general everything you can remove while still reproduing the issue - the repro should be minimal). On the other hand, the repro needs to be complete, if the entities you ommited are not related, then remove them as a whole (e.g. `Phone` or `Address` entities, or the enums). 

Probably won't be webpack related, my guess is an issue with the `em.create()` method not constructing the entity graph correctly.

**Comment by ceopaludetto** [comment]
When I was creating the repro i found the error. My relation between city and address are incorrect, in one side i put the OneToMany decorator, but, in the other side i put OneToOne decorator instead of ManyToOne, in city field i send the city id, this throw the error above.

I think there's possible to hint developer about misleading decorators. In one side we have the mappedBy property and the model, we can see if the other side has properly declared the decorator. Just to simplify, if we have an OneToMany in one side, we can check if we have ManyToOne in the other side. ~Sorry about the incorrect english~. Thanks for the fast reply.
