### ISSUE TITLE
Nested em.create not respecting default entity values with Reference wrapper

### ISSUE THREAD

**Issue by Langstra** [mikro-orm/mikro-orm#1592]
**Describe the bug**
Creating an entity using `em.create` when using TsMorphMetadataProvider gives different results than it does with ReflectMetadataProvider. Example:
```typescript
const radio = orm.em.create(Radio, {
  question: 'bla bla',
  option: {
    enabled: false
  }
});
```

Where `Option` has a property `createdAt = new Date()`. The `createdAt` property is not set on the option and when flushing this it gives the following database error.

**Stack trace**
```
NotNullConstraintViolationException: insert into `radio_option` (`enabled`) values (false) - SQLITE_CONSTRAINT: NOT NULL constraint failed: radio_option.created_at

    at SqliteExceptionConverter.convertException (/home/langstra/Documents/mikro-orm/packages/sqlite/src/SqliteExceptionConverter.ts:29:14)
    at SqliteDriver.convertException (/home/langstra/Documents/mikro-orm/packages/core/src/drivers/DatabaseDriver.ts:259:50)
    at /home/langstra/Documents/mikro-orm/packages/core/src/drivers/DatabaseDriver.ts:264:18
    at SqliteDriver.nativeInsert (/home/langstra/Documents/mikro-orm/packages/knex/src/AbstractSqlDriver.ts:190:17)
    at ChangeSetPersister.persistNewEntity (/home/langstra/Documents/mikro-orm/packages/core/src/unit-of-work/ChangeSetPersister.ts:68:17)
    at ChangeSetPersister.executeInserts (/home/langstra/Documents/mikro-orm/packages/core/src/unit-of-work/ChangeSetPersister.ts:29:7)
    at UnitOfWork.commitCreateChangeSets (/home/langstra/Documents/mikro-orm/packages/core/src/unit-of-work/UnitOfWork.ts:628:5)
    at UnitOfWork.persistToDatabase (/home/langstra/Documents/mikro-orm/packages/core/src/unit-of-work/UnitOfWork.ts:579:7)
    at SqliteConnection.transactional (/home/langstra/Documents/mikro-orm/packages/knex/src/AbstractSqlConnection.ts:46:19)
    at UnitOfWork.commit (/home/langstra/Documents/mikro-orm/packages/core/src/unit-of-work/UnitOfWork.ts:239:9)
    at SqlEntityManager.flush (/home/langstra/Documents/mikro-orm/packages/core/src/EntityManager.ts:699:5)
    at SqlEntityManager.persistAndFlush (/home/langstra/Documents/mikro-orm/packages/core/src/EntityManager.ts:643:5)
    at Object.<anonymous> (/home/langstra/Documents/mikro-orm/tests/issues/GH15xx.test.ts:79:5)

previous Error: insert into `radio_option` (`enabled`) values (false) - SQLITE_CONSTRAINT: NOT NULL constraint failed: radio_option.created_at
```

**To Reproduce**
1. Checkout to the branch of MR #1591
2. `$ yarn test GH issue 1592`
3. Check the error

**Expected behavior**
With both meta data providers it should have the same behavior.

**Versions**
Master

**Comment by B4nan** [comment]
FYI this has nothing to do with ts-morph, it's caused by the reference wrapper.
