### ISSUE TITLE
DriverException: set session_replication_role = 'replica'; - permission denied to set parameter "session_replication_role"

### ISSUE THREAD

**Issue by woltob** [mikro-orm/mikro-orm#1612]
**Describe the bug**

Getting this error while trying to run migrations `npx mikro-orm schema:create -r` :

DriverException: set session_replication_role = 'replica'; - permission denied to set parameter "session_replication_role"

Connecting to a managed PostgreSQL database on Azure.
Checked the other open issues for that already, like setting wrap: false or using the --disable-fk-checks option.

Nothing works. We would like to use MikroORM for production for our API and need this urgently to work.
Is a downgrade a potential solution?

This is my config:

```
const mikroOrmPostgresConfig = {
  migrations: {
    tableName: 'mikro_orm_migrations', // name of database table with log of executed transactions
    path: SRC_DIR + 'migrations/', // path to the folder with migrations
    emit: 'ts', // migration generation mode
    // pattern: /^[\w-]+\d+\.ts$/, // regex pattern for the migration files
    // transactional: true, // wrap each migration in a transaction
    // disableForeignKeys: false, // wrap statements with `set foreign_key_checks = 0` or equivalent
    // allOrNothing: true, // wrap all migrations in master transaction
    // dropTables: true, // allow to disable table dropping
    // safe: false, // allow to disable table and column dropping
    wrap: false,
  },
  metadataProvider: TsMorphMetadataProvider,
  tsNode: process.env.NODE_ENV === 'development' ? true : false,
  dbName: process.env.DATABASE_NAME,
  host: process.env.DATABASE_HOST,
  port: process.env.DATABASE_PORT,
  user: process.env.DATABASE_USER,
  password: process.env.DATABASE_PASSWORD,
  debug: true,
  ssl: true,
  wrap: false,
  driverOptions: {
    connection: { ssl: true },
    wrap: false,
  },
  logger: logger.log.bind(logger),
  entities: [ROOT_DIR + 'dist/entities/*.js'],
  entitiesTs: [ROOT_DIR + 'src/entities/*.ts'],
  type: 'postgresql',
  cli: {
    migrationsDir: SRC_DIR + 'migrations',
  },
} as Options;
```

**Stack trace**
```
[Nest] 57232   - 25/03/2021, 23:41:55   [MikroORM] [info] MikroORM successfully connected to database company_name_development on postgresql://postgresuser@company-name-db:*****@company-name-database.postgres.database.azure.com:5432
[Nest] 57232   - 25/03/2021, 23:41:56   [MikroORM] [query] select 1 from pg_database where datname = 'company_name_development' [took 45 ms]
[Nest] 57232   - 25/03/2021, 23:41:56   [MikroORM] [query] set names 'utf8'; [took 18 ms]
[Nest] 57232   - 25/03/2021, 23:41:56   [MikroORM] [query] set session_replication_role = 'replica'; [took 30 ms]
mikro-orm schema:create

Create database schema based on current metadata

Options:
  -r, --run      Runs queries                                          [boolean]
  -d, --dump     Dumps all queries to console                          [boolean]
  --fk-checks    Do not skip foreign key checks                        [boolean]
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]

DriverException: set session_replication_role = 'replica'; - permission denied to set parameter "session_replication_role"
    at PostgreSqlExceptionConverter.convertException (/Users/my_username/Documents/company_name/source_code/backend/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException (/Users/my_username/Documents/company_name/source_code/backend/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:40:22)
    at PostgreSqlDriver.convertException (/Users/my_username/Documents/company_name/source_code/backend/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:194:54)
    at /Users/my_username/Documents/company_name/source_code/backend/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:198:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at SchemaGenerator.execute (/Users/my_username/Documents/company_name/source_code/backend/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:119:13)
    at SchemaGenerator.createSchema (/Users/my_username/Documents/company_name/source_code/backend/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:27:9)
    at Function.handleSchemaCommand (/Users/my_username/Documents/company_name/source_code/backend/node_modules/@mikro-orm/cli/commands/SchemaCommandFactory.js:75:13)

previous error: set session_replication_role = 'replica'; - permission denied to set parameter "session_replication_role"
    at Parser.parseErrorMessage (/Users/my_username/Documents/company_name/source_code/backend/node_modules/pg-protocol/src/parser.ts:357:11)
    at Parser.handlePacket (/Users/my_username/Documents/company_name/source_code/backend/node_modules/pg-protocol/src/parser.ts:186:21)
    at Parser.parse (/Users/my_username/Documents/company_name/source_code/backend/node_modules/pg-protocol/src/parser.ts:101:30)
    at TLSSocket.<anonymous> (/Users/my_username/Documents/company_name/source_code/backend/node_modules/pg-protocol/src/index.ts:7:48)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 121,
  severity: 'ERROR',
  code: '42501',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'guc.c',
  line: '6745',
  routine: 'set_config_option'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! company_name-backend@0.0.1 db:init: `mikro-orm schema:create -r`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the company_name-backend@0.0.1 db:init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/my_username/.npm/_logs/2021-03-25T22_41_56_099Z-debug.log
```

**To Reproduce**
1. NestJS project with MikroORM and Azure managed Postgresql database (open port for your internet IP address)
2. Run npx mikro-orm schema:create -r
3. see what happens

**Expected behavior**
MIgrations should run normally.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.5 |
| typescript | 4.2.3 |
| mikro-orm | 4.5.0 |
| your-driver | postgres |

**Comment by woltob** [comment]
Whoever had this problem:

``` npx mikro-orm schema:create --fk-checks -r ```

solved it with my above settings.

It works now.

**Comment by B4nan** [comment]
`disableForeignKeys: false`
