### ISSUE TITLE
Entity Discovery depending on export/export default

### ISSUE THREAD

**Issue by rafaelvasco** [mikro-orm/mikro-orm#1633]
**Describe the bug**
When initializing mikro-orm using either:

Ex.:
```
entities: ['./dist/model/*.model.js'],
entitiesTs: ['./src/model/*.model.ts'],
```

or by passing the entities directly, it results in:

`mikro-orm Entity 'any' was not discovered`

when not using export default on the entities classes, 
with export default it works perfectly.

**Stack trace**
```
 return new MetadataError(`Entity '${className}' was not discovered, please make sure to provide it in 'entities' array when initializing the ORM (used in ${source})`);
               ^
MetadataError: Entity 'any' was not discovered, please make sure to provide it in 'entities' array when initializing the ORM (used in Item.type)
    at Function.fromUnknownEntity (C:\Dev\youteepme_backend\node_modules\@mikro-orm\core\errors.js:142:16)
    at C:\Dev\youteepme_backend\node_modules\@mikro-orm\core\metadata\MetadataValidator.js:49:46
    at Array.forEach (<anonymous>)
    at C:\Dev\youteepme_backend\node_modules\@mikro-orm\core\metadata\MetadataValidator.js:47:67
    at Array.forEach (<anonymous>)
    at MetadataValidator.validateDiscovered (C:\Dev\youteepme_backend\node_modules\@mikro-orm\core\metadata\MetadataValidator.js:47:20)
    at MetadataDiscovery.findEntities (C:\Dev\youteepme_backend\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:81:24)
    at MetadataDiscovery.discover (C:\Dev\youteepme_backend\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:34:9)
    at Function.init (C:\Dev\youteepme_backend\node_modules\@mikro-orm\core\MikroORM.js:42:24)
```

**To Reproduce**
1. Create an annotated entity class without export default
2. Define entities and entitiesTs arrays on ORM init, either using path based or by passing the classes directly
3. Run project using `ts-node -r tsconfig-paths/register src/index.ts`

**Expected behavior**
Entities get discovered normally.

**Additional context**
I was using export default class on my entities classes. mikro-orm discovered the classes and initialized without issues. After changing to export class instead, and then importing the classes from a index.ts on my entities folder it resulted in aforementioned error.

**Versions**

| Dependency | Version |
| - | - |
| node | 15.9.0 |
| typescript | 4.2.3 |
| mikro-orm | 4.5.1 |
| your-driver | mongo |

**Comment by B4nan** [comment]
If you look at the ORM tests, there is maybe one entity using default export, and dozens of regular named exports. Same with the example apps, all of them are using named exports.

So please provide full reproduction, executable one, as this is not enough to reproduce.

**Comment by rafaelvasco** [comment]
Yeah , strange. Example I was following used named exports. Probably something on my side. Going to close this for now then as I can't provide full reproduction.

**Comment by B4nan** [comment]
Btw are you using ts-morph? As that is the only way I could understand the type being infered as `any`. If so, is this from production run (via node)? If so, do you have `compilerOptions.declaration` enabled in your `tsconfig.json`? As the `d.ts` files are used for reflection when running via `node`.

**Comment by rafaelvasco** [comment]
Ah, yes. My bad , I forgot to mention. Yes, I'm using `TsMorphMetadataProvider`. I have declaration enabled, yes, but I'm running start script , my scripts section:

```
"scripts": {
        "start": "ts-node -r tsconfig-paths/register src/index.ts",
        "dev": "node ./node_modules/nodemon/bin/nodemon.js"
    },
```

**Comment by B4nan** [comment]
So you are using `nodemon`? What about without that, just `yarn start`?

**Comment by rafaelvasco** [comment]
Same result.

**Comment by rafaelvasco** [comment]
Maybe something in my tsconfig ? 

```
{
    "compilerOptions": {
        "target": "ES6",
        "lib": ["esnext"],
        "outDir": "./dist",
        "sourceMap": true,
        "strict": true,
        "strictNullChecks": true,
        "forceConsistentCasingInFileNames": true,
        "noUnusedLocals": true,
        "noImplicitReturns": true,
        "esModuleInterop": true,
        "module": "CommonJS",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "declaration": true,
        "isolatedModules": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "strictPropertyInitialization": false,
        "baseUrl": "./src"
    },
    "include": ["**/*.ts"],
    "exclude": ["node_modules", "dist"]
}
```

**Comment by rafaelvasco** [comment]
Updating on this:

There was a property on one of my entities annotated with:

`@ManyToOne()`

I noted this property was mentioned in the error. Figured it was not being resolved , so I changed it to:

`@ManyToOne({ entity: () => ItemType })`


Then it worked. I didn't saw It mentioned in the docs, but anyways , maybe , with a setup like mine, using ts-morph and ts-node , for these kind of properties you have to annotate it like that. As it was unable to resolve without the property. 

Thank you for the help.

**Comment by B4nan** [comment]
The ts-morph provider will literally read the type from TS compiler. So if it resolves to `any`, you probably have some circular dependency such that even TS won't resolve the type correctly. I would expect that if you hover over that property, you will see `any` too. On the other hand with `noImplicitAny` (which is enabled in strict mode), it should complain on compilation.

In general this should not be a problem with ts-morph, maybe you are hitting some edge case in `tsc` type resolving, or it's something with how you define/import the type in that file. How does the entity definition look like?

**Comment by rafaelvasco** [comment]
```
import { Entity, ManyToOne, Property } from '@mikro-orm/core'
import { BaseModel, ItemType } from 'model'

@Entity({ collection: 'items' })
export class Item extends BaseModel {
    @Property()
    name!: string

    @ManyToOne({ entity: () => ItemType })
    type!: ItemType

    constructor(name: string, type: ItemType) {
        super()
        this.name = name
        this.type = type
    }
}
```

```
import { Entity, Property } from '@mikro-orm/core'
import { BaseModel } from 'model'

@Entity({ collection: 'types' })
export class ItemType extends BaseModel {
    @Property()
    name!: string

    @Property()
    color!: string

    constructor(name: string, color: string) {
        super()
        this.name = name
        this.color = color
    }
}
```
