### ISSUE TITLE
Fetching entities via composite @ManyToOne sub-entity throws error

### ISSUE THREAD

**Issue by ZilRahman** [mikro-orm/mikro-orm#1695]
**Describe the bug**
Continuation of the same entities from #1687 

When I go to fetch all the users in a given city by using the following query, I get an error.

````
// fetch city with a given id, this is successful.
const city = await em.findOneOrFail(City, {id: input.cityId})
        
// This line throws the error.
const users = await em.find(User, {city}) 

````

**Stack trace**
```
Error: Trying to query by not existing property City.country
    at /Users/zil/Developer/test/lib/APP/api/node_modules/@mikro-orm/knex/dist/query/CriteriaNode.js:21:27
    at Array.forEach (<anonymous>)
    at new CriteriaNode (/Users/zil/Developer/test/lib/APP/api/node_modules/@mikro-orm/knex/dist/query/CriteriaNode.js:18:48)
    at new ScalarCriteriaNode (/Users/zil/Developer/test/lib/APP/api/node_modules/@mikro-orm/knex/dist/query/ScalarCriteriaNode.js:6:1)
    at Function.createScalarNode (/Users/zil/Developer/test/lib/APP/api/node_modules/@mikro-orm/knex/dist/query/CriteriaNodeFactory.js:22:22)
    at Function.createNode (/Users/zil/Developer/test/lib/APP/api/node_modules/@mikro-orm/knex/dist/query/CriteriaNodeFactory.js:19:21)
    at Function.createObjectItemNode (/Users/zil/Developer/test/lib/APP/api/node_modules/@mikro-orm/knex/dist/query/CriteriaNodeFactory.js:47:25)
    at /Users/zil/Developer/test/lib/APP/api/node_modules/@mikro-orm/knex/dist/query/CriteriaNodeFactory.js:38:28
    at Array.reduce (<anonymous>)
    at Function.createObjectNode (/Users/zil/Developer/test/lib/APP/api/node_modules/@mikro-orm/knex/dist/query/CriteriaNodeFactory.js:37:45)
    at Function.createNode (/Users/zil/Developer/test/lib/APP/api/node_modules/@mikro-orm/knex/dist/query/CriteriaNodeFactory.js:17:25)
    at /Users/zil/Developer/test/lib/APP/api/node_modules/@mikro-orm/knex/dist/query/CriteriaNodeFactory.js:28:49
    at Array.map (<anonymous>)
    at Function.createArrayNode (/Users/zil/Developer/test/lib/APP/api/node_modules/@mikro-orm/knex/dist/query/CriteriaNodeFactory.js:28:32)
    at Function.createNode (/Users/zil/Developer/test/lib/APP/api/node_modules/@mikro-orm/knex/dist/query/CriteriaNodeFactory.js:14:25)
    at Function.createObjectItemNode (/Users/zil/Developer/test/lib/APP/api/node_modules/@mikro-orm/knex/dist/query/CriteriaNodeFactory.js:47:25)
```

**To Reproduce**
1. Populate city, state and user table with data.
2. Run this query.

**Expected behavior**
I should get a list of all the users that are in a given city.

**Versions**

| Dependency | Version |
| - | - |
| node | 15.10.0 |
| typescript | 4.1.5 |
| mikro-orm | 4.5.4-dev.9 |
| mikro-orm/pstgresql | 4.5.4-dev.9 |

**Comment by B4nan** [comment]
`4.5.4-dev.11`
