### ISSUE TITLE
Unable to run npx mikro-orm migration:create

### ISSUE THREAD

**Issue by cbadger85** [mikro-orm/mikro-orm#1697]
**Describe the bug**
Unable to run `npx mikro-orm migration:create`. I receive an

```
npm ERR! could not determine executable to run
```

**Stack trace**
I don't have a stack trace, but I do have a dump of the log from npm
```
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/Users/cbadger85/.config/yarn/global/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'mikro-orm',
0 verbose cli   'migration:create'
0 verbose cli ]
1 info using npm@7.5.4
2 info using node@v12.18.2
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/Users/cbadger85/.config/yarn/global/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/cbadger85/projects/graphql-experiment/service/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/Users/cbadger85/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 6ms
19 verbose npm-session c409978ae4f3232a
20 timing npm:load Completed in 12ms
21 http fetch GET 200 https://registry.npmjs.org/mikro-orm 891ms
22 timing command:exec Completed in 913ms
23 verbose stack Error: could not determine executable to run
23 verbose stack     at getBinFromManifest (/Users/cbadger85/.config/yarn/global/node_modules/npm/lib/exec.js:272:23)
23 verbose stack     at exec (/Users/cbadger85/.config/yarn/global/node_modules/npm/lib/exec.js:182:15)
24 verbose cwd /Users/cbadger85/projects/graphql-experiment/service
25 verbose Darwin 18.7.0
26 verbose argv "/usr/local/bin/node" "/Users/cbadger85/.config/yarn/global/node_modules/npm/bin/npm-cli.js" "exec" "--" "mikro-orm" "migration:create"
27 verbose node v12.18.2
28 verbose npm  v7.5.4
29 error could not determine executable to run
30 verbose exit 1
```

**To Reproduce**
1. run `npx mikro-orm migration:create`

**Expected behavior**
A migration diff to be created.

**Additional context**
I've also tried just running `npx mikro-orm` and received the same error. I've also tried running `yarn mikro-orm migration:create` and creating a script in my `package.json` and receive the following error:

```
yarn run v1.22.10
error Command "mikro-orm" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Versions**
4.5.3

| Dependency | Version |
| - | - |
| node | 12.18.2 |
| typescript | 4.2.4 |
| mikro-orm | 4.5.3 |
| your-driver | postgres |

**Comment by B4nan** [comment]
You need to install the CLI package first.

**Comment by cbadger85** [comment]
Thanks for the quick feed back!

I somehow missed over the step about actually installing the cli >.<

as a possible enhancement to the documentation, would it make sense to add the following?

```
# installation
yarn add @mikro-orm/cli

# manually
$ node node_modules/.bin/mikro-orm

# via npx
$ npx mikro-orm

# or via yarn
$ yarn mikro-orm
```

The other parts of the documentation mention installation steps in code blocks, so it might make sense to move the cli installation instructions into a code block as well.
