### ISSUE TITLE
(node:33492) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token ] in JSON at position 435

### ISSUE THREAD

**Issue by cdesch** [mikro-orm/mikro-orm#1712]
**Describe the bug**
Error when running the initial migration

**Stack trace**

```
$ npx mikro-orm migration:create --initial --tracewarnings
(node:33492) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token ] in JSON at position 435
    at JSON.parse (<anonymous>)
    at Function.getTsConfig (C:\Projects\my_project\node_modules\@mikro-orm\core\utils\ConfigurationLoader.js:76:21)
    at Function.registerTsNode (C:\Projects\my_project\node_modules\@mikro-orm\core\utils\ConfigurationLoader.js:63:30)
    at Function.configure (C:\Projects\my_project\node_modules\@mikro-orm\cli\CLIConfigurator.js:20:13)
    at C:\Projects\my_project\node_modules\@mikro-orm\cli\cli.js:16:19
(Use `node --trace-warnings ...` to show where the warning was created)
(node:33492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). T
o terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:33492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**To Reproduce**
1. follow getting started guide and https://github.com/mikro-orm/express-js-example-app
2. run `npx mikro-orm migration:create --initial`
3. ...

**Expected behavior**

Run the initial migration and generate the migration or if the `mikro-orm.config.ts` is not valid, indicate where the error is. 

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | v14.15.4 |
| typescript |4.2.3|
| mikro-orm | 4.5.3 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Your `tsconfig.json` is not valid JSON.
