### ISSUE TITLE
Invalid mapping custom type primary key when update

### ISSUE THREAD

**Issue by mgce** [mikro-orm/mikro-orm#1721]
**Describe the bug**
To define primary keys I am using a Guid type from `guid-typescript` package. I've written a custom type definition with all the transformations from and to the database. The migration is creating correctly, but updating an entity is failing because it's trying to update an entity with an invalid `where` clause.
The Mikro-orm produce the following SQL output:
```
Update \"Couch\" set \"name\" = 'Example couch 22' where \"value\" = 'dd8ec02f-c65f-42b8-408a-034a6948448f' 
```
instead of
```
Update \"Couch\" set \"name\" = 'Example couch 22' where \"id\" = 'dd8ec02f-c65f-42b8-408a-034a6948448f' 
```
Instead of mapping id object to the string, it put the whole object into the `where` expression.

**Stack trace**
```
"InvalidFieldNameException: update \"Couch\" set \"name\" = 'Example couch 22' where \"value\" = 'dd8ec02f-c65f-42b8-408a-034a6948448f' - column \"value\" does not exist\n    at PostgreSqlExceptionConverter.convertException (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/@mikro-orm/postgresql@4.5.2_@mikro-orm+core@4.5.2/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:34:24)\n    at PostgreSqlDriver.convertException (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/@mikro-orm/core@4.5.2_d92aad7d255c240226982115d0ab5be6/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:194:54)\n    at /Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/@mikro-orm/core@4.5.2_d92aad7d255c240226982115d0ab5be6/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:198:24\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async PostgreSqlDriver.nativeUpdate (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/@mikro-orm/knex@4.5.2_@mikro-orm+core@4.5.2+pg@8.5.1/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:237:19)\n    at async ChangeSetPersister.persistManagedEntity (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/@mikro-orm/core@4.5.2_d92aad7d255c240226982115d0ab5be6/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:95:21)\n    at async ChangeSetPersister.executeUpdates (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/@mikro-orm/core@4.5.2_d92aad7d255c240226982115d0ab5be6/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:34:13)\n    at async UnitOfWork.commitUpdateChangeSets (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/@mikro-orm/core@4.5.2_d92aad7d255c240226982115d0ab5be6/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:523:9)\n    at async UnitOfWork.persistToDatabase (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/@mikro-orm/core@4.5.2_d92aad7d255c240226982115d0ab5be6/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:463:13)\n    at async PostgreSqlConnection.transactional (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/@mikro-orm/knex@4.5.2_@mikro-orm+core@4.5.2+pg@8.5.1/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:53:25)\n    at async UnitOfWork.commit (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/@mikro-orm/core@4.5.2_d92aad7d255c240226982115d0ab5be6/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:183:17)\n    at async SqlEntityManager.flush (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/@mikro-orm/core@4.5.2_d92aad7d255c240226982115d0ab5be6/node_modules/@mikro-orm/core/EntityManager.js:486:9)\n    at async SqlEntityManager.persistAndFlush (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/@mikro-orm/core@4.5.2_d92aad7d255c240226982115d0ab5be6/node_modules/@mikro-orm/core/EntityManager.js:438:9)\n    at async CouchRepository.update (/Users/user/repositories/my-project-name/src/modules/couch/build/core/repositories/couch.repository.js:9:9)\n    at async CouchService.update (/Users/user/repositories/my-project-name/src/modules/couch/build/core/services/couch.service.js:46:9)\n    at async /Users/user/repositories/my-project-name/src/modules/couch/build/api/routes/couch.router.js:59:22\n\nprevious error: update \"Couch\" set \"name\" = 'Example couch 22' where \"value\" = 'dd8ec02f-c65f-42b8-408a-034a6948448f' - column \"value\" does not exist\n    at Parser.parseErrorMessage (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/pg-protocol@1.4.0/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/pg-protocol@1.4.0/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/pg-protocol@1.4.0/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/Users/user/repositories/my-project-name/common/temp/node_modules/.pnpm/pg-protocol@1.4.0/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (events.js:210:5)\n    at Socket.EventEmitter.emit (domain.js:476:20)\n    at addChunk (_stream_readable.js:308:12)\n    at readableAddChunk (_stream_readable.js:289:11)\n    at Socket.Readable.push (_stream_readable.js:223:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)"
```

**To Reproduce**
1. Create the following entity:
```
@Entity()
export class Couch {
  @PrimaryKey({ type: GuidType })
  id: Guid;

  @Property({ type: GuidType })
  userId: Guid;

  @Property()
  name: string;

  @Property()
  description: string;

  @Property()
  rooms: number;

  @Property()
  createdAt: Date = new Date();
}
```
2. Create a definition for `GuidType`
```
import { Type } from "@mikro-orm/core";
import { Guid } from "guid-typescript";

export class GuidType extends Type<Guid | undefined, string | undefined> {
  convertToDatabaseValue(value: Guid | undefined): string | undefined {
    if (!value) {
      return value;
    }

    return value.toString();
  }

  convertToJSValue(value: string | undefined): Guid | undefined {
    if (!value) {
      return undefined;
    }

    return Guid.parse(value);
  }

  getColumnType(): string {
    return "uuid";
  }
}
```
3. Perform the following update for the previously created entity:
```
 const couch = await this.dbConnection.em.getRepository(Couch).findOne({ id });
 couch.name = "Example couch 22";
 await this.dbConnection.em.persistAndFlush(couch);
```
4. Get the following error:
```
{"@timestamp":"2021-04-25T12:00:44.995Z","@version":1,"message":"InvalidFieldNameException: update \"Couch\" set \"name\" = 'Example couch 22' where \"value\" = 'dd8ec02f-c65f-42b8-408a-034a6948448f' - column \"value\" does not exist","severity":"error","type":"stdin"}
```

**Expected behavior**
To create `where` expresson, the orm should use a custom type definition, to map value from js to the database value.
**Versions**

| Dependency | Version |
| - | - |
| node | v12.13.0 |
| typescript | 4.2.3 |
| mikro-orm | 4.5.2 |
| @mikro-orm/postgresql | 4.5.2 |

**Comment by B4nan** [comment]
`4.5.4-dev.21`
