### ISSUE TITLE
String array `populate` argument breaks `findAndCount` in v4.5.1+

### ISSUE THREAD

**Issue by karjaneth** [mikro-orm/mikro-orm#1736]
**Describe the bug**

[This change](https://github.com/mikro-orm/mikro-orm/commit/27e4dd2d93006f632e332e0e689a22ba61835acd) (first introduced in [v4.5.1](https://github.com/mikro-orm/mikro-orm/compare/v4.5.0...v4.5.1?diff=split#diff-13c1b466b90db7056ab0d8eed9a8f86d10f0777a91f5a90daa1e1c04ebc83002R178)) broke `findAndCount` by adding [this call to `.populate` in the `AbstractqlDriver`](https://github.com/mikro-orm/mikro-orm/blob/27e4dd2d93006f632e332e0e689a22ba61835acd/packages/knex/src/AbstractSqlDriver.ts#L178).

[The `EntityManager.findAndCount` method](https://github.com/mikro-orm/mikro-orm/blob/27e4dd2d93006f632e332e0e689a22ba61835acd/packages/core/src/EntityManager.ts#L273-L281) simply passes through to both `find` and `count`. When `find` is setting up its `options` object, [it calls `preparePopulate`](https://github.com/mikro-orm/mikro-orm/blob/27e4dd2d93006f632e332e0e689a22ba61835acd/packages/core/src/EntityManager.ts#L113) to normalize the `populate` argument regardless of what format it's provided in. If the `populate` argument is an array of strings, for example, `preparePopulate` [converts it to an array of `PopulateOption` objects](https://github.com/mikro-orm/mikro-orm/blob/27e4dd2d93006f632e332e0e689a22ba61835acd/packages/core/src/EntityManager.ts#L893-L901), each having a `field` property.

However, [`count` does no such thing](https://github.com/mikro-orm/mikro-orm/blob/27e4dd2d93006f632e332e0e689a22ba61835acd/packages/core/src/EntityManager.ts#L596-L611). It assumes that the `populate` property on its `options` object is already an array of `PopulateOption` objects, and passes it through to the `AbstractqlDriver.count` call. Previously that hadn't been a problem, since the `AbstractqlDriver.count` method wasn't using the `populate` property of the `options`. However, since v4.5.1, it does use the `populate` property.

If `populate` is an array of strings (as is commonly the case), this ends up causing a problem when the `QueryBuilder` [attempts to destructure](https://github.com/mikro-orm/mikro-orm/blob/27e4dd2d93006f632e332e0e689a22ba61835acd/packages/knex/src/query/QueryBuilder.ts#L644-L645) the `field` property from what it thinks is an object, but is actually a string. That destructured `field` is `undefined`, and [this call to `field.split`](https://github.com/mikro-orm/mikro-orm/blob/27e4dd2d93006f632e332e0e689a22ba61835acd/packages/knex/src/query/QueryBuilderHelper.ts#L463) throws an error that eventually bubbles up as `DriverException: Cannot read property 'split' of undefined`.

I assume the solution is to add a call to `preparePopulate` in the `EntityManager.count` method. Until it's fixed, our team is going to provide a `PopulateOption` array as the `populate` argument to `findAndCount`, which should avoid tripping over the bug.

**Stack trace**

Real stack trace, just with paths/filenames of my code sanitized.

```
DriverException: Cannot read property 'split' of undefined
    at MySqlExceptionConverter.convertException (/Users/MyUser/test-project/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at MySqlExceptionConverter.convertException (/Users/MyUser/test-project/node_modules/@mikro-orm/mysql-base/MySqlExceptionConverter.js:78:22)
    at MySqlDriver.convertException (/Users/MyUser/test-project/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:194:54)
    at /Users/MyUser/test-project/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:198:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at MySqlDriver.count (/Users/MyUser/test-project/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:146:21)
    at SqlEntityManager.count (/Users/MyUser/test-project/node_modules/@mikro-orm/core/EntityManager.js:411:23)
    at async Promise.all (index 1)
    at SqlEntityManager.findAndCount (/Users/MyUser/test-project/node_modules/@mikro-orm/core/EntityManager.js:195:35)
    at Test.test (/Users/MyUser/test-project/test.ts:157:41)
 
previous TypeError: Cannot read property 'split' of undefined
    at QueryBuilderHelper.splitField (/Users/MyUser/test-project/node_modules/@mikro-orm/knex/query/QueryBuilderHelper.js:364:30)
    at /Users/MyUser/test-project/node_modules/@mikro-orm/knex/query/QueryBuilder.js:509:56
    at Array.forEach (<anonymous>)
    at QueryBuilder.finalize (/Users/MyUser/test-project/node_modules/@mikro-orm/knex/query/QueryBuilder.js:507:24)
    at QueryBuilder.getKnexQuery (/Users/MyUser/test-project/node_modules/@mikro-orm/knex/query/QueryBuilder.js:226:14)
    at QueryBuilder.execute (/Users/MyUser/test-project/node_modules/@mikro-orm/knex/query/QueryBuilder.js:294:28)
    at MySqlDriver.count (/Users/MyUser/test-project/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:146:43)
    at SqlEntityManager.count (/Users/MyUser/test-project/node_modules/@mikro-orm/core/EntityManager.js:411:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
```

**To Reproduce**
1. Call `entityManager.findAndCount` with an array of strings as the `populate` argument.
2. Observe error

**Expected behavior**
It should successfully execute both the find and the count.

**Additional context**
For now, a workaround is to provide an array of `PopulateOption` objects instead of an array of strings as the populate argument to `findAndCount`.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.x |
| typescript | 4.2.4 |
| mikro-orm | 4.5.1 |

**Comment by B4nan** [comment]
> Call entityManager.findAndCount with an array of strings as the populate argument.

This works fine for me, at least on master with simple cases (e.g. `populate: ['books']`). Please provide full repro (ideally as a test case), this might have some other cause. Also its important to try latest version, its nice to know what version introduced it, but more important is to know whether latest is still failing. I was releasing quite a lot of bug fixes yesterday.

**Comment by karjaneth** [comment]
I'm still encountering the error on `4.5.5-dev.3`. I'll try to replicate in a minimal test case when I have some time.

**Comment by stephen-dahl** [comment]
here is a minimal reproduction

```
import { MikroORM } from '@mikro-orm/core';
import { Entity, PrimaryKey, Property } from '@mikro-orm/core';

@Entity()
export class ZipcodeTimezones {
	@Property({ length: 64, nullable: true })
	city?: string;

	@Property({ length: 1, nullable: true })
	dst?: string;

	@Property({ length: 2, columnType: 'char', nullable: true })
	state?: string;

	@Property({ length: 3, nullable: true })
	timezone?: string;

	@PrimaryKey({ length: 5, columnType: 'char' })
	zip!: string;
}

(async () => {
	const orm = await MikroORM.init({
		type: 'mysql',
		host: process.env.MYSQL_HOST,
		user: process.env.MYSQL_USER,
		password: process.env.MYSQL_PASS,
		dbName: process.env.MYSQL_DB,
		entities: [ZipcodeTimezones],
	});
	const result = await orm.em.findAndCount(ZipcodeTimezones, { state: 'NY' }, [
		'city',
	]);
	console.log(result);
	await orm.close();
	console.log('disconnected');
})();
```

```
    "@mikro-orm/core": "^4.5.4",
    "@mikro-orm/mysql": "^4.5.4",
    "@mikro-orm/reflection": "^4.5.4",
    "reflect-metadata": "^0.1.13",
```

**Comment by danielgak** [comment]
There is any update with this? I'm having the same issue when using the `.findAndCount()` method with all params.

**Comment by danielgak** [comment]
There is any update with this? I'm having the same issue when using the `.findAndCount()` method with all params ( _where, populate, orderby, limit and offset_ ). 

This is my error trace:
```
DriverException: Cannot read property 'split' of undefined

    at PostgreSqlExceptionConverter.convertException (@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException (@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:40:22)
    at PostgreSqlDriver.convertException (@mikro-orm/core/drivers/DatabaseDriver.js:194:54)
    at @mikro-orm/core/drivers/DatabaseDriver.js:198:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PostgreSqlDriver.count (@mikro-orm/knex/AbstractSqlDriver.js:146:21)
    at SqlEntityManager.count (@mikro-orm/core/EntityManager.js:411:23)
    at async Promise.all (index 1)
    at SqlEntityManager.findAndCount (@mikro-orm/core/EntityManager.js:195:35)

previous TypeError: Cannot read property 'split' of undefined
    at QueryBuilderHelper.splitField (@mikro-orm/knex/query/QueryBuilderHelper.js:364:30)
    at @mikro-orm/knex/query/QueryBuilder.js:509:56
    at Array.forEach (<anonymous>)
    at QueryBuilder.finalize (@mikro-orm/knex/query/QueryBuilder.js:507:24)
    at QueryBuilder.getKnexQuery (@mikro-orm/knex/query/QueryBuilder.js:226:14)
    at QueryBuilder.execute (@mikro-orm/knex/query/QueryBuilder.js:294:28)
    at PostgreSqlDriver.count (@mikro-orm/knex/AbstractSqlDriver.js:146:43)
    at SqlEntityManager.count (@mikro-orm/core/EntityManager.js:411:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 1)
```
```
    "@mikro-orm/core": "4.5.4",
    "@mikro-orm/nestjs": "4.2.0",
    "@mikro-orm/postgresql": "4.5.4",
    "@mikro-orm/reflection": "4.5.4",
```
If something else is needed I can also provide it

**Comment by B4nan** [comment]
Well the repro was provided just few hours ago, so no updates yet. Will try to look into this later today, I can confirm the repro above is failing. It's quite weird that it was working fine when I tried on some existing entities.

**Comment by B4nan** [comment]
`4.5.5-dev.8`

**Comment by karjaneth** [comment]
I can confirm that upgrading to `4.5.5-dev.8` fixes the issue for us. Thanks!
