### ISSUE TITLE
[bug] strange issue with custom Collection

### ISSUE THREAD

**Issue by lookfirst** [mikro-orm/mikro-orm#187]
```
import {Collection} from "mikro-orm";
import {IEntityType} from "mikro-orm/dist/decorators";
import {sortBy} from 'lodash';

export class SortedCollection<T extends IEntityType<T>> extends Collection<T> {
	constructor(owner: IEntityType<T>, items?: T[], initialized?: boolean) {
		super(owner, items, initialized);
	}

	// TODO: Easiest was to just do it here, but should probably move this to insertion phase instead.
	getItems(): T[] {
		const items = super.getItems();
		return sortBy(items, ['index']);
	}
}
```

```
NODE_ENV=development mikro-orm schema:drop -r
mikro-orm schema:drop

Drop database schema based on current metadata

Options:
  -r, --run      Runs queries                                          [boolean]
  -d, --dump     Dumps all queries to console                          [boolean]
  --no-fk        Disable foreign key checks if possible[boolean] [default: true]
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/functions/src/db/SortedCollection.ts:5:65)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Module.m._compile (/functions/node_modules/ts-node/src/index.ts:493:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Object.require.extensions.<computed> [as .ts] (/functions/node_modules/ts-node/src/index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/functions/src/db/model/Rig.ts:6:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Module.m._compile (/functions/node_modules/ts-node/src/index.ts:493:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Object.require.extensions.<computed> [as .ts] (/functions/node_modules/ts-node/src/index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
```

**Comment by lookfirst** [comment]
Not a high priority, I'm going to get rid of it anyway.

**Comment by B4nan** [comment]
This is almost always caused by circular dependencies.

**Comment by lookfirst** [comment]
I just noticed this:

`import {IEntityType} from "mikro-orm/dist/decorators";`

likely the issue...

**Comment by B4nan** [comment]
I don't think so. I would expect the issue to be in your entity definition where you use this collection wrapper.

**Comment by B4nan** [comment]
Interesting, it runs fine via ts-node, it also compiles, but from CLI I can also observe that error. Tried with latest alpha, where IEntityType has been replaced with AnyEntity, so I can confirm this is definitely not about that import from dist. As I said, I am pretty sure this is about circular dependencies, and it is usually solved by using callback factories, just like with `entity` attribute in decorators (or the hard way is usually to reorganize code and imports in the ORM, but not sure if that could help here, tried to mess around with that for some time with no luck). 

I think the solution could be to use the hydrator to instantiate the collection, but obviously could not instantiate the collection in entities like `myColl = new SortedCollection(this);`. Tried to just define the prop as `myColl: SortedCollection<...>;` but that still breaks it.

**Comment by lookfirst** [comment]
I gave up on my own collection implementation when it became clear it wasn't fully useful. so we can probably just close this if you are fine with that.

**Comment by B4nan** [comment]
Yeah I thought it could work but as we discussed, it would have to be integrated to hydrator and other parts or ORM too to be consistent. Let's close this in favour of #184 and #195.

**Comment by B4nan** [comment]
Btw funny thing to wrap this up, it is still broken even if I removed all references to the SortedCollection class :D Just its presence inside entities directory (so it gets required) breaks the CLI.
