### ISSUE TITLE
@mikro-orm/knex should define peer deps for @mikro-orm/entity-generator and @mikro-orm/migrations

### ISSUE THREAD

**Issue by vjpr** [mikro-orm/mikro-orm#1879]
This doesn't work otherwise.

```
import {MikroORM} from '@mikro-orm/core'
import '@mikro-orm/entity-generator'
import path, {join} from 'path'

export default async function generateEntities() {
  const orm = await MikroORM.init({
    dbName: 'chinook',
    type: 'postgresql',
    discovery: {
      warnWhenNoEntities: false, // by default, discovery throws when no entity is processed
      requireEntitiesArray: true, // force usage of class refrences in `entities` instead of paths
      alwaysAnalyseProperties: false, // do not analyse properties when not needed (with ts-morph)
    },
  })
  const generator = orm.getEntityGenerator()
  const dump = await generator.generate({
    save: true,
    baseDir: join(__dirname, '../entities'),
  })
  console.log(dump)
  await orm.close(true)
}

```

```
Error: Cannot find module '@mikro-orm/entity-generator'
Require stack:
- /xxx/node_modules/.pnpm/@mikro-orm+knex@4.5.5_@mikro-orm+core@4.5.5+pg@8.6.0/node_modules/@mikro-orm/knex/AbstractSqlPlatform.js
- /xxx/node_modules/.pnpm/@mikro-orm+knex@4.5.5_@mikro-orm+core@4.5.5+pg@8.6.0/node_modules/@mikro-orm/knex/index.js
- /xxx/node_modules/.pnpm/@mikro-orm+postgresql@4.5.5_@mikro-orm+core@4.5.5/node_modules/@mikro-orm/postgresql/index.js
- /xxx/node_modules/.pnpm/@mikro-orm+core@4.5.5_c3b2df4d1dfa6e49c3d652be4548a9f9/node_modules/@mikro-orm/core/utils/Configuration.js
- /xxx/node_modules/.pnpm/@mikro-orm+core@4.5.5_c3b2df4d1dfa6e49c3d652be4548a9f9/node_modules/@mikro-orm/core/utils/index.js
- /xxx/node_modules/.pnpm/@mikro-orm+core@4.5.5_c3b2df4d1dfa6e49c3d652be4548a9f9/node_modules/@mikro-orm/core/typings.js
- /xxx/node_modules/.pnpm/@mikro-orm+core@4.5.5_c3b2df4d1dfa6e49c3d652be4548a9f9/node_modules/@mikro-orm/core/index.js
- /xxx/xxx/src/scripts/generate-entities.ts
- /xxx/xxx/bin/generate-entities.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at PostgreSqlPlatform.getEntityGenerator (/xxx/node_modules/.pnpm/@mikro-orm+knex@4.5.5_@mikro-orm+core@4.5.5+pg@8.6.0/node_modules/@mikro-orm/knex/AbstractSqlPlatform.js:23:37)
    at MikroORM.getEntityGenerator (/xxx/node_modules/.pnpm/@mikro-orm+core@4.5.5_c3b2df4d1dfa6e49c3d652be4548a9f9/node_modules/@mikro-orm/core/MikroORM.js:99:42)
    at Object.generateEntities [as default] (/xxx/xxx/src/scripts/generate-entities.ts:15:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/xxx/node_modules/.pnpm/@mikro-orm+knex@4.5.5_@mikro-orm+core@4.5.5+pg@8.6.0/node_modules/@mikro-orm/knex/AbstractSqlPlatform.js',
    '/xxx/node_modules/.pnpm/@mikro-orm+knex@4.5.5_@mikro-orm+core@4.5.5+pg@8.6.0/node_modules/@mikro-orm/knex/index.js',
    '/xxx/node_modules/.pnpm/@mikro-orm+postgresql@4.5.5_@mikro-orm+core@4.5.5/node_modules/@mikro-orm/postgresql/index.js',
    '/xxx/node_modules/.pnpm/@mikro-orm+core@4.5.5_c3b2df4d1dfa6e49c3d652be4548a9f9/node_modules/@mikro-orm/core/utils/Configuration.js',
    '/xxx/node_modules/.pnpm/@mikro-orm+core@4.5.5_c3b2df4d1dfa6e49c3d652be4548a9f9/node_modules/@mikro-orm/core/utils/index.js',
    '/xxx/node_modules/.pnpm/@mikro-orm+core@4.5.5_c3b2df4d1dfa6e49c3d652be4548a9f9/node_modules/@mikro-orm/core/typings.js',
    '/xxx/node_modules/.pnpm/@mikro-orm+core@4.5.5_c3b2df4d1dfa6e49c3d652be4548a9f9/node_modules/@mikro-orm/core/index.js',
    '/xxx/xxx/src/scripts/generate-entities.ts',
    '/xxx/xxx/bin/generate-entities.js'
  ]
}

```

**Comment by vjpr** [comment]
## pnpm workaround

_.pnpmfile.cjs_

```
  // See: https://github.com/mikro-orm/mikro-orm/issues/1879
  if (pkg.name === '@mikro-orm/knex') {
    pkg.dependencies = {
      '@mikro-orm/entity-generator': '*',
      '@mikro-orm/migrations': '*',
    }
  }
```

**Comment by B4nan** [comment]
I guess this is something pnpm specific, or I might have introduced this just in the last patch version (as the location of the requires changed)? cc @merceyz 

Anyway, adding the peer deps as optional should be safe.

**Comment by merceyz** [comment]
Not pnpm specific, it started with https://github.com/mikro-orm/mikro-orm/commit/1db1a6376a4cd21412822cfbd1e68f7b178e54e6 where the require moved from core to knex

**Comment by B4nan** [comment]
`4.5.6-dev.6`

**Comment by vjpr** [comment]
@B4nan `yarn pnp` and `pnpm` work in such a way that they can only access dependencies that are explicitly declare in pjson. Yarn/npm normally installs all deps in the monorepo root `node_modules`, which is why it works for them normally.

**Comment by AndysonDK** [comment]
It's weird because now I get this error:
![image](https://user-images.githubusercontent.com/28491857/129054877-3810088e-3e41-45c7-8254-01886687dac5.png)
