### ISSUE TITLE
Sharing Entity classes between NestJS applications leads to error.

### ISSUE THREAD

**Issue by RichardBosworth** [mikro-orm/mikro-orm#189]
**Describe the bug**
When using a NestJS mono-repo, with an API application and a separate Microservice, the ideal is to share entity files in a NestJS library and use an EntityRepository to access them. 

This works well for the first project.
However, when attempting to use the same entities/files in the Microservice project, various errors are thrown (generally related to things being "undefined"). For example, calling "box.feedback.init()" - where feedback is a OneToMany collection in box, leads to an error on the "name" property of box - as this is the first property.

I believe this may be related in some way to the paths referenced in the temp folder.

The workaround is to copy the entity files and name them differently. However, this is not ideal.

Any ideas for a fix?

**Comment by RichardBosworth** [comment]
```
[Nest] 14108   - 10/07/2019, 00:20:48   [RpcExceptionsHandler] Cannot read property 'find' of undefined +7ms
TypeError: Cannot read property 'find' of undefined
    at Collection.init (/home/richard/Documents/brilliance-backend/node_modules/mikro-orm/dist/entity/Collection.js:87:32)
    at MatchingController.matchNameOnFeedbackCreation (/home/richard/Documents/brilliance-backend/dist/apps/matching/apps/matching/src/matching/controllers/matching.controller.js:29:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/richard/Documents/brilliance-backend/node_modules/@nestjs/microservices/context/rpc-proxy.js:10:32
    at async ServerRMQ.handleEvent (/home/richard/Documents/brilliance-backend/node_modules/@nestjs/microservices/server/server.js:60:32)

```

**Comment by RichardBosworth** [comment]
Oops. Solved. For reference:
If you build the entity files library using "nest build entities(/library name)", then you can change tsconfig "paths" to use the "dist/lib/entities" build.
Then clear the temp folder, delete any existing built applications, and run it again.
