### ISSUE TITLE
DriverException: $and/$or/$nor must be a nonempty array

### ISSUE THREAD

**Issue by ramiel** [mikro-orm/mikro-orm#1891]
**Describe the bug**
When a query contains $and or $or and it also `populate` on Mongo, the following error is thrown

```
DriverException: $and/$or/$nor must be a nonempty array
```

**Stack trace**
```
DriverException: $and/$or/$nor must be a nonempty array,
  at MongoExceptionConverter.convertException (PRJ_FOLDER/graphql/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16),
  at MongoExceptionConverter.convertException (PRJ_FOLDER/graphql/node_modules/@mikro-orm/mongodb/MongoExceptionConverter.js:17:22),
  at MongoDriver.convertException (PRJ_FOLDER/graphql/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:194:54),
  at PRJ_FOLDER/graphql/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:198:24,
  at processTicksAndRejections (internal/process/task_queues.js:95:5),
  at MongoDriver.find (PRJ_FOLDER/graphql/node_modules/@mikro-orm/mongodb/MongoDriver.js:21:21),
  at MongoEntityManager.find (PRJ_FOLDER/graphql/node_modules/@mikro-orm/core/EntityManager.js:93:25),
  at EntityLoader.populateMany (PRJ_FOLDER/graphql/node_modules/@mikro-orm/core/entity/EntityLoader.js:127:22),
  at EntityLoader.populateField (PRJ_FOLDER/graphql/node_modules/@mikro-orm/core/entity/EntityLoader.js:185:25),
  at EntityLoader.populate (PRJ_FOLDER/graphql/node_modules/@mikro-orm/core/entity/EntityLoader.js:37:13),
  at MongoEntityManager.lockAndPopulate (PRJ_FOLDER/graphql/node_modules/@mikro-orm/core/EntityManager.js:630:9),
  at MongoEntityManager.findOne (PRJ_FOLDER/graphql/node_modules/@mikro-orm/core/EntityManager.js:244:9),
  at dispatchHandler (PRJ_FOLDER/graphql/node_modules/type-graphql/dist/resolvers/helpers.js:82:24),
  at PRJ_FOLDER/graphql/node_modules/type-graphql/dist/resolvers/helpers.js:83:26,
  at dispatchHandler (PRJ_FOLDER/graphql/node_modules/type-graphql/dist/resolvers/helpers.js:82:24),
```

**To Reproduce**
Run such a query

```js
const res = await repository.findOne(
      {
        $and: [
          { id: "123456..." },
          { $or: [{ owner: user.id }, { members: [user.id] }] },
        ],
      },
      {
        populate: ['members'],
      },
    );
```

**Expected behavior**
Query should run correctly

**Additional context**
It may be related only to mongoDB driver

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 4.2.4 |
| mikro-orm | 4.5.5 |
| your-driver | mongodb |

**Comment by ramiel** [comment]
Rolling back to version 4.4.4 fix the issue

**Comment by roderik** [comment]
Just letting you know we have the same issue.

The queries that are logged are the ones that need to be executed, and they work when executing manually.

```
[query] db.getCollection('blockchain-node').find({ '$and': [ { deletedAt: { '$exists': false } }, { application: ObjectId('6095860aae006369fd0d9c43') } ] }, { session: undefined }).toArray(); [took 3 ms]                                                   
[query] db.getCollection('blockchain-node').countDocuments({ '$and': [ { deletedAt: { '$exists': false } }, { application: ObjectId('6095860aae006369fd0d9c43') } ] }, { session: undefined }); [took 8 ms]        
$and/$or/$nor must be a nonempty array        
DriverException: $and/$or/$nor must be a nonempty array                                                                                                
    at MongoExceptionConverter.convertException (/usr/src/app/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)                                                                                                                              
    at MongoExceptionConverter.convertException (/usr/src/app/node_modules/@mikro-orm/mongodb/MongoExceptionConverter.js:17:22)                                                                                                                               
    at MongoDriver.convertException (/usr/src/app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:194:54)                                                                                                                                              
    at /usr/src/app/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:198:24                                                                                                                                                                             
    at processTicksAndRejections (node:internal/process/task_queues:96:5)                                                                                                                                                                                     
    at MongoDriver.find (/usr/src/app/node_modules/@mikro-orm/mongodb/MongoDriver.js:21:21)                                                                                                                                                                   
    at MongoEntityManager.find (/usr/src/app/node_modules/@mikro-orm/core/EntityManager.js:93:25)                                                                                                                                                             
    at EntityLoader.populateMany (/usr/src/app/node_modules/@mikro-orm/core/entity/EntityLoader.js:127:22)                                                                                                                                                    
    at EntityLoader.populateField (/usr/src/app/node_modules/@mikro-orm/core/entity/EntityLoader.js:185:25)                                                                                                                                                   
    at EntityLoader.populate (/usr/src/app/node_modules/@mikro-orm/core/entity/EntityLoader.js:37:13)                                                                                                                                                         
previous MongoError: $and/$or/$nor must be a nonempty array                                                                                                                                                                                                   
    at MessageStream.messageHandler (/usr/src/app/node_modules/@mikro-orm/mongodb/node_modules/mongodb/lib/cmap/connection.js:268:20)                                                                                                                         
    at MessageStream.emit (node:events:365:28)                                                                                                                                                                                                                
    at MessageStream.emit (node:domain:470:12)                                                                                                                                                                                                                
    at processIncomingData (/usr/src/app/node_modules/@mikro-orm/mongodb/node_modules/mongodb/lib/cmap/message_stream.js:144:12)                                                                                                                              
    at MessageStream._write (/usr/src/app/node_modules/@mikro-orm/mongodb/node_modules/mongodb/lib/cmap/message_stream.js:42:5)                                                                                                                               
    at writeOrBuffer (node:internal/streams/writable:389:12)                                                                                                                                                                                                  
    at _write (node:internal/streams/writable:330:10)                                                                                                                                                                                                         
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)                                                                                                                                                                                   
    at TLSSocket.ondata (node:internal/streams/readable:751:22)                                                                                                                                                                                               
    at TLSSocket.emit (node:events:365:28)                                           
```

But we also use populate and filters

```
  public async list(args: ListBlockchainNodesArgs) {
    const whereClause: FilterQuery<BlockchainNode> = {
      application: await this.applicationRepository.findOneOrFail({ id: args.applicationId }),
    };
    const findOptions = { filters: ['active'], populate: ['blockchainNetwork'] };

    if (args.blockchainNetworkId) {
      whereClause.blockchainNetwork = await this.blockchainNetworkRepository.findOneOrFail({
        id: args.blockchainNetworkId,
      });
    }

    return this.genericList(whereClause, findOptions);
  }
```

Downgrading to 4.5.4 fixes this.

My guess one or both of the following changes in 4.5.5 are the cause

- core: fix findAndCount with populate (61bc7cf), closes #1736
- core: use $and for merging of multiple filter conditions (19f3f1d), closes #1776

**Comment by B4nan** [comment]
`4.5.6-dev.11`

**Comment by ramiel** [comment]
Thanks!
