### ISSUE TITLE
Cannot read property 'type' of undefined when populating nested entities.

### ISSUE THREAD

**Issue by danielgak** [mikro-orm/mikro-orm#1942]
**Describe the bug**
Im triying to populate two relations for the same entity in the same select (with 1 ManyToOne and OneToMany Collection) as follows:

```typescript
await orm.em.findOne(
  ThreadEntity,
  { id: 'threadId' },
  {
    by: LoadStrategy.JOINED,
    populate: {
      subscription: {
        to: 'threadId',
        by: 'userId',
      },
    },
    strategy: LoadStrategy.JOINED,
  },
); // TypeError
```

**Stack trace**
```
TypeError: Cannot read property 'type' of undefined

    at @mikro-orm/core/EntityManager.js:665:54
    at Array.map (<anonymous>)
    at SqlEntityManager.preparePopulateObject (@mikro-orm/core/EntityManager.js:657:38)
    at SqlEntityManager.preparePopulate (@mikro-orm/core/EntityManager.js:639:25)
    at SqlEntityManager.lockAndPopulate (@mikro-orm/core/EntityManager.js:629:39)
    at SqlEntityManager.findOne (@mikro-orm/core/EntityManager.js:228:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**
When quering a thread im trying to populate a collection of subscriptions to know if the user who is quering the thread is subscribed to it.

```typescript
export class ThreadEntity {
  @PrimaryKey({ index: true })
  id!: string;

  @ManyToOne({
    entity: () => UserEntity,
    onDelete: 'set null',
    nullable: true,
    index: true,
  })
  by?: UserEntity;

  @OneToMany({ entity: () => SubscriptionEntity, mappedBy: (s) => s.to })
  subscriptions = new Collection<SubscriptionEntity>(this);
}

export class SubscriptionEntity {
  @ManyToOne({ entity: () => UserEntity, primary: true, index: true, onDelete: 'cascade' })
  by!: UserEntity;

  @ManyToOne({
    entity: () => ThreadEntity,
    inversedBy: (e) => e.subscriptions,
    primary: true,
    index: true,
    onDelete: 'cascade',
  })
  to!: ThreadEntity;

  [PrimaryKeyType]: [string, string];
}

export class UserEntity {
  @PrimaryKey({ index: true })
  id!: string;

  @Property()
  name!: string;
}
```

So I would like to populate the "subscriptions" and the "by" at the same time, but im not able to do it. I tied few aproaches separatly, and they work, but I'm not able to do it in the same select.

```typescript
await orm.em.findOne(
  ThreadEntity,
  { id: 'threadId' },
  ['by']
); // Loads the by relation

await orm.em.findOne(
  ThreadEntity,
  { id: 'threadId' },
  { by: LoadStrategy.JOINED }
); // Loads the by relation

await orm.em.findOne(
  ThreadEntity,
  { id: 'threadId' },
  {
    populate: {
      subscription: {
        to: 'threadId',
        by: 'userId',
      },
    },
    strategy: LoadStrategy.JOINED, 
  }
); // Loads the subscribtion relation with the filter

await orm.em.findOne(
  ThreadEntity,
  { id: 'threadId' },
  { // also tryed other similar formats
    by: LoadStrategy.JOINED,
    populate: {
      subscription: {
        to: 'threadId',
        by: 'userId',
      },
    },
    strategy: LoadStrategy.JOINED,
  },
); // TypeError 
```

**Expected behavior**
Checking the [loading strategies docs](https://mikro-orm.io/docs/loading-strategies/), I've seen this example:
```typescript
// one level
const author = await orm.em.findOne(Author, 1, { 
  populate: {
    books: LoadStrategy.JOINED,
  },
});

// two or more levels - use `FindOptions.strategy`
const author = await orm.em.findOne(Author, 1, {
  populate: {
    books: { publisher: true },
  },
  strategy: LoadStrategy.JOINED
});
```
So I was expecting to be able to populate different relations at the same time.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.0.0 |
| typescript | 4.3.2 |
| mikro-orm/core | 4.5.6 |
| mikro-orm/nestjs | 4.2.0 |
| mikro-orm/postgresql | 4.5.6 |
| mikro-orm/reflection | 4.5.6 |

**Comment by B4nan** [comment]
Your populate parameter looks wrong, the right hand side should be just `true`, or a `LoadStrategy`, or an object, not a string or a property name. It's definitely not tested this way.

The error itself is caused by a typo, not sure if you have strict mode disabled in TS, as this should be reported by the compiler. You are requesting to populate `ThreadEntity.subscription` but the entity does not have such property, you have a `subscriptions` 1:m collection.

Try it this way (it's enough to specify the strategy once in the `FindOptions`):

```ts
await orm.em.findOne(
  ThreadEntity,
  { id: 'threadId' },
  {
    populate: {
      subscriptions: {
        to: true,
        by: true,
      },
    },
    strategy: LoadStrategy.JOINED,
  },
);
```

Note that you also had a `by` at the top level, there is no such thing in `FindOptions`.
