### ISSUE TITLE
Using DTO Class in constructor.

### ISSUE THREAD

**Issue by sojeda** [mikro-orm/mikro-orm#2001]
**Describe the bug**
I need help, is it possible to use a DTO class in a entity constructor? I am looking for an ORM that allows it. because I have entities with many parameters and it is cleaner this way

**Stack trace**
```
node_1   | [NestWinston] Error  7/2/2021, 2:36:42 PM Method: GET; Path: /123456/concepts; Error: Cannot read property 'storeId' of undefined;  - {"service":"xxxx","stack":["Typ
eError: Cannot read property 'storeId' of undefined\n    at new Concept (/usr/src/app/src/modules/concepts/entities/concept.entity.ts:89:31)\n    at EntityFactory.createEntity (
/usr/src/app/node_modules/@mikro-orm/core/entity/EntityFactory.js:69:20)\n    at EntityFactory.create (/usr/src/app/node_modules/@mikro-orm/core/entity/EntityFactory.js:34:77)\n
    at SqlEntityManager.find (/usr/src/app/node_modules/@mikro-orm/core/EntityManager.js:100:52)\n    at processTicksAndRejections (node:internal/process/task_queues:93:5)\n
at ConceptService.getAll (/usr/src/app/src/modules/concepts/concept.service.ts:13:33)\n    at ConceptController.findAll (/usr/src/app/src/modules/concepts/concept.controller.ts:
33:22)"]}
```

**To Reproduce**
1. Create a entity with constructor.

```
export interface StoreConceptPort {
  storeId: string;
}

import {
  IsNotEmpty,
} from 'class-validator';
import { UseCaseValidatableDto } from '@test/common/dto/use-case-validatable-dto';
import { Exclude, Expose, plainToClass } from 'class-transformer';
import { StoreConceptPort } from '@test/concepts/port/store-concept.port';
import { ServiceType } from '@test/concepts/service-type.enum';

@Exclude()
export class StoreConceptDto
  extends UseCaseValidatableDto
  implements StoreConceptPort
{
  @Expose()
  @IsNotEmpty()
  storeId: string;

  public static async new(payload: {
    storeId: string;
  }): Promise<StoreConceptDto> {
    const adapter: StoreConceptDto = plainToClass(StoreConceptDto, payload);
    await adapter.validate();

    return adapter;
  }
}
```

```
import {
  Embedded,
  Entity,
  EntityRepositoryType,
  Index,
  ManyToOne,
  Property,
  Unique,
} from '@mikro-orm/core';
import { ConceptRepository } from '@test/concepts/concept.repository';
import { BaseEntity } from '@test/common/entities/base-entity';
import { StoreConceptPort } from '@test/concepts/port/store-concept.port';

@Entity({ tableName: 'concepts' })
export class Concept extends BaseEntity {
  [EntityRepositoryType]?: ConceptRepository;

  @Index()
  @Property({
    name: 'store_id',
    type: 'varchar',
  })
  storeId: string;

  constructor(conceptDto: StoreConceptPort) {
    super();
    this.storeId = conceptDto.storeId;
  }

}
```

2. Find Entity with repository
```
import { Concept } from './entities/concept.entity';
import { ServiceType } from '@test/concepts/service-type.enum';
import { EntityRepository, Repository } from '@mikro-orm/core';

@Repository(Concept)
export class ConceptRepository extends EntityRepository<Concept> {
  public async findOneByStore(id, storeId): Promise<Concept> {
    return await this.findOneOrFail({
      storeId: { $eq: storeId },
      id: { $eq: id },
    });
  }
}
```
And use it.

3. See error: "TypeError: Cannot read property 'storeId' of undefined..."

**Expected behavior**
The model is expected to hydrate well

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 15.2.0 |
| typescript | 4.2.3 |
| mikro-orm | 4.5.7 |
| your-driver | ? |

**Comment by B4nan** [comment]
That stack trace is from different call - you can see it starts with `findAll()` not `findOne()`. The ORM will never use entity constructor to create instance, so unless you are using `forceEntityConstructor` flag, this is not even possible to happen, the instance is created via `Object.create()` instead. And if you are using that flag, you need to ensure your entity ctors all have optional parameters, as they can never be filled in.
