### ISSUE TITLE
Same Attribute In Multiple Discriminator Types Leads To Error

### ISSUE THREAD

**Issue by ThatOneAwkwardGuy** [mikro-orm/mikro-orm#2078]
**Describe the bug**
If you are using Single Table Inheritance and two of your types have the same attribute with different types e.g attributeA is on TypeA and TypeB but in TypeA attributeA is an embeddable property, while in TypeB it's a ManyToMany property.

**Stack trace**
```
[0] [Nest] 54591  - 07/30/2021, 18:38:25   ERROR [ExceptionsHandler] this.pkGetter is not a function
[0] TypeError: this.pkGetter is not a function
[0]     at WrappedEntity.getPrimaryKey (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/core/dist/entity/WrappedEntity.js:62:21)
[0]     at WrappedEntity.hasPrimaryKey (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/core/dist/entity/WrappedEntity.js:55:25)
[0]     at eval (eval at createFunction (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/core/dist/utils/Utils.js:629:52), <anonymous>:95:81)
[0]     at Function.callCompiledFunction (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/core/dist/utils/Utils.js:640:20)
[0]     at EntityComparator.prepareEntity (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/core/dist/utils/EntityComparator.js:35:30)
[0]     at UnitOfWork.registerManaged (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/core/dist/unit-of-work/UnitOfWork.js:67:59)
[0]     at EntityFactory.create (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/core/dist/entity/EntityFactory.js:38:29)
[0]     at MongoEntityManager.find (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/core/dist/EntityManager.js:104:52)
[0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0]     at EntityLoader.populateMany (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/core/dist/entity/EntityLoader.js:128:22)
```

**To Reproduce**
1. Define an abstract base class with a discriminator map
2. Create 2 types with an attribute that is the same
3. Define the attribute as @Embeddable in one and a relationship in the other e.g @ManyToOne

**Expected behavior**
I would expect the attributes to be considered in relation to the class they were defined in, instead of the base discriminator class which is what causes the conflict.

**Additional context**

**Versions**

| Dependency | Version |
| node | v12.22.1 |
| typescript | 4.3.5 |
| @mikro-orm/core| ^5.0.0-dev.264 |
| @mikro-orm/mongo-highlighter| ^1.0.0 |
| @mikro-orm/mongodb| ^5.0.0-dev.264 |
| @mikro-orm/nestjs| ^4.2.0 |
| @mikro-orm/reflection| ^5.0.0-dev.264 |

**Comment by B4nan** [comment]
This is not possible, with STI your base class is where all the metadata is stored. I see you are using mongo, but imagine how it works in SQL - you have single database table (that is where the STI name comes from). You cannot have one column that would be both an embeddable (so object or even multiple columns in fact with inlined mode) and a m:1 relation (so one or more columns with actual FK constraints).
