### ISSUE TITLE
Unable to run : npx mikro-orm migration:create >>Following Ben  Awad tutorial 

### ISSUE THREAD

**Issue by ElmandjraHawk** [mikro-orm/mikro-orm#2083]
When I run npx mikro-orm migration:create >> I get this error 
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Module.m._compile (C:\Users\fight\Desktop\LIREDDIT-SERVER\node_modules\ts-node\src\index.ts:1225:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\fight\Desktop\LIREDDIT-SERVER\node_modules\ts-node\src\index.ts:1228:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Function.getConfiguration (C:\Users\fight\Desktop\LIREDDIT-SERVER\node_modules\@mikro-orm\core\utils\ConfigurationLoader.js:21:32)
    at Function.getORM (C:\Users\fight\Desktop\LIREDDIT-SERVER\node_modules\@mikro-orm\cli\CLIHelper.js:16:25)
    at Function.handleMigrationCommand (C:\Users\fight\Desktop\LIREDDIT-SERVER\node_modules\@mikro-orm\cli\commands\MigrationCommandFactory.js:70:21)

Can you please help

**Comment by B4nan** [comment]
https://github.com/mikro-orm/mikro-orm/issues/604#issuecomment-642184929
