### ISSUE TITLE
CLI tool crashes when using Vanilla JavaScript

### ISSUE THREAD

**Issue by FilipVojtech** [mikro-orm/mikro-orm#2102]
**Describe the bug**
I am using MikroORM with Vanilla JS, Express and SQLite and I am getting errors when trying to create a database schema.

**Stack trace**
```
[discovery] ORM entity discovery started, using ReflectMetadataProvider
[discovery] - processing 2 files
[discovery] - processing entity BaseEntity (/home/polycorn/WebstormProjects/js-sqlite-mikroorm/entities/BaseEntity.js)
[discovery] - processing entity Service (/home/polycorn/WebstormProjects/js-sqlite-mikroorm/entities/Service.js)
mikro-orm schema:create

Create database schema based on current metadata

Options:
  -r, --run      Runs queries                                          [boolean]
  -d, --dump     Dumps all queries to console                          [boolean]
  --fk-checks    Do not skip foreign key checks                        [boolean]
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]

MetadataError: Only abstract entities were discovered, maybe you forgot to use @Entity() decorator?
    at Function.onlyAbstractEntitiesDiscovered (/usr/lib/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/errors.js:148:16)
    at MetadataValidator.validateDiscovered (/usr/lib/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/metadata/MetadataValidator.js:44:42)
    at MetadataDiscovery.findEntities (/usr/lib/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:81:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MetadataDiscovery.discover (/usr/lib/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:34:9)
    at async Function.init (/usr/lib/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/MikroORM.js:42:24)
    at async Function.handleSchemaCommand (/usr/lib/node_modules/@mikro-orm/cli/commands/SchemaCommandFactory.js:65:21) {
  entity: undefined
}

```

**To Reproduce**
1. Run `mikro-orm schema:create` with the -d or -r flag

**Expected behavior**
MikroORM generates a database schema

**Additional context**
If it helps, [here's](https://github.com/FilipVojtech/js-sqlite-mikroorm) a watered down repo

**Versions**

| Dependency | Version |
| - | - |
| node | v16.6.1 |
| typescript | nope |
| mikro-orm | 4.5.7 |
| your-driver | sqlite |

**Comment by FilipVojtech** [comment]
I finally figured it out!
I solved the issue by uninstalling the global CLI tool and replacing it by local installation. Then running the command through npx.
