### ISSUE TITLE
Virtual property with name causes ts-morph error: Cannot read property 'getType' of undefined

### ISSUE THREAD

**Issue by CyriacBr** [mikro-orm/mikro-orm#2134]
**Describe the bug**
When defining a virtual property with a name, [just like in the doc](https://mikro-orm.io/docs/defining-entities#virtual-properties), the ts-morth metadata provider crashes.
```ts
@Entity()
class User {
  @PrimaryKey()
  id!: number;

  @Property({ name: 'fullName' })
  getFullName() {
    return 'foo';
  }
}
```

**Stack trace**
```
TypeError: Cannot read property 'getType' of undefined
    at TsMorphMetadataProvider.readTypeFromSource (/media/[user]/0CC5166B0CC5166B/Work/[project]/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:82:33)
    at TsMorphMetadataProvider.initPropertyType (/media/[user]/0CC5166B0CC5166B/Work/[project]/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:63:36)
    at TsMorphMetadataProvider.initProperties (/media/[user]/0CC5166B0CC5166B/Work/[project]/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:48:17)
    at TsMorphMetadataProvider.loadEntityMetadata (/media/[user]/0CC5166B0CC5166B/Work/[project]/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:23:9)
    at MetadataDiscovery.discoverEntity (/media/[user]/0CC5166B0CC5166B/Work/[project]/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:182:13)
    at MetadataDiscovery.discoverReferences (/media/[user]/0CC5166B0CC5166B/Work/[project]/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:131:13)
    at MetadataDiscovery.findEntities (/media/[user]/0CC5166B0CC5166B/Work/[project]/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:71:9)
    at MetadataDiscovery.discover (/media/[user]/0CC5166B0CC5166B/Work/[project]/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:34:9)
    at Function.init (/media/[user]/0CC5166B0CC5166B/Work/[project]/node_modules/@mikro-orm/core/MikroORM.js:42:24)
```

**To Reproduce**
Full reproduction:
```ts
@Entity()
class User {
  @PrimaryKey()
  id!: number;

  @Property({ name: 'fullName' })
  getFullName() {
    return 'foo';
  }
}

(async () => {
  const orm = await MikroORM.init({
    metadataProvider: TsMorphMetadataProvider,
    entities: [User],
    dbName: 'mikro-orm.sqlite',
    type: 'sqlite',
    debug: true,
  });
})();
```

**Expected behavior**
Shouldn't crash.

**Versions**

| Dependency | Version |
| - | - |
| node |16.6.1 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.7 |
| your-driver | sqlite |

**Comment by B4nan** [comment]
Should be already fixed in latest dev

**Comment by B4nan** [comment]
As said, this is already fixed via https://github.com/mikro-orm/mikro-orm/commit/0c8217951ebc65e2b1e7ad4d331d04416699a30d, will ship the stable probably later today, for now you can use `4.5.8-dev.3`
