### ISSUE TITLE
Unab;e to Install

### ISSUE THREAD

**Issue by vashisth00** [mikro-orm/mikro-orm#2144]
Trace: 
  Error: https://registry.yarnpkg.com/@mikro-orm/postgresql/-/postgresql-4.5.8.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:696:66)
      at new ResponseError (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:802:124)
      at Request.<anonymous> (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:67058:16)
      at Request.emit (events.js:400:28)
      at Request.module.exports.Request.onRequestResponse (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:141539:10)
      at ClientRequest.emit (events.js:400:28)
      at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
      at TLSSocket.socketOnData (_http_client.js:515:22)
      at TLSSocket.emit (events.js:400:28)

npm manifest: 
  {
    "name": "scoring-systerm",
    "version": "1.0.0",
    "description": "Gemwire stuff",
    "main": "index.js",
    "scripts": {
      "watch": "tsc -w",
      "dev": "nodemon dist/index.js",
      "start": "ts-node src/index.ts",
      "start2": "node dist/index.js",
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "repository": {
      "type": "git",
      "url": "git+https://github.com/vashisth00/scoring-systerm.git"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "bugs": {
      "url": "https://github.com/vashisth00/scoring-systerm/issues"
    },
    "homepage": "https://github.com/vashisth00/scoring-systerm#readme",
    "devDependencies": {
      "@types/node": "^16.7.1",
      "nodemon": "^2.0.12",
      "ts-node": "^10.2.1",
      "typescript": "^4.3.5"
    },
    "dependencies": {
      "@mikro-orm/cli": "^4.5.8",
      "@mikro-orm/core": "^4.5.8",
      "@mikro-orm/migrations": "^4.5.8",
      "pg": "^8.7.1"
    }
  }

yarn manifest: 
  No manifest

**Comment by vashisth00** [comment]
It still doesn't work ...
