### ISSUE TITLE
ReferenceError: Cannot access 'Options' before initialization

### ISSUE THREAD

**Issue by sawa-ko** [mikro-orm/mikro-orm#2147]
**Describe the bug**
I can't use embedded properties in my entity, I want to do this so I can use it with mongodb.

**Stack trace**
```ts
..\dist\lib\database\entities\player.js:31
    tslib_1.__metadata("design:type", Options)
                                      ^

ReferenceError: Cannot access 'Options' before initialization
    at Object.<anonymous> (..\dist\lib\database\entities\player.js:31:39)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (..\dist\lib\database\entities\index.js:5:22)  
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Entity**
```ts
import { Embeddable, Embedded, Entity, Property } from '@mikro-orm/core';

import type { Snowflake } from 'discord-api-types';

import { BaseEntity } from './base';

@Entity({ tableName: 'players' })
export class PlayerEntity extends BaseEntity {
  @Property()
  guild_id: Snowflake;

  @Embedded(() => Options)
  options?: Options;

  constructor(guild_id: string) {
    super();
    this.guild_id = guild_id;
  }
}

@Embeddable()
class Options {
  @Embedded(() => LoopOptions)
  loop: LoopOptions;

  constructor(loop: LoopOptions) {
    this.loop = loop;
  }
}

@Embeddable()
class LoopOptions {
  @Property()
  enabled = false;

  @Property()
  type = false;
}
```

**To Reproduce**
1. Create an Entity with Embedded properties

**Expected behavior**
That there was no error and the entity was generated correctly.
I want to get a document created in this way in mongodb:

```ts
{
  guild_id: '...',
  options: {
      loop: {
          enabled: false,
          type: '...'
      }
  }
}
```

**Additional context**
No.

**Versions**

| Dependency | Version |
| - | - |
| node | 16 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.9 |
| your-driver | mongodb |

**Comment by coolshirt** [comment]
@kaname-png , How did you resolve this issue ?
