### ISSUE TITLE
Error on basic call this._em.getContext is not a function

### ISSUE THREAD

**Issue by exejutable** [mikro-orm/mikro-orm#2166]
**Describe the bug**

I run a basic query of findAll and return this stack trace

**Stack trace**
```
TypeError: this._em.getContext is not a function
    at RewardTransactionsRepository.get em [as em] (C:\Users\Adri\projects\dg\reward-service\node_modules\@mikro-orm\core\entity\EntityRepository.js:167:25)
    at RewardTransactionsRepository.findAll (C:\Users\Adri\projects\dg\reward-service\node_modules\@mikro-orm\core\entity\EntityRepository.js:63:21)
    at RewardManager.<anonymous> (C:\Users\Adri\projects\dg\reward-service\src\api\managers\RewardManager.ts:220:58)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Adri\projects\dg\reward-service\node_modules\tslib\tslib.js:114:62)

```

**Debug log**

```
[discovery] ORM entity discovery started, using ReflectMetadataProvider
[discovery] - processing 1 files
[discovery] - processing entity RewardTransactions (C:/Users/Adri/projects/dg/reward-service/src/api/entities/reward.transactions.entity.ts)
[discovery] - entity discovery finished, found 1 entities, took 78 ms
[info] MikroORM successfully connected to database sso on mysql://root:*****@localhost:3306
```

**To Reproduce**
1. Call a request 
2. Execute `await rewardTransactionsRepository.findAll()`

**Expected behavior**

Get all the rows of the table.

**Express middleware**

```typescript
api.use((req, res, next) => {
  RequestContext.create(bootstrap.getOrm().em, next);
});
```

**Entity**

```typescript

import { Entity, PrimaryKey, Property } from '@mikro-orm/core';

@Entity()
export class RewardTransactions {
  @PrimaryKey()
  id!: number

  @Property()
  reward_id!: number

  @Property()
  points_after!: number;

  @Property()
  points_before!: number

  @Property({
    columnType: 'timestamp',
    nullable: true,
    defaultRaw: 'CURRENT_TIMESTAMP',
  })
  createdAt?: Date;

  @Property({ columnType: 'timestamp', nullable: true, onUpdate: () => new Date() })
  updatedAt?: Date;

  @Property({ columnType: 'timestamp', nullable: true })
  deletedAt?: Date;
}

```

**Repository**

```typescript
import { EntityRepository, Repository } from '@mikro-orm/core';
import { Service } from 'typedi';
import { RewardTransactions } from '../entities/reward.transactions.entity';

@Repository(RewardTransactions)
@Service()
export class RewardTransactionsRepository extends EntityRepository<RewardTransactions> {

}

```

**Configuration**

```typescript
 await MikroORM.init({
        entities: ['./api/entities'],
        baseDir: PROJECT.src.path,
        dbName: 'sso',
        type: 'mysql',
        host: this.configuration.host,
        port: this.configuration.port,
        user: this.configuration.user,
        password: this.configuration.password,
        debug: true,
        pool: {
          min: 2,
          max: 100,
        },
      });
```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.4 |
| typescript | 4.3.4 |
| mikro-orm | 4.5.9 |
| @mikro-orm/mysql | 4.5.9 |
| reflect-metadata | 0.1.13 |
| typedi | 0.8.0 |

**package.json**

```json
{
  "name": "reward-service",
  "version": "0.0.1",
  "description": "Reward DG Service",
  "main": "src/app.ts",
  "author": "Adrian Gutierrez",
  "license": "MIT",
  "scripts": {
    "dev": "ts-node-dev  src/app.ts",
  },
  "jest-junit": {
    "outputDirectory": "test-reports"
  },
  "dependencies": {
    "@dg/coupons-http-client": "^1.0.0",
    "@dg/rest-common": "^0.0.1",
    "@dg/sso-http-client": "^0.0.1",
    "@elastic/ecs-winston-format": "^1.0.0",
    "@elastic/elasticsearch": "^7.11.0",
    "@mikro-orm/core": "^4.5.9",
    "@mikro-orm/mysql": "^4.5.9",
    "@types/express-rate-limit": "^5.1.2",
    "app-root-path": "^3.0.0",
    "aws-sdk": "^2.920.0",
    "axios": "^0.21.1",
    "body-parser": "^1.19.0",
    "class-transformer": "0.3.1",
    "class-validator": "0.12.2",
    "class-validator-jsonschema": "2.2.0",
    "compression": "^1.7.4",
    "config": "^3.3.3",
    "cors": "^2.8.5",
    "cron": "^1.8.2",
    "elastic-apm-node": "^3.12.1",
    "express": "^4.17.1",
    "express-rate-limit": "^5.2.6",
    "googleapis": "^67.1.0",
    "handlebars": "^4.7.7",
    "helmet": "^4.2.0",
    "i18n": "^0.13.2",
    "iap": "^1.1.1",
    "import-fresh": "^3.2.2",
    "in-app-purchase": "^1.11.4",
    "jest-junit": "^12.0.0",
    "jsonwebtoken": "^8.5.1",
    "moment": "^2.29.1",
    "multer": "^1.4.2",
    "mysql": "^2.18.1",
    "node-apple-receipt-verify": "^1.9.3",
    "php-serialize": "^4.0.2",
    "promise-mysql": "^5.0.0",
    "reflect-metadata": "^0.1.13",
    "routing-controllers": "0.9.0",
    "routing-controllers-openapi": "3.0.0",
    "ts-node": "^9.0.0",
    "typedi": "^0.8.0",
    "typescript": "^4.1.2",
    "winston": "^3.3.3",
    "winston-daily-rotate-file": "^4.5.2",
    "winston-elasticsearch": "^0.12.2"
  },
  "devDependencies": {
    "@types/body-parser": "^1.19.0",
    "@types/compression": "^1.7.0",
    "@types/config": "^0.0.37",
    "@types/express": "^4.17.9",
    "@types/i18n": "^0.12.0",
    "@types/jest": "^26.0.16",
    "@types/jsonwebtoken": "^8.5.0",
    "@types/multer": "^1.4.4",
    "@types/mysql": "^2.15.16",
    "@types/supertest": "^2.0.10",
    "@typescript-eslint/eslint-plugin": "^4.14.0",
    "@typescript-eslint/parser": "^4.14.0",
    "eslint": "^7.18.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-plugin-import": "^2.22.1",
    "jest": "^26.6.3",
    "supertest": "^6.0.1",
    "ts-jest": "^26.4.4",
    "ts-node-dev": "^1.0.0"
  }
}

```

**Comment by exejutable** [comment]
I create a minimum example:


**code:**

```typescript
import 'reflect-metadata';
import {Entity, Repository, MikroORM, PrimaryKey, Property} from "mikro-orm";
import  {EntityRepository} from '@mikro-orm/mysql'
import {Container, Service} from "typedi";

@Entity()
@Service()
export class RewardTransactions {

  @PrimaryKey()
  id!: number

  @Property()
  reward_id!: number

  @Property()
  points_after!: number;

  @Property()
  points_before!: number

  @Property({
    columnType: 'timestamp',
    nullable: true,
    defaultRaw: 'CURRENT_TIMESTAMP',
  })
  createdAt?: Date;

  @Property({ columnType: 'timestamp', nullable: true, onUpdate: () => new Date() })
  updatedAt?: Date;

  @Property({ columnType: 'timestamp', nullable: true })
  deletedAt?: Date;
}

@Repository(RewardTransactions)
@Service()
export class RewardTransactionsRepository extends EntityRepository<RewardTransactions> {

}

(async () => {
  const orm = await MikroORM.init({
    entities: [RewardTransactions],
    dbName: 'rewards',
    type: 'mysql',
    host: 'localhost',
    port: 3306,
    user: 'root',
    password: 'password',
    debug: true,
  });

  let rewardTransactionsRepository = Container.get(RewardTransactionsRepository)

  console.log(await rewardTransactionsRepository.findAll())

})();

```

**ts-config**
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017",
    "moduleResolution": "node",
    "declaration": true,
    "outDir": "./dist",
    "esModuleInterop": true,
    "strict": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
  }
}

```

**package.json**

```json
{
  "name": "example",
  "version": "0.0.1",
  "author": "Adrian Gutierrez",
  "license": "MIT",
  "dependencies": {
    "@mikro-orm/mysql": "^4.5.9",
    "mikro-orm": "^4.5.9",
    "reflect-metadata": "^0.1.13",
    "ts-node": "^9.0.0",
    "typedi": "^0.8.0",
    "typescript": "^4.1.2"
  },
  "mikro-orm": {
    "useTsNode": true
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-node-resolve": "^11.0.1",
    "@types/body-parser": "^1.19.0",
    "@types/compression": "^1.7.0",
    "@types/config": "^0.0.37",
    "@types/express": "^4.17.9",
    "@types/i18n": "^0.12.0",
    "@types/jest": "^26.0.16",
    "@types/jsonwebtoken": "^8.5.0",
    "@types/multer": "^1.4.4",
    "@types/mysql": "^2.15.16",
    "@types/supertest": "^2.0.10",
    "jest": "^26.6.3",
    "rollup": "^2.36.1",
    "rollup-plugin-terser": "^7.0.2",
    "supertest": "^6.0.1",
    "ts-jest": "^26.4.4",
    "ts-node-dev": "^1.0.0",
    "tsc": "^1.20150623.0"
  }
}

```

**Comment by B4nan** [comment]
Reposities need to be created via `em.getRepository()`, you are letting the DI container do it and it just blindly uses the constructor without providing the parameters. 

Can't help with typedi, never used it myself, but you definitely need to provide some factory method or register the service differently.

**Comment by exejutable** [comment]
> Reposities need to be created via `em.getRepository()`, you are letting the DI container do it and it just blindly uses the constructor without providing the parameters.
> 
> Can't help with typedi, never used it myself, but you definitely need to provide some factory method or register the service differently.
> 
> edit: you probably need something like this, and in the factory you should depend on the `EntityManager` so you can use that to just do `em.getRepository()`
> 
> https://docs.typestack.community/typedi/#using-factory-class-to-create-service

My mistake, i assumed that the library used typedi


I made this snippet for anyone who needs it

```typescript
import {Entity, EntityRepository, MikroORM, PrimaryKey, Property, Repository} from "mikro-orm";
import {Container, Inject, Service} from "typedi";

const asyncSpace = (async () => {

  @Entity()
  class RewardTransactions {

    @PrimaryKey()
    id!: number

    @Property()
    reward_id!: number

    @Property()
    points_after!: number;

    @Property()
    points_before!: number

    @Property({
      columnType: 'timestamp',
      nullable: true,
      defaultRaw: 'CURRENT_TIMESTAMP',
    })
    created_at?: Date;

    @Property({ columnType: 'timestamp', nullable: true, onUpdate: () => new Date() })
    updated_at?: Date;

    @Property({ columnType: 'timestamp', nullable: true })
    deleted_at?: Date;
  }


  const orm = await MikroORM.init({
    entities: [RewardTransactions],
    dbName: 'rewards',
    type: 'mysql',
    host: 'localhost',
    port: 3306,
    user: 'root',
    password: 'password',
    debug: true,
  });


  // HERE STARTS THE IMPORTANT
  @Service()
  class RepositoryFactory {
    rewardTransactionsRepository(): RewardTransactionsRepository {
      // Other valid way
      // return new RewardTransactionsRepository(orm.em, RewardTransactions)
      return orm.em.getRepository(RewardTransactions)
    }
  }

  @Repository(RewardTransactions)
  @Service({factory: [RepositoryFactory, 'rewardTransactionsRepository']})
  class RewardTransactionsRepository extends EntityRepository<RewardTransactions> {}

  // HERE ENDS



  @Service()
  class SomeClass {
    // Another way of inject
    @Inject()
    rewardTransactionsRepositoryInject: RewardTransactionsRepository

    // Another way of inject
    constructor(private rewardTransactionsRepository: RewardTransactionsRepository) {}

    async foo(): Promise<RewardTransactions[]> {
      // From container get
      let injectByContainer = await Container.get(RewardTransactionsRepository).findAll()

      // From constructor
      let injectConstructor = await this.rewardTransactionsRepository.findAll()

      // From Inject Decorator
      let injectByInjectDecorator = await this.rewardTransactionsRepositoryInject.findAll()

      return [...injectByInjectDecorator, ...injectConstructor, ...injectByContainer]
    }

  }

  let someClassInstance = Container.get(SomeClass)

  console.log(await someClassInstance.foo())

})();


})();

```


Thanks for you response
