### ISSUE TITLE
TypeError: Cannot read property 'serializedPrimaryKey' of undefined

### ISSUE THREAD

**Issue by TheMaestro0** [mikro-orm/mikro-orm#2191]
**Describe the bug**
#toJSON not correctly work with `Collection`

**Stack trace**
```
/home/abdulrahman/itchat/server/node_modules/@mikro-orm/core/entity/ArrayCollection.js:48
        field = field !== null && field !== void 0 ? field : this.property.targetMeta.serializedPrimaryKey;
                                                                                      ^
TypeError: Cannot read property 'serializedPrimaryKey' of undefined
    at Collection.getIdentifiers (/home/abdulrahman/itchat/server/node_modules/@mikro-orm/core/entity/ArrayCollection.js:48:87)
    at Function.processCollection (/home/abdulrahman/itchat/server/node_modules/@mikro-orm/core/entity/EntityTransformer.js:181:24)
    at Function.processProperty (/home/abdulrahman/itchat/server/node_modules/@mikro-orm/core/entity/EntityTransformer.js:148:38)
    at /home/abdulrahman/itchat/server/node_modules/@mikro-orm/core/entity/EntityTransformer.js:108:43
    at Array.map (<anonymous>)
    at Function.toObject (/home/abdulrahman/itchat/server/node_modules/@mikro-orm/core/entity/EntityTransformer.js:103:14)
    at Channel.prototype.toJSON (/home/abdulrahman/itchat/server/node_modules/@mikro-orm/core/entity/EntityHelper.js:27:62)
    at JSON.stringify (<anonymous>)
    at Getaway.publish (/home/abdulrahman/itchat/server/src/getaway/Getaway.ts:20:48)
    at ChannelSubscriber.afterCreate (/home/abdulrahman/itchat/server/src/subscribers/Channel.ts:11:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.runSerial (/home/abdulrahman/itchat/server/node_modules/@mikro-orm/core/utils/Utils.js:489:22)
    at async UnitOfWork.commitCreateChangeSets (/home/abdulrahman/itchat/server/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:523:13)
    at async UnitOfWork.persistToDatabase (/home/abdulrahman/itchat/server/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:473:13)
    at async UnitOfWork.commit (/home/abdulrahman/itchat/server/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:187:17)
    at async MongoEntityManager.flush (/home/abdulrahman/itchat/server/node_modules/@mikro-orm/core/EntityManager.js:497:9)...
```

**To Reproduce**
1. Create item and save it
2. Calling #toJSON

**Expected behavior**
Entity#toJSON to work

**Entity**
```typescript
@Entity({ tableName: 'channels' })
export class Channel extends Base {
    @ManyToMany('User')
    recipients = new Collection<User>(this)
}
```

**Base**
```typescript
import { PrimaryKey } from 'mikro-orm'
import { Snowflake } from '../utils'

export abstract class Base {
  @PrimaryKey({ unique: true })
  _id!: `${bigint}`

  setID(): this {
    this._id = Snowflake.generate()
    return this
  }
}
```
**ChannelSubscriber**
```typescript
import { EventArgs, EventSubscriber, Subscriber, EntityName } from '@mikro-orm/core'
import { Channel as T } from '../structures'
import { getaway } from '../server'

@Subscriber()
export class ChannelSubscriber implements EventSubscriber<T> {
	async afterCreate({ entity: channel }: EventArgs<T>): Promise<void> {
		if (channel.recipients) {
			await Promise.all(channel.recipients.getItems().map(({ _id }) => getaway.subscribe(_id, channel._id))) 
		}
		await getaway.publish(channel._id, 'CHANNEL_CREATE', channel) // #toJSON called here with JSON.stringify
	}
	
	getSubscribedEntities(): Array<EntityName<T>> {
		return [T]
	}
}
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.6.1 |
| typescript | 4.3.5 |
| mikro-orm | 4.5.7 |
| your-driver | mongodb |
| @mikro-orm/reflection | 4.5.9 |

**Comment by B4nan** [comment]
1. you should not use `mikro-orm` metapackage, use `@mikro-orm/core` instead
2. you need to have the ORM package versions aligned, so you can't use 4.5.7 with `@mikro-orm/reflection@4.5.9`

What you are facing is an issue with metadata discovery, and those two problems I just mentioned are quite often the source of such issues.

If you want more help, you need to provide full executable repro, as the issue is not reproducible like this. But I am quite sure it is about those two points I mentioned.
