### ISSUE TITLE
Bidirectional many to many between two STI subclasses

### ISSUE THREAD

**Issue by michallappo** [mikro-orm/mikro-orm#2246]
**Describe the bug**
I'm not sure if this is a bug or if this behavior is simply not supported, but when trying to define a many to many relationship between the two STI subclasses it is not possible to populate from inversed side.

**Stack trace**
```
TypeError: Cannot read property 'inversedBy' of undefined

  217 |     } else {
  218 |       const pivotProp1 = pivotMeta.properties[prop.type + '_owner'];
> 219 |       inverse = pivotProp1.inversedBy;
      |                            ^
  220 |     }
  221 | 
  222 |     return pivotMeta.properties[inverse];

  at PostgreSqlDriver.getPivotInverseProperty (packages/core/src/drivers/DatabaseDriver.ts:219:28)
  at PostgreSqlDriver.loadFromPivotTable (packages/knex/src/AbstractSqlDriver.ts:420:29)
  at EntityLoader.findChildrenFromPivotTable (packages/core/src/entity/EntityLoader.ts:279:35)
  at EntityLoader.populateField (packages/core/src/entity/EntityLoader.ts:233:19)
  at EntityLoader.populate (packages/core/src/entity/EntityLoader.ts:54:7)
  at SqlEntityManager.lockAndPopulate (packages/core/src/EntityManager.ts:889:5)
  at SqlEntityManager.findOne (packages/core/src/EntityManager.ts:347:5)
```

**To Reproduce**
Simple test case:

<details>
  <summary>Test case</summary>
  
```
import {
  Collection,
  Entity,
  Enum,
  ManyToMany,
  MikroORM,
  PrimaryKey,
} from "@mikro-orm/core";
import type { SqliteDriver } from "@mikro-orm/sqlite";

@Entity({
  discriminatorColumn: "type",
  discriminatorMap: { person: "Person", employee: "Employee" },
})
export abstract class BasePerson {
  @PrimaryKey()
  id!: number;

  @Enum()
  type!: "person" | "employee";
}

@Entity()
export class Person extends BasePerson {
  // ...
}

@Entity()
export class Employee extends BasePerson {
  @ManyToMany({ entity: () => PhotoFile, inversedBy: "employees" })
  photos = new Collection<PhotoFile>(this);
}

@Entity({
  discriminatorColumn: "type",
  discriminatorMap: { custom: "CustomFile", photo: "PhotoFile" },
})
export abstract class File {
  @PrimaryKey()
  id!: number;

  @Enum()
  type!: "custom" | "photo";
}

@Entity()
export class CustomFile extends File {
  // ...
}

@Entity()
export class PhotoFile extends File {
  @ManyToMany({ entity: () => Employee, mappedBy: "photos" })
  employees = new Collection<Employee>(this);
}

describe("Bidirectional many to many with multiple STI entities", () => {
  let orm: MikroORM<SqliteDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [BasePerson, Employee, Person, File, CustomFile, PhotoFile],
      dbName: "GH_many_to_many_test",
      type: "postgresql",
    });
    await orm.getSchemaGenerator().ensureDatabase();
    await orm.getSchemaGenerator().dropSchema();
    await orm.getSchemaGenerator().createSchema();
  });

  afterAll(() => orm.close(true));

  test("Owning side", async () => {
    const b = new Employee();
    await orm.em.persistAndFlush(b);
    orm.em.clear();

    await orm.em.findOne(Employee, {id: 1}, {
      populate: ["photos"],
    });
  });

  test("Inversed side", async () => {
    const a = new PhotoFile();
    await orm.em.persistAndFlush(a);
    orm.em.clear();

    await orm.em.findOne(PhotoFile, {id: 1}, {
      populate: ["employees"],
    });
  });
});
```
</details>

**Expected behavior**
It should be possible to populate from inversed side or it should be included in the documentation that STI relations are limited.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.1 |
| typescript | 4.4.2 |
| mikro-orm | 4.5.9 |
| mikro-orm/mysql | 4.5.9 |

**Comment by stickmy** [comment]
Will it be fixed in the 4.x version?
