### ISSUE TITLE
Error when using onUpdate parameter on an entity embed object

### ISSUE THREAD

**Issue by kaname-png** [mikro-orm/mikro-orm#2283]
**Describe the bug**
I want to try to update the embedded object of an entity and when updating it, also update a value automatically with the onUpdate parameter, but mongodb throws an error when trying to do that.

**Stack trace**
```ts
2021-10-17 10:06:39 - ❌ - previous MongoError: Updating the path 'embed.field' would create a conflict at 'embed'
2021-10-17 10:06:39 - ❌ -     at Function.create (C:\Users\Kaname\Documents\Proyectos\Kaede\kaede-rewrite\node_modules\mongodb\lib\core\error.js:57:12)
2021-10-17 10:06:39 - ❌ -     at toError (C:\Users\Kaname\Documents\Proyectos\Kaede\kaede-rewrite\node_modules\mongodb\lib\utils.js:123:22)
2021-10-17 10:06:39 - ❌ -     at C:\Users\Kaname\Documents\Proyectos\Kaede\kaede-rewrite\node_modules\mongodb\lib\operations\common_functions.js:384:39
2021-10-17 10:06:39 - ❌ -     at handler (C:\Users\Kaname\Documents\Proyectos\Kaede\kaede-rewrite\node_modules\mongodb\lib\core\sdam\topology.js:944:24)
2021-10-17 10:06:39 - ❌ -     at C:\Users\Kaname\Documents\Proyectos\Kaede\kaede-rewrite\node_modules\mongodb\lib\cmap\connection_pool.js:350:13
2021-10-17 10:06:39 - ❌ -     at handleOperationResult (C:\Users\Kaname\Documents\Proyectos\Kaede\kaede-rewrite\node_modules\mongodb\lib\core\sdam\server.js:558:5)
2021-10-17 10:06:39 - ❌ -     at MessageStream.messageHandler (C:\Users\Kaname\Documents\Proyectos\Kaede\kaede-rewrite\node_modules\mongodb\lib\cmap\connection.js:277:5)
2021-10-17 10:06:39 - ❌ -     at MessageStream.emit (node:events:390:28)
2021-10-17 10:06:39 - ❌ -     at MessageStream.emit (node:domain:475:12)
2021-10-17 10:06:39 - ❌ -     at processIncomingData (C:\Users\Kaname\Documents\Proyectos\Kaede\kaede-rewrite\node_modules\mongodb\lib\cmap\message_stream.js:144:12) {
2021-10-17 10:06:39 - ❌ -   driver: true,
2021-10-17 10:06:39 - ❌ -   index: 0,
2021-10-17 10:06:39 - ❌ -   code: 40
2021-10-17 10:06:39 - ❌ - }
```

**To Reproduce**
1. Create a document
2. Update embedded object field value
3. See error

**Expected behavior**

**Additional context**
Reproduction repo:
https://github.com/kaname-png/mikro-orm-error

**Versions**

| Dependency | Version |
| - | - |
| node | v16.11.0 |
| typescript | 4.4.4 |
| mikro-orm | 4.5.9 |
| your-driver | mongo |

**Comment by kaname-png** [comment]
@B4nan Can you help me?
sorry for the ping

**Comment by B4nan** [comment]
Well, this is not a bug, `onCreate/onUpdate` options on embeddables are simply not supported. Embeddables support only a subset of the options.
