### ISSUE TITLE
Cannot read properties of undefined (reading 'toLowerCase') (NextJS 11)

### ISSUE THREAD

**Issue by Arslanoov** [mikro-orm/mikro-orm#2323]
Hello. Thank you for the library

**Describe the bug**
When I am trying to initialize orm, this error appears

**Stack trace**
```
[discovery] ORM entity discovery started, using ReflectMetadataProvider
[discovery] - processing entity User
error - TypeError: Cannot read properties of undefined (reading 'toLowerCase')
at ReflectMetadataProvider.initPropertyType (/usr/src/app/node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:17:83)
    at /usr/src/app/node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:9:54
    at ReflectMetadataProvider.initProperties (/usr/src/app/node_modules/@mikro-orm/core/metadata/MetadataProvider.js:26:23)
    at async ReflectMetadataProvider.loadEntityMetadata (/usr/src/app/node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:9:9)
    at async MetadataDiscovery.discoverEntity (/usr/src/app/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:182:13)
    at async MetadataDiscovery.discoverReferences (/usr/src/app/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:131:13)
    at async MetadataDiscovery.findEntities (/usr/src/app/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:71:9)
    at async MetadataDiscovery.discover (/usr/src/app/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:34:9)
    at async Function.init (/usr/src/app/node_modules/@mikro-orm/core/MikroORM.js:42:24)
    at async handler (webpack-internal:///./src/api/useCases/articles/getAll/handler.ts:20:7) {
  page: '/articles'
}
```

**To Reproduce**
1. Clone this repository https://github.com/Arslanoov/red
2. run ```make build```
3. run ```make up```
4. run ```make migrate```
5. Try to open localhost:3000/articles page

**Expected behavior**
Page should open

**Additional context**
Api files: https://github.com/Arslanoov/red/tree/main/app/src/api
Models folder: https://github.com/Arslanoov/red/tree/main/app/src/api/model
ORM config: https://github.com/Arslanoov/red/blob/main/app/src/api/config/mikroOrm.ts
Database init: https://github.com/Arslanoov/red/blob/main/app/src/api/utils/database/init.ts

**Versions**

| Dependency | Version |
| - | - |
| node | 16 |
| typescript | 4.4.4 |
| mikro-orm | 4.5.9 |
| next | 11.1.2 |
| reflect-metadata | 0.1.13 |

**Comment by Arslanoov** [comment]
I fixed this issue by adding `type: 'string'` to all enum properties
It's strange, because documentation doesn't mention it
I think I should close this issue
![enum](https://user-images.githubusercontent.com/51407990/139865244-1e69003d-d332-4f71-a6b2-067818f5a942.png)
![role](https://user-images.githubusercontent.com/51407990/139865411-51b80f14-d416-4e71-99bc-9e95d8fc5e69.png)

**Comment by msheakoski** [comment]
Thank you @Arslanoov! I lost many hours trying to figure out if it was a TypeScript or SWC or Babel decorators issue, or something automatic that Next.js was doing. It was working without Next.js but when loading in an API route the "toLowerCase" error started happening.

What worked for me was `EnumType`:

```typescript
import { Enum, EnumType } from "@mikro-orm/core"

@Enum({ type: EnumType, items: () => CountryCode })
country!: CountryCode
```

**Comment by superiums** [comment]
same issue.
this is caused by the metaDataDiscovery.js

```js
 getMappedType(prop) {
        this.logger.log('discovery-->',JSON.stringify(prop))
        let t = prop.columnTypes?.[0] ?? prop.type.toLowerCase();
      
...
}
```

after debug, i found there's no type prop for Enum properties.
so i have to add a type ( tinnyint /smallint/string is ok) for all enum properties. but  it would be better to add a default type for it by mikroorm.

this works:
```ts
  @Enum({ type: 'tinyint', items: () => ORG_SCOPE, nullable: true })
  orgScope: ORG_SCOPE;
```
