### ISSUE TITLE
OnDelete: 'cascade' is not applied during CLI schema update

### ISSUE THREAD

**Issue by scottboyd-ai** [mikro-orm/mikro-orm#2324]
**Describe the bug**
I added an `onDelete: 'cascade'` property to a `@ManyToOne` relationship, but when I ran `mikro-orm schema:update -r`, the foreign key relationship was not updated.

This is on PostgreSQL.

Example Entities:

```
@Entity()
export class SignUp extends BaseModel {

    @ManyToOne()
    user: User;

    @ManyToOne({onDelete: 'cascade'}) // This was empty before the update command
    event: Event;
}
```
```
@Entity()
export class Event extends BaseModel{

    @Property()
    title: string;

    @Property()
    startDate: number;

    @Property({nullable: true})
    endDate?: number;
}
```
```
@Entity({abstract: true})
export abstract class BaseModel {
    @PrimaryKey()
    public id: string = v4();
}
```

**Stack trace**
```
[query] delete from "event" where "id" in ('eb47e4bc-4fa3-4b74-bc15-f87ca7b58921') [took 7 ms]
[query] rollback
[2021-10-30T18:23:59.856Z] ERROR: ForeignKeyConstraintViolationException: delete from "event" where "id" in ('eb47e4bc-4fa3-4b74-bc15-f87ca7b58921') - update or delete on table "event" violates foreign key constraint "sign_up_ev
ent_id_foreign" on table "sign_up"
    at PostgreSqlExceptionConverter.convertException (C:\Workspace\volunteerbackend\node_modules\@mikro-orm\postgresql\PostgreSqlExceptionConverter.js:26:24)
    at PostgreSqlDriver.convertException (C:\Workspace\volunteerbackend\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:202:54)
    at C:\Workspace\volunteerbackend\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:206:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ChangeSetPersister.executeDeletes (C:\Workspace\volunteerbackend\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:44:13)
    at async UnitOfWork.commitDeleteChangeSets (C:\Workspace\volunteerbackend\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:558:9)
    at async UnitOfWork.persistToDatabase (C:\Workspace\volunteerbackend\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:501:13)
    at async PostgreSqlConnection.transactional (C:\Workspace\volunteerbackend\node_modules\@mikro-orm\knex\AbstractSqlConnection.js:53:25)
    at async UnitOfWork.commit (C:\Workspace\volunteerbackend\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:184:17)
    at async SqlEntityManager.flush (C:\Workspace\volunteerbackend\node_modules\@mikro-orm\core\EntityManager.js:497:9)

previous error: delete from "event" where "id" in ('eb47e4bc-4fa3-4b74-bc15-f87ca7b58921') - update or delete on table "event" violates foreign key constraint "sign_up_event_id_foreign" on table "sign_up"
    at Parser.parseErrorMessage (C:\Workspace\volunteerbackend\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (C:\Workspace\volunteerbackend\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (C:\Workspace\volunteerbackend\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (C:\Workspace\volunteerbackend\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 314,
  severity: 'ERROR',
  code: '23503',
  detail: 'Key (id)=(eb47e4bc-4fa3-4b74-bc15-f87ca7b58921) is still referenced from table "sign_up".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'sign_up',
  column: undefined,
  dataType: undefined,
  constraint: 'sign_up_event_id_foreign',
  file: 'ri_triggers.c',
  line: '2490',
  routine: 'ri_ReportViolation'
}

```

**To Reproduce**
1. Create two entities, one with a `@ManyToOne` relationship to the other
2. Create the schema via CLI
3. Add a `onDelete: 'cascade'` property to the `@ManyToOne` definition
4. Run the CLI update command `mikro-orm schema:update -r`

**Expected behavior**
The foreign key relationship was updated to use an `ON DELETE CASCADE` method.

**Additional context**
If the table is dropped and recreated with the same `mikro-orm schema:update -r` command, the `ON CASCADE DELETE` exists.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.15.4 |
| typescript | 4.4.4 |
| mikro-orm | 4.5.9 |
| your-driver | 4.5.9 |

**Comment by B4nan** [comment]
Fixed in v5, no plans to backport schema related fixes as the changes are too incompatible.
