### ISSUE TITLE
Collection not initialized error despite not calling any operations on entity's collections

### ISSUE THREAD

**Issue by bryan-vh** [mikro-orm/mikro-orm#2331]
**Description**
Getting an error about a collection for an entity not being initialized despite only calling a simple find from a repository for that entity.

**Stack trace**
```
Error: Collection<Reservation> of entity User[4LvcX3AHjRh1FfwD4ccEX7VfnXu2] not initialized
at Collection.checkInitialized (/var/app/current/node_modules/@mikro-orm/core/entity/Collection.js:295:19)
at Collection.count (/var/app/current/node_modules/@mikro-orm/core/entity/Collection.js:163:14)
at Collection.get length [as length] (/var/app/current/node_modules/@mikro-orm/core/entity/ArrayCollection.js:110:21)
at isArrayLike (/var/app/current/node_modules/lodash/isArrayLike.js:30:42)
at keys (/var/app/current/node_modules/lodash/keys.js:34:10)
at baseGetAllKeys (/var/app/current/node_modules/lodash/_baseGetAllKeys.js:16:16)
at getAllKeys (/var/app/current/node_modules/lodash/_getAllKeys.js:13:10)
at baseClone (/var/app/current/node_modules/lodash/_baseClone.js:154:35)
at /var/app/current/node_modules/lodash/_baseClone.js:161:30
at arrayEach (/var/app/current/node_modules/lodash/_arrayEach.js:15:9)
```

**To Reproduce**
Running a simple findOneOrFail call for a given id passed in to the function:

```
async get(id: string): Promise<User> {
    const repo = this.em.getRepository(User)
    const user = await repo.findOneOrFail({ id })
    return user
}
```

**Expected behavior**
User entity should just return and no error should be thrown.

**Additional context**
User Entity:

```
import { Collection, Entity, Index, OneToMany, PrimaryKey, Property, Unique } from '@mikro-orm/core'
import { Invitation } from 'src/invitations/entities/invitation.entity'
import { Like } from 'src/likes/entities/like.entity'
import { Relationship } from 'src/relationships/entities/relationship.entity'
import { Reservation } from 'src/reservations/entities/reservation.entity'

@Entity()
export class User {
  @PrimaryKey()
  id!: string

  @Index()
  @Unique()
  @Property()
  username!: string

  @Property()
  name!: string

  @Property()
  birthday!: Date

  @Property()
  profile!: string

  @Property()
  photos?: string[]

  @Property()
  bio?: string

  // Relations

  @OneToMany(() => Reservation, (reservation) => reservation.user, { hidden: true })
  reservations = new Collection<Reservation>(this)

  @OneToMany(() => Like, (like) => like.user, { hidden: true })
  likes = new Collection<Like>(this)

  @OneToMany(() => Invitation, (invitation) => invitation.user, { hidden: true })
  invitations = new Collection<Invitation>(this)

  @OneToMany(() => Relationship, (relationship) => relationship.first, { hidden: true })
  firstRelationships = new Collection<Relationship>(this)

  @OneToMany(() => Relationship, (relationship) => relationship.second, { hidden: true })
  secondRelationships = new Collection<Relationship>(this)
}
```

**Versions**

| Dependency | Version |
| node | v17.0.1 |
| typescript | v4.3.5 |
| mikro-orm | v4.5.9 |

**Comment by B4nan** [comment]
Well, you can clearly see from the stack trace that you are triggering some validation that checks the collection length - for that it needs to be initialized.

```
at Collection.get length [as length] (/var/app/current/node_modules/@mikro-orm/core/entity/ArrayCollection.js:110:21)
at isArrayLike (/var/app/current/node_modules/lodash/isArrayLike.js:30:42)
```

**Comment by bryan-vh** [comment]
Is there any way that I could see where that validation check is occurring? I think that would be really helpful, but a bit unsure of the best way to go about it.

**Comment by bryan-vh** [comment]
Okay I figured out the issue, for some reason NestJS throws an error when using a global CacheInterceptor when I try to get the entity without loading its collections. Not sure why, but turning the interceptor off fixed the issue, thank you for pointing out the validation piece!

**Comment by B4nan** [comment]
You can use cache interceptor too, but you need to return POJOs from the endpoint explicitly.
