### ISSUE TITLE
I had an error using MikroORM in my Nest tests

### ISSUE THREAD

**Issue by WumaCoder** [mikro-orm/mikro-orm#2335]
**Describe the bug**
I had an error using MikroORM in my Nest tests

ValidationError: You cannot call em.flush() from inside lifecycle hook handlers

But there was no problem before, and this time it suddenly appeared
**Stack trace**
```
● GroupService › should user join group

    ValidationError: You cannot call em.flush() from inside lifecycle hook handlers

      41 |       await this.flush();
      42 |     } else {
    > 43 |       await this.persistAndFlush(entity);
         |                  ^
      44 |     }
      45 |     return entity;
      46 |   }

      at Function.cannotCommit (node_modules/@mikro-orm/core/errors.js:77:16)
      at UnitOfWork.commit (node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:168:44)
      at MongoEntityManager.flush (node_modules/@mikro-orm/core/EntityManager.js:497:36)
      at MongoEntityManager.persistAndFlush (node_modules/@mikro-orm/core/EntityManager.js:449:36)
      at UserRepo.persistAndFlush (node_modules/@mikro-orm/core/entity/EntityRepository.js:21:23)
      at UserRepo.save (src/entities/common.entity.ts:43:18)
      at UserService.create (src/modules/user/user.service.ts:19:32)

```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**
There is no error

**Additional context**
  ValidationError: You cannot call em.flush() from inside lifecycle hook handlers

**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | 4.5.9 |
| your-driver | mongo |

**Comment by B4nan** [comment]
It is a validation, it point to issues in your code, not to bugs in the orm. 

It usually means you are trying to flush one instance of UoW in parallel, which is not allowed.
