### ISSUE TITLE
Unsafe 'setValue' in wrapped.__identifier property (ChangeSetPersister.ts, method mapPrimaryKey)

### ISSUE THREAD

**Issue by Bernard2254** [mikro-orm/mikro-orm#2348]
**Describe the bug**

I'm trying to persist an Entity in MySQL. I've decided to use EntitySchema. After doing all the configuration described bellow, I'm receiving an `TypeError: Cannot read property 'setValue' of undefined`.

 **BaseEntity and BaseEntitySchema**
 ```
 export abstract class BaseEntity {
    uuid: string;
    dataCriacao: Date;
    dataAtualizacao: Date;
    versao: number;
}

export const BaseEntitySchema = new EntitySchema<BaseEntity>({
    name: 'BaseEntity',
    abstract: true,
    properties: {
        uuid: { type: 'string', onCreate: () => v4(), primary: true },
        dataCriacao: { type: 'Date', onCreate: () => new Date(), nullable: false },
        dataAtualizacao: { type: 'Date', onCreate: () => new Date(), onUpdate: () => new Date(), nullable: true },
        versao: { type: 'number', version: true, nullable: false }
    },
});
```

**ComplementOptionEntity and ComplementOptionEntitySchema**
```
export class ComplementOption extends BaseEntity {
  nome: string;
  descricao?: string;
  preco: number;
  complemento?: Complement;
  [EntityRepositoryType]?: ComplementOptionRepository;
}

export const ComplementOptionSchema = new EntitySchema<ComplementOption, BaseEntity>({
  name: 'ComplementOption',
  extends: 'BaseEntity',
  properties: {
    nome: { type: 'string', nullable: false },
    descricao: { type: 'string', nullable: true },
    preco: { type: 'number', nullable: false },
    complemento: { reference: 'm:1', entity: () => Complement, nullable: true }
  },
  customRepository: () => ComplementOptionRepository,
});
```

**ComplementOptionRepository**
```
@Repository(ComplementOption)
export class ComplementOptionRepository extends BaseRepositoryAbstract<ComplementOption> implements IComplementOptionRepository {
  async getAllOptions(): Promise<ComplementOption[]> {
    return await this.findAll();
  }
}

export interface IComplementOptionRepository {
    getAllOptions(): Promise<ComplementOption[]>;
}

export abstract class BaseRepositoryAbstract<M extends BaseEntity> extends EntityRepository<M> implements MyRepositoryAdapter<M> {

// implementation of MyRepositoryAdapter methods using EntityRepository

}

```

**Mikro-orm config**
```
MikroORM.init({
entities: [BaseEntitySchema, ComplementOptionSchema, ComplementSchema, ProductSchema],
user: 'root',
password: '',
host: '127.0.0.1',
port: 3306,
dbName:  'mf-register-server',
type:  'mysql',
highlighter:  process.env.REPOSITORY_LOGGER_HIGHLIGHTER == 'true' ? new  SqlHighlighter() : new  NullHighlighter(),
debug:  process.env.REPOSITORY_LOGGER_DEBUG == 'true' ? true : ['query'],
logger: (msg) =>  logger.debug(msg, context),
forceUtcTimezone:  true, // Use forceUtcTimezone option to force the Dates to be saved in UTC in datetime columns without timezone,
entityRepository:  MagnaRepository  // base repository (for all entities where you do not specify customRepository) ,
});
```

My question it's: Am I doing something wrong in my configuration? Should ChangeSetPersister.ts method 'mapPrimaryKey' use an unsafe 'setValue' in wrapped.__identifier property? As we can see in typings.d.ts, this property its optional. 

As in my cenario `wrapped.__identifier` its undefined. I'm receiving the error `TypeError: Cannot read property 'setValue' of undefined`.

**Stack trace**
```
TypeError: Cannot read property 'setValue' of undefined
    at ChangeSetPersister.mapPrimaryKey (/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:126:30)
    at ChangeSetPersister.processProperty (/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:202:22)
    at ChangeSetPersister.processProperties (/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:50:18)
    at /node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:19:46
...
```

**Expected behavior**
After run repo.create(complementOption), have the related table filled.

**Versions**

| Dependency | Version |
| - | - |
| node | v16.6.1 |
| typescript | 4.4.4 |
| mikro-orm | 4.5.9 |
| your-driver | MySQL |

**Comment by B4nan** [comment]
You should use `class` and link your `EntitySchema` with the entity classes, I believe that should be the issue here as your entity classes are not discovered this way. Using `name` with a strings class name will generate a runtime class and won't actually use the one you have defined, therefore the ORM won't see your custom classes as actual entities. 

```ts
export abstract class BaseEntity {
   uuid: string;
   dataCriacao: Date;
   dataAtualizacao: Date;
   versao: number;
}

export const BaseEntitySchema = new EntitySchema<BaseEntity>({
   class: BaseEntity, // use `class` instead of `name`
   abstract: true,
   properties: {
       uuid: { type: 'string', onCreate: () => v4(), primary: true },
       dataCriacao: { type: 'Date', onCreate: () => new Date(), nullable: false },
       dataAtualizacao: { type: 'Date', onCreate: () => new Date(), onUpdate: () => new Date(), nullable: true },
       versao: { type: 'number', version: true, nullable: false }
   },
});

export class ComplementOption extends BaseEntity {
  nome: string;
  descricao?: string;
  preco: number;
  complemento?: Complement;
  [EntityRepositoryType]?: ComplementOptionRepository;
}

export const ComplementOptionSchema = new EntitySchema<ComplementOption, BaseEntity>({
  class: ComplementOption, // use `class` instead of `name`
  extends: 'BaseEntity', // for extensions you still use string
  properties: {
    nome: { type: 'string', nullable: false },
    descricao: { type: 'string', nullable: true },
    preco: { type: 'number', nullable: false },
    complemento: { reference: 'm:1', entity: () => Complement, nullable: true }
  },
  customRepository: () => ComplementOptionRepository,
});
```

If that does not help, please provide the code that actually produces such error (so how do you create the entities and call flush, etc)

**Comment by Bernard2254** [comment]
Wonderful! I made the modifications you suggested and everything worked. Thank you very much! You saved me a lot of time
