### ISSUE TITLE
Better Embeddable Error Message

### ISSUE THREAD

**Issue by parisholley** [mikro-orm/mikro-orm#2357]
```
TypeError: Cannot read property 'class' of undefined
    at MetadataDiscovery.initEmbeddables (/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:469:46)
```

If you use `@Embedded(() => Type)` and forgot to put `@Embeddable()` on the Type class, you get the above message, which isn't clear without debugging.

```
    "@mikro-orm/cli": "^4.5.9",
    "@mikro-orm/core": "^4.5.9",
    "@mikro-orm/migrations": "^4.5.9",
    "@mikro-orm/nestjs": "^4.3.1",
    "@mikro-orm/postgresql": "^4.5.9",
    "@mikro-orm/reflection": "^4.5.9",
```

**Comment by B4nan** [comment]
This should be already handled [here](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/metadata/MetadataValidator.ts#L59), weird that it's not caught.

What is the full stack trace?

**Comment by parisholley** [comment]
```
TypeError: Cannot read property 'class' of undefined

    at MetadataDiscovery.initEmbeddables (node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:469:46)
    at node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:44:86
    at Array.forEach (<anonymous>)
    at node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:44:65
    at Array.forEach (<anonymous>)
    at MetadataDiscovery.discover (node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:44:18)
    at Function.init (node_modules/@mikro-orm/core/MikroORM.js:42:24)
```
