### ISSUE TITLE
CLI commands for consideration

### ISSUE THREAD

**Issue by localnet** [mikro-orm/mikro-orm#236]
**Is your feature request related to a problem? Please describe.**
At development time would be useful to have a command to create the database and other to seed it.

**Describe the solution you'd like**
A command to seed the database from a JSON file or simply to load a SQL file (I'm not sure which one would be more useful).

**Comment by B4nan** [comment]
Support to create/drop db has been added in #237. Instead of adding dedicated commands to do it, it's integrated in the create/drop schema commands (`schema:create` automatically tries to create the database if it not exists, and `schema:drop` allows to drop the whole database via flag). 

Also there is now `database:import <file>` command that allows to execute external SQL file.

Both available in `3.0.0-alpha.39`.

**Comment by localnet** [comment]
I am having troubles with `schema:create` and `schema:drop`:

```
$ npx mikro-orm schema:create -r
mikro-orm schema:create

Create database schema based on current metadata

Opciones:
  -r, --run      Runs queries                                         [booleano]
  -d, --dump     Dumps all queries to console                         [booleano]
  --fk-checks    Do not skip foreign key checks                       [booleano]
  -v, --version  Muestra número de versión                            [booleano]
  -h, --help     Muestra ayuda                                        [booleano]

SQLError: (conn=29, no: 1049, SQLState: 42000) Unknown database 'test'
    at Object.module.exports.createError (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/misc/errors.js:55:10)
    at Handshake.throwError (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/cmd/command.js:37:20)
    at Handshake.handshakeResult (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/cmd/handshake/handshake.js:103:28)
    at PacketInputStream.receivePacketBasic (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/io/packet-input-stream.js:104:9)
    at PacketInputStream.onData (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/io/packet-input-stream.js:160:20)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
 From event:
    at _registerHandshakeCmd (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/connection.js:632:11)
    at /home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/connection.js:59:11
    at new Promise (<anonymous>)
    at ConnectionCallback.Connection.connect (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/connection.js:58:16)
    at new ConnectionCallback (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/connection-callback.js:137:3)
    at Object.createConnection (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/callback.js:14:10)
    at /home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/knex/lib/dialects/mysql/index.js:65:38
    at Promise._execute (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/bluebird/js/release/debuggability.js:411:9)
    at Promise._resolveFromExecutor (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/bluebird/js/release/promise.js:103:10)
    at Client_MySQL.acquireRawConnection (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/knex/lib/dialects/mysql/index.js:64:12)
    at create (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/knex/lib/client.js:287:39) {
  fatal: true,
  errno: 1049,
  sqlState: '42000',
  code: 'ER_BAD_DB_ERROR'
}
```

If I create before manually the database, the command work perfectly:
```
mysql> create database test;
Query OK, 1 row affected (0.25 sec)

$ npx mikro-orm schema:create -r
Schema successfully created
```

And when I try to drop the database:
```
$ npx mikro-orm schema:drop --drop-db
mikro-orm schema:drop

Drop database schema based on current metadata

Opciones:
  -r, --run                Runs queries                               [booleano]
  -d, --dump               Dumps all queries to console               [booleano]
  --fk-checks              Do not skip foreign key checks             [booleano]
  --drop-migrations-table  Drop also migrations table                 [booleano]
  --drop-db                Drop the whole database                    [booleano]
  -v, --version            Muestra número de versión                  [booleano]
  -h, --help               Muestra ayuda                              [booleano]
```

If I try to add the `--drop-db` argumento to the `--run` argument, then it don't drop the database:
```
$ npx mikro-orm schema:drop -r --drop-db
Schema successfully dropped

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
| test               |
+--------------------+
```

I still have not been able to try `database:import`.

PS: If you prefer I can open a new issue with this information.

**Comment by B4nan** [comment]
Might be something specific to mariadb, will take a look.

**Comment by localnet** [comment]
After try with "mysql2" `schema:create` works perfectly:
```
$ npx mikro-orm schema:create -r
Schema successfully created

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
| test               |
+--------------------+
5 rows in set (0.00 sec)
```

But `schema:drop` don't drop the database:
```
$ npx mikro-orm schema:drop -r --drop-db
Schema successfully dropped

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
| test               |
+--------------------+
5 rows in set (0.00 sec)
```

**Comment by B4nan** [comment]
Fixed in `3.0.0-alpha.41`.

**Comment by localnet** [comment]
I am not sure if it is my fault, so a question:

I have a file `dataset.sql` with:
```sql
INSERT INTO
    account (id, name)
VALUES
    (1, 'account-1'),
    (2, 'account-2');

INSERT INTO
    artist (id)
VALUES
    (1),
    (2);
```

And I get this error:
```
$ npx mikro-orm database:import test/dataset.sql
mikro-orm database:import <file>

Imports the SQL file to the database

Opciones:
  -v, --version  Muestra número de versión                            [booleano]
  -h, --help     Muestra ayuda                                        [booleano]

SQLError: (conn=61, no: 1064, SQLState: 42000) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO
    artist (id)
VALUES
    (1),
    (2)' at line 7
sql: INSERT INTO
    account (id, name)
VALUES
    (1, 'account-1'),
    (2, 'account-2');

INSERT INTO
    artist (id)
VALUES
    (1),
    (2);
 - parameters:[]
    at Object.module.exports.createError (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/misc/errors.js:55:10)
    at PacketNodeEncoded.readError (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/io/packet.js:510:19)
    at Query.readResponsePacket (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/cmd/resultset.js:46:28)
    at PacketInputStream.receivePacketBasic (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/io/packet-input-stream.js:104:9)
    at PacketInputStream.onData (/home/alejandro/Documentos/Proyectos/tattoo/server/node_modules/mariadb/lib/io/packet-input-stream.js:160:20)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  fatal: false,
  errno: 1064,
  sqlState: '42000',
  code: 'ER_PARSE_ERROR'
}
```

If the file only has data for a table all work ok. Do I have to create one file per table?

**Comment by B4nan** [comment]
Try adding `multipleStatements: true` to the ORM options.

**Comment by localnet** [comment]
That was. I had not seen the option.

Thanks.

**Comment by B4nan** [comment]
It is driver specific thing, pg and mysql connectors does not allow running multiple commands in single query by default.

I am planning to add new configuration section to docs where all options will be described, this particular one is probably nowhere specified...
