### ISSUE TITLE
Maximum call stack size exceeded with sqlite driver.

### ISSUE THREAD

**Issue by JimmyKunSama** [mikro-orm/mikro-orm#2422]
**Describe the bug**
Orm.close() may not be closing the selected MikroOrm instance and it just keeps stacking. 

**Stack trace**
```
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at Sqlite3Dialect.processResponse (D:\~stash-vault~\project\nestjs\node_modules\@mikro-orm\sqlite\dist\SqliteConnection.js:55:56)
    at Sqlite3Dialect.processResponse (D:\~stash-vault~\project\nestjs\node_modules\@mikro-orm\sqlite\dist\SqliteConnection.js:58:20)
    at Sqlite3Dialect.processResponse (D:\~stash-vault~\project\nestjs\node_modules\@mikro-orm\sqlite\dist\SqliteConnection.js:58:20)
    at Sqlite3Dialect.processResponse (D:\~stash-vault~\project\nestjs\node_modules\@mikro-orm\sqlite\dist\SqliteConnection.js:58:20)
    at Sqlite3Dialect.processResponse (D:\~stash-vault~\project\nestjs\node_modules\@mikro-orm\sqlite\dist\SqliteConnection.js:58:20)
    at Sqlite3Dialect.processResponse (D:\~stash-vault~\project\nestjs\node_modules\@mikro-orm\sqlite\dist\SqliteConnection.js:58:20)
    at Sqlite3Dialect.processResponse (D:\~stash-vault~\project\nestjs\node_modules\@mikro-orm\sqlite\dist\SqliteConnection.js:58:20)
    at Sqlite3Dialect.processResponse (D:\~stash-vault~\project\nestjs\node_modules\@mikro-orm\sqlite\dist\SqliteConnection.js:58:20)
    at Sqlite3Dialect.processResponse (D:\~stash-vault~\project\nestjs\node_modules\@mikro-orm\sqlite\dist\SqliteConnection.js:58:20)
```

**To Reproduce**
1.  Create an api endpoint with
``` 
        const orm = await MikroORM.init({
          entities: [...],
          dbName: `1.db`,
          type: 'sqlite',
          autoJoinOneToOneOwner: false,
          allowGlobalContext: true,
        });
        return await orm.close() 
```
2. Repeatedly call the api more than 10000 times

**Expected behavior**
No call stack error

**Additional context**
I am using Nestjs.
I checked the getPatchedDialect() function in SqliteConnection.js and when I removed
``` 
        const processResponse = Sqlite3Dialect.prototype.processResponse;
        Sqlite3Dialect.prototype.processResponse = (obj, runner) => {
            console.log(obj.sql) // I added this
            if (obj.method === 'raw' && obj.sql.trim().match(SqliteConnection.RUN_QUERY_RE)) {
                return obj.context;
            }
            return processResponse(obj, runner);
        };
``` 
it worked, but then orm.flush throws an error. A deeper look into obj.sql with console.log revealed that every api call seems to add an extra call.

``` 
  pragma foreign_keys = on
  select 1

  pragma foreign_keys = on
  pragma foreign_keys = on
  select 1
  select 1

  pragma foreign_keys = on
  pragma foreign_keys = on
  pragma foreign_keys = on
  select 1
  select 1
  select 1
  ...
```

**Versions**
| Dependency | Version |
| - | - |
| node | 16.11.1 |
| typescript | 4.4.4 |
| mikro-orm | 5.0.0-dev.475 |
| your-driver | sqlite |

Thanks in advance for the help!

**Comment by B4nan** [comment]
Why do you want to create new connection inside API endpoint, to the very same database? Also, by `Repeatedly call the api more than 10000 times` you mean serially or in parallel? 

Anyway, please provide full repro for this. 

> A deeper look into obj.sql with console.log revealed that every api call seems to add an extra call.

That kinda confirms you are doing it in paralell. Both queries shoudl be there, new connections will contain first the `pragma foreign_keys = on` to enable FK support, and `select 1` which is how the ORM checks if we are connected to the database. 

Just an idea, but you could verify if the monkey patching is happening just once, I have a hunch it does it each time you call `MikroORM.init()` (which is expected to be called just once on app startup).

**Comment by B4nan** [comment]
Yes, that's it, it stacks the patch on itself. I still believe this is weird, but you should known better if it's valid for you :] No need for repro.

**Comment by JimmyKunSama** [comment]
Wow that was quick. Thank you for the fix!

> Why do you want to create new connection inside API endpoint, to the very same database? 
It's actually multiple databases but the problem showed up when I was testing one of the database :))
