### ISSUE TITLE
Set Function On SerializedPrimaryKey Ignores Primary Key Type

### ISSUE THREAD

**Issue by ThatOneAwkwardGuy** [mikro-orm/mikro-orm#2472]
**Describe the bug**
I am using MikroOrm with MongoDB and my _id primary key is a string. I also have the id attribute as a SerializedPrimaryKey. When I send a request from my front end to the backend, it only includes the id attribute and the data i need to update, however, i run into the following error 

**Stack trace**
```
[0] [Nest] 84557  - 27/11/2021, 17:19:30   ERROR [ExceptionsHandler] Argument passed in must be a string of 12 bytes or a string of 24 hex characters
[0] TypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters
[0]     at new BSONTypeError (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/bson/lib/error.js:39:42)
[0]     at new ObjectId (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/bson/src/objectid.ts:86:15)
[0]     at MongoPlatform.denormalizePrimaryKey (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/mongodb/dist/MongoPlatform.js:26:16)
[0]     at OtherAssetManual.set (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/core/dist/entity/EntityHelper.js:41:42)
[0]     at /Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/core/dist/entity/EntityAssigner.js:60:37
[0]     at Array.forEach (<anonymous>)
[0]     at Function.assign (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/core/dist/entity/EntityAssigner.js:24:27)
[0]     at WrappedEntity.assign (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/@mikro-orm/core/dist/entity/WrappedEntity.js:44:48)
[0]     at AssetService.<anonymous> (/Users/moyogeorge/Documents/GitHub/clearcourt/dist/apps/api/webpack:/clearcourt/apps/api/src/app/modules/asset/asset.service.ts:134:25)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/Users/moyogeorge/Documents/GitHub/clearcourt/node_modules/tslib/tslib.js:114:62)
[0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**
1. Create a base schema and a class that extends from it:
```
import {
  Entity,
  PrimaryKey,
  Property,
  SerializedPrimaryKey,
} from '@mikro-orm/core';

import { ApiHideProperty } from '@nestjs/swagger';
import { alphanumeric } from 'nanoid-dictionary';
import { customAlphabet } from 'nanoid';

@Entity({ abstract: true })
export abstract class BaseSchemaString {
  @ApiHideProperty()
  @PrimaryKey()
  _id: string = customAlphabet(alphanumeric, 21)();

  @SerializedPrimaryKey()
  id: string;

  @Property({ onCreate: () => new Date() })
  createdAt: Date = new Date();

  @Property({ onUpdate: () => new Date() })
  updatedAt: Date = new Date();
}

@Entity({ collection: CollectionsEnum.COMPANIES })
export class Company extends BaseSchemaString {
  @Property()
  @IsString()
  name: string;
}


```
2. When assigning to a company with the id attribute included (not the _id):
```
const company = await this.companyModel.findOne(companyID)
wrap(company).assign({name:"testing", id:companyID})
```

3. The set function (mentioned below, from @mikro-orm/core/dist/entity/EntityHelper.js)  is triggered, to set the id value to the _id attribute, however, the type of _id is not checked therefore the previously mentioned error is thrown.
```
    /**
     * defines magic id property getter/setter if PK property is `_id` and there is no `id` property defined
     */
    static defineIdProperty(meta, platform) {
        Object.defineProperty(meta.prototype, 'id', {
            get() {
                return this._id ? platform.normalizePrimaryKey(this._id) : null;
            },
            set(id) {
                this._id = id ? platform.denormalizePrimaryKey(id) : null;
            },
        });
    }
```

4. Compared to the  below function (from @mikro-orm/core/dist/entity/EntityHelper.js), where the type of _id is checked before it is denormalized:
```
    /**
     * denormalize PK to value required by driver (e.g. ObjectId)
     */
    denormalizePrimaryKey(data, primaryKey, prop) {
        const pk = this.platform.getSerializedPrimaryKeyField(primaryKey);
        if (Utils_1.Utils.isDefined(data[pk], true) || Utils_1.Utils.isDefined(data[primaryKey], true)) {
            let id = data[pk] || data[primaryKey];
            if (prop.type.toLowerCase() === 'objectid') {
                id = this.platform.denormalizePrimaryKey(id);
            }
            delete data[pk];
            data[primaryKey] = id;
        }
    }
```

**Expected behavior**
I would expect the set function to check the type of _id and if it is a string then skip the denormalizing.

**Additional context**

**Versions**

| Dependency | Version |
| @mikro-orm/core| ^5.0.0-dev.527 |
| @mikro-orm/mongodb| ^5.0.0-dev.527 |
| @mikro-orm/reflection| ^5.0.0-dev.527 |

**Comment by B4nan** [comment]
> I am using MikroOrm with MongoDB and my _id primary key is a string. I also have the id attribute as a SerializedPrimaryKey.

The purpose of `@SerializedPrimaryKey` is to provide string variant for an object id. If you don't use object id PKs, I don't see a reason to use the `@SerializedPrimaryKey`.

If you want to have `id` on runtime as opposed to `_id`, you can just remap the property name:

```
  @PrimaryKey({ name: '_id' })
  id: string = customAlphabet(alphanumeric, 21)();
```
