### ISSUE TITLE
Static migrations with programmatic way not working (empty string schema)

### ISSUE THREAD

**Issue by Uminily** [mikro-orm/mikro-orm#2537]
**Describe the bug**
Hello @B4nan, I try to use migrations in a programmatic way by going through a list of Migrations and following the documentation (very well done by the way and that allows me to really do what I want, it's a change from non-permissive tools), but probably something goes wrong with postgre Schemas (it has nothing to do with my old issues, I don't use schema in this context).

```
[query] select * from "migrations" order by "id" asc [took 2 ms]
== Migration1: migrating =======
[query] begin
[query] set names 'utf8'; [took 1 ms]
[query] set session_replication_role = 'replica'; [took 1 ms]
[query] select 1 + 1 [took 1 ms]
[query] set session_replication_role = 'origin'; [took 3 ms]
[query] commit
[query] insert into ""."migrations" ("name") values ('Migration1') [took 3 ms]
[query] rollback
```

The table name is preceded by a empty string.

**Stack trace**
```
UnhandledPromiseRejectionWarning: SyntaxErrorException: insert into ""."migrations" ("name") values ('Migration1') - zero-length delimited identifier at or near """"
    at PostgreSqlExceptionConverter.convertException (C:\Users\Umi\Desktop\endeavour\node_modules\@mikro-orm\postgresql\dist\PostgreSqlExceptionConverter.js:30:24)
    at PostgreSqlDriver.convertException (C:\Users\Umi\Desktop\endeavour\node_modules\@mikro-orm\core\dist\drivers\DatabaseDriver.js:189:54)
    at C:\Users\Umi\Desktop\endeavour\node_modules\@mikro-orm\core\dist\drivers\DatabaseDriver.js:193:24
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at PostgreSqlDriver.nativeInsert (C:\Users\Umi\Desktop\endeavour\node_modules\@mikro-orm\knex\dist\AbstractSqlDriver.js:153:21)
    at MigrationStorage.logMigration (C:\Users\Umi\Desktop\endeavour\node_modules\@mikro-orm\migrations\MigrationStorage.js:17:9)
```

**To Reproduce**
1. First, you have to use the migrationsList option in migrations, without schema option set (Here I changed the tableName to migrations, but it's the same with default value mikro-orm-migrations).
2. Then migrator.up()
3. Table "migrations" is created, but nativeInsert try to insert with empty-character schema

**Expected behavior**
Insert migrationLists migrations into migrations table :)
Thank you very much once again for your amazing work.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.17.3 |
| typescript | 4.5.4 |
| mikro-orm | 5.0.0-dev.562 |
| your-driver | postgresql 5.0.0-dev.562 |

**Comment by B4nan** [comment]
How does your full ORM config look like? Can you add logs to this place, to see what `this.options.tableName` and `tables` holds?

https://github.com/mikro-orm/mikro-orm/blob/9996a16eff665adda3298ffb6e421d6b3b29c126/packages/migrations/src/MigrationStorage.ts#L51

**Comment by Uminily** [comment]
Ofc, my config looks like :
```
{
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '5432'),
    dbName: process.env.DB_NAME || 'xxxxx',
    user: process.env.DB_USER || 'xxxx',
    password: process.env.DB_PASSWORD || 'xxxxx',
    type: 'postgresql',
    debug: true,
    loadStrategy: LoadStrategy.JOINED,
    allowGlobalContext: true,
    migrations: {
      tableName: 'migrations',
      migrationsList: [
        {
          name: 'Migration1',
          class: Migration1
        }
      ],
      transactional: true,
      allOrNothing: true,
      safe: true,
      emit: 'ts'
    },
    driverOptions: {
      connection: {
        ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false
      }
    }
}
```

And here are the logs as requested :
```
{ tableName: 'migrations' }

{
  tables: [
    {
      table_name: 'migrations',
      schema_name: null,
      table_comment: null
    }
  ]
}
```

**Comment by B4nan** [comment]
Hmm but that should not pass thru the condition and should not even issue the query

```ts
if (tables.find(t => t.table_name === this.options.tableName!)) {
```

**Comment by Uminily** [comment]
I removed tableName option to maximize the chances but same issue, the migrator creates the new migration table and lists the old migration table, but when inserting, the same issue occurs :

```
[query] select table_name, nullif(table_schema, 'public') as schema_name, (select pg_catalog.obj_description(c.oid) from pg_catalog.pg_class c where c.oid = (select ('"' || table_schema || '"."' || table_name || '"')::regclass::oid) and c.relname = table_name) as table_comment from information_schema.tables where table_schema not like 'pg_%' and table_schema != 'information_schema' and table_name != 'geometry_columns' and table_name != 'spatial_ref_sys' and table_type != 'VIEW' order by table_name [took 4 ms]

{ tableName: 'mikro_orm_migrations' }

{
  tables: [
    {
      table_name: 'migrations',
      schema_name: null,
      table_comment: null
    }
  ]
}

[query] create table "mikro_orm_migrations" ("id" serial primary key, "name" varchar(255), "executed_at" timestamptz default current_timestamp)
[query] begin
[query] select * from "mikro_orm_migrations" order by "id" asc [took 2 ms]
[query] select * from "mikro_orm_migrations" order by "id" asc [took 2 ms]
== Migration1: migrating =======
[query] begin
[query] set names 'utf8'; [took 2 ms]
[query] set session_replication_role = 'replica'; [took 1 ms]
[query] select 1 + 1 [took 0 ms]
[query] set session_replication_role = 'origin'; [took 0 ms]
[query] commit
[query] insert into ""."mikro_orm_migrations" ("name") values ('Migration1') [took 1 ms]
[query] rollback
```

**Comment by B4nan** [comment]
Ah ok I missed that, the problem is not ensuring the table but logging migrations.

**Comment by Uminily** [comment]
Sorry @B4nan, after a second clean install, everything works fine, I think the migration package was not in version 5 while all the others should be, or something like that. Really sorry for taking up your time.
