### ISSUE TITLE
MikroORM Fails to Perist Relation (MySQL Error)

### ISSUE THREAD

**Issue by dakotacookenmaster** [mikro-orm/mikro-orm#2569]
f**Describe the bug**
MikroORM fails to persist a bi-directional relationship with MySQL (field doesn't have a default value for a foreign key)

**Stack trace**
```
NotNullConstraintViolationException: insert into `upload` (`created_at`, `id`, `location`, `title`, `updated_at`) values ('2021-12-23 14:58:18.634', 'be6d7898-25c5-4339-a20d-287c12305f26', '/upload/content-section/bounce-search.svg', 'Profile Image', '2021-12-23 14:58:18.634') - Field 'created_by_id' doesn't have a default value
    at MySqlExceptionConverter.convertException (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\@mikro-orm\mysql\node_modules\@mikro-orm\mysql-base\dist\MySqlExceptionConverter.js:76:24)
    at MySqlDriver.convertException (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\@mikro-orm\core\dist\drivers\DatabaseDriver.js:177:54)
    at C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\@mikro-orm\core\dist\drivers\DatabaseDriver.js:181:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MySqlDriver.nativeInsert (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\@mikro-orm\mysql\node_modules\@mikro-orm\mysql-base\node_modules\@mikro-orm\knex\dist\AbstractSqlDriver.js:157:21)
    at async ChangeSetPersister.persistNewEntity (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\@mikro-orm\core\dist\unit-of-work\ChangeSetPersister.js:80:21)
    at async ChangeSetPersister.executeInserts (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\@mikro-orm\core\dist\unit-of-work\ChangeSetPersister.js:27:13)
    at async ChangeSetPersister.runForEachSchema (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\@mikro-orm\core\dist\unit-of-work\ChangeSetPersister.js:66:13)
    at async UnitOfWork.commitCreateChangeSets (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\@mikro-orm\core\dist\unit-of-work\UnitOfWork.js:615:9)
    at async UnitOfWork.persistToDatabase (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\@mikro-orm\core\dist\unit-of-work\UnitOfWork.js:567:13)

previous Error: insert into `upload` (`created_at`, `id`, `location`, `title`, `updated_at`) values ('2021-12-23 14:58:18.634', 'be6d7898-25c5-4339-a20d-287c12305f26', '/upload/content-section/bounce-search.svg', 'Profile Image', '2021-12-23 14:58:18.634') - Field 'created_by_id' doesn't have a default value
    at Packet.asError (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\mysql2\lib\packets\packet.js:728:17)
    at Query.execute (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\mysql2\lib\commands\command.js:29:26)
    at Connection.handlePacket (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\TrekTraveller\Documents\projects\emblem\server-new\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlState: 'HY000',
  sqlMessage: "Field 'created_by_id' doesn't have a default value",
  sql: "insert into `upload` (`created_at`, `id`, `location`, `title`, `updated_at`) values ('2021-12-23 14:58:18.634', 'be6d7898-25c5-4339-a20d-287c12305f26', '/upload/content-section/bounce-search.svg', 'Profile Image', '2021-12-23 14:58:18.634')"
}
Schema successfully dropped and recreated
```

**To Reproduce**

1. Define a bidirectional relationship:

Upload.ts
```JS
import { BeforeCreate, BeforeUpdate, Collection, Entity, ManyToOne, OneToMany, OneToOne, PrimaryKey, Property } from "@mikro-orm/core"
import { IsNotEmpty, validateOrReject } from "class-validator"
import { v4 as uuid } from "uuid"
import Announcement from "./Announcement"
import Assignment from "./Assignment"
import ContentSection from "./ContentSection"
import Course from "./Course"
import TextResponse from "./TextResponse"
import User from "./User"
/**
 * The Upload entity is used to create and interact with uploads. Uploads are used to allow a user to upload
 * their own file to an annoucement, assignment, or content section.
 */
@Entity()
export default class Upload {
    @PrimaryKey()
    id: string = uuid()

    @IsNotEmpty({ message: "Please enter a title." })
    @Property({
        nullable: false,
        length: 128,
    })
    title: string

    @IsNotEmpty({ message: "Please upload a file." })
    @Property({
        nullable: false,
        length: 512,
    })
    location: string

    @Property()
    created_at: Date = new Date()

    @Property({ onUpdate: () => new Date() })
    updated_at: Date = new Date()

    @ManyToOne({ entity: "User", inversedBy: "uploads" })
    created_by!: User

    @OneToMany({ entity: "User", mappedBy: "profile_image" })
    users = new Collection<User>(this)

    @ManyToOne({ entity: "ContentSection", inversedBy: "uploads", onDelete: "CASCADE" })
    content_section!: ContentSection

    @ManyToOne({ entity: "Announcement", inversedBy: "uploads", onDelete: "CASCADE" })
    announcement: Announcement

    @ManyToOne({ entity: "Assignment", inversedBy: "uploads", onDelete: "CASCADE" })
    assignment: Assignment

    @ManyToOne({ entity: "TextResponse", inversedBy: "uploads", onDelete: "CASCADE" })
    text_response: TextResponse

    @OneToOne({ entity: "Course", mappedBy: "upload", onDelete: "CASCADE" })
    course: Course

    // Extremely important! Must validate before insertion!
    @BeforeUpdate()
    @BeforeCreate()
    protected validate = async () => {
        await validateOrReject(this, {
            forbidUnknownValues: true,
        })
    }
}
```

User.ts
```JS
import { IsDate, IsEmail, IsNotEmpty, IsOptional, MaxLength, validateOrReject } from "class-validator"
import { IsStrongPassword } from "./decorators/IsStrongPassword"
import { BeforeCreate, BeforeUpdate, Cascade, Collection, Entity, ManyToMany, ManyToOne, OneToMany, PrimaryKey, Property } from "@mikro-orm/core"
import { v4 as uuid } from "uuid"
import Upload from "./Upload"
import Badge from "./Badge"
import Section from "./Section"
import Organization from "./Organization"
import Announcement from "./Announcement"
import Issue from "./Issue"
import Submission from "./Submission"
import PasswordResetToken from "./PasswordResetToken"
import AssignmentDueDateException from "./AssignmentDueDateException"
import Role from "./Role"

/**
 * The User entity is used to create and interact with users.
 */
@Entity()
export default class User {
    @PrimaryKey()
    public id: string = uuid()

    @IsNotEmpty({ message: "Please enter a first name." })
    @MaxLength(64, { message: "Please enter a first name less than 64 characters." })
    @Property({
        nullable: false,
        length: 64,
    })
    public first_name: string

    @IsNotEmpty({ message: "Please enter a last name." })
    @MaxLength(128, { message: "Please enter a last name less than 128 characters." })
    @Property({
        nullable: false,
        length: 128
    })
    public last_name: string

    @IsNotEmpty({ message: "Please enter an email address" })
    @MaxLength(512, { message: "Please enter an email address that is fewer than 512 characters." })
    @IsEmail({}, { message: "Please enter a valid email address." })
    @Property({
        nullable: false,
        length: 512,
        unique: true,
        hidden: true,
    })
    public email: string

    @IsNotEmpty({ message: "Please enter your password." })
    @IsStrongPassword({ message: "Please enter a stronger password." })
    @Property({
        nullable: false,
        hidden: true, // Prevents password from showing up in general queries
    })
    public password: string

    @IsDate({ message: "Please enter a valid datetime." })
    @IsOptional()
    @Property({
        length: 6,
        nullable: true,
        hidden: true, // Prevent last_login from showing up in general queries
    })
    public last_login: Date

    @Property()
    created_at: Date = new Date()

    @Property({ onUpdate: () => new Date() })
    updated_at: Date = new Date()

    @OneToMany({ entity: "Upload", mappedBy: "created_by" })
    uploads = new Collection<Upload>(this)

    @ManyToOne({ entity: "Upload", inversedBy: "users" })
    profile_image: Upload

    @ManyToMany({ entity: "Badge", inversedBy: "users", owner: true })
    badges = new Collection<Badge>(this)

    @ManyToMany({ entity: "Section", inversedBy: "students", owner: true })
    sections_enrolled_as_student = new Collection<Section>(this)

    @ManyToMany({ entity: "Section", inversedBy: "instructors", owner: true })
    sections_enrolled_as_instructor = new Collection<Section>(this)

    @ManyToMany({ entity: "Organization", inversedBy: "users", owner: true })
    organizations = new Collection<Organization>(this)

    @OneToMany({ entity: "Announcement", mappedBy: "created_by" })
    announcements = new Collection<Announcement>(this)

    @OneToMany({ entity: "Issue", mappedBy: "created_by" })
    issues_created = new Collection<Issue>(this)

    @OneToMany({ entity: "Issue", mappedBy: "updated_by" })
    issues_updated = new Collection<Issue>(this)

    @OneToMany({ entity: "Submission", mappedBy: "user" })
    submissions = new Collection<Submission>(this)

    @OneToMany({ entity: "PasswordResetToken", mappedBy: "user" })
    password_reset_tokens = new Collection<PasswordResetToken>(this)
    
    @ManyToMany({ entity: "AssignmentDueDateException", inversedBy: "users", owner: true })
    assignment_due_date_exceptions = new Collection<AssignmentDueDateException>(this)

    @ManyToMany({ entity: "Role", inversedBy: "users" })
    roles = new Collection<Role>(this)

    // Extremely important! Must validate before insertion!
    @BeforeCreate()
    @BeforeUpdate()
    private validate = async () => {
        await validateOrReject(this, {
            forbidUnknownValues: true,
        })
    }
}
```

3. Create the connections with real data and attempt to persist:

```JS
const image1 = new Upload()
image1.title="Profile Image"
image1.location="/upload/content-section/bounce-search.svg"

// Generate Users
const user1 = new User()
user1.first_name = "John"
user1.last_name = "Doe"
user1.email = "jdoe@gmail.com"
user1.password = "vrySt810nda0&pw39jda"
user1.uploads.add(image1)
user1.profile_image = image1
user1.roles.add(admin)

await em.persistAndFlush(user1)
```

**Expected behavior**
I would expect that the ORM would automatically connect the two relations and assign foreign keys as necessary to persist it.

**Additional context**
It is most certainly possible that I am defining the mappedBy or inversedBy relationships incorrectly. Please let me know if this is the case.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.0.0 |
| typescript | ^10.4.0 |
| mikro-orm | ^5.0.0-dev.591 |
| your-driver | 'mysql' |

**Comment by dakotacookenmaster** [comment]
I solved this issue, actually. It turns out that Mikro-ORM is less flexible when it comes to ManyToOne relations. TypeORM automatically marked the "many" side as nullable, but Mikro-ORM does not. Adding ```nullable: true``` to the many side seems to have fixed this issue.
