### ISSUE TITLE
Query is not building properly when using `fixedOrder` and working with schemas

### ISSUE THREAD

**Issue by victor-alegre-santos** [mikro-orm/mikro-orm#2621]
**Describe the bug**
When using a ManyToMany relation with a schema defined in `pivotTable` and property `fixedOrder` is set to true (regardless if `fixedOrderColumn` is defined or not), the  `order by` part of the built query is not correct.

**Stack trace**
```
TableNotFoundException: select "e0".*, "e1"."pivot_field_one" as "fk__pivot_field_one", "e1"."pivot_field_two" as "fk__pivot_field_two" from "schema"."command" as "e0" left join "schema"."pivot_table" as "e1" on "e0"."id" = "e1"."pivot_field_one" where "e1"."pivot_field_two" in (1, 2, 3) order by "schema"."pivot_table" asc - missing FROM-clause entry for table "schema"      
    at PostgreSqlExceptionConverter.convertException (...\node_modules\@mikro-orm\postgresql\PostgreSqlExceptionConverter.js:36:24)
    at PostgreSqlDriver.convertException (...\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:202:54)
    at ...\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:206:24
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at PostgreSqlDriver.loadFromPivotTable (...\node_modules\@mikro-orm\knex\AbstractSqlDriver.js:364:39)
    at EntityLoader.findChildrenFromPivotTable (...\node_modules\@mikro-orm\core\entity\EntityLoader.js:226:21)
    at EntityLoader.populateField (...\node_modules\@mikro-orm\core\entity\EntityLoader.js:185:25)
    at EntityLoader.populate (...\node_modules\@mikro-orm\core\entity\EntityLoader.js:37:13)     
    at SqlEntityManager.find (...\node_modules\@mikro-orm\core\EntityManager.js:105:9)
    at EntityLoader.populateMany (...\node_modules\@mikro-orm\core\entity\EntityLoader.js:127:22)    at EntityLoader.populateField (...\node_modules\@mikro-orm\core\entity\EntityLoader.js:187:9)    at EntityLoader.populate (...\node_modules\@mikro-orm\core\entity\EntityLoader.js:37:13)     
    at SqlEntityManager.lockAndPopulate (...\node_modules\@mikro-orm\core\EntityManager.js:630:9)    at SqlEntityManager.findOne (...\node_modules\@mikro-orm\core\EntityManager.js:244:9)        
    at SqlEntityManager.findOneOrFail (...\node_modules\@mikro-orm\core\EntityManager.js:254:24) 
    at async Promise.all (index 0)

previous error: select "e0".*, "e1"."pivot_field_one" as "fk__pivot_field_one", "e1"."pivot_field_two" as "fk__pivot_field_two" from "schema"."command" as "e0" left join "schema"."pivot_table" as "e1" on "e0"."id" = "e1"."pivot_field_one" where "e1"."pivot_field_two" in 
(1, 2, 3) order by "schema"."pivot_table" asc - missing FROM-clause entry for table "schema"
    at Parser.parseErrorMessage (...\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (...\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (...\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (...\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:131:17)
```

**To Reproduce**
1. Create an unidirectional ManyToMany collection
2. Set `pivotTable` with schema
3. Set `fixedOrder` to true

**Expected behavior**
The query should be built with a correct order by clause, `"e1"."id" asc` in this case.

**Additional context**
I tried it in two ways, neither worked
```
@ManyToMany({
    entity: () => Class,
    pivotTable: 'schema.pivot_table',
    fixedOrder: true,
    fixedOrderColumn: 'id',
    inverseJoinColumn: 'pivot_field_one'
})
field?: Collection<Class> = new Collection<Class>(this);
```

```
@ManyToMany({
    entity: () => Class,
    pivotTable: 'schema.pivot_table',
    fixedOrder: true,
    inverseJoinColumn: 'pivot_field_one'
})
field?: Collection<Class> = new Collection<Class>(this);
```

**Versions**

| Dependency | Version |
| - | - |
| node | 14.17.3 |
| typescript | 4.4.4 |
| @mikro-orm/core | 4.5.10 |
| @mikro-orm/nestjs | 4.3.1 |
| @mikro-orm/postgresql | 4.5.10 |

**Comment by B4nan** [comment]
This was much trickier than expect, unfortunately not backportable to v4.
