### ISSUE TITLE
Fail to migrate the new created migration file

### ISSUE THREAD

**Issue by suerta-git** [mikro-orm/mikro-orm#2637]
**Describe the bug**
There are 2 migration files:
```
./migrations
├── Migration20220109150239.js    # ✅ old one which is already migrated before 
└── Migration20220113153248.js    # ❌ new one created by cli from latest entities 
```

My journey is:
- `create` & `up` the 1st migration according to old entity definitions
- Do modifications on entities
- `create` the 2nd migration but `up` failed

**Stack trace**
```
DriverException: alter table "player" add constraint "player_pkey" primary key ("id"); - multiple primary keys for table "player" are not allowed
    at PostgreSqlExceptionConverter.convertException (/Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException (/Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:40:22)
    at PostgreSqlDriver.convertException (/Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:202:54)
    at /Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:206:24
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Function.runSerial (/Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/@mikro-orm/core/utils/Utils.js:490:22)
    at async /Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/@mikro-orm/migrations/MigrationRunner.js:23:17
    at async PostgreSqlConnection.transactional (/Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:53:25)
    at async MigrationRunner.run (/Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/@mikro-orm/migrations/MigrationRunner.js:20:13)

previous error: alter table "player" add constraint "player_pkey" primary key ("id"); - multiple primary keys for table "player" are not allowed
    at Parser.parseErrorMessage (/Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 123,
  severity: 'ERROR',
  code: '42P16',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'index.c',
  line: '223',
  routine: 'index_check_primary_key'
```

**To Reproduce**
1. Migrate up to 1st file
2. Generate the 2nd migration using latest entities
3. Migrate up to 2nd file

**Additional context**
<details>
<summary>Migrations</summary>

**Migration20220109150239.js**
```js
'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
const Migration = require('@mikro-orm/migrations').Migration;

class Migration20220109150239 extends Migration {

  async up() {
    this.addSql('create table "player" ("id" serial primary key, "name" varchar(255) null);');
  }

}
exports.Migration20220109150239 = Migration20220109150239;
```

**Migration20220113155133.js**
```js
'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
const Migration = require('@mikro-orm/migrations').Migration;

class Migration20220113155133 extends Migration {

  async up() {
    this.addSql('alter table "player" add column "created_at" timestamptz(0) not null, add column "updated_at" timestamptz(0) not null, add column "connection_id" varchar(255) not null;');
    this.addSql('alter table "player" drop constraint if exists "player_id_check";');
    this.addSql('alter table "player" alter column "id" type varchar(255) using ("id"::varchar(255));');
    this.addSql('alter table "player" add constraint "player_connection_id_unique" unique ("connection_id");');
    this.addSql('alter table "player" add constraint "player_pkey" primary key ("id");');
    this.addSql('alter table "player" drop column "name";');

    this.addSql('alter table "player" add constraint "player_connection_id_unique" unique ("connection_id");');
  }

}
exports.Migration20220113155133 = Migration20220113155133;
```

</details>

<details>
<summary>Latest entities</summary>

**BaseEntity.ts**
```ts
import { PrimaryKey, Property } from '@mikro-orm/core'

export default abstract class BaseEntity {
  @PrimaryKey()
  id!: string

  @Property()
  createdAt = new Date()

  @Property({ onUpdate: () => new Date() })
  updatedAt = new Date()
}
```

**Player.ts**
```ts
import { Entity, Property, Unique } from '@mikro-orm/core'
import BaseEntity from './BaseEntity'

@Entity()
export default class Player extends BaseEntity {
  @Property()
  @Unique()
  connectionId: string

  constructor(connectionId: string) {
    super()
    this.connectionId = connectionId
  }
}
```

</details>

<details>
<summary>DB schema</summary>
<img width="1035" alt="Screen Shot 2022-01-14 at 12 21 19 AM" src="https://user-images.githubusercontent.com/59438603/149368246-d90668ed-2861-48d5-8491-d3132d058479.png">

</details>

**Versions**

| Dependency | Version |
| - | - |
| node | v14.18.2 |
| typescript | v4.5.4 |
| mikro-orm | v4.5.10 |
| your-driver | @mikro-orm/postgresql |

**Comment by B4nan** [comment]
Schema diffing in v4 is quite broken, please try v5, if it fails the same way there, we can reopen this - but for that please provide complete reproduction. 

If you want to wait for stable release, only thing you can do is to manually fix the migrations. 

(it might be also something with the version of pg you are using, hard to say)

**Comment by suerta-git** [comment]
@B4nan You are right! After I change it the primary key issue disappears. 👍 
However the new migration is a little weird as there are 2 same queries.

```js
'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
const Migration = require('@mikro-orm/migrations').Migration;

class Migration20220113165927 extends Migration {

  async up() {
    this.addSql('alter table "player" add column "created_at" timestamptz(0) not null, add column "updated_at" timestamptz(0) not null, add column "connection_id" varchar(255) not null;');
    this.addSql('alter table "player" add constraint "player_connection_id_unique" unique ("connection_id");');
    this.addSql('alter table "player" drop column "name";');

    this.addSql('alter table "player" add constraint "player_connection_id_unique" unique ("connection_id");');  //  same as above
  }

}
exports.Migration20220113165927 = Migration20220113165927;
```

So that there is another error: 
```
TableExistsException: alter table "player" add constraint "player_connection_id_unique" unique ("connection_id"); - relation "player_connection_id_unique" already exists
    at PostgreSqlExceptionConverter.convertException (/Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:38:24)
    at PostgreSqlDriver.convertException (/Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:202:54)
    at /Users/jindong.zhang/Desktop/Code/PolygonGame/draw-guess-backend-node/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:206:24
...
```

**Comment by B4nan** [comment]
Yes, one of the things that are already fixed in v5 :]

**Comment by suerta-git** [comment]
Cool. I am happy to try v5 on my application and can I know the release plan of the stable version?

(But seems I have to hold on upgrading at this moment because I have dependency requires Node 12...)

**Comment by suerta-git** [comment]
@B4nan I met another issue in production environment.

There is one command like
<img width="895" alt="Screen Shot 2022-01-14 at 7 18 55 PM" src="https://user-images.githubusercontent.com/59438603/149507384-0ef88292-7043-45cf-b24c-03671dc334a1.png">

However setting this variable `session_replication_role` requires superuser privilege. But my postgres DB from cloud vender doesn't provide superuser privilege. 

Can I disable this behavior during migration?

**Comment by B4nan** [comment]
Yes you can, search the issues, there are many about this

**Comment by suerta-git** [comment]
Great! How about note it in document?
