### ISSUE TITLE
Invalid smart query resolution with FK as PK

### ISSUE THREAD

**Issue by ml1nk** [mikro-orm/mikro-orm#2648]
**Describe the bug**
If B is using FK as PK then
```typescript
const r = await orm.em.findOne(C, {  b: { a: { test: 'test' } } });
```
does resolve to B.test instead of A.test but typings are working like expected.

**Stack trace**
```
Trying to query by not existing property B.test

      27 |         // do not validate if the key is prefixed or type casted (e.g. `k::text`)
      28 |         if (validate && !this.prop && !k.includes('.') && !k.includes('::') && !Utils.isOperator(k) && !CriteriaNode.isCustomExpression(k)) {
    > 29 |           throw new Error(`Trying to query by not existing property ${entityName}.${k}`);
         |                 ^
      30 |         }
      31 |       });
      32 |     }

      at packages/knex/src/query/CriteriaNode.ts:29:17
          at Array.forEach (<anonymous>)
      at new CriteriaNode (packages/knex/src/query/CriteriaNode.ts:24:35)
      at new ScalarCriteriaNode (packages/knex/src/query/ScalarCriteriaNode.ts:8:1)
      at Function.createScalarNode (packages/knex/src/query/CriteriaNodeFactory.ts:30:18)
      at Function.createNode (packages/knex/src/query/CriteriaNodeFactory.ts:26:17)
      at Function.createObjectItemNode (packages/knex/src/query/CriteriaNodeFactory.ts:64:19)
      at packages/knex/src/query/CriteriaNodeFactory.ts:52:22
          at Array.reduce (<anonymous>)
      at Function.createObjectNode (packages/knex/src/query/CriteriaNodeFactory.ts:51:41)
```

**To Reproduce**
```typescript
@Entity()
export class A {

  @PrimaryKey()
  id!: number;

  @Property({ type: 'string' })
  test!: string;

}

@Entity()
export class B {

  [PrimaryKeyType]: number;
  [PrimaryKeyProp]: 'a';
  @ManyToOne({ entity: ()=>A, primary: true })
  a!: IdentifiedReference<A>;

}

@Entity()
export class C {

  @PrimaryKey({ type: Number })
  id!: number;

  @ManyToOne({ entity: ()=>B })
  b!: IdentifiedReference<B>;

}
```

```typescript
const r = await orm.em.findOne(C, {  b: { a: { test: 'test' } } });
expect(r).toBeNull();
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.3.2|
| typescript | 4.5 |
| mikro-orm |  5.0.0-dev.643 and 4.5.10 |
| postgresql | 14.1 |

**Comment by ml1nk** [comment]
OneToOne with primary leads to the same error. 

I analyzed the code and found out that "shouldAutoJoin" (ObjectCriteriaNode.ts) returns false, because primaryKeys is evaluated as true. I resolved it with:
~~~typescript

  private shouldAutoJoin(nestedAlias: string | undefined): boolean {
    if (!this.prop || !this.parent) {
      return false;
    }

    const embeddable = this.prop.reference === ReferenceType.EMBEDDED;
    const knownKey = [ReferenceType.SCALAR, ReferenceType.MANY_TO_ONE, ReferenceType.EMBEDDED].includes(this.prop.reference) || (this.prop.reference === ReferenceType.ONE_TO_ONE && this.prop.owner);
    const operatorKeys = knownKey && Object.keys(this.payload).every(key => Utils.isOperator(key, false));

    const primaryKeys = knownKey && Object.keys(this.payload).every(key => {
      const m = this.metadata.find(this.entityName)!;
      // if key is a primary key and not a fk to pk relation then return true
      return m.primaryKeys.includes(key) && (!m.compositePK || !((m.properties[key]!.reference === ReferenceType.ONE_TO_ONE && m.properties[key]!.owner) || m.properties[key]!.reference === ReferenceType.MANY_TO_ONE));
    });

    return !primaryKeys && !nestedAlias && !operatorKeys && !embeddable;
  }
~~~
but i'm unsure if it is the best solution.

**Comment by B4nan** [comment]
Your entity definition is wrong unless you are using ts-morph. Reference properties needs to be marked with `wrappedReference: true`.

```ts
  @ManyToOne({ entity: ()=>A, primary: true, wrappedReference: true })
  a!: IdentifiedReference<A>;
```

```ts
  @ManyToOne({ entity: ()=>B, wrappedReference: true })
  b!: IdentifiedReference<B>;
```

(not sure if that itself will help)

> but i'm unsure if it is a valid solution.

Apply the change to the ORM codebase and run its tests to verify that.

**Comment by ml1nk** [comment]
In addition if there is only one primary key like in my example, it changes
{  b: { a: { test: 'test' } } }
to
{  b: { test: 'test' } }
in
QueryHelper.ts
static inlinePrimaryKeyObjects(where, meta, metadata, key)

My current solution adds  
~~~typescript
&& !meta.props.some(e => (e.primary && (e.reference === ReferenceType.ONE_TO_ONE && e.owner) || e.reference === ReferenceType.MANY_TO_ONE))
~~~

~~~typescript
  static inlinePrimaryKeyObjects<T extends AnyEntity<T>>(where: Dictionary, meta: EntityMetadata<T>, metadata: MetadataStorage, key?: string): boolean {
    if (Array.isArray(where)) {
      where.forEach((item, i) => {
        if (this.inlinePrimaryKeyObjects(item, meta, metadata, key)) {
          where[i] = Utils.getPrimaryKeyValues(item, meta.primaryKeys, false);
        }
      });
    }

    if (!Utils.isPlainObject(where)) {
      return false;
    }


    if (meta.primaryKeys.every(pk => pk in where) && Utils.getObjectKeysSize(where) === meta.primaryKeys.length && !meta.props.some(e => (e.primary && (e.reference === ReferenceType.ONE_TO_ONE && e.owner) || e.reference === ReferenceType.MANY_TO_ONE))) {
      return !GroupOperator[key as string] && Object.keys(where).every(k => !Utils.isPlainObject(where[k]) || Object.keys(where[k]).every(v => !Utils.isOperator(v, false)));
    }

    Object.keys(where).forEach(k => {
      const meta2 = metadata.find(meta.properties[k]?.type) || meta;

      if (this.inlinePrimaryKeyObjects(where[k], meta2, metadata, k)) {
        where[k] = Utils.getPrimaryKeyValues(where[k], meta2.primaryKeys, true);
      }
    });

    return false;
  }
~~~

> Apply the change to the ORM codebase and run its tests to verify that.
i'm on it
