### ISSUE TITLE
CLI does not allow specifying TS config file

### ISSUE THREAD

**Issue by epechuzal** [mikro-orm/mikro-orm#2741]
**Describe the bug**
I want to run mikro-orm CLI and I want to specify path to config file via the `MIKRO_ORM_CLI` env var. 

The docs suggest that mikro-orm supports specifying a `mikro-orm.config.ts` file of my own in this var.

However it looks like the env var is only taken into consideration if the file ends in `js`.

**Stack trace**
```
ubuntu@my-machine:~/my-repo$ MIKRO_ORM_CLI=./libs/my-db/src/mikro-orm.config.ts npx mikro-orm schema:create -d
mikro-orm schema:create

Create database schema based on current metadata

Options:
  -r, --run      Runs queries                                          [boolean]
  -d, --dump     Dumps all queries to console                          [boolean]
  --fk-checks    Do not skip foreign key checks                        [boolean]
  --schema       Set the current schema for wildcard schema entities    [string]
  --seed         Allows to seed the database on create or drop and recreate
                                                                        [string]
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]

Error: MikroORM config file not found in ['./mikro-orm.config.js']
    at Function.getConfiguration (/home/ubuntu/publisher-platform/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:58:15)
    at async Function.getORM (/home/ubuntu/publisher-platform/node_modules/@mikro-orm/cli/CLIHelper.js:22:25)
    at async Function.handleSchemaCommand (/home/ubuntu/publisher-platform/node_modules/@mikro-orm/cli/commands/SchemaCommandFactory.js:72:21)
```

**To Reproduce**
1. Set the `MIKRO_ORM_CLI` env var to anything which does not end in `*.js`
2. CLI will ignore it

**Expected behavior**
CLI should allow me to specify any TS file.

I guess the only issue I can think of is that the CLI might not know which tsconfig.json to use but I guess that could be an arg or an env var as well (if it is not the default tsconfig.json in repo root)

**Additional context**
This is specifically because our repo is a typescript monorepo with multiple apps/libs inside of it (and there is more than one DB so there is more than one mikro-orm.config.ts file)

**Versions**

| Dependency | Version |
| - | - |
| node | 16 |
| typescript | 4.3.5 |
| mikro-orm | 5 |

**Comment by B4nan** [comment]
You need to have TS support enabled, either in package.json via `useTsNode` or via env var `MIKRO_ORM_CLI_USE_TS_NODE`. I guess it makes sense to do this automatically if you explicitly privide TS file via env var.

You can also use `tsConfigPath` in package.json or `MIKRO_ORM_CLI_TS_CONFIG_PATH` env var for specifying path to tsconfig.json.

**Comment by galliroberto** [comment]
> You need to have TS support enabled, either in package.json via `useTsNode` or via env var `MIKRO_ORM_CLI_USE_TS_NODE`. I guess it makes sense to do this automatically if you explicitly privide TS file via env var.
> 
> You can also use `tsConfigPath` in package.json or `MIKRO_ORM_CLI_TS_CONFIG_PATH` env var for specifying path to tsconfig.json.

Sorry man, what is the right conf inside tsconfig.json.
I tried many, without success
