### ISSUE TITLE
Invalid query generation if smart join with $and/$or used together with same table join in orderBy

### ISSUE THREAD

**Issue by vimmerru** [mikro-orm/mikro-orm#277]
**Describe the bug**
The following query will fail

```
const reports = await em.findAndCount<Report>(
        Report,
        {
            $or: [
                { organization: { domain: 'test' } },
                { product: { code: 'RR' } }
            ],
        },
        {
            orderBy: { organization: { name: "ASC" } },
        },
    );
```

**Stack trace**
```
[query] select `e0`.* from `report` as `e0` left join `organization` as `e3` on `e0`.`organization_id` = `e3`.`id` left join `product` as `e2` on `e0`.`product_id` = `e2`.`id` where (`e1`.`domain` = 'test' or `e2`.`code` = 'RR') order by `e3`.`name` asc [took 14 ms]
{ Error: Unknown column 'e1.domain' in 'where clause'
    at Packet.asError (/home/alexandermartynov/Рабочий стол/mikro-orm-test-1/mikro-orm-test/node_modules/mysql2/lib/packets/packet.js:708:17)
    at Query.execute (/home/alexandermartynov/Рабочий стол/mikro-orm-test-1/mikro-orm-test/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/home/alexandermartynov/Рабочий стол/mikro-orm-test-1/mikro-orm-test/node_modules/mysql2/lib/connection.js:408:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/home/alexandermartynov/Рабочий стол/mikro-orm-test-1/mikro-orm-test/node_modules/mysql2/lib/connection.js:70:12)
    at PacketParser.executeStart (/home/alexandermartynov/Рабочий стол/mikro-orm-test-1/mikro-orm-test/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/home/alexandermartynov/Рабочий стол/mikro-orm-test-1/mikro-orm-test/node_modules/mysql2/lib/connection.js:77:25)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: 'Unknown column \'e1.domain\' in \'where clause\'' }
```

**To Reproduce**
Check attached sample project

**Additional context**
Most probably it is related to incorrect joined table name counter if table present multiple times because of smart join, sorting and deep population

**Versions**

3.0.0-rc.4

**Comment by vimmerru** [comment]
[mikro-orm-test.zip](https://github.com/mikro-orm/mikro-orm/files/3973450/mikro-orm-test.zip)

**Comment by B4nan** [comment]
Will be part of next RC.

**Comment by jayeshanandani** [comment]
This is broken again in latest version. It doesnt work anymore.

**Comment by B4nan** [comment]
Nope, it is not broken again. The fix had a test case for regressions, and it is still passing. If you face similar issue, please file proper report with steps to reproduce (ideally including reproduction repository), as well as all the requested information in the issue template.
