### ISSUE TITLE
Persist problem when using foreign key as primary key

### ISSUE THREAD

**Issue by goeddek** [mikro-orm/mikro-orm#2810]
**Describe the bug**
We want to persist an Entity with a foreign key dependency to another Entity as Primary Key and and a One-To-Many relationship to a dependent Entity in one step. But instead of a successful creation, we are getting the following **Stack trace**:

```
NotNullConstraintViolationException: insert into "test_entity3" ("element_node_id") values (NULL) returning "id" - null value in column "element_node_id" violates not-null constraint
      at PostgreSqlExceptionConverter.convertException (/home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+postgresql@5.0.3_5b0430c21e6926769015aebacb3a1798/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:24:24)
      at PostgreSqlDriver.convertException (/home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+core@5.0.3_e709e71806bad5ba9f7df9c02a1ac6cf/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:180:54)
      at /home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+core@5.0.3_e709e71806bad5ba9f7df9c02a1ac6cf/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:184:24
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at PostgreSqlDriver.nativeInsert (/home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+knex@5.0.3_ea16011242c57dba9f8a23060ccfa251/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:157:21)
      at ChangeSetPersister.persistNewEntity (/home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+core@5.0.3_e709e71806bad5ba9f7df9c02a1ac6cf/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:85:21)
      at ChangeSetPersister.executeInserts (/home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+core@5.0.3_e709e71806bad5ba9f7df9c02a1ac6cf/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:29:13)
      at ChangeSetPersister.runForEachSchema (/home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+core@5.0.3_e709e71806bad5ba9f7df9c02a1ac6cf/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:68:13)
      at UnitOfWork.commitCreateChangeSets (/home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+core@5.0.3_e709e71806bad5ba9f7df9c02a1ac6cf/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:641:9)
      at UnitOfWork.persistToDatabase (/home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+core@5.0.3_e709e71806bad5ba9f7df9c02a1ac6cf/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:593:13)
      at PostgreSqlConnection.transactional (/home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+knex@5.0.3_ea16011242c57dba9f8a23060ccfa251/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:36:25)
      at UnitOfWork.doCommit (/home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+core@5.0.3_e709e71806bad5ba9f7df9c02a1ac6cf/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:254:17)
      at UnitOfWork.commit (/home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+core@5.0.3_e709e71806bad5ba9f7df9c02a1ac6cf/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:234:9)
      at SqlEntityManager.flush (/home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+core@5.0.3_e709e71806bad5ba9f7df9c02a1ac6cf/node_modules/@mikro-orm/core/EntityManager.js:572:9)
      at SqlEntityManager.persistAndFlush (/home/kgoedde/workspace/pgh/node_modules/.pnpm/@mikro-orm+core@5.0.3_e709e71806bad5ba9f7df9c02a1ac6cf/node_modules/@mikro-orm/core/EntityManager.js:518:9)
      at Context.<anonymous> (/home/kgoedde/workspace/pgh/test/tests/foreign.ts:26:5)
```
**To reproduce** the situation I build a simplified example:

~~~typescript
@Entity({ abstract: true })
export abstract class NodeExtendBase {
  [PrimaryKeyType]: number
  [PrimaryKeyProp]: 'node'
  @OneToOne({ primary: true, onDelete: 'cascade', onUpdateIntegrity: 'cascade' })
  node!: IdentifiedReference<NodeEntity>

  nodeId (): number { return this.node.id! }
}

@Entity({ tableName: 'test_entity1' })
export class NodeEntity {
  static factory (parent: NodeEntity | null): NodeEntity {
    const node = new NodeEntity()
    node.parent = parent === null ? null : orm.em.getReference(NodeEntity, parent.id, { wrapped: true })
    return node
  }

  @PrimaryKey()
  id!: number

  @ManyToOne({ onDelete: 'cascade', onUpdateIntegrity: 'cascade' })
  parent!: IdentifiedReference<NodeEntity> | null
}

@Entity({ tableName: 'test_entity2' })
export class ElementEntity extends NodeExtendBase {
  @OneToMany({ entity: () => DependentEntity, mappedBy: 'element', cascade: [Cascade.ALL] })
  dependents = new Collection<DependentEntity>(this)
}

@Entity({ tableName: 'test_entity3' })
export class DependentEntity {
  @PrimaryKey()
  id!: number

  @ManyToOne(() => ElementEntity, { onDelete: 'cascade' })
  element!: IdentifiedReference<ElementEntity>
}
~~~
And here are my test cases:
~~~typescript
const expect = chai.expect
chai.use(asPromised)

describe('pgh - Test for mikro orm', () => {
  beforeEach('initialize test environment', async () => {
    await reset()
  })
  it('pgh/create without existing parent', async () => {
    const element = new ElementEntity()
    element.node = Reference.create(NodeEntity.factory(null))

    const dependent = new DependentEntity()
    dependent.element = Reference.create(element)

    element.dependents.add(dependent)

    await expect(orm.em.persistAndFlush(element)).to.not.be.rejectedWith(NotNullConstraintViolationException)
  })
  it('pgh/create with existing parent', async () => {
    const parent = orm.em.create(NodeEntity, { })
    await orm.em.persistAndFlush(parent)

    const element = new ElementEntity()
    element.node = Reference.create(NodeEntity.factory(parent))

    const dependent = new DependentEntity()
    dependent.element = Reference.create(element)

    element.dependents.add(dependent)

    await expect(orm.em.persistAndFlush(element)).to.not.be.rejectedWith(NotNullConstraintViolationException)
  })
})
~~~
**Versions**

| Dependency | Version |
| - | - |
| node | 16.14 |
| typescript | 4.5.5 |
| mikro-orm | 5.0.3 |
| your-driver | PostgreSQL |

P.S: Having spend much of my working life with Entity Framework (standard and core) I have to say MicroORM is really awsome and easy to use.

**Comment by B4nan** [comment]
Can you try latest dev version? Sounds similar to another problem that got resolved a day ago or so. Also are you using ts-morph? (if not, you are missing some details in the entity definition, like `wrappedReference: true`)

**Comment by goeddek** [comment]
I tried the newest version ```5.0.4-dev.4```, but still got the same error

We are using ts-morph. the orm comes from:
~~~typescript
import { MikroORM } from '@mikro-orm/core'
import { PostgreSqlDriver } from '@mikro-orm/postgresql'

export let orm: MikroORM<PostgreSqlDriver>
~~~

**Comment by B4nan** [comment]
> We are using ts-morph. the orm comes from:

I was asking where does the instance come from, not property definition. You need to await the `init` call to have it.

But it does not really matter, just asking as it is weird, and will work correctly _only_ with `RequestContext` helper. Otherwise you will be working with global identity map (which will throw in v5) or with a _wrong_ identity map (e.g. if you create new forks inside forks).

**Comment by goeddek** [comment]
full init:
~~~typescript
let orm: MikroORM<PostgreSqlDriver> | null = null
  orm = await MikroORM.init({
    context: () => {
      const store = Context.getStore()
      if (store === undefined || orm === null) return undefined
      return store.getOrSet(contextEmKey, EntityManager, () => orm!.em.fork())
    },
    type: 'postgresql',
    cache: {
      adapter: Adapter
    },
    dbName: (config.env === 'test') ? dbC.database + '-' + Date.now().toString() : dbC.database,
    user: dbC.username,
    debug: dbC.debug,
    password: dbC.password,
    host: dbC.host,
    port: dbC.port,
    entities: entities,
    driverOptions: dbC.driver,
    allowGlobalContext: dbC.allowGlobalContext,
    baseDir: dbC.baseDir,
    metadataProvider: Object.keys(dataTemp).length > 0 ? (await import('../classes/Metadata')).Metadata : (await import('@mikro-orm/reflection')).TsMorphMetadataProvider,
    migrations: {
      snapshot: dbC.snapshot,
      path: dbC.path,
      pathTs: dbC.pathTs,
      disableForeignKeys: false,
      migrationsList: migrations
    },
    pool: {
      min: 0,
      max: 20
    }
  })
~~~

**Comment by B4nan** [comment]
Btw `Context.getStore()` is what? v5 already uses async local storage by default, you shouldn't need special context handling if that was the reason.

Anyway, it does not really matter, here is a simplified failing test case, I can reproduce even without the reference wrappers. I can see the queries are fired in correct order, so this might be just about propagating the new PK value down to the FK as PK. 

```ts
import { Cascade, Collection, Entity, ManyToOne, MikroORM, OneToMany, OneToOne, PrimaryKey, PrimaryKeyProp, PrimaryKeyType } from '@mikro-orm/core';

@Entity({ abstract: true })
export abstract class NodeExtendBase {

  [PrimaryKeyType]: number;
  [PrimaryKeyProp]: 'node';

  // eslint-disable-next-line @typescript-eslint/no-use-before-define
  @OneToOne({ entity: () => NodeEntity, primary: true, onDelete: 'cascade', onUpdateIntegrity: 'cascade' })
  node!: any;

}

@Entity()
export class NodeEntity {

  @PrimaryKey()
  id!: number;

  @ManyToOne({ entity: () => NodeEntity, onDelete: 'cascade', onUpdateIntegrity: 'cascade', nullable: true })
  parent?: NodeEntity | null;

}

@Entity()
export class ElementEntity extends NodeExtendBase {

  // eslint-disable-next-line @typescript-eslint/no-use-before-define
  @OneToMany({ entity: () => DependentEntity, mappedBy: 'element', cascade: [Cascade.ALL] })
  dependents = new Collection<DependentEntity>(this);

}

@Entity()
export class DependentEntity {

  @PrimaryKey()
  id!: number;

  @ManyToOne(() => ElementEntity, { onDelete: 'cascade' })
  element!: ElementEntity;

}

describe('GH issue 2810', () => {

  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [ElementEntity, DependentEntity, NodeEntity, NodeExtendBase],
      dbName: ':memory:',
      type: 'sqlite',
      debug: true,
    });
    await orm.getSchemaGenerator().createSchema();
  });

  beforeEach(async () => await orm.getSchemaGenerator().clearDatabase());
  afterAll(async () => await orm.close(true));

  test('create without existing parent', async () => {
    const element = new ElementEntity();
    element.node = new NodeEntity();
    element.node.parent = null;

    const dependent = new DependentEntity();
    dependent.element = element;
    element.dependents.add(dependent);

    await orm.em.persistAndFlush(element);
  });

  test('create with existing parent', async () => {
    const parent = orm.em.create(NodeEntity, {});
    await orm.em.fork().persistAndFlush(parent);

    const element = new ElementEntity();
    element.node = new NodeEntity();
    element.node.parent = orm.em.getReference(NodeEntity, parent.id);

    const dependent = new DependentEntity();
    dependent.element = element;
    element.dependents.add(dependent);

    await orm.em.persistAndFlush(element);
  });

});
```

**Comment by goeddek** [comment]
> Btw `Context.getStore()` is what? v5 already uses async local storage by default, you shouldn't need special context handling if that was the reason.

Sorry bad copy and paste... we have our own local storage object for different things, It makes no difference here and I should have just erased the line.

**Comment by B4nan** [comment]
No worries, just wanted to point out this is not needed in v5, but if you push there your own stuff, it totally make sense.
