### ISSUE TITLE
Schema generator doesnt work when an entity references another entity with a composite primary key

### ISSUE THREAD

**Issue by mpp94** [mikro-orm/mikro-orm#2842]
**Describe the bug**
I have basically 2 entities, **UserAction** and **Step**. A user action has many steps (_OneToMany_) and a step has only one action (_ManyToOne_). 

When userAction only has **one** primary key, MikroORM successfully identifiyes the entity and creates the column accordingly. 

The problem comes when I add a second primary key to the UserAction entity. I added a second PrimaryKey called _versionName_ and modified the PrimaryKeyType map. 

![image](https://user-images.githubusercontent.com/86189277/156364327-0c234288-f995-4c16-b0bf-154758624728.png)
![image](https://user-images.githubusercontent.com/86189277/156363506-a87778ee-4d2f-4760-929e-c315ff3aec43.png)
**Stack trace**
```
Error: You did not specify a column name for the specifictype column.
    at ColumnCompiler_MySQL.columnName (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/knex/lib/schema/columncompiler.js:37:13)
    at ColumnCompiler_MySQL.ColumnCompiler.defaults (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/knex/lib/schema/columncompiler.js:47:46)
    at ColumnCompiler_MySQL.ColumnCompiler.getColumnName (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/knex/lib/schema/columncompiler.js:78:24)
    at ColumnCompiler_MySQL.ColumnCompiler.compileColumn (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/knex/lib/schema/columncompiler.js:68:30)
    at ColumnCompiler_MySQL.ColumnCompiler.toSQL (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/knex/lib/schema/columncompiler.js:58:23)
    at /home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/knex/lib/schema/tablecompiler.js:49:51
    at Array.map (<anonymous>)
    at TableCompiler_MySQL.TableCompiler.create (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/knex/lib/schema/tablecompiler.js:49:34)
    at TableCompiler_MySQL.TableCompiler.toSQL (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/knex/lib/schema/tablecompiler.js:34:20)
    at TableBuilder.toSQL (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/knex/lib/schema/tablebuilder.js:44:42)
    at SchemaCompiler_MySQL.createTable (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/knex/lib/schema/compiler.js:89:25)
    at SchemaCompiler_MySQL.toSQL (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/knex/lib/schema/compiler.js:72:26)
    at SchemaBuilder.toSQL (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/knex/lib/schema/builder.js:79:43)
    at SchemaBuilder.Target.toQuery (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/knex/lib/interface.js:8:21)
    at SchemaGenerator.dump (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:488:29)
    at SchemaGenerator.getCreateSchemaSQL (/home/miguel/masmovil/app_operaciones/repo/be-network-operations/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:43:25)
...
```

**To Reproduce**
1. ... Create an **entity A** with 2 primary keys
2. ... Create another **entity B* with a primary key and a reference to *entity A*
3. ... Run the schema generator.

**Expected behavior**
An entity property should be able to reference another entity that has a composite primary key.

**Additional context**
I am using NestJS, but i doubt there lies the problem.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.17.5 |
| typescript | 4.4.4 |
| mikro-orm | 4.5.9 |
| @mikro-orm/mariadb | 4.5.9 |

**Comment by B4nan** [comment]
Upgrade to v5, schema diffing is completely rewritten. Will be happy to reopen if you can reproduce with v5.
