### ISSUE TITLE
Utils.getObjectKeysSize doesn't work with null prototype objects

### ISSUE THREAD

**Issue by johnnyomair** [mikro-orm/mikro-orm#2846]
**Describe the bug**
When passing a JS object with a null prototype (`[Object: null prototype] { <key>: <value> }`), for instance an argument from a GraphQL query, to the `andWhere()` method of the QueryBuilder, the error `TypeError: object.hasOwnProperty is not a function` arises.

**Stack trace**
```
TypeError: object.hasOwnProperty is not a function
    at Function.getObjectKeysSize (<project-root>/node_modules/@mikro-orm/core/utils/Utils.js:163:24)
    at Function.inlinePrimaryKeyObjects (<project-root>/node_modules/@mikro-orm/core/utils/QueryHelper.js:47:72)
    at <project-root>/node_modules/@mikro-orm/core/utils/QueryHelper.js:60:22
    at Array.forEach (<anonymous>)
    at Function.inlinePrimaryKeyObjects (<project-root>/node_modules/@mikro-orm/core/utils/QueryHelper.js:58:28)
    at Function.processWhere (<project-root>/node_modules/@mikro-orm/core/utils/QueryHelper.js:70:25)
    at QueryBuilder.where (<project-root>/node_modules/@mikro-orm/postgresql/node_modules/@mikro-orm/knex/query/QueryBuilder.js:136:39)
    at QueryBuilder.andWhere (<project-root>/node_modules/@mikro-orm/postgresql/node_modules/@mikro-orm/knex/query/QueryBuilder.js:163:21)
```

**To Reproduce**
1. Create a null prototype object: `const test = { key: "value", __proto__: null }`
2. Pass that object to the QueryBuilder's andWhere method: `qb.andWhere({ test: test })`

**Expected behavior**
The Utils.getObjectKeysSize works correctly with null prototype objects

**Additional context**
I've found that Utils.getObjectKeysSize calls `object.hasOwnProperty` directly, instead of using `Object.prototype.hasOwnProperty.call`: https://github.com/mikro-orm/mikro-orm/blob/ffe6bd886ddc0c97bbfde600c3bec26570f3ca33/packages/core/src/utils/Utils.ts#L176

**Versions**

| Dependency | Version |
| - | - |
| node | 14.19.0 |
| typescript | 4.5.2 |
| mikro-orm | 5.0.5 |
| postgres |  5.0.5 |

**Comment by johnnyomair** [comment]
> PR welcome if you think its just about that.

Created a PR with that change. I've also added two failing tests beforehand to verify the fix.

> Note that we need to distinquish what is POJO and what is a class instance, so that is why we have all this extra handling. There is this hack to allow using custom classes in where conditions: https://mikro-orm.io/docs/entity-manager#using-custom-classes-in-filterquery

Thanks for the info! I believe that this distinction doesn't apply in this case, as the GraphQL objects are POJOs. 

> Note that you should say what exact version you use, not a version range. In other words `^5.0.0` is a wrong input for the version part of issue template as it tells me nothing about what version you actually use.

You're absolutely right! My bad, I've updated the description.
