### ISSUE TITLE
SyntaxError: Unexpected token '?', @mikro-orm/core/typings.js:51

### ISSUE THREAD

**Issue by jarblz** [mikro-orm/mikro-orm#2885]
**Describe the bug**
Apologies in advance if this is user error, I'm pretty new to JS in general.  Upon starting a nestjs server, I receive the following error

**Stack trace**
```
nestjs_api_dev            | Debugger listening on ws://127.0.0.1:9229/7e95b841-d494-4fa9-8aa4-9cf4317d3acb
nestjs_api_dev            | For help, see: https://nodejs.org/en/docs/inspector
nestjs_api_dev            | /usr/src/app/node_modules/@mikro-orm/core/typings.js:51
nestjs_api_dev            |         this.root ?? (this.root = this);
nestjs_api_dev            |                    ^
nestjs_api_dev            |
nestjs_api_dev            | SyntaxError: Unexpected token '?'
nestjs_api_dev            |     at wrapSafe (internal/modules/cjs/loader.js:931:16)
nestjs_api_dev            |     at Module._compile (internal/modules/cjs/loader.js:979:27)
nestjs_api_dev            |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
nestjs_api_dev            |     at Module.load (internal/modules/cjs/loader.js:879:32)
nestjs_api_dev            |     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
nestjs_api_dev            |     at Module.require (internal/modules/cjs/loader.js:903:19)
nestjs_api_dev            |     at require (internal/modules/cjs/helpers.js:74:18)
nestjs_api_dev            |     at Object.<anonymous> (/usr/src/app/node_modules/@mikro-orm/core/index.js:19:17)
nestjs_api_dev            |     at Module._compile (internal/modules/cjs/loader.js:1015:30)
nestjs_api_dev            |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
```

**To Reproduce**
add mikro-orm to your app based on the official nestJS user guide from the website, start the server with `npm run start`

**Expected behavior**
An exception wouldn't be raised, ideally.

**Versions**
from package.json: 

```
{
  "name": "nestjs-docker",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  },
  "dependencies": {
    "@mikro-orm/core": "^5.0.5",
    "@mikro-orm/nestjs": "^5.0.0",
    "@mikro-orm/postgresql": "^5.0.5",
    "@mikro-orm/reflection": "^5.0.5",
    "@mikro-orm/sql-highlighter": "^1.0.1",
    "@nestjs/common": "^8.0.0",
    "@nestjs/config": "^1.2.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^8.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.4.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.4.1",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-morph": "^14.0.0",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.(t|j)s$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  },
  "mikro-orm": {
    "useTsNode": true,
    "configPaths": [
      "./src/mikro-orm.config.ts",
      "./dist/mikro-orm.config.js"
    ]
  }
}

```

**Comment by B4nan** [comment]
Node 14+ is required, your current version does not understand the `??` language construct.

**Comment by jarblz** [comment]
> Node 14+ is required, your current version does not understand the `??` language construct.

Ah I was getting confused because I had the most updated version on my machine but my docker image was old.  Thanks so much for the quick reply!
