### ISSUE TITLE
updateSchema() throws TypeError when encountering compound foreign keys on SQLite

### ISSUE THREAD

**Issue by ghakko** [mikro-orm/mikro-orm#2959]
With the following schema:
```
@Entity() class Foo {
  @OneToMany(() => Bar, bar => bar.foo) bars = new Collection<Bar>(this);
  @PrimaryKey() id!: number;
  @PrimaryKey() something?: number;
}

@Entity() class Bar {
  @ManyToOne() foo!: Foo;
  @PrimaryKey() id!: number;
}
```
Running updateSchema() on the above in SQLite will correctly create the two tables. But running it a second time then causes a TypeError:
```
/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:204
  return ast.columns.map((column) => identifier(column, wrap)).join(', ');
                     ^
TypeError: ast.columns.map is not a function
    at columnNameList (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:204:22)
    at columnNameListOptional (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:200:40)
    at foreignKeyClause (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:193:43)
    at foreignTableConstraint (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:189:9)
    at tableConstraint (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:156:14)
    at /tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:142:29
    at Array.reduce (<anonymous>)
    at tableConstraintList (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:140:26)
    at createTable (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:16:7)
    at compileCreateTable (/tmp/crashme/node_modules/knex/lib/dialects/sqlite3/schema/internal/compiler.js:2:10)
```
This does not happen with MariaDB.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.14.2 |
| typescript | 4.6.3 |
| @mikro-orm | 5.1.1 |
| @mikro-orm/sqlite | 5.1.1 |

**Comment by B4nan** [comment]
That is a knex issue, can't help with that, please report it to them, together with the SQL that causes it (you can use `getCreateSchemaSQL()` to get it). This issue is about their custom sqlite reflection of existing schemas.

cc @kibertoad

**Comment by ghakko** [comment]
The Knex people have replied, and said [it’s really a Mikro-ORM issue](https://github.com/knex/knex/issues/5092#issuecomment-1103907059).
