### ISSUE TITLE
Fails to execute query without getKnexQuery()

### ISSUE THREAD

**Issue by josepotal** [mikro-orm/mikro-orm#2967]
**Describe the bug**
It needs a `getKnexQuery()` or `getFormattedQuery()`, to execute without errors.

`book table` has a columns `id` and `author_id`, author_id is the id of the author table
`author table` has columns `id` and others
```
Author Entity

@Entity({
  tableName: "author",
})
export class Author {
  @PrimaryKey({ type: UnsafeInt8 })
  id: number | null;

  @OneToMany(() => Book, (book) => book.author, {
    orderBy: { id: QueryOrder.ASC },
  })
  book = new Collection<Book>(this);

  constructor({ id }: { id?: number | null }) {
    this.id = id ?? null;
  }
}

Book Entity

@Entity({
  tableName: "book",
})
export class Book {
  @PrimaryKey({ type: UnsafeInt8 })
  id: number | null;

  @ManyToOne({
    entity: () => Author,
  })
  author: Author;

  constructor({ id, author }: { id?: number | null; author: Author }) {
    this.id = id ?? null;
    this.author = author;
  }
}
```

Executing query that throws error
```
const authorQB = em.createQueryBuilder(Author, "author");

authorQB.select(["author.id"]);
authorQB.leftJoin("author.book", "book");
authorQB.limit(10).offset(0);

await authorQB.execute();
```

Executing query that works fine **(adding authorQB.getKnexQuery())**
```
const authorQB = em.createQueryBuilder(Author, "author");

authorQB.getKnexQuery();  

authorQB.select(["author.id"]);
authorQB.leftJoin("author.book", "book");
authorQB.limit(10).offset(0);

await authorQB.execute();
```

**Stack trace**
Error thrown when no adding authorQB.getKnexQuery();

```
select "author"."id" from "public"."author" as "author" left join "public"."book" as "book" on "author"."id" = "book"."author_id" where "author"."id" in 'select "author"."id" from (select "author"."id" from "public"."author" as "author" left join "public"."book" as "book" on "author"."id" = "book"."author_id" group by "author"."id" limit 10) as "author"' - syntax error at or near "'select "author"."id" from (select "author"."id" from "public"."author" as "author" left join "public"."book" as "book" on "author"."id" = "book"."author_id" group by "author"."id" limit 10) as "author"'"
```

```
error: select "author"."id" from "public"."author" as "author" left join "public"."book" as "book" on "author"."id" = "book"."author_id" where "author"."id" in 'select "author"."id" from (select "author"."id" from "public"."author" as "author" left join "public"."book" as "book" on "author"."id" = "book"."author_id" group by "author"."id" limit 10) as "author"' - syntax error at or near "'select "author"."id" from (select "author"."id" from "public"."author" as "author" left join "public"."book" as "book" on "author"."id" = "book"."author_id" group by "author"."id" limit 10) as "author"'"
    at Parser.parseErrorMessage (.../node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (.../node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (.../node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (.../node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 293,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '154',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1134',
  routine: 'scanner_yyerror'
}

```

**Expected behavior**
Work without  `getKnexQuery()` or `getFormattedQuery()`.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.14.0 |
| typescript | 4.6.2 |
| mikro-orm | 5.1 |
| postgresql | |

**Comment by B4nan** [comment]
This is not reproducible on my end, please provide minimal executable reproduction, ideally as a test case. You can see how issue tests may look like in https://github.com/mikro-orm/mikro-orm/tree/master/tests/issues.

**Comment by B4nan** [comment]
Closing as there is no failing reproduction, will be happy to reopen if you can provide one.
