### ISSUE TITLE
CLI command "fresh" fails to execute when disableForeignKeys is set to false

### ISSUE THREAD

**Issue by luksiv** [mikro-orm/mikro-orm#3004]
### Description
When trying to execute the command `npx mikro-orm migration:fresh` it fails and throws an error.
### Stack trace
```
DriverException: set session_replication_role = 'replica'; - permission denied to set parameter "session_replication_role"
    at PostgreSqlExceptionConverter.convertException (my-project/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException (my-project/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:42:22)
    at PostgreSqlDriver.convertException (my-project/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:173:54)
    at my-project/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:177:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SchemaGenerator.execute (my-project/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:350:13)
    at async SchemaGenerator.dropSchema (my-project/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:77:9)
    at async Function.handleFreshCommand (my-project/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:164:9)
    at async Function.handleMigrationCommand (my-project/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:110:17)
```
### Configuration
```
const config: Options = {
  ...,
  migrations: {
    ...,
    disableForeignKeys: false,
  },
  schemaGenerator: {
    disableForeignKeys: false,
  },
  ...
};
```
### To reproduce
Execute command `npx mikro-orm migration:fresh` with any schema using PostgreSQL and setting `schemaGenerator.disableForeignKeys = true` and/or `migrations.disableForeignKeys = true`.
### Additional context
PostgreSQL
### Versions

| Dependancy | Version |
| --- | --- |
| node | 16.10.0 |
| typescript | 4.3.5 |
| mikro-orm | 5.1.2 |
| your-driver | pg |

**Comment by vincentwinkel** [comment]
I also have this issue on Heroku (works well on local).

Dependancy | Version
-- | --
node | 14.18.1
typescript | 4.3.5
mikro-orm | 5.3.1
your-driver | pg

```
> ./node_modules/.bin/mikro-orm "schema:fresh" "-r" "--seed" "FakeSeeder"

mikro-orm schema:fresh

Drop and recreate database schema based on current metadata

Options:
  -r, --run      Runs queries                                          [boolean]
  --schema       Set the current schema for wildcard schema entities    [string]
  --seed         Allows to seed the database on create or drop and recreate
                                                                        [string]
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]

DriverException: set session_replication_role = 'replica'; - permission denied to set parameter "session_replication_role"
```
