### ISSUE TITLE
JIT runtime error in custom repository

### ISSUE THREAD

**Issue by ArtemGolovko** [mikro-orm/mikro-orm#3081]
**Describe the bug**
JIT runtime error.
Error appered in select query builder. It looks like that:
```ts
this.createQueryBuilder('comment')
            .select([
                'comment.*',
                'likes.username as likesUsername',
                'count(likes.username) as likesCount'
            ])
            .leftJoinAndSelect('comment.post', 'post')
            .leftJoinAndSelect('comment.author', 'author')
            .leftJoin('comment.likes', 'likes')
            .groupBy('comment.id')
            .where(
                { post: { id: postId } }
            )
            .getResultList()
```

**Stack trace**
```
at compareArrays (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\utils\Utils.js:76:22)
    at eval (eval at createFunction (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\utils\Utils.js:709:20), <anonymous>:43:15)
    at Function.callCompiledFunction (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\utils\Utils.js:720:20)
    at EntityComparator.diffEntities (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\utils\EntityComparator.js:24:30)
    at EntityFactory.mergeData (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\entity\EntityFactory.js:66:39)
    at EntityFactory.create (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\entity\EntityFactory.js:33:18)
    at eval (eval at createFunction (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\utils\Utils.js:709:20), <anonymous>:42:29)
    at Function.callCompiledFunction (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\utils\Utils.js:720:20)
    at ObjectHydrator.hydrate (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\hydration\ObjectHydrator.js:24:23)
    at EntityFactory.hydrate (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\entity\EntityFactory.js:158:27)
```

**To Reproduce**
1. Create those entities
*User*
```ts
@Entity({ customRepository: () => UserRepository })
export default class User {
    [EntityRepositoryType]?: UserRepository

    @PrimaryKey({ type: types.string, autoincrement: false })
    username!: string

    @Property({ type: types.string })
    name!: string

    @Property({ type: types.string })
    avatar!: string

    @Property({ type: types.string })
    profileBanner!: string

    @Property({ type: types.boolean, default: false })
    isPrivate!: boolean

    @ManyToMany(() => User, 'subscribed', { owner: true })
    subscribers = new Collection<User>(this);

    @ManyToMany(() => User, user => user.subscribers)
    subscribed = new Collection<User>(this);

    @OneToMany(() => Post, post => post.author)
    posts = new Collection<Post>(this);

    @ManyToMany(() => Post, post => post.likes)
    postsLiked = new Collection<Post>(this);

    @ManyToMany(() => Post, post => post.markedUsers)
    markedInPost = new Collection<Post>(this);

    @OneToMany(() => Comment, comment => comment.author)
    comments = new Collection<Comment>(this);

    @ManyToMany(() => Comment, comment => comment.likes)
    commentsLiked = new Collection<Comment>(this);

    @OneToMany(() => Reply, reply => reply.author)
    replies = new Collection<Reply>(this);

    @OneToMany(() => Reply, reply => reply.to)
    repliesFor = new Collection<Reply>(this);

    @ManyToMany(() => Reply, reply => reply.likes)
    repiesLiked = new Collection<Reply>(this);

    @Property({ persist: false })
    subscribersCount?: number

    @Property({ persist: false })
    subscribedCount?: number
}
```
Post
```ts
@Entity({ customRepository: () => PostRepository })
export default class Post {
    [EntityRepositoryType]?: PostRepository

    @PrimaryKey({ type: types.integer, autoincrement: true })
    id!: number

    @Property({ type: types.datetime })
    createdAt!: Date

    @Property({ type: types.datetime, nullable: true })
    updatedAt: Date|null = null

    @Property({ type: types.text })
    text!: string

    @Property({ type: types.array })
    images!: string[]

    @ManyToOne(() => User)
    author!: User

    @ManyToMany(() => User, 'postsLiked', { owner: true })
    likes = new Collection<User>(this);

    @ManyToMany(() => User, 'markedInPost', { owner: true })
    markedUsers = new Collection<User>(this);

    @ManyToMany(() => Hashtag, 'associatedPosts', { owner: true })
    hashtags = new Collection<Hashtag>(this);

    @OneToMany(() => Comment, comment => comment.post)
    comments = new Collection<Comment>(this);

    @Property({ persist: false })
    likesCount?: number
}
```
*Comment*
```ts
@Entity({ customRepository: () => CommentRepository })
export default class Comment {
    [EntityRepositoryType]?: CommentRepository

    @PrimaryKey({ type: types.integer, autoincrement: true })
    id!: number

    @Property({ type: types.text })
    text!: string

    @ManyToOne(() => User)
    author!: User

    @ManyToOne(() => Post)
    post!: Post

    @ManyToMany(() => User, 'commentsLiked', { owner: true })
    likes = new Collection<User>(this);

    @OneToMany(() => Reply, reply => reply.comment)
    replies = new Collection<Reply>(this);

    @Property({ persist: false })
    likesCount?: number
}
```
*Reply*
```ts
@Entity()
export default class Reply {
    @PrimaryKey({ type: types.integer, autoincrement: true })
    id!: number

    @Property({ type: types.text })
    text!: string

    @ManyToOne(() => User)
    author!: User

    @ManyToOne(() => Comment)
    comment!: Comment

    @ManyToOne(() => User, { nullable: true })
    to!: User|null

    @ManyToMany(() => User, 'repiesLiked', { owner: true })
    likes = new Collection<User>(this);
}
```
*Hashtag*
```ts
@Entity({ customRepository: () => HashtagRepository })
export default class Hashtag {
    [EntityRepositoryType]?: HashtagRepository

    @PrimaryKey({ type: types.integer, autoincrement: true })
    id!: number

    @Property({ type: types.string, unique: true })
    name!: string

    @ManyToMany(() => Post, post => post.hashtags)
    associatedPosts = new Collection<Post>(this);
}
```
2. Use this custom comment repository
```ts
import { EntityRepository } from "@mikro-orm/mysql";
import Comment from "../Entity/Comment";

export default class CommentRepository extends EntityRepository<Comment> {
    private commentQuery() {
        return this.createQueryBuilder('comment')
            .select([
                'comment.*',
                'likes.username as likesUsername',
                'count(likes.username) as likesCount'
            ])
            .leftJoinAndSelect('comment.post', 'post')
            .leftJoinAndSelect('comment.author', 'author')
            .leftJoin('comment.likes', 'likes')
            .groupBy('comment.id')
        ;
    }

    public async findAllByPostId(postId: number) {
        return await this.commentQuery()
            .where(
                { post: { id: postId } }
            )
            .getResultList()
        ;
    }
}
```
3. Use this orm config
```ts
export default {
    entities: [User, Post, Comment, Reply, Hashtag],
    type: 'mysql',
    migrations: {
        tableName: 'migrations',
        pathTs: 'src/Migrations',
        path: 'dist/Migrations'
    },
    debug: true,
} as Options;
```
4. Generate and run migrations
5. Seed with random data
6. Use this `main.ts`
```ts
(async () => {

const orm = await MikroORM.init();
const commentRepository = orm.em.getRepository(Comment);
commentRepository.findAllByPostId(1);

})();
```
7. Execute main.ts with ts-node

**Expected behavior**
To return Promise<Comment[]>

**Additional context**
For details, see [https://github.com/ArtemGolovko/api-metero](https://github.com/ArtemGolovko/api-metero/)
MySql 5.7
Full Error:
```
JIT runtime error: Cannot read properties of undefined (reading 'length')

  function(last, current) {
    const diff = {};
    if (current.id == null && last.id == null) {

    } else if ((current.id && last.id == null) || (current.id == null && last.id)) {
      diff.id = current.id;
    } else if (last.id !== current.id) {
      diff.id = current.id;
    }

    if (current.createdAt == null && last.createdAt == null) {

    } else if ((current.createdAt && last.createdAt == null) || (current.createdAt == null && last.createdAt)) {
      diff.createdAt = current.createdAt;
    } else if (last.createdAt.valueOf() !== current.createdAt.valueOf()) {
      diff.createdAt = current.createdAt;
    }

    if (current.updatedAt == null && last.updatedAt == null) {

    } else if ((current.updatedAt && last.updatedAt == null) || (current.updatedAt == null && last.updatedAt)) {
      diff.updatedAt = current.updatedAt;
    } else if (last.updatedAt.valueOf() !== current.updatedAt.valueOf()) {
      diff.updatedAt = current.updatedAt;
    }

    if (current.text == null && last.text == null) {

    } else if ((current.text && last.text == null) || (current.text == null && last.text)) {
      diff.text = current.text;
    } else if (last.text !== current.text) {
      diff.text = current.text;
    }

    if (current.images == null && last.images == null) {

    } else if ((current.images && last.images == null) || (current.images == null && last.images)) {
      diff.images = current.images;
    } else if (!compareArrays(last.images, current.images)) {
>     diff.images = current.images;
           ^
    }

    if (current.author == null && last.author == null) {

    } else if ((current.author && last.author == null) || (current.author == null && last.author)) {
      diff.author = current.author;
    } else if (last.author !== current.author) {
      diff.author = current.author;
    }

    return diff;
  }
JIT runtime error: Cannot read properties of undefined (reading 'length')

  function(entity, data, factory, newEntity, convertCustomTypes, schema) {
    if (typeof data.id !== 'undefined') {
      if (convertCustomTypes) {
        const value = convertToJSValue_id(data.id);
        data.id = convertToDatabaseValue_id(value);
        entity.id = value;
      } else {
        entity.id = data.id;
      }
    }
    if (typeof data.text !== 'undefined') {
      if (convertCustomTypes) {
        const value = convertToJSValue_text(data.text);
        data.text = convertToDatabaseValue_text(value);
        entity.text = value;
      } else {
        entity.text = data.text;
      }
    }
    if (data.author === null) {
      entity.author = null;
    } else if (typeof data.author !== 'undefined') {
      if (isPrimaryKey(data.author, true)) {
        entity.author = factory.createReference('User', data.author, { merge: true, convertCustomTypes, schema });
      } else if (data.author && typeof data.author === 'object') {
        entity.author = factory.create('User', data.author, { initialized: true, merge: true, newEntity, convertCustomTypes, schema });
      }
    }
    if (data.author != null && convertCustomTypes) {
      data.author = convertToDatabaseValue_author(entity.author.__helper.getPrimaryKey());
    }
    if (data.post === null) {
      entity.post = null;
    } else if (typeof data.post !== 'undefined') {
      if (isPrimaryKey(data.post, true)) {
        entity.post = factory.createReference('Post', data.post, { merge: true, convertCustomTypes, schema });
      } else if (data.post && typeof data.post === 'object') {
        entity.post = factory.create('Post', data.post, { initialized: true, merge: true, newEntity, convertCustomTypes, schema });
      }
>   }
           ^
    if (data.post != null && convertCustomTypes) {
      data.post = convertToDatabaseValue_post(entity.post.__helper.getPrimaryKey());
    }
    const createCollectionItem_likes = value => {
      if (isPrimaryKey(value, false)) return factory.createReference('User', value, { convertCustomTypes, schema, merge: true });
      if (value && value.__entity) return value;
      return factory.create('User', value, { newEntity, convertCustomTypes, schema, merge: true });
    }
    if (data.likes && !Array.isArray(data.likes) && typeof data.likes === 'object') {
      data.likes = [data.likes];
    }
    if (Array.isArray(data.likes)) {
       const items = data.likes.map(value => createCollectionItem_likes(value));
       const coll = Collection.create(entity, 'likes', items, newEntity);
       if (newEntity) {
         coll.setDirty();
       } else {
         coll.takeSnapshot();
       }
    } else if (!entity.likes && data.likes instanceof Collection) {
       entity.likes = data.likes;
    } else if (!entity.likes) {
      const coll = Collection.create(entity, 'likes', undefined, !!data.likes || newEntity);
      coll.setDirty(false);
      if (isPrimaryKey(value, false)) return factory.createReference('Reply', value, { convertCustomTypes, schema, merge: true });
      if (value && value.__entity) return value;
    }
    if (data.replies && !Array.isArray(data.replies) && typeof data.replies === 'object') {
      data.replies = [data.replies];
    }
    if (Array.isArray(data.replies)) {
       const items = data.replies.map(value => createCollectionItem_replies(value));
       const coll = Collection.create(entity, 'replies', items, newEntity);
       if (newEntity) {
         coll.setDirty();
       } else {
       }
    } else if (!entity.replies && data.replies instanceof Collection) {
       entity.replies = data.replies;
    } else if (!entity.replies) {
      const coll = Collection.create(entity, 'replies', undefined, !!data.replies || newEntity);
      coll.setDirty(false);
    }
    if (typeof data.likesCount !== 'undefined') entity.likesCount = data.likesCount;
  }
TypeError: Cannot read properties of undefined (reading 'length')
    at compareArrays (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\utils\Utils.js:76:22)
    at eval (eval at createFunction (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\utils\Utils.js:709:20), <anonymous>:43:15)
    at Function.callCompiledFunction (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\utils\Utils.js:720:20)
    at EntityComparator.diffEntities (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\utils\EntityComparator.js:24:30)
    at EntityFactory.mergeData (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\entity\EntityFactory.js:66:39)
    at EntityFactory.create (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\entity\EntityFactory.js:33:18)
    at eval (eval at createFunction (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\utils\Utils.js:709:20), <anonymous>:42:29)
    at Function.callCompiledFunction (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\utils\Utils.js:720:20)
    at ObjectHydrator.hydrate (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\hydration\ObjectHydrator.js:24:23)
    at EntityFactory.hydrate (C:\Users\Artem\projects\api-metero\node_modules\@mikro-orm\core\entity\EntityFactory.js:158:27)
```
SQL queries:
```
[query] select `post`.`id` from `post` as `post` where `post`.`id` = '1' [took 9 ms]
[query] select `comment`.*, `likes`.`username` as `likesUsername`, count(likes.username) as likesCount, `post`.`id` as `post__id`, `post`.`created_at` as `post__created_at`, `post`.`updated_at` as `post__updated_at`, `post`.`text` as `post__text`, `post`.`images` as `post__images`, `post`.`author_username` as `post__author_username`, `author`.`username` as `author__username`, `author`.`name` as `author__name`, `author`.`avatar` as `author__avatar`, `author`.`profile_banner` as `author__profile_banner`, `author`.`is_private` as `author__is_private` from `comment` as `comment` left join `post` as `post` on `comment`.`post_id` = `post`.`id` left join `user` as `author` on `comment`.`author_username` = `author`.`username` left join `comment_likes` as `c1` on `comment`.`id` = `c1`.`comment_id` left join `user` as `likes` on `c1`.`user_username` = `likes`.`username` where `comment`.`post_id` = '1' group by `comment`.`id` [took 10 ms]
```
**Versions**

| Dependency | Version |
| - | - |
| node | v16.14.2 |
| typescript | ^4.6.3 |
| mikro-orm | ^5.1.2 |
| mysql | ^5.1.2 |
| ts-node | ^10.7.0 |

**Comment by B4nan** [comment]
Reproductions should be _minimal_, your repo is quite huge. Please simplify it (turn it into a reproduction) and try to update to latest version first. Use as few entities and properties as possible, ideally just one or two entities, with one PK and one property should be enough. Also this is definitely not about custom repositories, rather about mapping results from QB, so no need to involve them in the reproduction.

From the compiled function code, it should be impossible to reach to a state where `compareArrays` function is called with one of the arguments being undefined (which is what your stack trace is saying).

    // if both are null/undefined do nothing
    if (current.images == null && last.images == null) {

    // or if one of them is undefined and not the other
    } else if ((current.images && last.images == null) || (current.images == null && last.images)) {
      diff.images = current.images;

    // so here both has to be defined
    } else if (!compareArrays(last.images, current.images)) {
     diff.images = current.images;
    }

You could also try to put `console.log()` in the compiled function to see what's happening. The code is generated here:

https://github.com/mikro-orm/mikro-orm/blob/37c1ae4ff706b2911b946a97ff018cd856c71f4d/packages/core/src/utils/EntityComparator.ts#L486

**Comment by ArtemGolovko** [comment]
Thanks for the help
