### ISSUE TITLE
Running migrations requires schema permissions on postgres

### ISSUE THREAD

**Issue by mpauly-exnaton** [mikro-orm/mikro-orm#3106]
[This commit](https://github.com/mikro-orm/mikro-orm/commit/f21181377fd9ff9885e3b0610394d0c7002614bf) runs a `create schema if not exists` on running migrations on postgres if I am not mistaken. The corresponding query will fail if the assigned user does not appropriate permissions, even if the schema already exists. This is not ideal, as it requires giving the MikroORM users additional permissions.

Error on running the migrations:
```
error: create schema if not exists "public" - permission denied for database onboarding
    at Parser.parseErrorMessage (/Users/mpauly/something/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/mpauly/something/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/mpauly/something/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/mpauly/something/node_modules/pg-protocol/src/index.ts:7:48)
```

**To Reproduce**
1. Setup a database and create a user that does not have permissions to edit schemas
2. Create an initial migration with `npm run mikro-orm -- migration:create `
3. Apply the migration with `npm run mikro-orm --  migration:up`

**Expected behavior**
The migration is applied as a schema already exists.

**Versions**
As expected, for me the bug only occurs with version 5.1.3.
| Dependency | Version |
| - | - |
| node | 17.6.0 |
| typescript | 4.6.2 |
| mikro-orm | 5.1.3 |
| @mikro-orm/postgresql | 5.1.3 |

**Comment by B4nan** [comment]
How does your ORM config look like? This query should be invoked only if you specify the schema name explicitly in the migrations table name. Which you should _not_ if its `public` schema, as that is the default.

**Comment by mpauly-exnaton** [comment]
As far as I am aware, the ORM config did not contain an explicit schema in our case, but I might be mistaken. 

Thanks for fixing this, and thanks a lot for running mikro-orm!
