### ISSUE TITLE
cascade attempting to insert when it shouldn't

### ISSUE THREAD

**Issue by milesje** [mikro-orm/mikro-orm#3113]
When performing `em.persistAndFlush(entity)` it is attempting to do an insert for a ManyToOne relation, but it fails because it is already in the database.

**Stack trace**
```
ERROR [ExceptionsHandler] insert into "cust-test"."vehicle_type" ("description", "id", "unit_type") values ('Tractor Conv (TA)', '318f4a49-135f-4d54-967a-2e2772c12d37', 'PU') returning "id", "description", "unit_type" - duplicate key value violates unique constraint "vehicle_type_pkey"
UniqueConstraintViolationException: insert into "cust-test"."vehicle_type" ("description", "id", "unit_type") values ('Tractor Conv (TA)', '318f4a49-135f-4d54-967a-2e2772c12d37', 'PU') returning "id", "description", "unit_type" - duplicate key value violates unique constraint "vehicle_type_pkey"
    at PostgreSqlExceptionConverter.convertException (/home/jmiles/code/market-edge/market-edge-ws-nestjs/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:28:24)
    at PostgreSqlDriver.convertException (/home/jmiles/code/market-edge/market-edge-ws-nestjs/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:173:54)
    at /home/jmiles/code/market-edge/market-edge-ws-nestjs/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:177:24
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PostgreSqlDriver.nativeInsert (/home/jmiles/code/market-edge/market-edge-ws-nestjs/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:161:21)
    at ChangeSetPersister.persistNewEntity (/home/jmiles/code/market-edge/market-edge-ws-nestjs/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:85:21)
    at ChangeSetPersister.executeInserts (/home/jmiles/code/market-edge/market-edge-ws-nestjs/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:29:13)
    at ChangeSetPersister.runForEachSchema (/home/jmiles/code/market-edge/market-edge-ws-nestjs/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:68:13)
    at UnitOfWork.commitCreateChangeSets (/home/jmiles/code/market-edge/market-edge-ws-nestjs/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:657:9)
    at UnitOfWork.persistToDatabase (/home/jmiles/code/market-edge/market-edge-ws-nestjs/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:609:13)
```

**Expected behavior**
I would have expected the relational data to be either skipped or an update to have been performed.

**Additional context**
This is an NestJS project where I have a database table that it is  already populated with vehicle types. I'm attempting to insert a new Vehicle with the vehicle type from the populated data associated with it.

```
const entity = await this.em.create(Vehicle, data, {schema});
entity.vehicleType = await this.em.getReference(VehicleType, vehicleTypeId);
await this.em.persistAndFlush(entity);
```
This code is attempting to perform an insert on the VehicleType (vehicle_type) table instead of just associating the referenced entity.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.1.0 |
| typescript | 4.6.4 |
| mikro-orm | 5.1 .3 |
| pg | 8.7.3 |
| knex | 2.0.0 |

**Comment by milesje** [comment]
Here is a shortend version of the 2 entities in question....
Vehicle
```
@Entity({schema: "*"})
export class Vehicle {
  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id: string
....
  @ManyToOne(() => VehicleType, {cascade: []})
  vehicleType: VehicleType
```

VehicleType
```
@Entity({schema: "*"})
export class VehicleType {
  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id: string
  @Property({ default: '' })
  description: string
  @Property({ default: '' })
  unitType: string

  @OneToMany(() => Vehicle, (vehicles) => vehicles.vehicleType)
  vehicles = new Collection<Vehicle>(this)
}
```
