### ISSUE TITLE
when using Mongodb with mikroorm it does not recreate indexes and there seems to be no other way to drop indexes

### ISSUE THREAD

**Issue by Loki-Afro** [mikro-orm/mikro-orm#3118]
**Describe the bug**
when using Mongodb with mikroorm it does not recreate indexes and there seems to be no other way to drop indexes.
We are using `this.orm.getSchemaGenerator().ensureIndexes();` this only complaints about index definition mismatches, there is no way to simply drop indexes and recreate them in such cases.
**If an orm can create indexes it should also care about their upgrade path**
There is also no way to gather information from the resulting error since it basically pushed the mongodb error to the user without treating it accordingly (api leakage)

**Stack trace**
```
MongoServerError: Index with name: ldapDn_1 already exists with different options
    at MessageStream.messageHandler (/home/zarathustra/code/schulcloud-server/node_modules/mongodb/src/cmap/connection.ts:753:20)
    at MessageStream.emit (node:events:390:28)
    at processIncomingData (/home/zarathustra/code/schulcloud-server/node_modules/mongodb/src/cmap/message_stream.ts:168:12)
    at MessageStream._write (/home/zarathustra/code/schulcloud-server/node_modules/mongodb/src/cmap/message_stream.ts:65:5)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12) {
  ok: 0,
  code: 85,
  codeName: 'IndexOptionsConflict'
}

```

**To Reproduce**
1. define an entity with any kind of index
2. let mikroorm create indexes
3. change an existing index definition in an entity (nullable false -> nullable true for example)
4. rerun {{ensureIndexes}} - exception occurs

**Expected behavior**
Indexes get recreated with an warning, most probably with another option to enable this feature

**Versions**

| Dependency | Version |
| node | v16.13.1 |
| typescript | 4.2.4 |
| mikro-orm | 5.0.5 |
| your-driver | mongodb |

**Comment by Loki-Afro** [comment]
Mongoose does this as well https://github.com/Automattic/mongoose/blob/e95518b2cd871ff54cc9dcb5b1c9b40ca7dc6e04/lib/model.js#L1472

**Comment by totalard** [comment]
just put ensureindex: true in config

**Comment by B4nan** [comment]
@totalard the problem is not with ensuring indexes, but that we only care about creating new indexes, not removing old indexes nor changing redefined ones.
