### ISSUE TITLE
Event Subscriber Constructor Register issue

### ISSUE THREAD

**Issue by totalard** [mikro-orm/mikro-orm#3133]
I have subscribed to abstract entity using class subscriber

```
@Subscriber()
export class SoftDeleteSubscriber implements EventSubscriber<BaseSoftEntity> {
  getSubscribedEntities(): EntityName<BaseSoftEntity>[] {
    return [BaseSoftEntity];
  }

  async onFlush(args: FlushEventArgs): Promise<void> {
    console.log(args);
    const changeSets = args.uow.getChangeSets();
    const toRemove = changeSets.filter(
      (cs) => cs.type === ChangeSetType.DELETE,
    );
    toRemove.forEach((cs) => {
      cs.type = ChangeSetType.UPDATE;
      cs.entity.deletedAt = new Date();
      cs.payload.deletedAt = new Date();
    });
  }
}
```

i missing the constructor and register for it, so i changed to this, my other subscribers are working fine using constructor

```
@Subscriber()
export class SoftDeleteSubscriber implements EventSubscriber<BaseSoftEntity> {
  constructor(private em: MongoEntityManager) {
    this.em.getEventManager().registerSubscriber(this);
  }

  getSubscribedEntities(): EntityName<BaseSoftEntity>[] {
    return [BaseSoftEntity];
  }

  async onFlush(args: FlushEventArgs): Promise<void> {
    console.log(args);
    const changeSets = args.uow.getChangeSets();
    const toRemove = changeSets.filter(
      (cs) => cs.type === ChangeSetType.DELETE,
    );
    toRemove.forEach((cs) => {
      cs.type = ChangeSetType.UPDATE;
      cs.entity.deletedAt = new Date();
      cs.payload.deletedAt = new Date();
    });
  }
}
```

Now it trigger error

```
E:\tt_ecom\ttl-nest\src\services\SoftDeleteSubscriber.service.ts:14
    this.em.getEventManager().registerSubscriber(this);
            ^
TypeError: Cannot read property 'getEventManager' of undefined
    at new SoftDeleteSubscriber (E:\tt_ecom\ttl-nest\src\services\SoftDeleteSubscriber.service.ts:14:13)
    at E:\tt_ecom\ttl-nest\node_modules\@mikro-orm\core\decorators\Subscriber.js:8:36
    at DecorateConstructor (E:\tt_ecom\ttl-nest\node_modules\reflect-metadata\Reflect.js:541:33)
    at Object.decorate (E:\tt_ecom\ttl-nest\node_modules\reflect-metadata\Reflect.js:130:24)
    at __decorate (E:\tt_ecom\ttl-nest\dist\services\SoftDeleteSubscriber.service.js:4:92)
    at Object.<anonymous> (E:\tt_ecom\ttl-nest\src\services\SoftDeleteSubscriber.service.ts:12:34)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (E:\tt_ecom\ttl-nest\src\app.module.ts:19:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (E:\tt_ecom\ttl-nest\src\main.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

but the same way i written many subscribers, all are working fine, why this subscriber trigger error, **I HAVE ALSO ISSUE THAT THIS SUBSCIBER TRIGGER EVEN THE ENTITY IS NOT INHERITED FROM THE SPECIFIED ABSTRACT ENTITY**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | ? |
| mikro-orm | 5.1.4 |
| your-driver | mongo |

**Comment by B4nan** [comment]
If you want to have constructor in your subscriber, you are the one who needs to call it, not the ORM. For the `@Subscriber` decorator to work, you need to make sure it gets executed before you call `MikroORM.init` (in other words, the file where its used needs to be imported). Ideally you should prefer registering the subscriber via ORM config instead, that way you don't need the `@Subscriber` decorator at all.

This is all documented:

https://mikro-orm.io/docs/events#eventsubscriber

**Comment by B4nan** [comment]
> I HAVE ALSO ISSUE THAT THIS SUBSCIBER TRIGGER EVEN THE ENTITY IS NOT INHERITED FROM THE SPECIFIED ABSTRACT ENTITY

You cannot subscriber to an abstract entity, that's not supported as abstract entities dont exist during runtime, they are inlined during discovery.
