### ISSUE TITLE
Undefined metadata when persisting a collection

### ISSUE THREAD

**Issue by jwaaang** [mikro-orm/mikro-orm#3180]
**Describe the bug**

**Stack trace**
```
    console.log
      [query] rollback

      at DefaultLogger.log (../../../.yarn/__virtual__/@mikro-orm-core-virtual-ba48361820/0/cache/@mikro-orm-core-npm-5.1.5-782f2c15b5-c670518c62.zip/node_modules/@mikro-orm/core/logging/DefaultLogger.js:31:14)

  ● test › create execution

    Error: Error: TypeError: Cannot read properties of undefined (reading 'properties')

      at Collection.get property [as property] (../../../.yarn/__virtual__/@mikro-orm-core-virtual-ba48361820/0/cache/@mikro-orm-core-npm-5.1.5-782f2c15b5-c670518c62.zip/node_modules/@mikro-orm/core/entity/ArrayCollection.js:140:44)
      at Collection.[nodejs.util.inspect.custom] (../../../.yarn/__virtual__/@mikro-orm-core-virtual-ba48361820/0/cache/@mikro-orm-core-npm-5.1.5-782f2c15b5-c670518c62.zip/node_modules/@mikro-orm/core/entity/ArrayCollection.js:196:55)
      at PipelineStage.meta.<computed> (../../../.yarn/__virtual__/@mikro-orm-core-virtual-ba48361820/0/cache/@mikro-orm-core-npm-5.1.5-782f2c15b5-c670518c62.zip/node_modules/@mikro-orm/core/entity/EntityHelper.js:119:48)
      This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
      Please open an issue with this stack trace at https://github.com/nodejs/node/issues
      at PipelineStage.meta.<computed> (../../../.yarn/__virtual__/@mikro-orm-core-virtual-ba48361820/0/cache/@mikro-orm-core-npm-5.1.5-782f2c15b5-c670518c62.zip/node_modules/@mikro-orm/core/entity/EntityHelper.js:119:48)
      This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
      Please open an issue with this stack trace at https://github.com/nodejs/node/issues
      at Collection.[nodejs.util.inspect.custom] (../../../.yarn/__virtual__/@mikro-orm-core-virtual-ba48361820/0/cache/@mikro-orm-core-npm-5.1.5-782f2c15b5-c670518c62.zip/node_modules/@mikro-orm/core/entity/ArrayCollection.js:195:40)
      This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
      Please open an issue with this stack trace at https://github.com/nodejs/node/issues
      at PipelineExecution.meta.<computed> (../../../.yarn/__virtual__/@mikro-orm-core-virtual-ba48361820/0/cache/@mikro-orm-core-npm-5.1.5-782f2c15b5-c670518c62.zip/node_modules/@mikro-orm/core/entity/EntityHelper.js:119:48)
      at Function.propertyRequired (../../../.yarn/__virtual__/@mikro-orm-core-virtual-ba48361820/0/cache/@mikro-orm-core-npm-5.1.5-782f2c15b5-c670518c62.zip/node_modules/@mikro-orm/core/errors.js:64:154)
```

**To Reproduce**
I have two entities:
```
@Entity()
export class Execution extends BaseEntity {
  @ManyToOne()
  task?: Task;

  @ManyToMany(() => Stage, Stage => Stage.executions)
  stages = new Collection<Stage>(this);

  @Property()
  active?: boolean = false;

  constructor(id?: string) {
    super(id);
  }
}

```

and 

```
@Entity()
export class Stage extends BaseEntity {
  @Property()
  project?: string;

  @ManyToMany(() => Execution, execution => Execution.stages, {
    owner: true,
  })
  executions = new Collection<Execution>(this);
}
```

when i try to persist a new Execution entity:

```
execution = new Execution(executionId);
const exec = this.em.create(Execution, execution);
this.em.persist(exec);
await this.em.flush();
```
I get the above error.

**Expected behavior**
I expect the flush to go thru.

**Additional context**
https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/entity/ArrayCollection.ts#L170
seems like this is the LoC that's breaking.

Also this is being run inside a nestJS service using "@mikro-orm/nestjs": "^5.0.1".

Running it on debug mode shows all the entities being discovered properly.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.0 |
| typescript | 4.2.3 |
| mikro-orm | 5.1.4 |
| your-driver | 5.7.25-TiDB-v6.1.0 |

**Comment by jwaaang** [comment]
I changed the metadata provider to:
```
metadataProvider: TsMorphMetadataProvider,
```
and it now works. Strange that the `ReflectMetadataProvider` did not work

**Comment by B4nan** [comment]
You should pass a POJO to em.create, not entity instance. Moreover that error seems to be coming from serializing/logging, not flushing.

**Comment by B4nan** [comment]
actually not, its coming from validation of required properties, your `task` property is missing `entity` option:

```ts
  @ManyToOne(() => Task)
  task?: Task;
```

I will add better error handling around this, you should get a "missing metadata error" instead.

**Comment by jwaaang** [comment]
this is what i have in my config:
```
const config: Options = {
  entities: ['./dist/**/*.entity.js'],
  entitiesTs: ['./src/**/*.entity.ts'],
  dbName: 'task-pipeline',
  type: 'mysql',
  port: 4000, // TiDB default port
  migrations: {
    path: 'dist/migrations',
    pathTs: 'src/migrations',
  },
  autoLoadEntities: true,
  debug: true,
  metadataProvider: TsMorphMetadataProvider,
};
```

moreover it looks like entity is discovered fine:
```
console.log
      [discovery] - processing entity Execution
```

**Comment by jwaaang** [comment]
ah i see what's happening. the entity that is discovered is actually from `dist` instead of `src` and is the `js` file.

how do i make it discover from `src` instead?

**Comment by B4nan** [comment]
you can force that via `tsNode: true` but keep in mind you should not have that in your production config

**Comment by B4nan** [comment]
it should be detected automatically, how do you run your app?

**Comment by jwaaang** [comment]
using `nest`. i am testing right now using `jest`. 

so should i have a different config for prod and testing? and in prod it should automatically pick up the `.ts` entities?

**Comment by jwaaang** [comment]
using `tsNode: true` made the test work!

**Comment by B4nan** [comment]
`ts-jest` should be detected if you are on latest versions, or do you use something else for TS support?

**Comment by jwaaang** [comment]
i am using `"ts-jest": "^26.5.4",` and have this for my jest config:

```
"jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "ts"
    ],
    "rootDir": "src",
    "testRegex": ".*\\.spec\\.ts$",
    "transform": {
      "^.+\\.ts$": "ts-jest"
    },
    "collectCoverageFrom": [
      "**/*.(t|j)s"
    ],
    "coverageDirectory": "../coverage",
    "testEnvironment": "node"
  },
```

**Comment by jwaaang** [comment]
ah that did it! works now even without the tsnode config

thanks so much @B4nan
