### ISSUE TITLE
Support for mongodb Geospatial queries?

### ISSUE THREAD

**Issue by einnjo** [mikro-orm/mikro-orm#320]
I'm trying to query a collection using MongoDB's [Geospatial](https://docs.mongodb.com/manual/reference/operator/query/near/#op._S_near) querying features like so:
```ts
    const sheltersInRange = await this.shelterRepository.find({
      location: {
        $near: {
          $geometry: {
            type: "Point",
            coordinates: [long, lat]
          },
          $maxDistance: maxDistance,
          $minDistance: 0
        }
      }
    });
```
But the **$near** operator is not part of the current query interface. With SQL drivers you can fall back to **QueryBuilder** when you want more control over the query, is there anything similar for the Mongo driver?

**Comment by B4nan** [comment]
Just type cast the query parameter to `any`, it should work, the only problem is with the `FilterQuery` type from the ORM (once we have separate ORM modules for mongo driver, I will probably introduce different flavour of `FilterQuery` type for mongo to overcome this). You could type cast only the problematic part to preserve some type checking. 

    const sheltersInRange = await this.shelterRepository.find({
      location: {
        $near: {
          $geometry: {
            type: "Point",
            coordinates: [long, lat]
          },
          $maxDistance: maxDistance,
          $minDistance: 0
        }
      } as any
    });

For mongo you can also work directly with the collection by doing:

```typescript
em.getConnection().getCollection()...
```

(you will need to have correct type hint for the EM, `EntityManager<MongoDriver>`)

**Comment by B4nan** [comment]
Closing as answered, let me know if it did not work for you.

**Comment by isdiop** [comment]
hi @B4nan i have an issue when i ty your example 

do you have any idea ? 

```
[Nest] 5711   - 22/11/2020 à 15:51:02   [ExceptionsHandler] invalid point in geo near query $geometry argument: { type: "Point", coordinates: { $in: [ 4.835659, 45.764043 ] } }  Point must only contain numeric elements +10476ms
DriverException: invalid point in geo near query $geometry argument: { type: "Point", coordinates: { $in: [ 4.835659, 45.764043 ] } }  Point must only contain numeric elements
    at MongoExceptionConverter.convertException (/Users/ibraah/code/fitnezzy/api/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at MongoExceptionConverter.convertException (/Users/ibraah/code/fitnezzy/api/node_modules/@mikro-orm/mongodb/MongoExceptionConverter.js:17:22)
    at MongoDriver.convertException (/Users/ibraah/code/fitnezzy/api/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:171:54)
    at /Users/ibraah/code/fitnezzy/api/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:175:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async MongoDriver.find (/Users/ibraah/code/fitnezzy/api/node_modules/@mikro-orm/mongodb/MongoDriver.js:21:21)
    at async MongoEntityManager.find (/Users/ibraah/code/fitnezzy/api/node_modules/@mikro-orm/core/EntityManager.js:88:25)
    at async ClubService.search (/Users/ibraah/code/fitnezzy/api/dist/src/club/club.service.js:82:16)
    at async SearchService.searchClub (/Users/ibraah/code/fitnezzy/api/dist/src/search/search.service.js:22:16)
    at async SearchController.searchClub (/Users/ibraah/code/fitnezzy/api/dist/src/search/search.controller.js:28:16)

previous MongoError: invalid point in geo near query $geometry argument: { type: "Point", coordinates: { $in: [ 4.835659, 45.764043 ] } }  Point must only contain numeric elements
    at MessageStream.messageHandler (/Users/ibraah/code/fitnezzy/api/node_modules/@mikro-orm/mongodb/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:315:20)
    at MessageStream.EventEmitter.emit (domain.js:485:12)
    at processIncomingData (/Users/ibraah/code/fitnezzy/api/node_modules/@mikro-orm/mongodb/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/Users/ibraah/code/fitnezzy/api/node_modules/@mikro-orm/mongodb/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:353:12)
    at MessageStream.Writable.write (_stream_writable.js:303:12)
    at TLSSocket.ondata (_stream_readable.js:713:22)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
```

**Comment by manu-urba** [comment]
@ibraah88 did you find a solution for your issue?
