### ISSUE TITLE
reloadVersionValues fails to match updated version from queried data to changeset entity when using a custom type

### ISSUE THREAD

**Issue by rat-matheson** [mikro-orm/mikro-orm#3209]
**Describe the bug**
When an entity with optimistic locking is updated, the new version number is retrieved after the update from the DB.  However, the serialized key used to map the queried value to the entity are not the same since the queried data appears to not be transformed via the custom transformations.  It looks like "this.driver.find" does not apply custom type conversions to the results but I'm not 100% sure.  Greatly appreciate any pointers as I debug further.  

As a side note, would it be possible to add typescript docs explaining what the difference is between EntityData<T>, AnyEntity<T>, Partial<T>, and just T.  They seem to be used in overlapping scenarios but I know they are intended for different purposes have subtle differences that I don't understand.

**Stack trace**
```
[query] begin
[query] update `user` set `aud_deleted_date` = 1654868860730, `aud_deleted_by` = '_DjGFx49NSwbeHx7ZQw7c', `aud_updated_date` = 1654868860766, `d` = 'ifluWIaZWMaJj6oBc8x9yBre8DlY3DQeAbSVE2l9a+U=.1654868860766', `version` = `version` + 1 where `id` = 'SYmANMp04i2Z_WLQ0IyNu' and `aud_deleted_date` = 0 and `version` = 1 [took 7 ms]
[query] select `u0`.`id`, `u0`.`aud_deleted_date`, `u0`.`version` from `user` as `u0` where (`u0`.`id`, `u0`.`aud_deleted_date`) in ( values ('SYmANMp04i2Z_WLQ0IyNu', 1654868860730)) [took 1 ms]
reloadVersionValues id~~~deletedDate [ [ 'SYmANMp04i2Z_WLQ0IyNu', 2022-06-10T13:47:40.730Z ] ] [
  {
    id: 'SYmANMp04i2Z_WLQ0IyNu',
    deletedDate: 1654868860730,
    _version: 2
  }
]
data from map Map(1) {
  'SYmANMp04i2Z_WLQ0IyNu~~~1654868860730' => {
    id: 'SYmANMp04i2Z_WLQ0IyNu',
    deletedDate: 1654868860730,
    _version: 2
  }
} undefined SYmANMp04i2Z_WLQ0IyNu~~~Fri Jun 10 2022 13:47:40 GMT+0000 (GMT)
JIT runtime error: Cannot read properties of undefined (reading 'id')

  function(entity, data, factory, newEntity, convertCustomTypes, schema) {
    if (typeof data.id !== 'undefined') entity.id = data.id;
>   if (typeof data.deletedDate !== 'undefined') {
               ^
      if (convertCustomTypes) {
        const value = convertToJSValue_deletedDate(data.deletedDate);
        data.deletedDate = convertToDatabaseValue_deletedDate(value);
        entity.deletedDate = value;
      } else {
        entity.deletedDate = data.deletedDate;
      }
    }
    if (typeof data._version !== 'undefined') entity._version = data._version;
  }
[query] rollback
Unhandled exception TypeError: Cannot read properties of undefined (reading 'id')
    at eval (eval at createFunction (C:\Users\joelw\eclipse-workspace\tower-poi\packages\tower-nest\node_modules\@mikro-orm\core\utils\Utils.js:739:20), <anonymous>:6:19)
    at Function.callCompiledFunction (C:\Users\joelw\eclipse-workspace\tower-poi\packages\tower-nest\node_modules\@mikro-orm\core\utils\Utils.js:750:20)
    at ObjectHydrator.hydrate (C:\Users\joelw\eclipse-workspace\tower-poi\packages\tower-nest\node_modules\@mikro-orm\core\hydration\ObjectHydrator.js:24:23)
    at ChangeSetPersister.reloadVersionValues (C:\Users\joelw\eclipse-workspace\tower-poi\packages\tower-nest\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:278:27)
    at ChangeSetPersister.persistManagedEntity (C:\Users\joelw\eclipse-workspace\tower-poi\packages\tower-nest\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:139:9)
    at ChangeSetPersister.executeUpdates (C:\Users\joelw\eclipse-workspace\tower-poi\packages\tower-nest\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:42:13)
    at ChangeSetPersister.runForEachSchema (C:\Users\joelw\eclipse-workspace\tower-poi\packages\tower-nest\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:68:13)
    at UnitOfWork.commitUpdateChangeSets (C:\Users\joelw\eclipse-workspace\tower-poi\packages\tower-nest\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:682:9)
    at UnitOfWork.persistToDatabase (C:\Users\joelw\eclipse-workspace\tower-poi\packages\tower-nest\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:613:13)
    at SqliteConnection.transactional (C:\Users\joelw\eclipse-workspace\tower-poi\packages\tower-nest\node_modules\@mikro-orm\knex\AbstractSqlConnection.js:36:25)
```

**To Reproduce**
If necessary, I will try to make a test to reproduce the issue.  I suspect you might have some insights just be looking at some of the logging info I added to the compiled version [ChangeSetPersister.reloadVersionValues](https://github.com/mikro-orm/mikro-orm/blob/32ab21583d2718ab874ff71b3f13c9e6a9e5faf0/packages/core/src/unit-of-work/ChangeSetPersister.ts#L320).  

As you can see, the data returned from ```this.driver.find(meta.name, { [pk]: { $in: pks } }, options);``` is in the raw format stored in the DB.  The date is returned as an integer.  When it is added to a map to later update the entity, the key from ```Utils.getCompositeKeyHash(item, meta)``` is "SYmANMp04i2Z_WLQ0IyNu~~~1654868860730".  However, the key from the entity itself is matched using ```changeSet.entity.__helper.getSerializedPrimaryKey()``` which returns 'SYmANMp04i2Z_WLQ0IyNu~~~Fri Jun 10 2022 13:47:40 GMT+0000 (GMT)'.  In the entity, the number has already been converted to a date using a custom property type.

```javascript
/**
 * This method also handles reloading of database default values for inserts, so we use
 * a single query in case of both versioning and default values is used.
 */
 async reloadVersionValues(meta, changeSets, options) {
    const reloadProps = meta.versionProperty ? [meta.properties[meta.versionProperty]] : [];
    if (changeSets[0].type === ChangeSet_1.ChangeSetType.CREATE) {
        // do not reload things that already had a runtime value
        reloadProps.push(...meta.props.filter(prop => prop.defaultRaw && prop.defaultRaw.toLowerCase() !== 'null' && changeSets[0].entity[prop.name] == null));
    }
    if (reloadProps.length === 0) {
        return;
    }
    const pk = utils_1.Utils.getPrimaryKeyHash(meta.primaryKeys);
    const pks = changeSets.map(cs => cs.entity.__helper.getPrimaryKey());
    options = this.propagateSchemaFromMetadata(meta, options, {
        fields: reloadProps.map(prop => prop.fieldNames[0]),
    });
    const data = await this.driver.find(meta.name, { [pk]: { $in: pks } }, options);

    console.log("reloadVersionValues", pk, pks, data)
    // OUTPUT
    //
    // reloadVersionValues id~~~deletedDate [ [ 'SYmANMp04i2Z_WLQ0IyNu', 2022-06-10T13:47:40.730Z ] ] [
    //     {
    //       id: 'SYmANMp04i2Z_WLQ0IyNu',
    //       deletedDate: 1654868860730,
    //       _version: 2
    //     }
    //   ]
      
    const map = new Map();
    data.forEach(item => map.set(utils_1.Utils.getCompositeKeyHash(item, meta), item));
    for (const changeSet of changeSets) {
        const data = map.get(changeSet.entity.__helper.getSerializedPrimaryKey());
        
        console.log("data from map", map, data, changeSet.entity.__helper.getSerializedPrimaryKey())
        // OUTPUT
        //
        // data from map Map(1) {
        //     'SYmANMp04i2Z_WLQ0IyNu~~~1654868860730' => {
        //       id: 'SYmANMp04i2Z_WLQ0IyNu',
        //       deletedDate: 1654868860730,
        //       _version: 2
        //     }
        // } undefined SYmANMp04i2Z_WLQ0IyNu~~~Fri Jun 10 2022 13:47:40 GMT+0000 (GMT)

        this.hydrator.hydrate(changeSet.entity, meta, data, this.factory, 'returning', false, true);
    }
}
```

Relevant parts of the model

```typescript

    @PrimaryKey({
        length:30
    })
    public id:string;

    @PrimaryKey({
      fieldName:"aud_deleted_date",
      type:new TransformType<0|number|Date>({
          getColumnType: (prop: EntityProperty, platform: Platform) => "INTEGER",
          toDbValue:(v) => {
              if (v == null || <any>v == "0" || v == 0) {
                  return 0;
              } else if (v instanceof Date) {
                  return v.getTime();
              }
            
              return new Date(v).getTime();
          },
          toJsValue: (value) => (value == "0" || value == null || value == 0) ? 0 : new Date(value)
      }),
    
      hidden:true,
      comment:"If the data is not deleted, the value is 0.  Otherwise, it is the date the data was deleted"
    })
    public deletedDate:Date | 0 = 0;

    [PrimaryKeyType]: [string, number];

```

Relevant transformation code
```typescript
export type TransformTypeOptions<JsType = any, DbType = any> = {
    toDbValue?:(value:JsType) => DbType,
    toJsValue?:(value:DbType) => JsType,
    getColumnType?: (prop: EntityProperty, platform: Platform) => string
};

export class TransformType<JsType = any, DbType = any> extends Type<JsType, DbType> {

    constructor(private options:TransformTypeOptions<JsType, DbType>) {
        super()
    }

    override getColumnType = (prop: EntityProperty, platform: Platform):string => 
        (this.options.getColumnType ?? super.getColumnType)(prop, platform)

    override convertToDatabaseValue = (value:JsType): DbType => 
        this.options.toDbValue ? this.options.toDbValue(value) : <any>value;
  
    override convertToJSValue = (value: DbType): JsType => 
        this.options.toJsValue ? this.options.toJsValue(value) : <any>value;
}
```

**Work around**

I think I could just get ride of the custom type and use number for the value so that the DB and the JS match.  
**Versions**

| Dependency | Version |
| - | - |
| node | ? |
| typescript | ? |
| mikro-orm | 5.2.0|
| your-driver | sqlite |

**Comment by rat-matheson** [comment]
Quick update - when I got ride of the custom transformation and just used a numeric unix timestamp for all the deletedDates, I no longer had the issue so it really seems to be related to applying custom transformations

**Comment by B4nan** [comment]
The problem was actually the opposite, the runtime value is what gets used for the PK hash in the identity map, so while ugly and weird, the `SYmANMp04i2Z_WLQ0IyNu~~~Fri Jun 10 2022 13:47:40 GMT+0000 (GMT)` form is what is there and what should be in the look up map too. 

We already have a `toJSON` method you can define on the custom type, I guess we could also use that when constructing the PK hash used in the identity map, but that's not really related to your issue.
