### ISSUE TITLE
I am not able to perform a migration in a lambda function

### ISSUE THREAD

**Issue by MatteoGioioso** [mikro-orm/mikro-orm#321]
**Describe the bug**
I am not able to perform a migration in a lambda function. I get the following error

**Stack trace**
```
ERROR	{ Error: File not found: /var/task/tsconfig.json
    at DefaultFileSystemHost.getFileNotFoundErrorIfNecessary (/opt/nodejs/node_modules/ts-morph/dist/ts-morph.js:3053:50)
    at DefaultFileSystemHost.readFileSync (/opt/nodejs/node_modules/ts-morph/dist/ts-morph.js:2946:24)
    at FileSystemWrapper.readFileSync (/opt/nodejs/node_modules/ts-morph/dist/ts-morph.js:4060:32)
    at TsConfigResolver.getTsConfigFileJson (/opt/nodejs/node_modules/ts-morph/dist/ts-morph.js:4500:38)
    at TsConfigResolver.decorator (/opt/nodejs/node_modules/ts-morph/dist/ts-morph.js:2101:46)
    at TsConfigResolver.parseJsonConfigFileContent (/opt/nodejs/node_modules/ts-morph/dist/ts-morph.js:4496:59)
    at TsConfigResolver.decorator (/opt/nodejs/node_modules/ts-morph/dist/ts-morph.js:2101:46)
    at TsConfigResolver.getCompilerOptions (/opt/nodejs/node_modules/ts-morph/dist/ts-morph.js:4447:21)
    at TsConfigResolver.decorator (/opt/nodejs/node_modules/ts-morph/dist/ts-morph.js:2101:46)
    at Project.addSourceFilesFromTsConfig (/opt/nodejs/node_modules/ts-morph/dist/ts-morph.js:20447:75)
    at TsMorphMetadataProvider.initSourceFiles (/opt/nodejs/node_modules/mikro-orm/dist/metadata/TsMorphMetadataProvider.js:88:41)
    at TsMorphMetadataProvider.getSourceFile (/opt/nodejs/node_modules/mikro-orm/dist/metadata/TsMorphMetadataProvider.js:63:24)
    at TsMorphMetadataProvider.getExistingSourceFile (/opt/nodejs/node_modules/mikro-orm/dist/metadata/TsMorphMetadataProvider.js:20:21)
    at TsMorphMetadataProvider.readTypeFromSource (/opt/nodejs/node_modules/mikro-orm/dist/metadata/TsMorphMetadataProvider.js:51:35)
    at TsMorphMetadataProvider.initPropertyType (/opt/nodejs/node_modules/mikro-orm/dist/metadata/TsMorphMetadataProvider.js:42:47)
    at TsMorphMetadataProvider.initProperties (/opt/nodejs/node_modules/mikro-orm/dist/metadata/TsMorphMetadataProvider.js:27:28) path: '/var/task/tsconfig.json', code: 'ENOENT' }
...
```
Why is it looking for the `ts.config` ?
Shouldn't perform the migration on the already compiled code? 

**To Reproduce**

```
public async getConnection(): Promise<MikroORM> {
    let connection;

    if (this._orm && (await this._orm.isConnected())) {
      connection = this._orm;
    } else {
      const credentials = await this.getCredentials();

      const connectionOptions: Options = {
        dbName: process.env.DB_NAME as string,
        host: process.env.DB_HOST,
        port: (process.env.DB_PORT as unknown) as number,
        user: credentials.username,
        password: credentials.password,
        entities: [CommentEntity],
        migrations: {
          path: "./migrations", // path to the folder with migrations
          transactional: true, // wrap each migration in a transaction
          disableForeignKeys: true, // wrap statements with `set foreign_key_checks = 0` or equivalent
          allOrNothing: true // wrap all migrations in master transaction
        },
        type: "postgresql",
        cache: { enabled: false }
      };

      connection = await MikroORM.init(connectionOptions);
    }

    return connection;
  }

  public async migrate(): Promise<void> {
    const connection = await this.getConnection();
    await connection.getMigrator().up();
    await connection.close();
  }
```

And then I call `migrate` from my lambda function.

**Expected behavior**
Should perform migration

**Versions**

| Dependency | Version |
| - | - |
| node | 13 |
| typescript | 3.7.4 |
| mikro-orm | 3.1.0 |
| your-driver | postgres |

Thanks

**Comment by B4nan** [comment]
> Why is it looking for the ts.config ?

You are using `TsMorphMetadataProvider` (the default one), and you are not specifying `entitiesDirsTs`, so the ORM will (as part of entity discovery) look for your `tsconfig.json` file (by default under `process.cwd() + '/tsconfig.json'`, which for you will be `/var/task/tsconfig.json`). 

> Shouldn't perform the migration on the already compiled code?

This depends on how you run the code, if you run it via `node`, then compiled code will be used. But that is another story, even when you run the compiled code, `TsMorphMetadataProvider` will scan your TS entity files to read property types from them. Also note that using `TsMorphMetadataProvider` without caching will harm performance a lot. 

So the answer is depending on what you really want. You might want to use `ReflectMetadataProvider` instead, that is fast and does not require caching so it will be a better match for this lamba use case. 

https://mikro-orm.io/docs/metadata-providers/#reflectmetadataprovider

Or if you want to stay with the default `TsMorphMetadataProvider`, either make sure the path to your `tsconfig.json` file is correct (you can specify it via `discovery: { tsConfigPath: '...' }`), or use `entitiesDirsTs` array to specify paths to your entity source files. In both cases, make sure you also deploy your entity TS source files as `TsMorphMetadataProvider` requires that. 

Btw you can also pre-generate production ORM cache via CLI (`mikro-orm cache:generate`) and deploy that instead of your TS source files. There are few deployment options listed here: https://mikro-orm.io/docs/deployment#deploy-pre-built-cache

**Comment by MatteoGioioso** [comment]
Ok, thanks, I did manage to solve it. Also I needed to change the pattern for the migrations

```
      const connectionOptions: Options = {
        dbName: process.env.DB_NAME as string,
        host: process.env.DB_HOST,
        port: (process.env.DB_PORT as unknown) as number,
        user: credentials.username,
        password: credentials.password,
        entities: [CommentEntity],
        migrations: {
          path: "./migrations", // path to the folder with migrations
          pattern: /^[\w-]+\d+\.js$/,
          transactional: true, // wrap each migration in a transaction
          disableForeignKeys: true, // wrap statements with `set foreign_key_checks = 0` or equivalent
          allOrNothing: true // wrap all migrations in master transaction
        },
        type: "postgresql",
        cache: { enabled: false },
        metadataProvider: ReflectMetadataProvider
      };
```

Thanks for the help indeed
