### ISSUE TITLE
MikroORM.init throws an error if driverOptions is undefined

### ISSUE THREAD

**Issue by kizahasi** [mikro-orm/mikro-orm#3234]
**Describe the bug**

MikroORM.init throws `TypeError: Cannot read properties of undefined (reading 'context')` error if I set undefined to driverOptions.

If driverOptions is not set, no error is thrown.

**Stack trace**
```
C:\Users\Bob\Desktop\mikro-orm-issue\node_modules\@mikro-orm\sqlite\node_modules\@mikro-orm\knex\AbstractSqlConnection.js:106
        if (driverOptions.context?.client instanceof knex_1.knex.Client) {
                          ^
TypeError: Cannot read properties of undefined (reading 'context')
    at SqliteConnection.createKnexClient (C:\Users\Bob\Desktop\mikro-orm-issue\node_modules\@mikro-orm\sqlite\node_modules\@mikro-orm\knex\AbstractSqlConnection.js:106:27)
    at SqliteConnection.connect (C:\Users\Bob\Desktop\mikro-orm-issue\node_modules\@mikro-orm\sqlite\SqliteConnection.js:11:28)
    at async SqliteDriver.connect (C:\Users\Bob\Desktop\mikro-orm-issue\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:41:9)
    at async MikroORM.connect (C:\Users\Bob\Desktop\mikro-orm-issue\node_modules\@mikro-orm\core\MikroORM.js:59:28)
    at async Function.init (C:\Users\Bob\Desktop\mikro-orm-issue\node_modules\@mikro-orm\core\MikroORM.js:48:13)
```

**To Reproduce**

```typescript
import { MikroORM } from "@mikro-orm/core";
import { SomeEntity } from "./someEntity";

export const someFunc = async () => {
  const orm = await MikroORM.init({
    type: "sqlite",
    entities: [SomeEntity],
    dbName: "./db.sqlite",

    driverOptions: undefined, // This line causes error. If this line is deleted, no error is thrown.
  });

 ...
};
```

**Expected behavior**

No error

**Additional context**

It seems @mikro-orm/knex@5.1.5 does not have this issue.

**Versions**

| Dependency | Version |
| - | - |
| node | 16.15.0 |
| typescript | 4.7.4 |
| mikro-orm | 5.2.0 |
| your-driver | sqlite |

**Comment by B4nan** [comment]
It needs to be defined, passing `undefined` is not supported, just like with all the other optional properties with default value. Why would you want to do that? "empty value" for `driverOptions` is an empty object, not `undefined`.
