### ISSUE TITLE
SchemaGenerator fails at properties with autoincrement (postgres driver) 

### ISSUE THREAD

**Issue by thotzl** [mikro-orm/mikro-orm#3235]
**Description**
The SchemaGenerator seems to fail on auto-incremented properties that are not supposed to be primary keys. It tries to make a primary key out of it, although it works correctly for migrations.

*E. g.*:
I made the property `foobar` autoincremented, generated a migration and executed it. Everything works as expected. But when I use the SchemaGenerator it tries to make a primary key of `foobar` and fails on it because I already have one (`id`)

**Example class**
``` 
// 
@Entity()
class SomeTable {
    @PrimaryKey()
    id!: number;

    @Unique({ name: "foobar_unique" })
    @Property({ autoincrement: true }) // auto increment was newly added
    foobar!: number;
}
```

**Stack trace SchemaGenerator**
```
...\node_modules\@mikro-orm\core\platforms\ExceptionConverter.js:8
        return new exceptions_1.DriverException(exception);
               ^
DriverException: create table "some_table" ("id" serial primary key, "foobar" serial primary key); - multiple primary keys for table "foobar" are not allowed
    at PostgreSqlExceptionConverter.convertException (...\node_modules\@mikro-orm\core\platforms\ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException (...\node_modules\@mikro-orm\postgresql\PostgreSqlExceptionConverter.js:42:22)
    at PostgreSqlDriver.convertException (...\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:182:54)
    at ...\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:186:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SchemaGenerator.execute (...\node_modules\@mikro-orm\knex\schema\SchemaGenerator.js:360:13)
    at async SchemaGenerator.createSchema (...\node_modules\@mikro-orm\knex\schema\SchemaGenerator.js:27:9)
    at async SchemaGenerator.refreshDatabase (...\node_modules\@mikro-orm\core\utils\AbstractSchemaGenerator.js:30:9)
    at async fixturesInit (...\my-ts-file.ts)
```

**Migration (autogenerated example - works as expected)**
```
import { Migration } from "@mikro-orm/migrations";

export class Migration20220620141236 extends Migration {
    async up(): Promise<void> {
        this.addSql('alter table "some_table" alter column "foobar" type int using ("foobar"::int);');
        this.addSql('alter table "some_table" alter column "foobar" drop not null;');
        this.addSql('create sequence if not exists "some_table_foobar_seq";');
        this.addSql(
            'select setval(\'some_table_foobar_seq\', (select max("foobar") from "some_table"));'
        );
        this.addSql(
            'alter table "some_table" alter column "foobar" set default nextval(\'some_table_foobar_seq\');'
        );
    }

    async down(): Promise<void> {
        this.addSql('alter table "some_table" alter column "foobar" type int4 using ("foobar"::int4);');
        this.addSql('alter table "some_table" alter column "foobar" set not null;');
        this.addSql('alter table "some_table" alter column "foobar" drop default;');
    }
}
```
**Differences between Migration and SchemaGenrator**
- SchmemaGenerator: `"foobar" serial primary key`
- Migration: `alter table "some_table" alter column "foobar" set default nextval(\'some_table_foobar_seq\');`

**Versions**

| Dependency | Version |
| node | v16.14.0 |
| typescript | 4.6.2 |
| @mikro-orm/nestjs | 5.0.1 |
| @mikro-orm/postgresql | 5.1.1 |
| @mikro-orm/migrations 5.1.1 |
| @mikro-orm/core | 5.1.1 |
| @mikro-orm/seeder | 5.1.1 |

**Comment by B4nan** [comment]
This has been already fixed, you should upgrade before you report anything.

**Comment by thotzl** [comment]
> This has been already fixed, you should upgrade before you report anything.

sorry
