### ISSUE TITLE
Saving a new entity in v5 triggers a validation error if PK is not set to nullable

### ISSUE THREAD

**Issue by NavaceSystem** [mikro-orm/mikro-orm#3251]
**Describe the bug**
When saving a new entity via `em.create > em.persist > em.flush`, if PK is not set to `nullable` it throws a validation error that the field is required. 

**Stack trace**
```
ValidationError: Value for DatedPartCostEntity.id is required, 'undefined' found
entity: DatedPartCostEntity {
  supplierOrganisationId: '93',
  partId: '12136',
  cost: 1.87672,
  applicableDate: 2022-09-01T00:00:00.000Z,
  notificationDate: 2022-06-25T03:12:41.751Z
}
    at Function.propertyRequired (/Users/raza/dev/dev_navace/navace-backend/node_modules/.pnpm/@mikro-orm+core@5.2.0_@mikro-orm+mysql@5.2.0/node_modules/@mikro-orm/core/errors.js:64:16)
    at EntityValidator.validateRequired (/Users/raza/dev/dev_navace/navace-backend/node_modules/.pnpm/@mikro-orm+core@5.2.0_@mikro-orm+mysql@5.2.0/node_modules/@mikro-orm/core/entity/EntityValidator.js:46:48)
    at ChangeSetPersister.processProperties (/Users/raza/dev/dev_navace/navace-backend/node_modules/.pnpm/@mikro-orm+core@5.2.0_@mikro-orm+mysql@5.2.0/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:77:28)
    at /Users/raza/dev/dev_navace/navace-backend/node_modules/.pnpm/@mikro-orm+core@5.2.0_@mikro-orm+mysql@5.2.0/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:24:46
    at Array.forEach (<anonymous>)
    at ChangeSetPersister.executeInserts (/Users/raza/dev/dev_navace/navace-backend/node_modules/.pnpm/@mikro-orm+core@5.2.0_@mikro-orm+mysql@5.2.0/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:24:20)
    at ChangeSetPersister.runForEachSchema (/Users/raza/dev/dev_navace/navace-backend/node_modules/.pnpm/@mikro-orm+core@5.2.0_@mikro-orm+mysql@5.2.0/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:68:48)
    at ChangeSetPersister.executeInserts (/Users/raza/dev/dev_navace/navace-backend/node_modules/.pnpm/@mikro-orm+core@5.2.0_@mikro-orm+mysql@5.2.0/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:21:25)
    at UnitOfWork.commitCreateChangeSets (/Users/raza/dev/dev_navace/navace-backend/node_modules/.pnpm/@mikro-orm+core@5.2.0_@mikro-orm+mysql@5.2.0/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:657:39)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  entity: DatedPartCostEntity {
    supplierOrganisationId: '93',
    partId: '12136',
    cost: 1.87672,
    applicableDate: 2022-09-01T00:00:00.000Z,
    notificationDate: 2022-06-25T03:12:41.751Z
  }
}
```

**To Reproduce**
1. Have an entity with PK not nullable:
```
@Entity({ tableName: 'datedPrice' })
export class DatedPartCostEntity {
  @PrimaryKey()
  id: string

  @Property()
  cost: number

  @Property()
  priceMovement?: number | null

  @Property({
    serializer: datePropSerializer,
  })
  applicableDate: Date

  @Property({
    serializer: datePropSerializer,
  })
  notificationDate: Date

  @Property()
  supplierOrganisationId: string

  @Property()
  partId: string

  constructor({
    id,
    supplierOrganisationId,
    partId,
    cost,
    applicableDate,
  }: {
    id?: string
    supplierOrganisationId: string
    partId: string
    cost: number
    applicableDate: Date
  }) {
    if (id) this.id = id
    this.supplierOrganisationId = supplierOrganisationId
    this.partId = partId
    this.cost = cost
    this.applicableDate = applicableDate
  }
}
```
2. Create, persist and flush a new entity:
```
const newEntity = em.create(DatedPartCostEntity, {
        supplierOrganisationId,
        partId,
        cost,
        applicableDate: date,
        notificationDate: new Date(),
      })
em.persist(newEntity)
await em.flush()
```

**Expected behavior**
Should result in an insert to the DB with an auto-generated id in the DB. I should not have to provide PK for a new entity.

**Additional context**
This wasn't the case in v4, only started happening after upgrading to v5. If I set `nullable: true` on the `id` field it all works as expected.

`validate: true` is set when initialising through `MikroORM.init`

**Versions**

| Dependency | Version |
| - | - |
| node | 14.19.3 |
| typescript | 4.1.6 |
| mikro-orm | 5.2.0 |
| your-driver | mysql |

**Comment by NavaceSystem** [comment]
@B4nan 

> Why are you mapping it to string? What is the type in your database?

The DB type is INT but I'm casting it to string in the app, and doing an int validation through a custom type, to make all the ids string type. 

So basically if PK is not a number it has to have a value or be nullable.

**Comment by B4nan** [comment]
our entity definition does not match your database schema. Your PK is just a string, strings cant be autoincrement, there is no sequence of strings.

Try this instead:

```ts
@PrimaryKey({ autoincrement: true })
id: string
```
