### ISSUE TITLE
Failure to load a relationship on lazy load with entity wildcard

### ISSUE THREAD

**Issue by LMoota** [mikro-orm/mikro-orm#3270]
**Describe the bug**
I have two entities with entity wildcard in each and with relationship to each other.
After retrieving the first entity from the database in a dynamic schema, I am calling .loadItems(), but it is not respecting the schema of the owner entity (even the entity in question also has a wildcard) and looking for the public schema.
I understand that it would need to have the same schema as the owner, which in this example would be 'test'.
Or at least have an option to set the schema.

**Stack trace**
```
TableNotFoundException: select "f0".* from "public"."flow" as "f0" where "f0"."integration_id" = '82f76e09-504c-432a-8a34-4b839cff3d6c' order by "f0"."id" asc - relation "public.flow" does not exist
    at PostgreSqlExceptionConverter.convertException (/Users/lucas-dev/Projects/ipaas/api/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:38:24)
    at PostgreSqlDriver.convertException (/Users/lucas-dev/Projects/ipaas/api/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:182:54)
    at /Users/lucas-dev/Projects/ipaas/api/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:186:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PostgreSqlDriver.find (/Users/lucas-dev/Projects/ipaas/api/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:46:24)
    at SqlEntityManager.find (/Users/lucas-dev/Projects/ipaas/api/node_modules/@mikro-orm/core/EntityManager.js:105:25)
    at Collection.init (/Users/lucas-dev/Projects/ipaas/api/node_modules/@mikro-orm/core/entity/Collection.js:183:23)
    at Collection.loadItems (/Users/lucas-dev/Projects/ipaas/api/node_modules/@mikro-orm/core/entity/Collection.js:34:13)
```

**To Reproduce**
1. Create two entities with wildcards and relationship
2. Retrieve entity owner in DB in some schema other than public
3. After, on the entity's related property, call the .loadItems() method to retrieve and populate.

| Dependency                | Version   |
| "@mikro-orm/core"    |  "^5.2.1" |
| "@mikro-orm/nestjs" |  "^5.0.2" |
| node                            | v16.15.1   |
| typescript                   | 4.7.4        |

**Comment by B4nan** [comment]
Please provide reproduction as code, this is not enough.

**Comment by LMoota** [comment]
```
@Entity({ schema: '*' })
export class Integration {
  @PrimaryKey({ type: 'uuid', defaultRaw: 'uuid_generate_v4()' })
  id: string;

  @OneToMany(() => Flow, flow => flow.integration, {})
  public flows: Collection<Flow>;
}

@Entity({ schema: '*' })
export class Flow {
 @PrimaryKey({ type: 'uuid', defaultRaw: 'uuid_generate_v4()' })
  id: string;

  @ManyToOne()
  public integration: Integration;
}
```

On callable:
```
 const integrationRepository = this.em.getRepository(Integration);
 const schema  = this.getClientSchema(params.clientId);
const integration  = await integrationRepository.findOneOrFail(
      {
        id: params.integrationId,
      }, {
        schema,
      });

await integration.flows.loadItems();
```

Thanks for your quick response, is that enough?
