### ISSUE TITLE
mikro-orm@5.2.2 fails when trying to remove an entity with M:N relationship

### ISSUE THREAD

**Issue by wasd171** [mikro-orm/mikro-orm#3287]
**Describe the bug**
In some conditions an attempt to `em.remove()` an entity with defined and populated bi-directional M:N relation fails.

**Stack trace**
```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

UniqueConstraintViolationException: insert into `participant_groups` (`participant_id`, `group_id`) values (1, 1) - SQLITE_CONSTRAINT: UNIQUE constraint failed: participant_groups.participant_id, participant_groups.group_id
    at SqliteExceptionConverter.convertException (/home/vagrant/mikro-orm-issue/node_modules/@mikro-orm/sqlite/SqliteExceptionConverter.js:20:20)
    at SqliteDriver.convertException (/home/vagrant/mikro-orm-issue/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:182:54)
    at /home/vagrant/mikro-orm-issue/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:186:24
    at async SqliteDriver.nativeInsertMany (/home/vagrant/mikro-orm-issue/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:219:21)
    at async SqliteDriver.nativeInsertMany (/home/vagrant/mikro-orm-issue/node_modules/@mikro-orm/sqlite/SqliteDriver.js:13:21)
    at async SqliteDriver.updateCollectionDiff (/home/vagrant/mikro-orm-issue/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:579:13)
    at async UnitOfWork.persistToDatabase (/home/vagrant/mikro-orm-issue/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:637:13)
    at async SqliteConnection.transactional (/home/vagrant/mikro-orm-issue/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:36:25)
    at async UnitOfWork.doCommit (/home/vagrant/mikro-orm-issue/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:259:17)
    at async UnitOfWork.commit (/home/vagrant/mikro-orm-issue/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:235:13)

previous Error: insert into `participant_groups` (`participant_id`, `group_id`) values (1, 1) - SQLITE_CONSTRAINT: UNIQUE constraint failed: participant_groups.participant_id, participant_groups.group_id {
  errno: 19,
  code: 'SQLITE_CONSTRAINT'
}

```

**To Reproduce**

```ts
import { Collection, Entity, ManyToMany, MikroORM, PrimaryKey } from '@mikro-orm/core';

@Entity()
export class Group {

  @PrimaryKey()
  id!: number;

  @ManyToMany({
    entity: 'Participant',
    mappedBy: 'groups',
  })
  participants = new Collection<Participant>(this);

}

@Entity()
export class Participant {

  @PrimaryKey()
  id!: number;

  @ManyToMany({
    entity: () => Group,
    inversedBy: 'participants',
  })
  groups = new Collection<Group>(this);

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [Participant],
    dbName: ':memory:',
    type: 'better-sqlite',
  });
  await orm.getSchemaGenerator().createSchema();
});

afterAll(() => orm.close(true));

test('removing items from m:n (GH 3287)', async () => {
  const group1 = new Group();
  group1.participants.add(new Participant());
  await orm.em.persistAndFlush(group1);
  await orm.em.clear();

  const group = await orm.em.findOneOrFail(Group, group1, {
      // This does not work
      populate: ['participants'],
      // This works
      // populate: ["participants.groups"],
    },
  );

  orm.em.remove(group);

  // Throws an error when flushing
  await orm.em.flush();
});
```

**Expected behavior**
Entity `Group` should be removed without error.

**Additional context**
If we choose to overfetch and to populate the relationship as `Group -> Participants -> Groups` everything works OK.
Probably related to changes introduced in https://github.com/mikro-orm/mikro-orm/pull/3273

**Versions**

| Dependency | Version |
| - | - |
| node | v16.11.1 |
| typescript | ^4.5.5 |
| mikro-orm | 5.2.2 |
| sqlite / postgresql | 5.2.2 |

**Comment by B4nan** [comment]
Thanks for the repro, weird we didnt already have such case tested.

**Comment by B4nan** [comment]
FYI your repro would fail even without calling `em.remove()`, the issue here is that owning side of the collection is marked as dirty (and contains one item propagated to it from the populated inverse side).

**Comment by wasd171** [comment]
Thanks for the fix! Unfortunately it seems like it still does not work with `5.2.3` when using a `JOINED` loading strategy. I have updated my reproduction here: https://github.com/CareerLunch/mikro-orm-issue/tree/mikro-orm-5.2.3-joined-many-to-many-bug
Shall I open a new issue?
