### ISSUE TITLE
"duplicate key value violates unique constraint" when adding M:N relation

### ISSUE THREAD

**Issue by fathyb** [mikro-orm/mikro-orm#3323]
**Describe the bug**
Adding a many to many relation can trigger the following error.
```
    UniqueConstraintViolationException: insert into "user_orgs" ("user_id", "org_id") values (1, 0) returning "user_id", "org_id" - duplicate key value violates unique constraint "user_orgs_pkey"
```

**Stack trace**
```
      at PostgreSqlExceptionConverter.convertException (packages/postgresql/src/PostgreSqlExceptionConverter.ts:33:16)
      at PostgreSqlDriver.convertException (packages/core/src/drivers/DatabaseDriver.ts:250:50)
      at packages/core/src/drivers/DatabaseDriver.ts:255:18
      at async PostgreSqlDriver.nativeInsertMany (packages/knex/src/AbstractSqlDriver.ts:273:17)
      at async PostgreSqlDriver.updateCollectionDiff (packages/knex/src/AbstractSqlDriver.ts:717:7)
      at async UnitOfWork.persistToDatabase (packages/core/src/unit-of-work/UnitOfWork.ts:788:7)
      at async PostgreSqlConnection.transactional (packages/knex/src/AbstractSqlConnection.ts:51:19)
      at async UnitOfWork.doCommit (packages/core/src/unit-of-work/UnitOfWork.ts:329:9)
      at async UnitOfWork.commit (packages/core/src/unit-of-work/UnitOfWork.ts:300:7)
      previous error: insert into "user_orgs" ("user_id", "org_id") values (1, 0) returning "user_id", "org_id" - duplicate key value violates unique constraint "user_orgs_pkey"
      at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)
```

**To Reproduce**
Test case:
```ts
import type { BetterSqliteDriver } from "@mikro-orm/better-sqlite";
import {
  Collection,
  Entity,
  MikroORM,
  PrimaryKey,
  ManyToMany,
} from "@mikro-orm/core";

let counter = 0;

@Entity()
export class Org {
  @PrimaryKey()
  id: number = counter++;

  @ManyToMany({
    entity: "User",
    mappedBy: "orgs",
  })
  users = new Collection<User>(this);
}

@Entity()
export class User {
  @PrimaryKey()
  id: number = counter++;

  @ManyToMany({
    entity: "Org",
  })
  orgs = new Collection<Org>(this);
}

let orm: MikroORM<BetterSqliteDriver>;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [User, Org],
    dbName: ":memory:",
    type: "better-sqlite",
  });

  const generator = orm.getSchemaGenerator();
  await generator.ensureDatabase();
  await generator.dropSchema();
  await generator.createSchema();
});

afterAll(() => orm.close(true));

beforeAll(async () => {
  const org = new Org();

  org.users.add(new User());
  orm.em.persist(org);

  await orm.em.flush();

  orm.em.clear();
});

test("add an m:m relation", async () => {
  const user = await orm.em.getRepository(User).findOneOrFail({ id: 1 });
  const org = await orm.em.getRepository(Org).findOneOrFail({ id: 0 });

  org.users.add(user);

  await orm.em.flush();
});
```

**Expected behavior**
The test should pass.

**Additional context**
It fails with the following error:
```
  ● add an m:n relation

    UniqueConstraintViolationException: insert into "user_orgs" ("user_id", "org_id") values (1, 0) returning "user_id", "org_id" - duplicate key value violates unique constraint "user_orgs_pkey"

      31 |         return new ForeignKeyConstraintViolationException(exception);
      32 |       case '23505':
    > 33 |         return new UniqueConstraintViolationException(exception);
         |                ^
      34 |       case '23514':
      35 |         return new CheckConstraintViolationException(exception);
      36 |       case '42601':

      at PostgreSqlExceptionConverter.convertException (packages/postgresql/src/PostgreSqlExceptionConverter.ts:33:16)
      at PostgreSqlDriver.convertException (packages/core/src/drivers/DatabaseDriver.ts:250:50)
      at packages/core/src/drivers/DatabaseDriver.ts:255:18
      at async PostgreSqlDriver.nativeInsertMany (packages/knex/src/AbstractSqlDriver.ts:273:17)
      at async PostgreSqlDriver.updateCollectionDiff (packages/knex/src/AbstractSqlDriver.ts:717:7)
      at async UnitOfWork.persistToDatabase (packages/core/src/unit-of-work/UnitOfWork.ts:788:7)
      at async PostgreSqlConnection.transactional (packages/knex/src/AbstractSqlConnection.ts:51:19)
      at async UnitOfWork.doCommit (packages/core/src/unit-of-work/UnitOfWork.ts:329:9)
      at async UnitOfWork.commit (packages/core/src/unit-of-work/UnitOfWork.ts:300:7)
      previous error: insert into "user_orgs" ("user_id", "org_id") values (1, 0) returning "user_id", "org_id" - duplicate key value violates unique constraint "user_orgs_pkey"
      at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)
```

**Versions**

| Dependency | Version |
| - | - |
| node | `16.15.1` |
| typescript | `4.7.4` |
| mikro-orm | `5.2.3` |
| your-driver | `PostgreSQL` |

**Comment by B4nan** [comment]
I am not following your reproduction, you literally create the m:n relation in `beforeAll` hook, and then try to create it again in the test. If you would load the collection first, we would ignore that automatically, but you don't, so there is no way to know that element is already there.

```ts
const user = await orm.em.getRepository(User).findOneOrFail({ id: 1 });
const org = await orm.em.getRepository(Org).findOneOrFail({ id: 0 }, { populate: ['users'] });

org.users.add(user);

await orm.em.flush();
```

**Comment by fathyb** [comment]
Adding `await org.users.init()` doesn't work either.
```ts
const user = await orm.em.getRepository(User).findOneOrFail({ id: 1 });
const org = await orm.em.getRepository(Org).findOneOrFail({ id: 0 });

await org.users.init();
org.users.add(user);

await orm.em.flush();
```

Adding `await org.users.loadItems()` doesn't work either.
```ts
const user = await orm.em.getRepository(User).findOneOrFail({ id: 1 });
const org = await orm.em.getRepository(Org).findOneOrFail({ id: 0 });

await org.users.loadItems();
org.users.add(user);

await orm.em.flush();
```

**Comment by B4nan** [comment]
I see, I believe that's another side effect of #3287, so feel free to subscribe there.

Note that using `em.populate` will work fine:

```ts
const user = await orm.em.getRepository(User).findOneOrFail({ id: 1 });
const org = await orm.em.getRepository(Org).findOneOrFail({ id: 0 });

await oem.em.populate(org, ['users']);
org.users.add(user);

await orm.em.flush();
```

**Comment by B4nan** [comment]
Reopening, its something else, will fix it in a minute.

**Comment by vaskouk** [comment]
Is this fixed for `upsert` & many-to-many functionality? I am trying to upsert an existing record in database along with its relations and I get this error: ``

```
for (const login of logins) {
const item = entityManager.create(ClientUserMikro, {
    serverId: login._id as unknown as string,
    lockPin: await bcrypt.hash(login.lockPin, 10),
    email: login.email ?? ""
});
item.permissions.set(permissionTemplatesMap.get(roleCode));
clientUsersData.push(item);
}
migratedClient.users.set(clientUsersData);
await entityManager.upsert(ClientMikro, migratedClient, {
onConflictFields: ["serverId"],
onConflictAction: "merge"
});

---

**returning "id" - duplicate key value violates unique constraint "Clients_parse_id_unique"\n` +
      ' - detail: Key (parse_id)=(Os7gqz1cN1) already exists.'**
```

Should I fetch first the entity to see if it exists and then update/persist it whether exists or not?
