### ISSUE TITLE
Unable to use alias with `DeleteQueryBuilder`

### ISSUE THREAD

**Issue by derevnjuk** [mikro-orm/mikro-orm#3366]
**Describe the bug**
The `EntityManager.createQueryBuilder()` provides the ability to pass an alias for the table name via the second parameter:
```ts
await this.em
  .createQueryBuilder(User, 'u')
  .delete({
    'u.createdAt': {
      $lt: new Date()
    }
  })
  .execute();
```
However, it does not work with `DeleteQueryBuilder`, which generates the following query:  
```sql
delete from "user_flows" where "uf"."createdAt" < '2022-08-05T13:44:53.213Z'
```

**Stack trace**

```
error: delete from "user_flows" where "uf"."createdAt" < '2022-08-05T13:44:53.213Z' - missing FROM-clause entry for table "uf"
  at Parser.parseErrorMessage (/node_modules/pg-protocol/src/parser.ts:369:69)
  at Parser.handlePacket (/node_modules/pg-protocol/src/parser.ts:188:21)
  at Parser.parse (/node_modules/pg-protocol/src/parser.ts:103:30)
  at Socket.<anonymous> (/node_modules/pg-protocol/src/index.ts:7:48)
  at Socket.emit (events.js:400:28)
  at Socket.emit (domain.js:475:12)
  at addChunk (internal/streams/readable.js:293:12)
  at readableAddChunk (internal/streams/readable.js:267:9)
  at Socket.Readable.push (internal/streams/readable.js:206:10)
  at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
  at TCP.callbackTrampoline (internal/async_hooks.js:130:17) 
```

**Expected behavior**
`DeleteQueryBuilder` should use tables aliases when building a SQL query, e.g. 
```sql
delete from "user_flows" as "uf" where "uf"."createdAt" < '2022-08-05T13:44:53.213Z'
```
**Versions**

| Dependency | Version |
| - | - |
| node | >= 14 |
| typescript | >=4 |
| mikro-orm | >=5 |
| postgresql | >=5 |

**Comment by B4nan** [comment]
Is that valid sql? I guess pg only? Aliases are supported only for select queries, and that is intentional, not a bug.

**Comment by derevnjuk** [comment]
@B4nan right, this is an example for PG. However, this works well in MySQL https://dev.mysql.com/doc/refman/8.0/en/delete.html. I can't say for sure about SQLlite and MariaDB
