### ISSUE TITLE
TypeError when running tests

### ISSUE THREAD

**Issue by uris77** [mikro-orm/mikro-orm#3382]
**Describe the bug**
When I run jest tests, I get a TypeError when establishing the connection. I don't get this error when the application is booted up tho. 

**Stack trace**
```
TypeError: Cannot read properties of undefined (reading 'Client')
       9 |
      10 | export default async (): Promise<MikroORM<PostgreSqlDriver>> => {
    > 11 |   if (!orm) {
         |               ^
      12 |     orm = await MikroORM.init<PostgreSqlDriver>(config);
      13 |   }
      14 |   return orm;

      at PostgreSqlConnection.createKnexClient (node_modules/@mikro-orm/knex/AbstractSqlConnection.js:106:66)
      at PostgreSqlConnection.connect (node_modules/@mikro-orm/postgresql/PostgreSqlConnection.js:9:28)
      at PostgreSqlDriver.connect (node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:45:31)
      at MikroORM.connect (node_modules/@mikro-orm/core/MikroORM.js:59:46)
      at Function.init (node_modules/@mikro-orm/core/MikroORM.js:48:23)
      at Object.<anonymous>.exports.default (src/db/useDb.ts:11:15)
      at createApp (src/app.ts:25:22)
      at Object.<anonymous> (src/__tests__/health-api-test.ts:12:21)
...
```

**To Reproduce**
1. Try to run any test in a project that uses MikroORM.

**Expected behavior**
Tests should not fail because importing knex inside MikroORM's AbstractSqlConnection is undefined.

**Additional context**
I troubleshooted this locally, and I noticed that error happens here https://github.com/mikro-orm/mikro-orm/blob/master/packages/knex/src/AbstractSqlConnection.ts#L140 :

```
    if (driverOptions.context?.client instanceof knex.Client) {
      this.logger.log('info', 'Reusing knex client provided via `driverOptions`');
      return driverOptions as Knex;
    }

```

Somehow, `knex` is undefined when it is imported, but only in testing.

**Versions**

| Dependency | Version |

 node 16.16.0
typescript  4.5.4
mikro-orm  5.3.1
your-driver postgres

**Comment by uris77** [comment]
Was not able to reproduce in a new project. Seems to be an issue with dependencies.
