### ISSUE TITLE
Unable to use `$in` operator in a join clause

### ISSUE THREAD

**Issue by lagnat** [mikro-orm/mikro-orm#3412]
**Describe the bug**
When trying to use $in on a join(), knex complains that `in` is not allowed.  Some googling indicates that one should use `onIn` however this does not work either.

**Stack trace**
```
Uncaught TypeError TypeError: The operator "in" is not permitted
    at operator (/node_modules/knex/lib/formatter/wrappingFormatter.js:132:11)
    at onBasic (/node_modules/knex/lib/query/querycompiler.js:902:7)
    at join (/node_modules/knex/lib/query/querycompiler.js:445:40)
    at <anonymous> (/node_modules/knex/lib/query/querycompiler.js:133:40)
    at select (/node_modules/knex/lib/query/querycompiler.js:132:16)
    at toSQL (/node_modules/knex/lib/query/querycompiler.js:73:29)
    at toSQL (/node_modules/knex/lib/query/querybuilder.js:83:44)
    at Target.toQuery (/node_modules/knex/lib/builder-interface-augmenter.js:9:21)
    at toString (/node_modules/knex/lib/query/querybuilder.js:78:17)
    at eval (repl:1:19)```
```
**To Reproduce**
```
const qb = MikroInstance.get()
            .em.fork()
            .qb(Stream)
            .join('event', 'st', {
                status: {
                    $in: ['foo', 'bar'],
                },
            });

qb.getKnexQuery().toString()
```

**Expected behavior**
Valid SQL is produced

**Additional context**
None

**Versions**

| Dependency | Version |
| - | - |
| node | v14.18.3 |
| typescript | 4.7.4 |
| mikro-orm | 5.3.1 |
| your-driver | Sqlite |

**Comment by B4nan** [comment]
Should be resolved once #3399 is merged
