### ISSUE TITLE
PK columnType 'bigint' throws invalid type error for string when using QueryBuilder

### ISSUE THREAD

**Issue by labzy88** [mikro-orm/mikro-orm#3437]
**Describe the bug**
I'm using MariaDB. The PK is columnType 'bigint' (auto-increment), the entity uses type string, which I would prefer.

EntityValidator.validateProperty() throws:

```ValidationError: Trying to set Object.id of type 'string' to '1' of type 'number'```

**Stack trace**
```
Trying to set Object.id of type 'string' to '1' of type 'number' - {
stack: [
  "ValidationError: Trying to set Object.id of type 'string' to '1' of type 'number'\n" +
    '    at Function.fromWrongPropertyType (/usr/src/app/node_modules/@mikro-orm/core/errors.js:22:16)\n' +
    '    at EntityValidator.validateProperty (/usr/src/app/node_modules/@mikro-orm/core/entity/EntityValidator.js:62:44)\n' +
    '    at /usr/src/app/node_modules/@mikro-orm/core/EntityManager.js:473:42\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at SqlEntityManager.map (/usr/src/app/node_modules/@mikro-orm/core/EntityManager.js:470:27)\n' +
    '    at /usr/src/app/node_modules/@mikro-orm/knex/query/QueryBuilder.js:411:37\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at QueryBuilder.getResultList (/usr/src/app/node_modules/@mikro-orm/knex/query/QueryBuilder.js:411:20)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
]
}
```

**To Reproduce**
1. Create entity with ```@PrimaryKey({ columnType: 'bigint' })```
```
@Entity()
export class TblTest {
  @PrimaryKey({ columnType: 'bigint' })
  id!: string;
}
```
2. Run  as QueryBuilder select query
```
const qb = em.qb(TblTest)
await qb.select('*')
```

**Expected behavior**
EntityValidator.validateProperty() to accept string type for 'bigint' columnType on MySQL/MariaDB db.

**Additional context**
It does work if I change the type ```id!: number;```

**Versions**

"@mikro-orm/cli": "^5.3.1",
"@mikro-orm/core": "^5.3.1",
"@mikro-orm/mariadb": "^5.3.1",
"@mikro-orm/nestjs": "^5.1.1",
"typescript": "^4.3.5

**Comment by B4nan** [comment]
This way you just use a string type, with custom db column name. Use `type: 'bigint'` instead, which is a shortcut for `type: BigIntType` (or `type: t.bigint`).

```ts
@Entity()
export class TblTest {
  @PrimaryKey({ type: 'bigint' })
  id!: string;
}
```

**Comment by labzy88** [comment]
Hi @B4nan, thanks!

I'm not sure I understand cos that entity is the same as what I have. Are you saying my database type should be changed from bigint to varchar or something similar?

**Comment by B4nan** [comment]
Then provide complete reproduction, there are many tests for this, it works fine. Actually I think it should work fine even the way you had it. The database will return it as string if its defined as bigint, unless you somehow reconfigure it yourself. 

Maybe you just dont have the type defined as bigint in the database schema?

**Comment by B4nan** [comment]
> EntityValidator.validateProperty() to accept string type for 'bigint' columnType on MySQL/MariaDB db.

That error says the opposite - database returns it as number, while the ORM expects it to be string.

**Comment by labzy88** [comment]
@B4nan indeed! It's the opposite, apologies!

So the database schema is 'bigint'. Here is the actual dump of the schema in question
```
CREATE TABLE `jnc_orders_weeks_shopify` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) unsigned NOT NULL,
  `week` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `delivery_mismatch_confirmed` int(1) unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `modified_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_id_week` (`order_id`,`week`),
  KEY `week` (`week`),
  CONSTRAINT `jnc_orders_weeks_shopify_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `tbl_orders` (`order_id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `jnc_orders_weeks_shopify_ibfk_2` FOREIGN KEY (`week`) REFERENCES `tbl_weeks` (`week`) ON DELETE NO ACTION ON UPDATE CASCADE
)
```
I'm battling with an old database, so I used the mikro-orm entity generator, which created this:

```
import { Entity, ManyToOne, PrimaryKey, Property, Unique } from '@mikro-orm/core';
import { TblOrders } from './TblOrders';
import { TblWeeks } from './TblWeeks';

@Entity()
@Unique({ name: 'order_id_week', properties: ['orderId', 'week'] })
export class JncOrdersWeeksShopify {

  @PrimaryKey({ columnType: 'bigint' })
  id!: string;

  @ManyToOne({ entity: () => TblOrders, fieldName: 'order_id', onUpdateIntegrity: 'cascade' })
  orderId!: TblOrders;

  @ManyToOne({ entity: () => TblWeeks, fieldName: 'week', onUpdateIntegrity: 'cascade', index: 'week' })
  week!: TblWeeks;

  @Property({ nullable: true })
  deliveryMismatchConfirmed?: number;

  @Property({ defaultRaw: `current_timestamp()` })
  createdAt!: Date;

  @Property({ nullable: true })
  modifiedAt?: Date;

}
```

The entity all looks correct, the database type for id is bigint, to be honest I'm stumped. I'll try to make a complete reproduction for you when I can, but for now I'll have to find a workaround. Thanks for your help and insight!

**Comment by B4nan** [comment]
Seeing the error actually says `Object` and not `TblTest`, this feels like you might have some other issues there too.

How does your ORM config look like?

**Comment by labzy88** [comment]
So I'm using NestJS:

Here is my configs, everything seems to work fine, until I get to this query builder validation issue.

```
// src/app.module.ts

import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import configuration, { MariaDbConfig } from './config/configuration';
import { MikroOrmModule, MikroOrmModuleOptions } from '@mikro-orm/nestjs';

@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: ['.env', '.env.dev'],
      load: [configuration],
    }),
    MikroOrmModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService): Promise<MikroOrmModuleOptions> => {
        const config = configService.get<MariaDbConfig>('mariaDb');
        return {
          discovery: {
            // warnWhenNoEntities: false,
          },
          type: 'mariadb',
          host: config.host,
          dbName: config.database,
          user: config.admin.user,
          password: config.admin.password,
          entities: ['./dist/client/entities'],
          entitiesTs: ['./src/client/entities'],
        }
      },
      inject: [ConfigService],
    })
  ],
})
export class AppModule {}
```
in the service I'm using the maridb entity manager

```
import { MikroORM } from '@mikro-orm/core';
import { EntityManager as MdbEntityManager } from '@mikro-orm/mariadb';
import { Injectable } from '@nestjs/common';
import { JncOrdersWeeksShopify } from 'src/client/entities/JncOrdersWeeksShopify';

@Injectable()
export class ShopifyOrdersService {
  constructor(
    private mOrm: MikroORM,
    private em: MdbEntityManager,
  ) {}
  
  async getOrders() {
    // const found = this.em.find(JncOrdersWeeksShopify, { id: '1' }); /// <-- this works

    //qb doesn't work, validation error
    const qb = this.em.qb(JncOrdersWeeksShopify)
    await qb.select('*')
  }
}
```

**Comment by labzy88** [comment]
Also, another observation, using Knex works, but when using the Entity Manager to map, I get the exact same error stack. So to add to my previous comment...

```
@Injectable()
export class ShopifyOrdersService {
  constructor(
    private mOrm: MikroORM,
    private em: MdbEntityManager,
  ) {}
  
  async getOrders() {
    // const found = this.em.find(JncOrdersWeeksShopify, { id: '1' }); /// <-- this works

    //qb doesn't work, validation error
    const qb = this.em.qb(JncOrdersWeeksShopify)
    await qb.select('*')

    const knex = this.em.getKnex();
    const result = await knex<JncOrdersWeeksShopify>({ a: 'jnc_orders_weeks_shopify' });
    console.log(result)
    /*
    logged result is:
    [
      {
        id: 1,
        order_id: 6417,
        week: '2022_35',
        delivery_mismatch_confirmed: null,
        created_at: '2022-08-31 09:55:17',
        modified_at: null
      },
      {
        id: 2,
        order_id: 6418,
        week: '2022_35',
        delivery_mismatch_confirmed: null,
        created_at: '2022-08-31 10:18:20',
        modified_at: null
      }
    ]
    */
    const entities = result.map(a => this.em.map(JncOrdersWeeksShopify, a)); // <-- throws same validation error stack
  }
}
```

@B4nan  like you said this is well tested, I also think it might be something with the configuration. For now I'll use the entity manager directly or knex, which do seem to be working for me. Thanks for your time and help! I'll let you know if/when I can make a complete reproduction that produces the same error.

**Comment by B4nan** [comment]
Btw I did try to use the QB the same way as you did (with `await qb.select('*')` on `BookTag2` entity), just to rule out its something with QB and `em.map` but it works fine in the ORM tests. But this is about the mariadb package returning numbers where it should be returning strings.

Looking at the schema in ORM tests, it is:

```sql
create table `book_tag2` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(50) not null) default character set utf8mb4 engine = InnoDB;
```

The only difference from yours is the `bigint` vs `bigint(20)`, not sure if that could fit safely into JS number, maybe yes, in such case you could just map to number instead.

**Comment by B4nan** [comment]
You can override anything via `driverOptions`, it will be merged with the object that is passed to the `knex` function.

**Comment by labzy88** [comment]
ok I'm really stuck in that case, will try with bigint instead of bigint(20) too...

Worst case, I change all the entity 'bigint' to type number.

As I'm working on an old database the entity generator is amazing, and during development I use it a lot, is there a way I could get all bigint fields to type number using the generator?

**Comment by labzy88** [comment]
I didn't see that feature, sorry! fyi, I applied it to the generator and it did work, thanks!!

```
const orm = await MikroORM.init({
    discovery: {
      warnWhenNoEntities: false,
      getMappedType(type: string, platform: Platform) {
        if (type === 'bigint') return Type.getType(IntegerType);
        return platform.getDefaultMappedType(type);
      }
    },
    ...
}
```

That's an acceptable solution for a very very very long time, but I also am unsure if bigint(20) is out of range for JS. I really would like to solve it at some point, but like you said this is well tested and it's clearly not an issue with MikroORM, so thank you so much for taking the time to help me solve this.
