### ISSUE TITLE
Populate throws ValidationError after upgrading from 5.3.1 to 5.4.1

### ISSUE THREAD

**Issue by co-sic** [mikro-orm/mikro-orm#3490]
**Describe the bug**
After upgrading from v5.3.1 to v5.4.1 of mikro-orm I get a ValidationError while populating an Entity.

**Stack trace**
```
ValidationError: Entity 'Contract' does not have property 'contracts'
    at Function.invalidPropertyName (***/node_modules/@mikro-orm/core/errors.js:53:16)
    at SqlEntityManager.preparePopulate (***/node_modules/@mikro-orm/core/EntityManager.js:855:44)
    at SqlEntityManager.lockAndPopulate (***/node_modules/@mikro-orm/core/EntityManager.js:815:39)
    at SqlEntityManager.findOne (***/node_modules/@mikro-orm/core/EntityManager.js:317:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SqlEntityManager.findOneOrFail (***/node_modules/@mikro-orm/core/EntityManager.js:338:22)
    at getUnlockedEmployeesForContract (***/src/services/employeeService/getUnlockedEmployeesForContract.ts:32:22) {
  entity: undefined
}
```

**To Reproduce**
Minimal example:

```ts
@Entity()
export class Customer extends MikroORMBaseEntity<Customer, 'id'> {
  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string;

  @OneToMany(() => Contract, (contract) => contract.customer)
  contracts = new Collection<Contract>(this);

  @ManyToOne()
  parentCustomer: Customer | null = null;

  @OneToMany(() => Customer, (customer) => customer.parentCustomer)
  childCustomers = new Collection<Customer>(this);
}

@Entity()
export class Contract extends MikroORMBaseEntity<Contract, 'id'> {
 @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string;

  @ManyToOne()
  customer!: Customer;
}

const contract = await orm.entityManager.getRepository(Contract).findOneOrFail(
      { id: contractId },
      { populate: ['customer.childCustomers.contracts'] },
    );
```

It seems like it is detecting the childCustomer property as a Contract, even though it is a Customer.
If needed i can provide a working minimal example repository.

**Versions**

| Dependency | Version |
| - | - |
| node | v18.8.0 |
| typescript | 4.8.3 |
| mikro-orm | 5.4.1 |

**Comment by B4nan** [comment]
Thanks, here is a failing test case based on this:

```ts
import { Collection, Entity, ManyToOne, MikroORM, OneToMany, PrimaryKey } from '@mikro-orm/core';
import type { SqliteDriver } from '@mikro-orm/sqlite';

@Entity()
export class Contract {

  @PrimaryKey()
  id!: number;

  @ManyToOne('Customer')
  customer!: any;

}

@Entity()
export class Customer {

  @PrimaryKey()
  id!: number;

  @OneToMany(() => Contract, contract => contract.customer)
  contracts = new Collection<Contract>(this);

  @ManyToOne({ entity: 'Customer', nullable: true })
  parentCustomer?: Customer;

  @OneToMany(() => Customer, customer => customer.parentCustomer)
  childCustomers = new Collection<Customer>(this);

}

let orm: MikroORM<SqliteDriver>;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [Contract, Customer],
    dbName: ':memory:',
    type: 'sqlite',
  });
  await orm.schema.createSchema();
});

afterAll(async () => {
  await orm.close(true);
});

test(`GH issue 3490`, async () => {
  const c = orm.em.create(Customer, {
    childCustomers: [
      {
        contracts: [
          { id: 1 },
          { id: 2 },
          { id: 3 },
        ],
      },
    ],
  });
  await orm.em.fork().persist(c).flush();

  const contract = await orm.em.findOneOrFail(Contract, c.id,
    { populate: ['customer.childCustomers.contracts'] },
  );

  expect(contract.customer.childCustomers[0].contracts).toHaveLength(3);
});
```
