### ISSUE TITLE
schema cli not working when relation

### ISSUE THREAD

**Issue by seunggu** [mikro-orm/mikro-orm#354]
**Describe the bug**
When i use schema cli without relation. it works as expect.
But when i used schmea cli using entity with relation for other entity,
error ocurred with following stack trace.
I assume that typesciprt paths occur error.

**Stack trace**
```
> api@1.0.0 schema:drop:dev /Users/seunggu/Desktop/api
> mikro-orm schema:drop --run

Error: Cannot find module '@shared/infra/persistence/repoitory/test/entity/Test.entity'
Require stack:
- /Users/seunggu/Desktop/api/src/shared/infra/persistence/repoitory/test/entity/TestValueObject.entity.ts
- /Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js
- /Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/metadata/index.js
- /Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/utils/Configuration.js
- /Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/utils/index.js
- /Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/EntityManager.js
- /Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/MikroORM.js
- /Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/cli/CLIHelper.js
- /Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/seunggu/Desktop/api/src/shared/infra/persistence/repoitory/test/entity/TestValueObject.entity.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module.m._compile (/Users/seunggu/Desktop/api/node_modules/ts-node/src/index.ts:814:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/seunggu/Desktop/api/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at MetadataDiscovery.getEntityClassOrSchema (/Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:414:25)
    at MetadataDiscovery.discoverDirectory (/Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:80:33)
    at Function.runSerial (/Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/utils/Utils.js:303:22) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/seunggu/Desktop/api/src/shared/infra/persistence/repoitory/test/entity/TestValueObject.entity.ts',
    '/Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js',
    '/Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/metadata/index.js',
    '/Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/utils/Configuration.js',
    '/Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/utils/index.js',
    '/Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/EntityManager.js',
    '/Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/MikroORM.js',
    '/Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/cli/CLIHelper.js',
    '/Users/seunggu/Desktop/api/node_modules/mikro-orm/dist/cli.js'
  ]
}

```

**To Reproduce**
1. entity with relation
2. cli for schema drop or create

**Expected behavior**
cli works as expect

**Additional context**

**Versions**
3.2.1

| Dependency | Version |
| - | - |
| node | 12.14.0 |
| typescript | 3.7.5 |
| mikro-orm | 3.2.1 |
| your-driver | mysql2 |

**Comment by B4nan** [comment]
This is not about relations, but rather about you using custom paths mapping. When you run the app normally, some framework you are probably using is registering `tsconfig-paths` so your custom mapping can work. That is obviously not done when you run MikroORM CLI, so you need to register them manually. 

https://github.com/dividab/tsconfig-paths

Not very ergonomic, but something like this should work:

```
node -r tsconfig-paths/register node_modules/.bin/mikro-orm schema:drop --run
```

Most probably you could also register in the CLI config programatically:

```
require('tsconfig-paths').register();

export default { ... }; // your ORM config
```

**Comment by seunggu** [comment]
Thank you for your reply.
It works now. i close issue

**Comment by Rorymacauley** [comment]
@B4nan did you ever implement a way for this to work automatically? I ran in to this issue when setting up for the first time and thankfully found the solution here and fixed it by adding `require('tsconfig-paths/register');`

**Comment by B4nan** [comment]
It does work automatically, if you have `paths` mapping in your tsconfig and it is on expected place (by default root of the project).

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/utils/ConfigurationLoader.ts#L89

**Comment by janacm** [comment]
Note to self: This happened when I copy-pasted a repo that uses MikroORM, including its `node_modules` folder. Deleting the node modules folder and running `npm install` fixed my issue.
