### ISSUE TITLE
ArrayType field cannot be updated from null to an empty array

### ISSUE THREAD

**Issue by leopold537** [mikro-orm/mikro-orm#3540]
**Describe the bug**
When I'm trying to update Entity with a @Property({ type: ArrayType, nullable: true }) field that has value changed from null to [] (empty array) with repository, an error is thrown.
I tracked issue to the generated comparator
```
  if (current.days == null && last.days == null) {

  } else if ((current.days && last.days == null) || (current.days == null && last.days)) {
    diff.days = current.days;
  } else if (!compareArrays(last.days, current.days)) {
    diff.days = current.days;
  }
```
As an empty array is serialized to '' (empty string), all conditions checking null and nullable values are resolved as false and compareArrays method is used. compareArray doesn't check if parameters are null and it fails on reading length of null.

**Stack trace**
```
2022-09-25T20:19:30.308Z ERROR [12784] ExceptionsHandler : Cannot read properties of null (reading 'length')
TypeError: Cannot read properties of null (reading 'length')
    at compareArrays (...\node_modules\@mikro-orm\core\utils\Utils.js:56:1)
    at eval (eval at createFunction (...\node_modules\@mikro-orm\core\utils\Utils.js:735:1), <anony
mous>:53:15)
    at ChangeSetComputer.computePayload (...\node_modules\@mikro-orm\core\unit-of-work\ChangeSetCom
puter.js:85:1)
    at ChangeSetComputer.computeChangeSet (...\node_modules\@mikro-orm\core\unit-of-work\ChangeSetC
omputer.js:31:1)
    at UnitOfWork.findNewEntities (...\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:403:
1)
    at UnitOfWork.computeChangeSets (...\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:33
6:1)
    at UnitOfWork.doCommit (...\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:249:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at UnitOfWork.commit (...\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:235:1)
    at SqlEntityManager.flush (...\node_modules\@mikro-orm\core\EntityManager.js:641:1)

```

**To Reproduce**
1. create Entity with field of type string[] annotated with @Property({ type: ArrayType, nullable: true })
2. Create repository. Peroform following actions with repository.
3. Create and save a new record in DB with string[] field set to null
4. Select previously inserted record, set string[] field to [] (empty array) and update record.

**Expected behavior**
Record is updated with string[] field set to '' (empty string)

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | v16.16.0 |
| typescript | 4.8.3 |
| mikro-orm | 5.4.2 |
| your-driver | mysql |

**Comment by B4nan** [comment]
This seems to be already fixed in master, closing with a passing test case.
