### ISSUE TITLE
Question for upsert factor

### ISSUE THREAD

**Issue by seunggu** [mikro-orm/mikro-orm#356]
I tryied to develop a mapper between domain model and orm entity.
I wonder what is factory whether insert or update?:)

**Comment by B4nan** [comment]
Not sure I understand, you mean how the ORM knows when to insert and when to update?

https://mikro-orm.io/docs/unit-of-work#how-mikroorm-detects-changes

All known entities (inside the identity map) are considered as updates, rest is considered insert.

**Comment by seunggu** [comment]
@B4nan um, I should have explained issue, sorry.
following is my issue. please help it.

I have domain models for ddd and entities for persistence.
I want to map domain to entities as following.

when i saved entities for persistence by my custom repository,
I received error.


```
● BaseRepository › .save() › should update domain to database when domain exist in database

    insert into `test` (`bool`, `created_at`, `id`) values (true, '2020-02-25 20:05:22.765', 'id') - Duplicate entry 'id' for key 'PRIMARY'Error: Duplicate entry 'id' for key 'PRIMARY'

      at Packet.asError (node_modules/mysql2/lib/packets/packet.js:712:17)
      at Query.execute (node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (node_modules/mysql2/lib/connection.js:417:32)
      at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:75:12)
      at PacketParser.executeStart (node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (node_modules/mysql2/lib/connection.js:82:25)
```

my code is

```
// Test.ts

import { AggregateRoot } from '@shared/domain/Aggregate';
import { TestId } from '@shared/infra/persistence/repoitory/test/domain/TestId';
import { TestValueObject } from '@shared/infra/persistence/repoitory/test/domain/testValueObject';

export class Test extends AggregateRoot<TestId> {
  private _bool: boolean;
  private _testValueObjects: TestValueObject[];
  private _createdAt: Date;

  get bool(): boolean {
    return this._bool;
  }

  get testValueObjects(): TestValueObject[] {
    return this._testValueObjects;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  constructor(id: TestId, bool: boolean, testVos: TestValueObject[], createdAt: Date) {
    super(id);
    this._bool = bool;
    this._testValueObjects = testVos;
    this._createdAt = createdAt;
  }

  changeBool(bool: boolean): void {
    this._bool = bool;
  }

  addTestVO(testVO: TestValueObject): void {
    this._testValueObjects.push(testVO);
  }
}
```


```
// TestValueObject.ts

import { IsString } from 'class-validator';

import { ValueObject } from '@shared/domain/ValueObject';
import { Guard } from '@shared/utils/Guard';

export class TestValueObject extends ValueObject<TestValueObject> {
  @IsString()
  private _value: string;

  constructor(value: string) {
    super();
    this._value = value;
    Guard.validate(this);
  }

  get value(): string {
    return this._value;
  }
}

```


```
// Test.entity.ts

import { Entity, Property, PrimaryKey, Collection, OneToMany } from 'mikro-orm';

import { IAsggregateRootEntity } from '@shared/infra/persistence/entity/Aggegate.entity.interface';
import { TestValueObject } from '@shared/infra/persistence/repoitory/test/entity/TestValueObject.entity';

@Entity()
export class Test implements IAsggregateRootEntity {
  @PrimaryKey()
  id: string;

  @Property()
  bool: boolean;

  @OneToMany({
    entity: () => TestValueObject,
    mappedBy: 'test',
    orphanRemoval: true,
    eager: true,
  })
  testValueObjects = new Collection<TestValueObject>(this);

  @Property()
  createdAt: Date;

  @Property({ nullable: true })
  deletedAt: Date | null;
}
```


```
// TestValueObject.entity.ts

import { Entity, Property, PrimaryKey, ManyToOne, IdentifiedReference } from 'mikro-orm';

import { IValueObjectEntity } from '@shared/infra/persistence/entity/ValueObject.entity.interface';
import { Test } from '@shared/infra/persistence/repoitory/test/entity/Test.entity';

@Entity()
export class TestValueObject implements IValueObjectEntity {
  @PrimaryKey()
  id: number;

  @Property()
  value: string;

  @ManyToOne({ entity: () => Test, wrappedReference: true })
  test: IdentifiedReference<Test>;
}
```


```
// Test.mapper.ts

import { Injectable } from '@nestjs/common';
import { Collection, wrap } from 'mikro-orm';

import { IMapper } from '@shared/core/Mapper.interface';
import { TestId } from '@shared/infra/persistence/repoitory/test/domain/TestId';
import { Test } from '@shared/infra/persistence/repoitory/test/domain/Test';
import { TestValueObject } from '@shared/infra/persistence/repoitory/test/domain/TestValueObject';
import { Test as TestEntity } from '@shared/infra/persistence/repoitory/test/entity/Test.entity';
import { TestValueObject as TestValueObjectEntity } from '@shared/infra/persistence/repoitory/test/entity/TestValueObject.entity';

@Injectable()
export class TestMapper implements IMapper<Test, TestEntity> {
  public toDomain(entity: TestEntity): Test {
    const testValueObjects = entity.testValueObjects.getItems().map(testVOEntity => {
      const testVO = new TestValueObject(testVOEntity.value);
      testVO.setPrimaryKey(testVOEntity.id);
      return testVO;
    });

    return new Test(new TestId(entity.id), entity.bool, testValueObjects, entity.createdAt);
  }

  public toPersistence(domain: Test): TestEntity {
    const entity = new TestEntity();
    entity.id = domain.id.value;
    entity.bool = domain.bool;
    entity.createdAt = domain.createdAt;

    const testValueObjectEntities = domain.testValueObjects.map(testVO => {
      const testValueObjectEntity = new TestValueObjectEntity();
      if (testVO.primaryKey) testValueObjectEntity.id = testVO.primaryKey;
      testValueObjectEntity.value = testVO.value;
      testValueObjectEntity.test = wrap(entity).toReference();
      return testValueObjectEntity;
    });
    entity.testValueObjects = new Collection(entity, testValueObjectEntities);
    entity.testValueObjects.populated(true);
    entity.testValueObjects.setDirty(true);
    return entity;
  }
}
```



```
// Base.repository.ts

import { Injectable, Inject, Type } from '@nestjs/common';
import { EntityManager, wrap } from 'mikro-orm';

import { IRepository } from '@shared/core/Repository.interface';
import { AggregateRoot } from '@shared/domain/Aggregate';
import { Identity } from '@shared/domain/Identity';
import { IMapper } from '@shared/core/Mapper.interface';
import { IAsggregateRootEntity } from '@shared/infra/persistence/entity/Aggegate.entity.interface';

@Injectable()
export abstract class BaseRepository<
  TAggregateRoot extends AggregateRoot<TIdentity>,
  TIdentity extends Identity,
  TPersistenceEntity extends IAsggregateRootEntity
> implements IRepository<TAggregateRoot, TIdentity> {
  @Inject()
  private readonly em: EntityManager;
  private readonly entityType: Type<TPersistenceEntity>;
  protected abstract readonly mapper: IMapper<TAggregateRoot, TPersistenceEntity>;

  constructor(entityType: Type<TPersistenceEntity>) {
    this.entityType = entityType;
  }

  public abstract nextId(): TIdentity;

  public async findById(id: TIdentity): Promise<TAggregateRoot | null> {
    const entityInDB = await this.em.findOne(this.entityType, id.value);
    if (entityInDB === null) return null;
    return this.mapper.toDomain(entityInDB);
  }

  public async save(domain: TAggregateRoot): Promise<void> {
    const entity = this.mapper.toPersistence(domain);
    const entityInDB = (await this.em.findOne(this.entityType, entity.id)) as Type<TPersistenceEntity>;

    if (entityInDB === null) {
      await this.em.persistAndFlush(entity);
      return;
    }

    wrap(entityInDB).assign(entity);
    this.em.persistLater(entityInDB);
    await this.em.flush();
  }

  public async remove(domain: TAggregateRoot): Promise<void> {
    const entity = this.mapper.toPersistence(domain);
    const entityInDB = await this.em.findOne(this.entityType, entity.id);

    if (entityInDB === null) return;

    // for soft delete
    entity.deletedAt = new Date();
    wrap(entityInDB).assign(entity);
    await this.em.persistAndFlush(entityInDB);
  }
}

```


```
// Base.repository.spec.ts

import { MikroORM } from 'mikro-orm';
import { Test as NestTest } from '@nestjs/testing';

import { TestRepository } from '@shared/infra/persistence/repoitory/test/repository/Test.repository';
import { MikroOrmPersistenceTestingModule } from '@shared/infra/persistence/MikroOrmPersistence';
import { TestMapper } from '@shared/infra/persistence/repoitory/test/mapper/Test.mapper';
import { Test } from '@shared/infra/persistence/repoitory/test/domain/Test';
import { TestId } from '@shared/infra/persistence/repoitory/test/domain/TestId';
import { TestValueObject } from '@shared/infra/persistence/repoitory/test/domain/TestValueObject';
import { Test as TestEntity } from '@shared/infra/persistence/repoitory/test/entity/Test.entity';
import { TestValueObject as TestValueObjectEntity } from '@shared/infra/persistence/repoitory/test/entity/TestValueObject.entity';

describe('BaseRepository', () => {
  let orm: MikroORM;
  let repository: TestRepository;

  beforeAll(async () => {
    const moduleRef = await NestTest.createTestingModule({
      imports: [MikroOrmPersistenceTestingModule],
      providers: [TestMapper, TestRepository],
    }).compile();
    orm = moduleRef.get<MikroORM>(MikroORM);
    repository = moduleRef.get<TestRepository>(TestRepository);
  });

  afterAll(async () => {
    await orm.close();
  });

  describe('.findById()', () => {
    beforeEach(async () => {
      const testValueObject1 = new TestValueObjectEntity();
      testValueObject1.value = '1';
      const testValueObject2 = new TestValueObjectEntity();
      testValueObject2.value = '2';

      const testEntity = new TestEntity();
      testEntity.id = 'id';
      testEntity.bool = true;
      testEntity.createdAt = new Date();
      testEntity.testValueObjects.add(testValueObject1);
      testEntity.testValueObjects.add(testValueObject2);
      await orm.em.persistAndFlush(testEntity);
    });

    afterEach(async () => {
      const result = await orm.em.findOne(TestEntity, 'id');
      if (result) {
        result.testValueObjects.set([]);
        await orm.em.persist(result);
        await orm.em.removeEntity(result);
        await orm.em.flush();
      }
    });

    it('should return domain that match id', async () => {
      const test = await repository.findById(new TestId('id'));
      expect(test).toBeInstanceOf(Test);
      expect(test?.id).toEqual(new TestId('id'));
      expect(test?.bool).toEqual(true);
      expect(test?.testValueObjects).toHaveLength(2);
      expect(test?.testValueObjects[0].value).toEqual('1');
      expect(test?.testValueObjects[0].primaryKey).not.toBeNull();
      expect(test?.testValueObjects[1].value).toEqual('2');
      expect(test?.testValueObjects[1].primaryKey).not.toBeNull();
    });
  });

  describe('.save()', () => {
    let test: Test;

    beforeEach(async () => {
      test = new Test(new TestId('id'), false, [new TestValueObject('1'), new TestValueObject('2')], new Date());
    });

    afterEach(async () => {
      const result = await orm.em.findOne(TestEntity, 'id');
      if (result) {
        result.testValueObjects.set([]);
        await orm.em.persist(result);
        await orm.em.removeEntity(result);
        await orm.em.flush();
      }
    });

    it('should insert domain to database when domain doesn`t exist in database', async () => {
      await repository.save(test);
      const result = (await repository.findById(new TestId('id'))) as Test;
      expect(result.id).toEqual(new TestId('id'));
      expect(result.bool).toEqual(false);
      expect(result.testValueObjects).toHaveLength(2);
      expect(result.testValueObjects[0].value).toEqual('1');
      expect(result.testValueObjects[0].primaryKey).not.toBeNull();
      expect(result.testValueObjects[1].value).toEqual('2');
      expect(result.testValueObjects[1].primaryKey).not.toBeNull();
    });

    it('should update domain to database when domain exist in database', async () => {
      await repository.save(test);
      const testToChange = (await repository.findById(new TestId('id'))) as Test;

      testToChange.changeBool(true);
      testToChange.addTestVO(new TestValueObject('3'));
      await repository.save(testToChange);
      const result = (await repository.findById(new TestId('id'))) as Test;
      expect(result.id).toEqual(new TestId('id'));
      expect(result.bool).toEqual(false);
      expect(result.testValueObjects).toHaveLength(3);
      expect(result.testValueObjects[0].value).toEqual('1');
      expect(result.testValueObjects[0].primaryKey).not.toBeNull();
      expect(result.testValueObjects[1].value).toEqual('2');
      expect(result.testValueObjects[1].primaryKey).not.toBeNull();
      expect(result.testValueObjects[2].value).toEqual('2');
      expect(result.testValueObjects[2].primaryKey).not.toBeNull();
    });
  });
});


```

**Comment by B4nan** [comment]
Well it looks like you are creating new entity with the same static id (string “id”), in before each hook. The error is from the db itself, as you are trying to create multiple records with same unique primary key.

**Comment by B4nan** [comment]
Right, but you then remove it... 

Could you create a reproduction repository for me so I can try myself?

**Comment by seunggu** [comment]
@B4nan 
Thank you for your help.
I prepared repository about working.

https://github.com/seunggu/mikro-orm-issue.git

**Comment by B4nan** [comment]
To be honest I do not really understand why would one want to create so much abstraction on top of the ORM. You are basically creating new data mapper, on top of the MikroORM, which is already a data mapper. Also because of how you do it, you cut yourself from all the nice features that the identity map brings, like comparing entities by identity, not talking about the additional complexity and performance hit. 

Maybe `EntitySchema` would be better suited for you? That way you would define the mapping programatically and you could make the ORM use your own POJO class for representing the entity in memory, without using decorators. 

https://mikro-orm.io/docs/entity-schema/

Anyway, your particular problem is in the mapper part, where you create new instance of entity via its constructor:

```typescript
  public toPersistence(domain: Test): TestEntity {
    const entity = new TestEntity(); // <--- here, this will always result in insert query
    entity.id = domain.id.value; // this has no effect, you set the PK, but ORM still sees it as new method. this is what I mentioned in the first reply here
    entity.bool = domain.bool;
    entity.createdAt = domain.createdAt;

    const testValueObjectEntities = domain.testValueObjects.map(testVO => { // this whole collection replacement will also cause troubles, you are supposed to be working with the collection that is already instanced on the entity, not replace it with new one
      const testValueObjectEntity = new TestValueObjectEntity(); // <--- this will also result in insert queries
      if (testVO.primaryKey) testValueObjectEntity.id = testVO.primaryKey;
      testValueObjectEntity.value = testVO.value;
      testValueObjectEntity.test = wrap(entity).toReference();
      return testValueObjectEntity;
    });
    entity.testValueObjects = new Collection(entity, testValueObjectEntities);
    entity.testValueObjects.populated(true);
    entity.testValueObjects.setDirty(true);
    return entity;
  }
```

Then you apply this entity to the one loaded from the database, that is where things break. 

```typescript
    const entity = this.mapper.toPersistence(domain);
    const entityInDB = (await this.em.findOne(this.entityType, entity.id)) as Type<TPersistenceEntity>;
    wrap(entityInDB).assign(entity); // here instead of passing POJO with data, you pass fully functional entity instance that is already wired with its children (in this case 1:m collection items)
```

The `assign` method is supposed to be doing what your mapper is. But what you are doing here is to create new entities (instances), they get autowired with the "artificial" entity (`entity` variable in the code), which you then use to feed the `assign` method. That results in the ORM seeing 2 `Test` entities, both with primary key `id`. 

So I guess you should have something like `assign` method on the mapper level, that would do this for you:

```typescript
  // in the Test.mapper.ts
  public assign(entity: TestEntity, domain: Test): TestEntity {
    entity.id = domain.id.value;
    entity.bool = domain.bool;
    entity.createdAt = domain.createdAt;
    const testValueObjects = entity.testValueObjects.getIdentifiers();

    for (const testVO of domain.testValueObjects) {
      if (!testValueObjects.includes(testVO.primaryKey!)) {
        const testValueObjectEntity = new TestValueObjectEntity();
        if (testVO.primaryKey) testValueObjectEntity.id = testVO.primaryKey;
        testValueObjectEntity.value = testVO.value;
        testValueObjectEntity.test = wrap(entity).toReference();
        entity.testValueObjects.add(testValueObjectEntity);
      }
    }

    return entity;
  }

    // in the base repository
    const entityInDB = (await this.em.findOne(this.entityType, domain.id)) as Type<TPersistenceEntity>;
    this.mapper.assign(entity, domain);
```

That way the repository tests are passing, you just have some wrong assertions there:

    it('should update domain to database when domain exist in database', async () => {
      await repository.save(test);
      const testToChange = (await repository.findById(new TestId('id'))) as Test;

      console.log('bb');
      testToChange.changeBool(true);
      testToChange.addTestVO(new TestValueObject('3'));
      await repository.save(testToChange);

      console.log('cc');
      const result = (await repository.findById(new TestId('id'))) as Test;
      expect(result.id).toEqual(new TestId('id'));
      expect(result.bool).toEqual(true); // this was false
      expect(result.testValueObjects).toHaveLength(3);
      expect(result.testValueObjects[0].value).toEqual('1');
      expect(result.testValueObjects[0].primaryKey).not.toBeNull();
      expect(result.testValueObjects[1].value).toEqual('2');
      expect(result.testValueObjects[1].primaryKey).not.toBeNull();
      expect(result.testValueObjects[2].value).toEqual('3'); // this was '2'
      expect(result.testValueObjects[2].primaryKey).not.toBeNull();
    });

**Comment by kallekulp** [comment]
Sorry to bring up this old issue. I have also been meaning to do something similar. 

The reasoning for having separate entities is that in larger and more complex systems, maintaining a clear separation between domain and persistence concerns becomes crucial for managing complexity and ensuring the integrity of the domain logic. This separation allows for independent evolution of the domain and persistence layers, enabling easier testing, swapping out data storage mechanisms, and accommodating changes in business requirements without affecting the entire system. 

I'm not saying Mikro-ORM is bad, just the opposite: it's the best ORM I have seen in TS/JS, but using ORM entities directly in the domain layer may seem convenient initially, it can lead to tight coupling and difficulties in managing complexity as the project scales.

**Comment by ajfranzoia** [comment]
@kallekulp are you using using Mikro for DDD? What approach are you using to separate domain/persistence layers?
