### ISSUE TITLE
Question: How do I use Migrations with Webpack?

### ISSUE THREAD

**Issue by thekevinbrown** [mikro-orm/mikro-orm#362]
I can't seem to figure out the correct way to pass migration instances instead of paths to the migrations configuration [which is supported by umzug](https://github.com/sequelize/umzug/issues/184). I'm using webpack so I can't do it based on paths.

Do you have an example I can use?

**Comment by thekevinbrown** [comment]
I'm also currently getting:

`Error: Cannot find module 'typescript'`

Which I think is coming from `ts-morph`, even though I've done this:

```typescript
import { MikroORM, ReflectMetadataProvider } from 'mikro-orm';

const orm = await MikroORM.init({
	//...
	metadataProvider: ReflectMetadataProvider,
	discovery: { disableDynamicFileAccess: true },
});
```

The "stack" if you could call it that is:

```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'typescript'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'typescript'",
    "Require stack:",
    "- /var/task/index.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:955:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)",
    "    at Module.load (internal/modules/cjs/loader.js:811:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:723:14)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)",
    "    at internal/main/run_main_module.js:17:11"
  ]
}
```

Of course `/var/task/index.js` is my webpack bundle, so I'm not really sure where this is coming from.

**Comment by B4nan** [comment]
Hmm hard to tell, never used webpack with the ORM myself, maybe @jsprw will have an idea?

> I can't seem to figure out the correct way to pass migration instances instead of paths to the migrations configuration which is supported by umzug. I'm using webpack so I can't do it based on paths.

I don't think this will be supported out of the box just because you can do this with umzug. I am using custom migration runner.

> Error: Cannot find module 'typescript'

Just a guess, but make sure you also do not have `useTsNode` enabled in your package.json. 

If you prepare a repro repository, I will be happy to take a look myself.

**Comment by thekevinbrown** [comment]
I've started simple with the repro. The current error is that the migrations directory doesn't exist.

https://github.com/thekevinbrown/mikro-orm-webpack-migrations

If this isn't supported in Mikro ORM that's fine. What I was hoping for was to get TypeORM style auto-generation of migrations when I change my entities, then to be able to bundle those up with webpack and run them in a lambda.

Cheers!

**Comment by B4nan** [comment]
Hmm I am not sure if there is a way to get this working. You can pass migration instances to umzug, but you will never be able to use the `up()` method to migrate to the latest version. It works solely based on the file system, it looks for files in given directory that were not yet executed. In the webpack context, everything is one file, you do not know whether there is actually a new migration available or not. It least that is how I understand it... 

The issue you linked is open still, and the solution with passing `Migration` class is not working for me, but I might have done something wrong.

To get around this, you would have to implement your own `Migrator` that will not require things but rather accept a list of migrations. The class is relatively small, and all its dependencies should be usable so you really only need to change the require logic `Migrator.resolve` method. 

https://github.com/mikro-orm/mikro-orm/blob/master/lib/migrations/Migrator.ts

Going forward, I will be happy to make it protected or add another way to achieve webpack compatibility, if we find the correct way.

**Comment by thekevinbrown** [comment]
I was able to use the schema generator to integrate with my own migrations process. It generates migrations then manages an `index.ts` file so that we can always:

```typescript
import * as Migrations from './migrations';

Object.values(Migrations);
```

Each migration has a sort key so they come out deterministically, then I built a super lightweight runner.

I'm not sure how much of this belongs in Mikro ORM vs in my own project in the long term, but that's working for me so far.

**Comment by nicolas-van** [comment]
I provided a solution for that in this PR: https://github.com/sequelize/umzug/pull/199 . I just had the same problem and fixed it.

If you want a quick work around here is the key function to convert migrations: https://github.com/nicolas-van/umzug/blob/master/src/migrationsList.js

**Comment by B4nan** [comment]
What about this, do you think we need some changes in the ORM to support this? Have you seen that recent issue in umzug repo?

I think it would be nice to have a working example repo for this use case, if not a direct support in the ORM.

**Comment by thekevinbrown** [comment]
Sorry for the delay.

I ended up using SchemaGenerator by itself and building my own lightweight runner and CLI that generates these migrations and adds them to an index.ts file because I couldn't get anything else working.

So the answer is no, I haven't dug too deeply into trying to get umzug working in this context, I've just built my own tooling around it.

**Comment by thekevinbrown** [comment]
I've ported our tooling over (which does not currently use Mikro's migrations support, but does work with webpack) into this repository: https://github.com/thekevinbrown/express-ts-webpack-example-app

@B4nan, what are the next steps here from your perspective? I can see three ways forward:

1. We might decide that supporting this use case in the migrations framework in Mikro isn't realistic. In this scenario I'd transfer the express-ts-webpack-example-app into the mikro-orm organisation and we'd document this on the migrations documentation.
2. Mikro might require some changes to support this use case. In this scenario, I'd be happy to help with any work I can, it'd be good to know what you're expecting as work that's needed here.
3. If Mikro's ready to go and I just need to leverage Mikro a bit differently to get this to work, let me know and I'll apply those changes to the example app repo, then I'll transfer it into the mikro-orm organisation.

Thanks!

**Comment by B4nan** [comment]
Looking into that migrations thing, we definitely need to consolidate and reuse what is already here. That is why I suggested to extend (or reimplement) the `Migrator` class, but use the rest (but the ideal solution is to adjust it to accommodate the webpack problem). The `resolve` method there is now protected, so you can do whatever needed there instead of that hard require. Generating new migrations is definitely something to be reused too. 

Ideally we should find a way to use that new migrations list feature (https://github.com/sequelize/umzug/pull/199). 

Thinking about that `index.ts` file where you store the list, it could be a bit error prone (1. create a migration, 2. remove it, 3. `index.ts` keeps reference to it so it will break everything). Could we use a JSON file for that or do you really need a TS file with references to the migration classes? We can live with that, but it would have to be enabled by default and this possible problem with removing migrations would have to be noted in the docs.

**Comment by B4nan** [comment]
Closing due to inactivity (open for PR tho, if you find a nice way to allow this).
