### ISSUE TITLE
Support for mongodb Geospatial queries?

### ISSUE THREAD

**Issue by rptally** [mikro-orm/mikro-orm#3641]
**Describe the bug**
I saw the conversation at [https://github.com/mikro-orm/mikro-orm/issues/320](url) and saw the conversation never finished but was closed. 

I attempted to do the MongoDB Geospatial request as defined by @B4nan and here is what happened:

Working Mongo query (expected):
```
db.place.find({
  location: {
    $near: {
      $geometry: {
        type: "Point",
        coordinates: [ -96.501, 33.005 ]
      },
      $maxDistance: 1609.34,
      $minDistance: 0
    }
  }
})
```

Here's the source for the method in Mikro-ORM
```
async getNear(lng: number, lat: number, distance: number): Promise<Place[]> {
  const placesInRange = await this.placeRepo.find({
    location: {
      $near: {
        $geometry: {
          type: "Point",
          coordinates: [ lng, lat ]
        },
        $maxDistance: distance,
        $minDistance: 0
      }
    }
  } as any);

  return placesInRange;
}
```

Here's the error that came back from the run:
```
[Nest] 15521  - 10/23/2022, 5:23:14 PM   ERROR [ExceptionsHandler] invalid point in geo near query 
    $geometry argument: { type: "Point", coordinates: { $in: [ -96.501, 33.005 ] } }  Point must only 
    contain numeric elements
```
I'm unsure why it converted the array of numbers to a $in: [] ?   How can I keep it from adding the $in?  or Can anyone put up a working example to work from?   thx

**Stack trace**
[Nest] 13509  - 10/23/2022, 4:59:36 PM   ERROR [ExceptionsHandler] invalid point in geo near query $geometry argument: { type: "Point", coordinates: { $in: [ -96.50155918619637, 33.00520212965284 ] } }  Point must only contain numeric elements
DriverException: invalid point in geo near query $geometry argument: { type: "Point", coordinates: { $in: [ -96.501, 33.005 ] } }  Point must only contain numeric elements
    at MongoExceptionConverter.convertException (/Users/peter/Projects/api/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at MongoExceptionConverter.convertException (/Users/peter/Projects/api/node_modules/@mikro-orm/mongodb/MongoExceptionConverter.js:17:22)
    at MongoDriver.convertException (/Users/peter/Projects/api/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:192:54)
    at /Users/peter/Projects/api/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:196:24
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at MongoDriver.find (/Users/peter/Projects/api/node_modules/@mikro-orm/mongodb/MongoDriver.js:24:21)
    at MongoEntityManager.find (/Users/peter/Projects/node_modules/@mikro-orm/core/EntityManager.js:106:25)
    at PlacesService.getNear (/Users/peter/Projects/api/src/places/places.service.ts:48:30)
    at PlacesController.placesNear (/Users/peter/Projects/api/src/places/places.controller.ts:45:23)
    at /Users/peter/Projects/api/node_modules/@nestjs/core/router/router-execution-context.js:46:28

previous MongoServerError: invalid point in geo near query $geometry argument: { type: "Point", coordinates: { $in: [ -96.50155918619637, 33.00520212965284 ] } }  Point must only contain numeric elements
    at Connection.onMessage (/Users/peter/Projects/api/node_modules/mongodb/src/cmap/connection.ts:438:20)
    at MessageStream.<anonymous> (/Users/peter/Projects/api/node_modules/mongodb/src/cmap/connection.ts:256:56)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/Users/peter/Projects/api/node_modules/mongodb/src/cmap/message_stream.ts:193:14)
    at MessageStream._write (/Users/peter/Projects/api/node_modules/mongodb/src/cmap/message_stream.ts:70:5)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at MessageStream.Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:766:22)
    at Socket.emit (node:events:513:28)

**To Reproduce**

Just run the method and the issue consistently happens. 

**Expected behavior**

The expectation is the array of numbers that represent the [ longitude, latitude ] are passed through without the $in modification. 

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 18.9.0 |
| typescript | 4.8.4 |
| mikro-orm | @mikro-orm/core: 5.4.2 |
| your-driver | ? |
| --- | --- |
| "@mikro-orm/core"| "^5.4.2",
|    "@mikro-orm/nestjs"| "^5.1.2",
|    "@mikro-orm/mongodb"| "^5.4.2",
|    "@nestjs/common"| "^9.0.0",
|    "@nestjs/config"| "^2.2.0",
|    "@nestjs/core"| "^9.0.0",

**Comment by B4nan** [comment]
You will need to work with the mongo collection API instead if you don't want the query expansion - as generally speaking an array on right hand side in a query always means `$in` operator (unless it is already inside the context of array operators, like the ones in postgres).

```ts
const coll = em.getCollection(Place);
const res = await coll.find({
  location: {
    $near: {
      $geometry: {
        type: "Point",
        coordinates: [ -96.501, 33.005 ]
      },
      $maxDistance: 1609.34,
      $minDistance: 0
    }
  }
});
const entities = res.map(row => em.map(Place, row));
```

**Comment by B4nan** [comment]
Why would you want to do that? Is that even possible on SQL level?
