### ISSUE TITLE
Tries to return virtual property on insert

### ISSUE THREAD

**Issue by willemgovaerts** [mikro-orm/mikro-orm#3704]
**Describe the bug**
When inserting an entity which has a virtual property by calling `em.create(Entity, ...)` and `em.flush()` the query tries to return the virtual property resulting in an error.

**Stack trace**
```
InvalidFieldNameException: insert into "entity" (...) values (...) returning ..., "something" - column "something" does not exist
    at PostgreSqlExceptionConverter.convertException (node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:36:24)
    at PostgreSqlDriver.convertException (node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:192:54)
    at /Users/willemgovaerts/Documents/projects/valcori-api/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:196:24
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PostgreSqlDriver.nativeInsertMany (node_modules/@mikro-orm/knex/AbstractSqlDriver.js:285:21)
    at ChangeSetPersister.persistNewEntity (node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:85:21)
    at ChangeSetPersister.executeInserts (node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:29:13)
    at ChangeSetPersister.runForEachSchema (node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:68:13)
    at UnitOfWork.commitCreateChangeSets (node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:708:9)
    at UnitOfWork.persistToDatabase (node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:660:13)
```

**To Reproduce**
1. create an entity with a simple virtual property
```
@Property({ persist: false })
  public something: number = 0;
```
2. create and flush this entity

**Expected behavior**
Virtual properties should not be included in the `returning` clause

**Additional context**
The fix implemented in [35d51fe](https://github.com/mikro-orm/mikro-orm/commit/35d51fecff9479f3d704bfcffa90d4fd5dcaf21a) seems not to work since `hydrateProps` also contains the virtual property

**Versions**

| Dependency | Version |
| - | - |
| node | v18.10.0 |
| typescript | v4.3.5 |
| mikro-orm | v5.5.1 |
| your-driver | PostgreSqlDriver |

**Comment by B4nan** [comment]
Fixed in master

**Comment by B4nan** [comment]
https://github.com/mikro-orm/mikro-orm/releases/tag/v5.5.2
