### ISSUE TITLE
Help with custom type

### ISSUE THREAD

**Issue by ryankauk** [mikro-orm/mikro-orm#372]
Hey I have a postgres postgis db with column type geometry and thought [the docs here](https://mikro-orm.io/docs/custom-types) would be the best place. I'm unsure what's the best way to use a postgres function to set the value 

``` typescript
convertToDatabaseValue(value: any, platform: Platform) {
        console.log(value)
        if (value instanceof Geometry) {
     

        
            return `ST_SetSRID(ST_MakePoint(${value.lng}, ${value.lat}),4326)`;

        }
        throw ValidationError.invalidType(GeometryType, value, 'JS');
}
```

Best would be to parameterize the values, figured accessing knex would be best option? I'm not sure about the integration with orm to achieve this. Any help is appreciated

**Comment by B4nan** [comment]
Hmm maybe you could use `knex.raw`? 

```typescript
return knex.raw(`ST_SetSRID(ST_MakePoint(?, ?),4326)`, [value.lng, value.lat]);
```

**Comment by localnet** [comment]
I have never tried [knex-postgis](https://www.npmjs.com/package/knex-postgis) but maybe you could use it.

**Comment by B4nan** [comment]
@ryankauk any update on this?

**Comment by B4nan** [comment]
Closing for inactivity, let me know if it helped, will be happy to reopen if not.

**Comment by ryankauk** [comment]
hey @B4nan sorry for the late reply, didn't see your reply and was busy refactor my server to your orm. Really love the project so far. My favourite long needed orm for node.js.

I just tried out your solution here's a little more context 

```typescript
const location = new Location({
    ...input,
    lat: point.lat,
    lng: point.lng,
    geom: new Geometry(point.lng, point.lat),
});
await db.em.persistAndFlush(location);
```

```typescript
convertToDatabaseValue(value: any, platform: Platform) {

    if (value instanceof Geometry) {
        return knex.raw(`ST_SetSRID(ST_MakePoint(?, ?),4326)`, [value.lng, value.lat]);
    } else if (value === null) {
        return value;
    }


    throw ValidationError.invalidType(GeometryType, value, 'JS');
}
```


However this ends up throwing an error "TypeError: Converting circular structure to JSON" from here:

https://github.com/mikro-orm/mikro-orm/blob/e3e02ea566703d3bfa36429095a92d96f0c01a22/lib/query/QueryBuilderHelper.ts#L75-L77

as data[k] ends up evaluating as a knex Raw object in this situation to:


```
Raw {
  client: Client_PG {
    config: { connection: undefined, client: 'pg' },
    logger: Logger {
      _inspectionDepth: 5,
      _enableColors: true,
      _debug: undefined,
      _warn: undefined,
      _error: undefined,
      _deprecate: undefined
    },
    connectionSettings: {},
    connectionConfigExpirationChecker: null,
    valueForUndefined: Raw {
      client: [Circular],
      sql: 'DEFAULT',
      bindings: undefined,
      _wrappedBefore: undefined,
      _wrappedAfter: undefined,
      _debug: undefined
    },
    makeKnex: [Function: makeKnex],
    _events: [Object: null prototype] {
      start: [Function],
      query: [Function],
      'query-error': [Function],
      'query-response': [Function]
    },
    _eventsCount: 4
  },
  sql: 'ST_SetSRID(ST_MakePoint(?, ?),4326)',
  bindings: [ -50, 50 ],
  _wrappedBefore: undefined,
  _wrappedAfter: undefined,
  _debug: undefined
}
```

**Comment by B4nan** [comment]
> Maybe adding an extra check for knex.Raw should be sufficient?

I guess we could make it even better, we know that the property is custom type, therefore we do not need any additional processing of the value (if so, that is what should be part of the `convertToDatabaseValue` method). 

Please try to adjust the condition in `mikro-orm/lib/query/QueryBuilderHelper.ts` to see if that woks:

```typescript
if (Array.isArray(data[k]) || (Utils.isObject(data[k], [Date]) && !prop.customType)) {
  data[k] = JSON.stringify(data[k]);
}
```

If so, will be happy to accept PR :]

**Comment by ryankauk** [comment]
Just tried this out, there seems to be a similar issue in "processParams" in query/SmartQueryHelper.ts. However it seems here there's no access to the props

**Comment by darkbasic** [comment]
Keep me posted about any updates because I'm going to try PostGIS' Geography Type in the next couple of days.

**Comment by ryankauk** [comment]
@darkbasic mikro-orm still works with postgis, it exposes knex so you can use knex-postgis, there's just some of the convenience factors that there's an issue with. Right now I just create an object with knex itself along with querying.

**Comment by B4nan** [comment]
I guess you are talking about this part? What if you comment it out? 

https://github.com/mikro-orm/mikro-orm/blob/master/lib/query/SmartQueryHelper.ts#L27

I guess we could also check the constructor name of the object to see if its a POJO or not (if not, we can ignore it there)

**Comment by darkbasic** [comment]
@ryankauk it seems that `knex-postgis` doesn't support `ST_GeographyFromText`

@B4nan commenting it out leads to the following:
```
(node:58381) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Client_PG'
    |     property 'valueForUndefined' -> object with constructor 'Raw'
    --- property 'client' closes the circle
    at JSON.stringify (<anonymous>)
    at escapeObject (/home/niko/WebstormProjects/beach/mikro-orm/node_modules/knex/lib/dialects/postgres/index.js:86:19)
    at escapeFn (/home/niko/WebstormProjects/beach/mikro-orm/node_modules/knex/lib/query/string.js:47:18)
    at Client_PG.finalEscape [as _escapeBinding] (/home/niko/WebstormProjects/beach/mikro-orm/node_modules/knex/lib/query/string.js:18:12)
    at /home/niko/WebstormProjects/beach/mikro-orm/node_modules/knex/lib/client.js:145:19
    at String.replace (<anonymous>)
    at Client_PG._formatQuery (/home/niko/WebstormProjects/beach/mikro-orm/node_modules/knex/lib/client.js:137:16)
    at /home/niko/WebstormProjects/beach/mikro-orm/node_modules/knex/lib/interface.js:10:26
    at arrayMap (/home/niko/WebstormProjects/beach/mikro-orm/node_modules/lodash/lodash.js:639:23)
    at map (/home/niko/WebstormProjects/beach/mikro-orm/node_modules/lodash/lodash.js:9554:14)
    at Builder.Target.toQuery (/home/niko/WebstormProjects/beach/mikro-orm/node_modules/knex/lib/interface.js:9:12)
    at Builder.toString (/home/niko/WebstormProjects/beach/mikro-orm/node_modules/knex/lib/query/builder.js:72:17)
    at PostgreSqlConnection.getSql (/home/niko/WebstormProjects/beach/mikro-orm/dist/connections/AbstractSqlConnection.js:71:23)
    at PostgreSqlConnection.executeKnex (/home/niko/WebstormProjects/beach/mikro-orm/dist/connections/AbstractSqlConnection.js:63:26)
    at PostgreSqlConnection.execute (/home/niko/WebstormProjects/beach/mikro-orm/dist/connections/AbstractSqlConnection.js:31:31)
    at QueryBuilder.execute (/home/niko/WebstormProjects/beach/mikro-orm/dist/query/QueryBuilder.js:185:59)
    at PostgreSqlDriver.nativeInsert (/home/niko/WebstormProjects/beach/mikro-orm/dist/drivers/AbstractSqlDriver.js:61:43)
    at ChangeSetPersister.persistEntity (/home/niko/WebstormProjects/beach/mikro-orm/dist/unit-of-work/ChangeSetPersister.js:32:37)
    at ChangeSetPersister.persistToDatabase (/home/niko/WebstormProjects/beach/mikro-orm/dist/unit-of-work/ChangeSetPersister.js:20:20)
    at UnitOfWork.commitChangeSet (/home/niko/WebstormProjects/beach/mikro-orm/dist/unit-of-work/UnitOfWork.js:208:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at UnitOfWork.persistToDatabase (/home/niko/WebstormProjects/beach/mikro-orm/dist/unit-of-work/UnitOfWork.js:342:13)
(node:58381) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:58381) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by darkbasic** [comment]
Also, even if I was ok without the knex interpolation there is the following problem if I simply return a string:
```
insert into "location" ("city", "created_at", "geog", "id", "latitude", "longitude", "updated_at") values ('Osimo', '2020-03-25 09:29:51.452', 'ST_SetSRID(ST_MakePoint(13.478303, 43.489405),4326)', 8, 43.489405, 13.478303, '2020-03-25 09:29:51.481') returning "id"
```

Before the `ST_SetSRID` function it adds a `'` which breaks the query.
