### ISSUE TITLE
Maximum call stack size exceeded - ArrayType + TsMorphMetadataProvider + findAndCount - clone

### ISSUE THREAD

**Issue by ml1nk** [mikro-orm/mikro-orm#3720]
**Describe the bug**
When using findAndCount some properties of qb are cloned:

packages/knex/src/query/QueryBuilder.ts
~~~ts
    // clone array/object properties
    const properties = [
      'flags', '_populate', '_populateWhere', '_populateMap', '_joins', '_joinedProps', '_aliases', '_cond', '_data', '_orderBy',
      '_schema', '_indexHint', '_cache', 'subQueries', 'lockMode', 'lockTables',
    ];
    properties.forEach(prop => (qb as any)[prop] = Utils.copy(this[prop]));
~~~

Inside some of these properties is metadata (_aliases.c0.metadata for example) which also gets cloned (intentional?). In some cases it becomes a cycle until the stack size is exceeded. I tried to figure out when it occurs:

- TsMorphMetadataProvider is used
- ArrayType (any other customType?) is used by the entity
- The cache is disabled, invalid or deleted

Even if you activate the cache and restart orm by closing and init it again, it stils fails to clone metadata/customType.

**Stack trace**
```
 FAIL  tests/issues/GHXXXX.test.ts (164.932 s)
  GHXXXX
    ✕ call stack size exceeded (160270 ms)

  ● GHXXXX › call stack size exceeded

    DriverException: Maximum call stack size exceeded

       6 |   /* istanbul ignore next */
       7 |   convertException(exception: Error & Dictionary): DriverException {
    >  8 |     return new DriverException(exception);
         |            ^
       9 |   }
      10 |
      11 | }

      at PostgreSqlExceptionConverter.convertException (packages/core/src/platforms/ExceptionConverter.ts:8:12)
      at PostgreSqlExceptionConverter.convertException (packages/postgresql/src/PostgreSqlExceptionConverter.ts:48:18)
      at PostgreSqlDriver.convertException (packages/core/src/drivers/DatabaseDriver.ts:262:50)
      at packages/core/src/drivers/DatabaseDriver.ts:267:18
      previous RangeError: Maximum call stack size exceeded
      at _clone (packages/core/src/utils/clone.ts:13:18)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at packages/core/src/utils/clone.ts:81:28
          at Map.forEach (<anonymous>)
      at _clone (packages/core/src/utils/clone.ts:79:14)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at packages/core/src/utils/clone.ts:81:28
          at Map.forEach (<anonymous>)
      at _clone (packages/core/src/utils/clone.ts:79:14)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at packages/core/src/utils/clone.ts:81:28
          at Map.forEach (<anonymous>)
      at _clone (packages/core/src/utils/clone.ts:79:14)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at packages/core/src/utils/clone.ts:81:28
          at Map.forEach (<anonymous>)
      at _clone (packages/core/src/utils/clone.ts:79:14)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at packages/core/src/utils/clone.ts:81:28
          at Map.forEach (<anonymous>)
      at _clone (packages/core/src/utils/clone.ts:79:14)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at packages/core/src/utils/clone.ts:81:28
          at Map.forEach (<anonymous>)
      at _clone (packages/core/src/utils/clone.ts:79:14)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at _clone (packages/core/src/utils/clone.ts:104:27)
      at packages/core/src/utils/clone.ts:81:28
          at Map.forEach (<anonymous>)
      at _clone (packages/core/src/utils/clone.ts:79:14)
      at _clone (packages/core/src/utils/clone.ts:104:27)
```

**To Reproduce**
~~~ts
import { ArrayType, Entity, MikroORM, PrimaryKey, Property } from '@mikro-orm/core';
import type { PostgreSqlDriver } from '@mikro-orm/postgresql';
import { TsMorphMetadataProvider } from '@mikro-orm/reflection';


@Entity()
export class A {

  @PrimaryKey()
  id!: number;

  @Property({ type: ArrayType })
  types!: string[];

}

describe.only('GHXXXX', () => {

  let orm: MikroORM<PostgreSqlDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      cache: {
        enabled: false,
      },
      entities: [A],
      dbName: 'my-db-name',
      metadataProvider: TsMorphMetadataProvider,
      type: 'postgresql',
    });

    await orm.schema.refreshDatabase();
  });

  afterAll(() => orm.close(true));

  test('call stack size exceeded', async () => {

      await orm.em.findAndCount(A, 5);

  });
});
~~~

**Additional context**
Not from the test above but our productive code (TreeNodeEntity contains an ArrayType)

_aliases.c0.metadata.indexes.node.targetMeta.properties.types.customType.platform.config.cache...

![image](https://user-images.githubusercontent.com/4943440/201144022-001b0fe3-6a13-4055-bb64-0c84f1699e3e.png)
![image](https://user-images.githubusercontent.com/4943440/201144079-9cbd89c7-77a1-4711-b487-66ff135e66c7.png)

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 5.5.3 |
| pg | 8.8.0 |

**Comment by ml1nk** [comment]
I tried your change but there is still a call stack size exceeded when _joins is used in the same constellation.

On our codebase:
_joins.prop.name.targetMeta

Repro:
~~~ts
import { ArrayType, Entity, MikroORM, OneToOne, PrimaryKey, Property, Ref } from '@mikro-orm/core';
import type { PostgreSqlDriver } from '@mikro-orm/postgresql';
import { TsMorphMetadataProvider } from '@mikro-orm/reflection';


@Entity()
export class A {

  @PrimaryKey()
  id!: number;

  @Property({ type: ArrayType })
  types!: string[];

  @OneToOne()
  other!: Ref<B>;

}

@Entity()
export class B {

  @PrimaryKey()
  id!: number;

  @OneToOne({ mappedBy: 'other' })
  other!: Ref<A>;

}

describe.only('GHXXXX', () => {

  let orm: MikroORM<PostgreSqlDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      cache: {
        enabled: false,
      },
      entities: [A, B],
      dbName: 'my-db-name',
      metadataProvider: TsMorphMetadataProvider,
      type: 'postgresql',
    });

    await orm.schema.refreshDatabase();
  });

  afterAll(() => orm.close(true));

  test('no stackoverflow should occur', async () => {
      await orm.em.createQueryBuilder(A).leftJoin('other', 'other').getCount();
  });
});
~~~

**Comment by B4nan** [comment]
Oh right, I know what caused it, the platform on the custom type, otherwise, it was fine to clone the metadata instances.

**Comment by ml1nk** [comment]
It was fine to clone the metadata, but ist it needed? Even without cycle the metadata should be relativ constant and is rather large for a deep clone or am i missing something?

**Comment by B4nan** [comment]
Yeah, but that's much more complex refactoring, there are potentially many places like this. Feel free to send a PR, I will go with the simple way 🤷

**Comment by ml1nk** [comment]
That's more than enough for me, i lost hours here. I will try to create one, if i ever see it in the perf-tab.

**Comment by ml1nk** [comment]
It's working fine now. Thank you very much.
