### ISSUE TITLE
type: string[] - malformed array literal when setting a value that includes the character ","

### ISSUE THREAD

**Issue by Tronikelis** [mikro-orm/mikro-orm#3810]
**Describe the bug**
When updating the values of a property that is an array of strings, the orm does not escape "," which leads to breaking behavior. This is probably related to #3037

My property
```ts
@Property({ type: "string[]", default: defaults.options })
options = defaults.options;
```

Relevant failing query:
```
update "ExamSimQuestions" set "options" = '{Example optionadad,comma at the end,}', "updatedAt" = '2022-12-01T17:18:18.573Z' where "id" = 124
```

**Stack trace**
```
DriverException: update \"ExamSimQuestions\" set \"options\" = '{Example optionadad,Example text,Example text,Example text,,,,,}', \"updatedAt\" = '2022-12-01T16:56:35.435Z' where \"id\" = 124 - malformed array literal: \"{Example optionadad,Example text,Example text,Example text,,,,,}\"
    at PostgreSqlExceptionConverter.convertException (C:\\Users\\bdona\\Downloads\\coding\\tronikel.training-mikro-orm\ode_modules\\@mikro-orm\\core\\platforms\\ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException (C:\\Users\\bdona\\Downloads\\coding\\tronikel.training-mikro-orm\ode_modules\\@mikro-orm\\postgresql\\PostgreSqlExceptionConverter.js:42:22)
    at PostgreSqlDriver.convertException (C:\\Users\\bdona\\Downloads\\coding\\tronikel.training-mikro-orm\ode_modules\\@mikro-orm\\core\\drivers\\DatabaseDriver.js:192:54)
    at C:\\Users\\bdona\\Downloads\\coding\\tronikel.training-mikro-orm\ode_modules\\@mikro-orm\\core\\drivers\\DatabaseDriver.js:196:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgreSqlDriver.nativeUpdate (C:\\Users\\bdona\\Downloads\\coding\\tronikel.training-mikro-orm\ode_modules\\@mikro-orm\\knex\\AbstractSqlDriver.js:326:19)
    at async ChangeSetPersister.persistManagedEntity (C:\\Users\\bdona\\Downloads\\coding\\tronikel.training-mikro-orm\ode_modules\\@mikro-orm\\core\\unit-of-work\\ChangeSetPersister.js:137:21)
    at async ChangeSetPersister.executeUpdates (C:\\Users\\bdona\\Downloads\\coding\\tronikel.training-mikro-orm\ode_modules\\@mikro-orm\\core\\unit-of-work\\ChangeSetPersister.js:42:13)
    at async ChangeSetPersister.runForEachSchema (C:\\Users\\bdona\\Downloads\\coding\\tronikel.training-mikro-orm\ode_modules\\@mikro-orm\\core\\unit-of-work\\ChangeSetPersister.js:68:13)
    at async UnitOfWork.commitUpdateChangeSets (C:\\Users\\bdona\\Downloads\\coding\\tronikel.training-mikro-orm\ode_modules\\@mikro-orm\\core\\unit-of-work\\UnitOfWork.js:742:9)

previous error: update \"ExamSimQuestions\" set \"options\" = '{Example optionadad,Example text,Example text,Example text,,,,,}', \"updatedAt\" = '2022-12-01T16:56:35.435Z' where \"id\" = 124 - malformed array literal: \"{Example optionadad,Example text,Example text,Example text,,,,,}\"
    at Parser.parseErrorMessage (C:\\Users\\bdona\\Downloads\\coding\\tronikel.training-mikro-orm\ode_modules\\pg-protocol\\dist\\parser.js:287:98)
    at Parser.handlePacket (C:\\Users\\bdona\\Downloads\\coding\\tronikel.training-mikro-orm\ode_modules\\pg-protocol\\dist\\parser.js:126:29)
    at Parser.parse (C:\\Users\\bdona\\Downloads\\coding\\tronikel.training-mikro-orm\ode_modules\\pg-protocol\\dist\\parser.js:39:38)
    at Socket.<anonymous> (C:\\Users\\bdona\\Downloads\\coding\\tronikel.training-mikro-orm\ode_modules\\pg-protocol\\dist\\index.js:11:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**To Reproduce**
1. Create an entity with a property that has the type "string[]"
2. Try to insert values that have "," into the array
3. "," is not escaped, producing malformed array literal

**Expected behavior**
Every string in the array should be escaped, or at least the "," character

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 18.12.0 |
| typescript | 4.9.3 |
| mikro-orm | 5.5.3 |
| your-driver | postgres |

**Comment by B4nan** [comment]
This is rather about quoting the empty value, I don't think there is some magic escape sequence, I believe the literal should look like `{Example optionadad,Example text,Example text,Example text,"","","","",""}`.

**Comment by B4nan** [comment]
Not reproducible, lets reopen with a failing repro, here is my take:

```ts
import { Entity, OptionalProps, PrimaryKey, Property, SimpleLogger } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/postgresql';
import { mockLogger } from '../helpers';

@Entity()
class User {

  [OptionalProps]?: 'options';

  @PrimaryKey()
  id!: number;

  @Property({ type: 'string[]', default: ['foo'] })
  options = ['foo'];

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [User],
    dbName: 'mikro_orm_test_gh_3810',
    loggerFactory: options => new SimpleLogger(options),
  });
  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close();
});

test('3810', async () => {
  const mock = mockLogger(orm, ['query']);
  const u1 = orm.em.create(User, {});
  await orm.em.flush();

  u1.options.push('');
  u1.options.push('');
  u1.options.push('');
  await orm.em.flush();

  expect(mock.mock.calls).toEqual([
    ['[query] begin'],
    ['[query] insert into "user" ("options") values ($1) returning "id", "options"'],
    ['[query] commit'],
    ['[query] begin'],
    ['[query] update "user" set "options" = $1 where "id" = $2'],
    ['[query] commit'],
  ]);
});
```

**Comment by Tronikelis** [comment]
> Oh right, it's about the comma at the end, not empty value 🤦 I got confused by the repetition of commas in your example.

Yeah my bad, I wasn't sure how to convey the idea properly,
Thanks for fixing 👍
