### ISSUE TITLE
Unable to insert object with array of embeddables

### ISSUE THREAD

**Issue by bryan-vh** [mikro-orm/mikro-orm#3864]
**Describe the bug**
When trying to insert an object that contains an array of embeddables, it throws an error. When I remove the array of embeddables property from the entity, it then works (although throws a schema error since the property isn't present).

**Stack trace**
```
[Nest] 52499  - 12/21/2022, 4:06:27 PM     LOG [MikroORM] [query] insert into "profile" ("birthday", "ethnicity", "first_name", "gender", "last_name", "media", "platforms", "prompts", "user_id") values ('2000-01-23T01:23:45.678+09:00', 7, 'John', 0, 'Smith', '{a,b,c,d}', '{0,2,3}', '[{"prompt":"","answer":""},{"prompt":"","answer":""}]', 'sample') on conflict ("user_id") do update set "first_name" = excluded."first_name", "last_name" = excluded."last_name", "birthday" = excluded."birthday", "gender" = excluded."gender", "ethnicity" = excluded."ethnicity", "platforms" = excluded."platforms", "media" = excluded."media", "prompts" = excluded."prompts" returning "user_id" [took 3 ms]
[Nest] 52499  - 12/21/2022, 4:06:27 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'toJSON')
TypeError: Cannot read properties of undefined (reading 'toJSON')
    at /Users/bvanhorn/Documents/MB PRO 14/Link/link-backend/node_modules/@mikro-orm/core/serialization/EntityTransformer.js:101:73
    at Array.map (<anonymous>)
    at Function.processProperty (/Users/bvanhorn/Documents/MB PRO 14/Link/link-backend/node_modules/@mikro-orm/core/serialization/EntityTransformer.js:101:37)
    at /Users/bvanhorn/Documents/MB PRO 14/Link/link-backend/node_modules/@mikro-orm/core/serialization/EntityTransformer.js:50:43
    at Array.map (<anonymous>)
    at Function.toObject (/Users/bvanhorn/Documents/MB PRO 14/Link/link-backend/node_modules/@mikro-orm/core/serialization/EntityTransformer.js:45:14)
    at Profile.prototype.toJSON (/Users/bvanhorn/Documents/MB PRO 14/Link/link-backend/node_modules/@mikro-orm/core/entity/EntityHelper.js:26:62)
    at JSON.stringify (<anonymous>)
    at stringify (/Users/bvanhorn/Documents/MB PRO 14/Link/link-backend/node_modules/express/lib/response.js:1150:12)
    at ServerResponse.json (/Users/bvanhorn/Documents/MB PRO 14/Link/link-backend/node_modules/express/lib/response.js:271:14)
```

**To Reproduce**
1. Start my NestJS app with MikroORM
2. Fire Insomnia request to post route to create a dummy row in the DB (postgres)
3. Observe that insert throws an error

**Expected behavior**
Should insert entity into the DB.

**Additional context**

Profile entity:
```
@Entity()
export class Profile {
  @PrimaryKey()
  userId!: string;

  @Property()
  firstName!: string;

  @Property({ nullable: true })
  lastName?: string;

  @Property()
  birthday!: Date;

  @Enum(() => Gender)
  gender!: Gender;

  @Enum(() => Ethnicity)
  ethnicity!: Ethnicity;

  @Enum({ items: () => Platform, array: true })
  platforms!: Platform[];

  @Property()
  media!: string[];

  @Embedded(() => Prompt, { array: true })
  prompts!: Prompt[];
}
```

Prompt embeddable:
```
@Embeddable()
export class Prompt {
  @Property()
  prompt!: string;

  @Property()
  answer!: string;
}
```

Sample JSON from test request
```
{
	"userId": "sample",
	"firstName": "John",
	"lastName": "Smith",
	"birthday": "2000-01-23T01:23:45.678+09:00",
	"gender": 0,
	"ethnicity": 7,
	"platforms": [0, 2, 3],
	"media": ["a", "b", "c", "d"],
	"prompts": [
		{
			"prompt": "",
			"answer": ""
		},
		{
			"prompt": "",
			"answer": ""
		}
	]
}
```

Function calling upsert
```
async upsert(profile: Profile): Promise<Profile> {
    return this.repository.upsert(profile);
}
```

**Versions**

| Dependency | Version |
| - | - |
| node | v19.3.0 |
| typescript | v4.7.4 |
| mikro-orm | v5.6.1 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Not reproducible, here is a passing test case, lets reopen with a failing one.

```ts
import { Embeddable, Embedded, Entity, PrimaryKey, Property } from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/postgresql';

@Embeddable()
export class Prompt {

  @Property()
  prompt!: string;

  @Property()
  answer!: string;

}

@Entity()
export class Profile {

  @PrimaryKey()
  userId!: string;

  @Property()
  firstName!: string;

  @Property({ nullable: true })
  lastName?: string;

  @Property()
  birthday!: Date;

  @Embedded(() => Prompt, { array: true })
  prompts!: Prompt[];

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [Profile],
    dbName: `mikro_orm_3864`,
  });

  await orm.schema.refreshDatabase();
});

afterAll(() => orm.close(true));

test('3864', async () => {
  const user = await orm.em.upsert(Profile, {
    userId: 'sample',
    firstName: 'John',
    lastName: 'Smith',
    birthday: '2000-01-23T01:23:45.678+09:00',
    prompts: [
      {
        prompt: '',
        answer: '',
      },
      {
        prompt: '',
        answer: '',
      },
    ],
  });
  console.log(JSON.stringify(user));
});
```

**Comment by bryan-vh** [comment]
Okay, will look into NestJS docs to see if I'm missing something in parsing the body into the entity when receiving the request, thank you!
