### ISSUE TITLE
Source file not found when relative path contain multiple double-dot

### ISSUE THREAD

**Issue by bozorgmehr96** [mikro-orm/mikro-orm#3944]
**Describe the bug**
When relative path to source file contains multiple double-dots @mikro-orm/reflection is unable to find files.

**Stack trace**
```
[Nest] 48471  - 01/14/2023, 3:39:52 PM   ERROR [ExceptionHandler] Source file '../../shared/db/dist/src/entities/asset.entity.ts' not found. Check your 'entitiesTs' option and verify you have 'compilerOptions.declaration' enabled in your 'tsconfig.json'. If you are using webpack, see https://bit.ly/35pPDNn
MetadataError: Source file '../../shared/db/dist/src/entities/asset.entity.ts' not found. Check your 'entitiesTs' option and verify you have 'compilerOptions.declaration' enabled in your 'tsconfig.json'. If you are using webpack, see https://bit.ly/35pPDNn
    at TsMorphMetadataProvider.getSourceFile (/home/mohammad/workbench/odin/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:113:19)
    at TsMorphMetadataProvider.getExistingSourceFile (/home/mohammad/workbench/odin/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:31:28)
    at TsMorphMetadataProvider.getExistingSourceFile (/home/mohammad/workbench/odin/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:27:89)
    at async TsMorphMetadataProvider.readTypeFromSource (/home/mohammad/workbench/odin/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:64:24)
    at async TsMorphMetadataProvider.initPropertyType (/home/mohammad/workbench/odin/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:53:36)
    at async TsMorphMetadataProvider.initProperties (/home/mohammad/workbench/odin/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:38:17)
    at async TsMorphMetadataProvider.loadEntityMetadata (/home/mohammad/workbench/odin/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:23:9)
    at async MetadataDiscovery.discoverEntity (/home/mohammad/workbench/odin/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:225:9)
    at async MetadataDiscovery.discoverReferences (/home/mohammad/workbench/odin/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:164:13)
    at async MetadataDiscovery.findEntities (/home/mohammad/workbench/odin/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:91:9)
```

**Expected behavior**
Source file should be found regardless of how many steps its go up in directory

**Additional context**
The problem is regex of replace() in TsMorphMetadataProvider getSourceFile method.
Something like `/^\.+(\/\.+)*/` could fix this issue.

**Versions**

| Dependency | Version |
| - | - |
| node | 18.12.1 |
| typescript | 4.9.4 |
| mikro-orm | 5.6.4 |
| mikro-orm/reflection | 5.6.4 |
| @mikro-orm/postgresql | 5.6.4 |

**Comment by bozorgmehr96** [comment]
It could be solved with baseUrl.

**Comment by B4nan** [comment]
How was the problematic file named? By double-dot, do you mean two consecutive dots?

**Comment by Smona** [comment]
I wanted to try out svelte-kit with mikro, but i'm running into this bug as well. svelte-kit's [`$lib` alias](https://kit.svelte.dev/docs/modules#$lib) maps to a relative URL apparently, leading to errors like `Source file '../../../../src/lib/server/entities/index.ts' not found.`.

I would love to be able to follow svelte-kit's prescribed paradigms (idiosyncratic though they may be) while still using mikro-orm, so I hope this issue gets re-opened.

**Comment by B4nan** [comment]
Provide a reproduction and we can reopen.

**Comment by Smona** [comment]
My apologies, I think my issue was actually related to sveltekit using vite, which apparently does not support metadata reflection. I think this requirement could have been made a little more clear in the docs, but if I disable the `TsMorphMetadataProvider` and specify `type`s on my properties, I am able to use the ORM without issue. Sorry for the noise!

**Comment by B4nan** [comment]
Maybe you could leverage this in v6: https://github.com/mikro-orm/mikro-orm/pull/4167

Could be used locally as well if you treat it as a build step.

**Comment by enzolupia** [comment]
Thanks @B4nan , so no chances we can have this working with v5.8.5 ?

**Comment by B4nan** [comment]
I'll be happy to look into a complete reproduction, or accept a PR if you see a way to fix your problem.
