### ISSUE TITLE
After update from 5.3.1 to 5.6.8 insert leading to "syntax error at or near" when entity has array field marked as jsonb

### ISSUE THREAD

**Issue by QuestionAndAnswer** [mikro-orm/mikro-orm#3998]
**Describe the bug**

After update from 5.3.1 to 5.6.8.
Trying to make entity insert with an entity which has field of T[] set to empty array and explicitly marked as type: "jsonb" leading to insert error. Presumably when passing data to knex layer, as generated stack trace and sql query simply missing the value to be inserted into db.

**Stack trace**
```
SyntaxErrorException: insert into "parent" ("id", "field") values ('1927e1b5-171b-4b75-b7c2-2a9ba03708f4', ) returning "id" - syntax error at or near ")"
    at PostgreSqlExceptionConverter.convertException (/Users/user1/Projects/mikro-orm-bug/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:32:24)
    at PostgreSqlDriver.convertException (/Users/user1/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:197:54)
    at /Users/user1/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:201:24
    at processTicksAndRejections (/Users/user1/Projects/mikro-orm-bug/lib/internal/process/task_queues.js:96:5)
    at async PostgreSqlDriver.nativeInsertMany (/Users/user1/Projects/mikro-orm-bug/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:285:21)
    at async ChangeSetPersister.persistNewEntity (/Users/user1/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:85:21)
    at async ChangeSetPersister.executeInserts (/Users/user1/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:29:13)
    at async ChangeSetPersister.runForEachSchema (/Users/user1/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:68:13)
    at async UnitOfWork.commitCreateChangeSets (/Users/user1/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:715:9)
    at async UnitOfWork.persistToDatabase (/Users/user1/Projects/mikro-orm-bug/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:667:13)

previous error: insert into "parent" ("id", "field") values ('1927e1b5-171b-4b75-b7c2-2a9ba03708f4', ) returning "id" - syntax error at or near ")"
    at Parser.parseErrorMessage (/Users/user1/Projects/mikro-orm-bug/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/Users/user1/Projects/mikro-orm-bug/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/Users/user1/Projects/mikro-orm-bug/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/Users/user1/Projects/mikro-orm-bug/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (/Users/user1/Projects/mikro-orm-bug/lib/events.js:390:28)
    at Socket.emit (/Users/user1/Projects/mikro-orm-bug/lib/domain.js:475:12)
    at addChunk (/Users/user1/Projects/mikro-orm-bug/lib/internal/streams/readable.js:315:12)
    at readableAddChunk (/Users/user1/Projects/mikro-orm-bug/lib/internal/streams/readable.js:289:9)
    at Socket.Readable.push (/Users/user1/Projects/mikro-orm-bug/lib/internal/streams/readable.js:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {length: 90, name: 'SyntaxErrorException', severity: 'ERROR', code: '42601', detail: undefined, …}
```

**To Reproduce**

entity.ts
```typescript
import { Entity, PrimaryKey, Property } from "@mikro-orm/core";

@Entity()
export class Parent {
  @PrimaryKey()
  id!: string;

  @Property({ type: "jsonb" })
  field!: Record<string, string>[];
}
```

mikro-orm.config.ts
```typescript
import { defineConfig } from "@mikro-orm/postgresql";
import { TsMorphMetadataProvider } from "@mikro-orm/reflection";

export default defineConfig({
  entitiesTs: ["./src/entity.ts"],
  entities: ["./dist/entity.js"],
  dbName: "mikro-orm-test",
  user: "postgres",
  password: "admin",
  migrations: {
    path: "./dist/migrations",
    pathTs: "./src/migrations",
    allOrNothing: true,
    transactional: true,
    disableForeignKeys: false,
  },
  cache: {
    enabled: false,
  },
  metadataProvider: TsMorphMetadataProvider,
});
```

index.ts
```typescript
import { MikroORM } from "@mikro-orm/postgresql";
import mikroOrmConfig from "./mikro-orm.config";
import { Parent } from "./entity";
import { randomUUID } from "crypto";

MikroORM.init(mikroOrmConfig)
  .then(async (orm) => {
    await orm.getMigrator().up();
    return orm;
  })
  .then(async (orm) => {
    const em = orm.em.fork();

    const a = new Parent();
    a.id = randomUUID();
    a.field = [];

    em.persist(a);

    await em.flush();

    return orm;
  })
  .then(() => console.log("ok"))
  .catch((err) => console.error(err));
```

**Expected behavior**
Insertion is not failing.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 16.13.0 |
| typescript | 4.9.5 |
| mikro-orm | 5.6.8 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
It should be `type: 'json'`, the `type` is not the same as `columnType` - it serves rather for the JS/TS type name, e.g. `string` rather than `varchar`. 

Note that [`type: 'json'` means you use the `JsonType`](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/metadata/MetadataDiscovery.ts#L991-L993) which is needed to handle JSON arrays propertly. In postgres, this will result in [`jsonb` column type](https://github.com/mikro-orm/mikro-orm/blob/master/packages/postgresql/src/PostgreSqlPlatform.ts#L162-L164) automatically.

```ts
@Property({ type: "json" })
field!: Record<string, string>[];
```

**Comment by QuestionAndAnswer** [comment]
Hm. I get it. But, what the point of having 'jsonb' in type field available then?

**Comment by B4nan** [comment]
It is always used as a fallback for the column type, so technically what you do is setting only the column type, but the ORM does not understand it.

I'll try to support this out of box, you are not the first one struggling with this.

**Comment by QuestionAndAnswer** [comment]
Okay, thanks for explanation.

**Comment by B4nan** [comment]
Let's keep this open
