### ISSUE TITLE
Query error after assigning array of class-based DTOs to a collection with cascade

### ISSUE THREAD

**Issue by okovpashko** [mikro-orm/mikro-orm#4035]
**Describe the bug**
During the migration of my Nest.js project from TypeORM to MikroORM I stumbled upon an issue with getting a DB query error during the cascade updating of an entity with a `1:n` relation.

After spending hours reading the docs, trying the different approaches, and debugging I understood that the issue is caused by using class-based DTOs which is a quite popular approach in Nest.js.

One of my services has an `update` method that looks like that:
```typescript
  async update(id: number, updateEntityDto: UpdateAuthorDto): Promise<Author | null> {
    const entity = await this.authorsRepository.findOne(id);

    if (entity == null) {
      return null;
    }

    this.authorsRepository.assign(entity, updateEntityDto);
    await this.authorsRepository.persistAndFlush(entity);

    return entity;
  }
```

Where `UpdateAuthorDto` is a class-based DTO with the validation rules from `class-validator` package:
```typescript
class UpdateAuthorDto {
  @IsString()
  @IsNotEmpty()
  name!: string;

  @ValidateNested()
  @Type(() => UpdateBookDto)
  books!: UpdateBookDto[];
}
```
and the `UpdateBookDto` is also a class-based DTO:
```typescript
class UpdateBookDto {
  @IsNumber()
  @IsOptional()
  id?: number;

  @IsString()
  @IsNotEmpty()
  name: string;
}
```

The issue is not reproduced if I convert class-based DTOs to plain objects using `instanceToPlain()` function from `class-transformer` package beforehand:

```typescript 
    this.authorsRepository.assign(entity, {
      ...updateEntityDto,
      books: instanceToPlain(updateEntityDto.books),
    });
```

**Stack trace**
```
[10:59:18.664] ERROR: update "books" set "author_id" = 4 where "id" = '[object Object]' - invalid input syntax for type integer: "[object Object]"
    context: "ExceptionsHandler"
    err: {
      "type": "Error",
      "message": "update \"books\" set \"author_id\" = 4 where \"id\" = '[object Object]' - invalid input syntax for type integer: \"[object Object]\"",
      "stack":
          DriverException: update "books" set "author_id" = 4 where "id" = '[object Object]' - invalid input syntax for type integer: "[object Object]"
              at PostgreSqlExceptionConverter.convertException (myproject/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
              at PostgreSqlExceptionConverter.convertException (myproject/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:42:22)
              at PostgreSqlDriver.convertException (myproject/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:197:54)
              at myproject/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:201:24
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
              at PostgreSqlDriver.nativeUpdate (myproject/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:326:19)
              at ChangeSetPersister.persistManagedEntity (myproject/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:137:21)
              at ChangeSetPersister.executeUpdates (myproject/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:42:13)
              at ChangeSetPersister.runForEachSchema (myproject/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:68:13)
              at UnitOfWork.commitUpdateChangeSets (myproject/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:755:9)
          
          previous error: update "books" set "authors" = 4 where "id" = '[object Object]' - invalid input syntax for type integer: "[object Object]"
              at Parser.parseErrorMessage (myproject/node_modules/pg-protocol/src/parser.ts:369:69)
              at Parser.handlePacket (myproject/node_modules/pg-protocol/src/parser.ts:188:21)
              at Parser.parse (myproject/node_modules/pg-protocol/src/parser.ts:103:30)
              at Socket.<anonymous> (myproject/node_modules/pg-protocol/src/index.ts:7:48)
              at Socket.emit (node:events:527:28)
              at Socket.emit (node:domain:475:12)
              at addChunk (node:internal/streams/readable:315:12)
              at readableAddChunk (node:internal/streams/readable:289:9)
              at Socket.Readable.push (node:internal/streams/readable:228:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    }

```

**To Reproduce**
1. Create a `1:n` relation with cascading (`Cascade.ALL`). For example `Author` -> `Books`.
2. Create a class-based DTO for a Book relation.
3. Assign an array of book DTOs to an author.
4. Persist and flush author.

**Expected behavior**
The `books` collection is updated and persisted in DB as described in docs.

**Additional context**
The assignment result is the following:
```
Author {
  id: 4,
  name: 'John Doe',
  books: Collection<Book> {
    '0': (Book) { id: [UpdateBookDto], author: [Author] },
    initialized: true,
    dirty: true
  }
}

```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.15.1 |
| typescript | 4.9.5 |
| mikro-orm | 5.6.8 |
| your-driver | postgresql@5.6.8 |

**Comment by B4nan** [comment]
The problem here is that assign expects you to provide the payload as POJO. You can make your class act like a POJO when you extend the `PlainObject` from it.

```
import { PlainObject } from '@mikro-orm/core';

class UpdateBookDto extends PlainObject {
  // ...
}
```

**Comment by okovpashko** [comment]
Thank you for the explanation and the workaround. I confirm that it solves the issue and it's pretty easy to implement in my codebase because all the DTOs extend the abstract `BaseDto` that can be easily extended from the `PlainObject`.

BTW, assignment of a parent DTO (UpdateAuthorDto) to an entity works without issues so probably the `assignCollection()` method can be improved to handle such cases.

> The problem here is that assign expects you to provide the payload as POJO

Is this expectation reflected in the docs? It would be really helpful to have such a notice, probably highlighted as an important requirement.

Also, I would like to ask you to describe working with the assignments to properties that hold collections, especially the fact that the collection is merged and mention that it's easy to use together with cascading. This is a quite powerful feature and I was impressed when I realized that it's possible without any additional moves.

Despite my suggestions, the overall quality of the documentation is impressive. Thank you for that!

**Comment by B4nan** [comment]
> Is this expectation reflected in the docs? It would be really helpful to have such a notice, probably highlighted as an important requirement.

Probably not, and the `PlainObject` class is documented only for a different use case - as in filters it is the same story and that what why this class was added.

https://mikro-orm.io/docs/entity-manager#using-custom-classes-in-filterquery

> Also, I would like to ask you to describe working with the assignments to properties that hold collections, especially the fact that the collection is merged and mention that it's easy to use together with cascading. This is a quite powerful feature and I was impressed when I realized that it's possible without any additional moves.

Can you maybe prepare an example code and I would just comment on what it does in the docs? I am not entirely sure what you mean by this, so an example would help - give me something you would want to have mentioned in the docs.

**Comment by B4nan** [comment]
I'm afraid we will need to keep this as is, will add a section to the assign docs about it.
