### ISSUE TITLE
eager: true not working anymore with self-referenced entity

### ISSUE THREAD

**Issue by axotion** [mikro-orm/mikro-orm#4061]
**Describe the bug**
The problem is with parameter `eager: true`. If we have an entity with self-reference relationship and we want to load N levels (category with children category etc) with `eager: true` flag then in version 5 of mikroorm it doesn't work anymore

**Stack trace**
```
ERROR [ExceptionsHandler] Collection<Category> of entity Category[2] not initialized
                           | Error: Collection<Category> of entity Category[2] not initialized
                          |     at Collection.checkInitialized (/usr/src/app/node_modules/@mikro-orm/core/entity/Collection.js:302:19)
                           |     at Collection.count (/usr/src/app/node_modules/@mikro-orm/core/entity/Collection.js:152:14)
                          |     at Collection.get length [as length] (/usr/src/app/node_modules/@mikro-orm/core/entity/ArrayCollection.js:152:21)
...
```

**To Reproduce**
1. Create model
```
@Entity({
  customRepository: () => CategoryRepository
})
export class Category {
  @PrimaryKey()
  id: number;


  @ManyToOne(() => Category)
  parent: Category & NestedSetSubjectAbstract<Category>;

  @OneToMany({
    entity: () => Category,
    mappedBy: (category) => category.parent,
    cascade: [Cascade.ALL],
    orphanRemoval: true,
    eager: true
  })
  children = new Collection<Category>(
    this
  );
}
```
2. Try to load string entity with findOne method
3. You will get  "children: Collection<Category> { initialized: true, dirty: false }" at second nested level (name Newww Categorsdasdy)
4. 
![image](https://user-images.githubusercontent.com/7965436/220116242-f3a35b51-d9e1-4ddb-bdff-79ea3c06b3ff.png)
5. Categories hierarchy in DB
![image](https://user-images.githubusercontent.com/7965436/220115666-88e27100-c015-49ad-8ff4-4522b7435978.png)

**Expected behavior**
Initialized and loaded children collection at second and N levels

**Additional context**
Worked in version 4.x, doesn't work in 5.x

**Versions**

| Dependency | Version |
| - | - |
| node | 18 |
| mikro-orm | 5.6.11 |

**Comment by axotion** [comment]
Sure, here is whole reproduction as code

https://github.com/axotion/mikro-orm-4061-reproduction

All you have to do is run `docker-compose up` and the whole case will run. I've also added a comments to what was expected
