### ISSUE TITLE
orm.em.assign does not create references out of ids inside embeddables

### ISSUE THREAD

**Issue by ml1nk** [mikro-orm/mikro-orm#4106]
**Describe the bug**
The method orm.em.assign in opposite to orm.em.create does not create references out of ids if it is necessary inside an embeddable, see reproduction.

**Stack trace**
~~~
  console.error
    JIT runtime error: Cannot read properties of undefined (reading 'getPrimaryKey')
    
      function(entity) {
        const ret = {};
        if (typeof entity.id !== 'undefined') {
          ret.id = entity.id;
        }
      
        if (entity.b != null) {
          if (typeof entity.b !== 'undefined') {
            if (entity.b.c === null) {
              ret.b_c = null;
    >       } else if (typeof entity.b.c !== 'undefined') {
                                                   ^
              ret.b_c = toArray(entity.b.c.__helper.getPrimaryKey(true));
            }
          }
        
        }
      
        return ret;
      }

      984 |
      985 |         // eslint-disable-next-line no-console
    > 986 |         console.error(`JIT runtime error: ${e.message}\n\n${code}`);
          |                 ^
      987 |       }
      988 |
      989 |       throw e;

      at Function.callCompiledFunction (packages/core/src/utils/Utils.ts:986:17)
      at EntityComparator.prepareEntity (packages/core/src/utils/EntityComparator.ts:49:18)
      at ChangeSetComputer.computePayload (packages/core/src/unit-of-work/ChangeSetComputer.ts:104:34)
      at ChangeSetComputer.computeChangeSet (packages/core/src/unit-of-work/ChangeSetComputer.ts:44:56)
      at UnitOfWork.findNewEntities (packages/core/src/unit-of-work/UnitOfWork.ts:533:46)
      at UnitOfWork.computeChangeSets (packages/core/src/unit-of-work/UnitOfWork.ts:437:12)
      at UnitOfWork.doCommit (packages/core/src/unit-of-work/UnitOfWork.ts:333:12)
      at UnitOfWork.commit (packages/core/src/unit-of-work/UnitOfWork.ts:317:7)
      at SqlEntityManager.flush (packages/core/src/EntityManager.ts:1250:5)
      at Object.<anonymous> (tests/issues/GHXXXX.test.ts:72:7)
~~~

```
    TypeError: Cannot read properties of undefined (reading 'getPrimaryKey')

      at eval (eval at createFunction (packages/core/src/utils/Utils.ts:956:14), <anonymous>:15:47)
      at Function.callCompiledFunction (packages/core/src/utils/Utils.ts:967:14)
      at EntityComparator.prepareEntity (packages/core/src/utils/EntityComparator.ts:49:18)
      at ChangeSetComputer.computePayload (packages/core/src/unit-of-work/ChangeSetComputer.ts:104:34)
      at ChangeSetComputer.computeChangeSet (packages/core/src/unit-of-work/ChangeSetComputer.ts:44:56)
      at UnitOfWork.findNewEntities (packages/core/src/unit-of-work/UnitOfWork.ts:533:46)
      at UnitOfWork.computeChangeSets (packages/core/src/unit-of-work/UnitOfWork.ts:437:12)
      at UnitOfWork.doCommit (packages/core/src/unit-of-work/UnitOfWork.ts:333:12)
      at UnitOfWork.commit (packages/core/src/unit-of-work/UnitOfWork.ts:317:7)
      at SqlEntityManager.flush (packages/core/src/EntityManager.ts:1250:5)
      at Object.<anonymous> (tests/issues/GHXXXX.test.ts:72:7)
```

**To Reproduce**

~~~ts
import { Embeddable, Embedded, Entity, Ref, ManyToOne, MikroORM, PrimaryKey } from '@mikro-orm/core';
import type { PostgreSqlDriver } from '@mikro-orm/postgresql';

@Entity()
export class C {

  @PrimaryKey()
  id!: number;

}

@Embeddable()
export class B {

  @ManyToOne(() => C, { ref: true })
  c!: Ref<C>;

}

@Entity()
export class A {

  @PrimaryKey()
  id!: number;

  @Embedded(() => B)
  b!: B;

}


describe.only('GHXXXX', () => {

  let orm: MikroORM<PostgreSqlDriver>;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [A, B, C],
      dbName: 'my-db-name',
      type: 'postgresql',
    });

    await orm.schema.refreshDatabase();
  });

  afterAll(() => orm.close(true));

  test('orm.create.assign on embedded with reference', async () => {
    orm.em.create(A, {
      id: 1,
      b: {
        c: { id: 1 },
      },
    });

    orm.em.create(C, {
      id: 2,
    });

    await orm.em.flush();
    orm.em.clear();

    const a1 = await orm.em.find(A, {});

    expect(a1.length).toEqual(1);
    expect(a1[0].b.c.id).toEqual(1);

    orm.em.assign(a1[0], {
      b: {
        c: 2,
      },
    }); // a1[0].b.c === 2 instead of reference

    await orm.em.flush(); // TypeError: Cannot read properties of undefined (reading 'getPrimaryKey')

    orm.em.clear();
    expect(a1.length).toEqual(1);
    expect(a1[0].b.c.id).toEqual(2);
  });
});
~~~

**Versions**

| Dependency | Version |
| - | - |
| node |18.14.22 |
| typescript | 4.9.5 |
| mikro-orm | [549beec](https://github.com/mikro-orm/mikro-orm/commit/549beec69ed9b82ce48696985397bbc5aa68d2ce) |

**Comment by B4nan** [comment]
FYI you need to add `ref: true` to the decorator options here (or use ts-morph, which your test case is not doing). But that itself won't help, the issue remains the same.
