### ISSUE TITLE
compareObjects can't compare object created by Object.create(null)

### ISSUE THREAD

**Issue by filenwind** [mikro-orm/mikro-orm#4109]
**Describe the bug**
`compareObjects` can't compare object created by `Object.create(null)`

**Stack trace**
```javascript
TypeError: a.valueOf is not a function
    at compareObjects (/project/sandbox/node_modules/@mikro-orm/core/utils/Utils.js:30:18)
    at equals (/project/sandbox/node_modules/@mikro-orm/core/utils/Utils.js:102:16)
    at compareObjects (/project/sandbox/node_modules/@mikro-orm/core/utils/Utils.js:48:14)
    at equalTest (/project/sandbox/index.js:18:32)
    at Object.<anonymous> (/project/sandbox/index.js:27:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

**To Reproduce**
[https://codesandbox.io/p/sandbox/friendly-lovelace-bcvsxn?file=%2Findex.js](https://codesandbox.io/p/sandbox/friendly-lovelace-bcvsxn?file=%2Findex.js)

**Expected behavior**
Can compare object create by `Object.create(null)` successfully

**Additional context**

I open the issue  just in case you didn't see my reply at [here](https://github.com/mikro-orm/mikro-orm/discussions/4101#discussioncomment-5228760)

And yes, I also test other lib, ex: [lodash/isEqual](https://www.npmjs.com/package/lodash), [deep-equal](https://www.npmjs.com/package/deep-equal), [fast-deep-equal](https://www.npmjs.com/package/fast-deep-equal)

You can see `fast-deep-equal` has the same problem, but there have a [PR](https://github.com/epoberezkin/fast-deep-equal/pull/134) for this... although it didn't be merge yet...Orz...

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 5.6.13 |

Thanks for your help!

**Comment by B4nan** [comment]
There is one gotcha, and it is exactly why I asked you before to provide reproductions of your issue instead of comparisons of internals (like the `compareObjects` function) with other libraries.

I can easily fix the problem you report here, but it uncovers another - comparing `{}` with `Object.create(null)` will result in `false` - as they don't share the same prototype. The ORM won't hydrate your properties with `Object.create(null)`, so where are they coming from? So they can probably only occur on the side you control (entity property value).

```ts
compareObject(Object.create(null), {})
```

I guess you want this to pass too, right?

**Comment by filenwind** [comment]
Yes, I want that pass too, appreciate your help!
