### ISSUE TITLE
Entity with Embeddable fails on serialization if embeddable object exists in data on EntityRepository.create(data)

### ISSUE THREAD

**Issue by dginzbourg** [mikro-orm/mikro-orm#4158]
**Describe the bug**
If dto object contains embeddable property as an input to repository.create(dto), then this property isn't wrapped with helpers and serialize() fails with the exception below. 
 

**Stack trace**
```
TypeError: Cannot read properties of undefined (reading 'toJSON')
    at Function.processProperty (/Users/dginzbourg/repos/vcp-bulk/node_modules/@mikro-orm/core/serialization/EntitySerializer.js:114:56)
    at /Users/dginzbourg/repos/vcp-bulk/node_modules/@mikro-orm/core/serialization/EntitySerializer.js:58:30
    at Array.map (<anonymous>)
    at Function.serialize (/Users/dginzbourg/repos/vcp-bulk/node_modules/@mikro-orm/core/serialization/EntitySerializer.js:53:14)
    at /Users/dginzbourg/repos/vcp-bulk/node_modules/@mikro-orm/core/serialization/EntitySerializer.js:163:75
    at Array.map (<anonymous>)
    at serialize (/Users/dginzbourg/repos/vcp-bulk/node_modules/@mikro-orm/core/serialization/EntitySerializer.js:163:49)
    at DtoEntityConvertor.fromEntity (/Users/dginzbourg/repos/vcp-bulk/src/common/service-convert.transform.ts:28:26)
    at ListsService.create (/Users/dginzbourg/repos/vcp-bulk/src/routes/list/lists/lists.service.ts:72:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**To Reproduce**
1
```
@Embeddable()
export class ListSyncStatusEntityTest {
  @Property({ fieldName: 'sync_status_data_modified' })
  data_modified: boolean;
}

@Entity({
  tableName: `${DB_SCHEMA_LIST}.list`,
  customRepository: () => ListsRepositoryTest,
})
export class ListEntityTest {
  @PrimaryKey({ type: 'uuid', defaultRaw: 'uuid_generate_v4()', columnType: 'uuid' })
  id: string;

  @Embedded(() => ListSyncStatusEntityTest, {
    prefix: false,
  })
  sync_status: ListSyncStatusEntityTest;
}

```

2 
```
 dto = { sync_status: {data_modified: true}};
 entity = listsRepository.create(dto);
 await listsRepository.persistAndFlush(entity);
 dto = serialize(entity);
```
This code throws exception. What I see in the debugger that sync_status property is just JS object and not wrapped with entity helpers.

3 if I change the code to
```
 dto = {};
 entity = listsRepository.create(dto);
entity.sync_status.data_modified = true;
 await listsRepository.persistAndFlush(entity);
 dto = serialize(entity);
```
then it works and I see that sync_status property is wrapped after call to create().

**Expected behavior**
I'd expect that Embedded entity is wrapped even the object is provided in repository.create(). 

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 18.13.0|
| typescript |4.9.5 |
| mikro-orm | 5.6.15 |
| your-driver | @mikro-orm/postgresql 5.6.15 |

**Comment by dginzbourg** [comment]
I found the problem. I was using nestjs ```entity = plainToInstance(EntityClass, dto) to initialize ``` and then passing this object to orm.em.create(entity).
