### ISSUE TITLE
toJSON() with virtual property not working with "Date" type - MongoDB

### ISSUE THREAD

**Issue by nobodyshome** [mikro-orm/mikro-orm#4165]
**Describe the bug**
Apologies if i'm missing something, not entirely sure what the issue is and just taking my best guess. Struggling to find a solution both in the docs, googling & trial and error.
When serialising, it seems as if "Date" types become strings before any virtual properties have access to it as a Date, returning as a string, eg: "ISODate(<date>)". 

**Stack trace**
```
[Nest] 27656  - 25/03/2023, 21:18:30   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'toISOString')
TypeError: Cannot read properties of undefined (reading 'toISOString')
    at User.get joined [as joined] (E:\Projects\Civitas\api\src\entities\mongodb\user.entity.ts:40:28)
    at E:\Projects\Civitas\api\node_modules\.pnpm\@mikro-orm+core@5.6.15_nxexk2fpvn3lkq2gsfnfdthq2a\node_modules\@mikro-orm\core\serialization\EntityTransformer.js:66:73
    at Array.filter (<anonymous>)
    at Function.toObject (E:\Projects\Civitas\api\node_modules\.pnpm\@mikro-orm+core@5.6.15_nxexk2fpvn3lkq2gsfnfdthq2a\node_modules\@mikro-orm\core\serialization\EntityTransformer.js:66:14)
    at WrappedEntity.toObject (E:\Projects\Civitas\api\node_modules\.pnpm\@mikro-orm+core@5.6.15_nxexk2fpvn3lkq2gsfnfdthq2a\node_modules\@mikro-orm\core\entity\WrappedEntity.js:39:54)
    at User.toJSON (E:\Projects\Civitas\api\src\entities\mongodb\user.entity.ts:44:37)
    at JSON.stringify (<anonymous>)
    at serialize (E:\Projects\Civitas\api\node_modules\.pnpm\fastify@4.15.0\node_modules\fastify\lib\reply.js:869:15)
    at preserializeHookEnd (E:\Projects\Civitas\api\node_modules\.pnpm\fastify@4.15.0\node_modules\fastify\lib\reply.js:504:17)
    at preserializeHook (E:\Projects\Civitas\api\node_modules\.pnpm\fastify@4.15.0\node_modules\fastify\lib\reply.js:488:5)
```

**To Reproduce**
1. Have the following Schema:
```
  @Property()
  created_at: Date = new Date();

  @Property({ persist: false })
  get joined() {
    return this.created_at.toISOString().split('T')[0];
  }

  toJSON(strict = true, strip = ['_id', 'id', 'email', 'created_at', 'updated_at'], ...args: any[]): { [p: string]: any } {
    const object = wrap(this, true).toObject(...args);

    if (strict) {
      strip.forEach((exclude) => delete object[exclude]);
    }

    return object;
  }
```
2. Call `entity.toJSON()`

**Expected behavior**
In the schema above, "joined" should be able to access functions of "Date" from "created_at" instead for some reason "created_at" is a string. Not entirely sure if this is intended or bug. 

**Versions**
```
| Dependency         | Version |
| node               | 18.14.0 |
| typescript         | 4.9.5   |
| mikro-orm          | 9.3.12  |
| mikro-orm/mongodb  | 5.6.15  |
| mikro-orm/nestjs   | 5.1.7   |
```

**Comment by B4nan** [comment]
Are you sure the value is stored as a date object in the database, and not a string? This is all handled by the mongo driver, not by ORM, it does not convert string dates to data objects for mongo (not for most of the drivers actually). What do you see if you `console.log` that entity before you try to serialize it?

**Comment by nobodyshome** [comment]
Yeah, can confirm it's stored in the database as Date, the functions work on the entitiy itself.... `entity.created_at.toString()` works.

Before toJSON()
```
User {
  _id: ObjectId('641ea9ff744624ad76ad0157'),
  ......
  created_at: ISODate('2023-03-25T07:59:59.970Z'),
}
```

After toJSON()
```
{
  ........
  created_at: ISODate('2023-03-25T07:59:59.970Z'),
  joined: ISODate('2023-03-25T07:59:59.970Z')
}
```

With the following schema:
```
  @Property()
  created_at: Date = new Date();

  @Property({ persist: false })
  get joined() {
    return this.created_at; //.toISOString().split('T')[0];
  }

  toJSON(strict = true, strip = ['_id', 'id', 'email', 'updated_at'], ...args: any[]): { [p: string]: any } {
    const object = wrap(this, true).toObject(...args);

    if (strict) {
      strip.forEach((exclude) => delete object[exclude]);
    }

    return object;
  }
```

**Comment by B4nan** [comment]
Not reproducible, passing test:

```ts
import { Entity, MikroORM, PrimaryKey, Property, wrap } from '@mikro-orm/core';
import { MongoDriver } from '@mikro-orm/mongodb';

@Entity()
class User {

  @PrimaryKey()
  _id!: number;

  @Property()
  created_at: Date = new Date();

  @Property({ persist: false })
  get joined() {
    console.log(this.created_at instanceof Date, this.created_at);
    return this.created_at.toISOString().split('T')[0];
  }

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [User],
    dbName: 'db_4165',
    driver: MongoDriver,
  });
  await orm.schema.clearDatabase();
});

afterAll(async () => {
  await orm.close(true);
});

test(`GH issue 4165`, async () => {
  const u = new User();
  u._id = 123;
  await orm.em.persist(u).flush();
  orm.em.clear();
  const [r] = await orm.em.find(User, {});
  console.log(r);
  console.log(wrap(r).toObject());
});
```
