### ISSUE TITLE
Wrong select in with big int

### ISSUE THREAD

**Issue by alexhype17** [mikro-orm/mikro-orm#4227]
**Describe the bug**
Wrong select in with big int

**Stack trace**
```
error: select "item".*, "bids"."id" as "bids__id", "bids"."item_id" as "bids__item_id" from "item_entity" as "item" left join "bid_entity" as "bids" on "item"."id" = "bids"."item_id" where "item"."id" in 'select "item"."id" from (select "item"."id" from "item_entity" as "item" left join "bid_entity" as "bids" on "item"."id" = "bids"."item_id" group by "item"."id" limit 10) as "item"' - syntax error at or near "'select "item"."id" from (select "item"."id" from "item_entity" as "item" left join "bid_entity" as "bids" on "item"."id" = "bids"."item_id" group by "item"."id" limit 10) as "item"'"

      at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:369:69)
      at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:188:21)
      at Parser.parse (node_modules/pg-protocol/src/parser.ts:103:30)
      at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)
```

**To Reproduce**
```
import {
  Entity,
  LoadStrategy,
  SimpleLogger, OneToMany, ManyToOne, Collection, PrimaryKey, BigIntType,
} from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/postgresql';

@Entity()
class BidEntity {
  @PrimaryKey({ type: BigIntType })
  id!: string;

  @ManyToOne('ItemEntity', {
    serializer: value => value.id,
    serializedName: 'itemId',
  })
  item: any;
}

@Entity()
class ItemEntity {
  @PrimaryKey({ type: BigIntType })
  id!: string;

  @OneToMany('BidEntity', 'item', {
    orphanRemoval: true,
    strategy: LoadStrategy.JOINED,
    mappedBy: 'item',
  })
  bids = new Collection<BidEntity>(this);
}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    entities: [BidEntity, ItemEntity],
    loggerFactory: options => new SimpleLogger(options),
  });
  await orm.schema.refreshDatabase();
});

afterAll(() => orm.close(true));

test('select big int', async () => {
  await orm.em
    .createQueryBuilder(ItemEntity, 'item')
    .select('*')
    .leftJoinAndSelect('item.bids', 'bids')
    .limit(10)
    .getResultAndCount();
});
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.18.0 |
| typescript | 5.0.4 |
| mikro-orm | 5.6.16 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Fixed via https://github.com/mikro-orm/mikro-orm/commit/b789031300e752cfd9565371e7989776b18bd3a0
