### ISSUE TITLE
ColumnType: 'json' behaves differently from Type: 'json'

### ISSUE THREAD

**Issue by ladal1** [mikro-orm/mikro-orm#4229]
**Describe the bug**
A column marked with `columnType: "json"` (like json columns generated by entity generator) will not support json attribute querying as they should on `type: "json"`

**Stack trace**
One of the many thrown
```
JSON properties [mysql] › em.flush() with various JSON values

    DriverException: Invalid query condition: { value: { foo: 'test' } }

       6 |   /* istanbul ignore next */
       7 |   convertException(exception: Error & Dictionary): DriverException {
    >  8 |     return new DriverException(exception);
         |            ^
       9 |   }
      10 |
      11 | }

      at MySqlExceptionConverter.convertException (packages/core/src/platforms/ExceptionConverter.ts:8:12)
      at MySqlExceptionConverter.convertException (packages/mysql/src/MySqlExceptionConverter.ts:85:18)
      at MySqlDriver.convertException (packages/core/src/drivers/DatabaseDriver.ts:269:50)
      at packages/core/src/drivers/DatabaseDriver.ts:274:18
          at runMicrotasks (<anonymous>)
      at MySqlDriver.find (packages/knex/src/AbstractSqlDriver.ts:73:20)
      at MySqlDriver.findOne (packages/knex/src/AbstractSqlDriver.ts:97:17)
      at SqlEntityManager.findOne (packages/core/src/EntityManager.ts:472:18)
      at SqlEntityManager.findOneOrFail (packages/core/src/EntityManager.ts:515:16)
      at Object.<anonymous> (tests/features/custom-types/json-properties.test.ts:91:17)
```

**To Reproduce**
1. Replace https://github.com/mikro-orm/mikro-orm/blob/master/tests/features/custom-types/json-properties.test.ts#L12 with `@Property({ columnType: "json" })`
2. Run tests

**Expected behavior**
Test pass as the attribute querying works

**Additional context**
Discussed here: https://mikroorm.slack.com/archives/CFSAF8DEX/p1681395406810639

**Versions**

| Dependency | Version |
| - | - |
| node | 16.17.1 |
| typescript | 5.0.4 |
| mikro-orm | 5.0.0 (cloned latest) |

**Comment by B4nan** [comment]
Fixing this is rather simple, but if you use `json` column type instead of `jsonb`, it opens another problem - as a regular `json` column in postgres requires casting, otherwise you end up with errors like this:

```
select "u0".* from "user" as "u0" where "u0"."value" = '"test"' limit 1 - operator does not exist: json = unknown
```

Do you have an actual reason to use JSON instead of JSONB?

**Comment by ladal1** [comment]
I mean the issue where I encountered it was simply trying to query for json field value as here: https://mikro-orm.io/docs/json-properties, I aimed to get to this where condition in the query `"meta"->'nested'->>'foo' = '123'` which wouldn't work (and I was working over jsonb at the time)
