### ISSUE TITLE
`Cannot read properties of undefined (reading '__data')` on entity creation with one-to-one relation

### ISSUE THREAD

**Issue by denis-maiorov-brightsec** [mikro-orm/mikro-orm#4254]
**Describe the bug**
Creating and persisting entities with OneToOne relation on Entity that uses owning Entity primary key as their primary.
Worked with 5.5.0 version, fails with 5.6.16

**Stack trace**
```
/Users/domayorov/brightsec/mikro-orm-one-to-one-persist-bug/node_modules/@mikro-orm/core/entity/EntityHelper.js:174
            delete (0, wrap_1.helper)(other).__data[prop.name];
                                            ^

TypeError: Cannot read properties of undefined (reading '__data')
    at Function.propagateOneToOne (/Users/domayorov/brightsec/mikro-orm-one-to-one-persist-bug/node_modules/@mikro-orm/core/entity/EntityHelper.js:174:45)
    at Function.propagate (/Users/domayorov/brightsec/mikro-orm-one-to-one-persist-bug/node_modules/@mikro-orm/core/entity/EntityHelper.js:162:30)
    at OrderEntity.set [as summary] (/Users/domayorov/brightsec/mikro-orm-one-to-one-persist-bug/node_modules/@mikro-orm/core/entity/EntityHelper.js:145:30)
    at OrderEntity.set (/Users/domayorov/brightsec/mikro-orm-one-to-one-persist-bug/node_modules/@mikro-orm/core/entity/EntityHelper.js:81:41)
    at eval (eval at createFunction (/Users/domayorov/brightsec/mikro-orm-one-to-one-persist-bug/node_modules/@mikro-orm/core/utils/Utils.js:780:20), <anonymous>:13:22)
    at Function.callCompiledFunction (/Users/domayorov/brightsec/mikro-orm-one-to-one-persist-bug/node_modules/@mikro-orm/core/utils/Utils.js:791:20)
    at ObjectHydrator.hydrate (/Users/domayorov/brightsec/mikro-orm-one-to-one-persist-bug/node_modules/@mikro-orm/core/hydration/ObjectHydrator.js:26:23)
    at EntityFactory.hydrate (/Users/domayorov/brightsec/mikro-orm-one-to-one-persist-bug/node_modules/@mikro-orm/core/entity/EntityFactory.js:187:27)
    at EntityFactory.create (/Users/domayorov/brightsec/mikro-orm-one-to-one-persist-bug/node_modules/@mikro-orm/core/entity/EntityFactory.js:53:14)
    at SqlEntityManager.create (/Users/domayorov/brightsec/mikro-orm-one-to-one-persist-bug/node_modules/@mikro-orm/core/EntityManager.js:826:41)

```

**To Reproduce**
1. Create owning Entity and inverse Entity
2. Associate entities using OneToOne with inversed Entity using owning Entity id as primary key
3. Try to create new entity with prefilled primary keys and persist

Reproduction example: https://github.com/denis-maiorov-brightsec/mikro-orm-4254

**Expected behavior**
Both entities are persisted

**Additional context**
Runtime error shown in stack trace section

**Versions**

| Dependency | Version |
| - | - |
| node | 16 |
| typescript | 4.8.3 |
| mikro-orm | 5.6.16 |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Please provide complete reproduction as code, I need to see what exactly are you doing, how your entities are defined as well as the ORM configuration.

**Comment by denis-maiorov-brightsec** [comment]
@B4nan updated original comment, here's repo with reproduction https://github.com/denis-maiorov-brightsec/mikro-orm-4254
