### ISSUE TITLE
Using FindOptions<T> and EntityRepository<SomeModelWithAtLeastOneKey> together cause typescript to hang and crash

### ISSUE THREAD

**Issue by AmauryD** [mikro-orm/mikro-orm#4258]
**Describe the bug**
Using FindOptions<T> and EntityRepository<SomeModelWithAtLeastOneKey> together cause typescript to hang.
I do not have a clear description because the bug is really weird.

**Stack trace**
```
/Users/amauryd/Projects/minimal-repro/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:113984
      throw e;
      ^

RangeError: Maximum call stack size exceeded
    at createError (/Users/amauryd/Projects/minimal-repro/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:43479:23)
    at error (/Users/amauryd/Projects/minimal-repro/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:43483:24)
    at instantiateTypeWithAlias (/Users/amauryd/Projects/minimal-repro/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:57985:7)
    at instantiateType (/Users/amauryd/Projects/minimal-repro/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:57969:29)
    at instantiateIndexInfo (/Users/amauryd/Projects/minimal-repro/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:58101:42)
    at instantiateList (/Users/amauryd/Projects/minimal-repro/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:57617:24)
    at instantiateIndexInfos (/Users/amauryd/Projects/minimal-repro/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:57637:12)
    at resolveObjectTypeMembers (/Users/amauryd/Projects/minimal-repro/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:52491:20)
    at resolveTypeReferenceMembers (/Users/amauryd/Projects/minimal-repro/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:52524:5)
    at resolveStructuredTypeMembers (/Users/amauryd/Projects/minimal-repro/node_modules/.pnpm/typescript@5.0.4/node_modules/typescript/lib/tsc.js:53296:11)

Node.js v18.12.1
```

**To Reproduce**
Here is a reproduction repository : https://github.com/AmauryD/minimal-repro.

Use 
`pnpm i`
`pnpm tsc` # Typescript server should hang

I isolated the bug as much as possible.

**Expected behavior**
Typescript does not hang.

**Additional context**
Hangs in typescript 4.x or 5.x.
_**It works in Mikro-orm version <= 5.6.5.**_

**Versions**

| Dependency | Version |
| - | - |
| node | 18.12.1 |
| typescript | 5.0.4 |
| mikro-orm | >5.6.5 |

**Comment by B4nan** [comment]
Maybe better to report this directly to the TS repository?

**Comment by B4nan** [comment]
You should have the populate hint type argument, that way it will probably work:

```ts
function somethingReturningFindOptions<T, P extends string = never> (): FindOptions<T, P> {
  return {} as never
}
```

**Comment by AmauryD** [comment]
> 



> You should have the populate hint type argument, that way it will probably work:
> 
> ```ts
> function somethingReturningFindOptions<T, P extends string = never> (): FindOptions<T, P> {
>   return {} as never
> }
> ```

It does not. But using FindOneOptions seems to work.
I created the issue because it works in version 5.6.5 and older. I will probably create an issue in Typescript if the error is not on your side.

**Comment by B4nan** [comment]
Why do you want to use `FindOptions` in place of `FindOneOptions`? Those are a bit different, it's not just an extension, and it clearly messes up with the inference, I can see the T type arg is getting inferred as `string | UserModel | ExpandScalar<UserModel>[]` and that apparently makes the compiler explode. Even when I add the `extends object` constraint there.

The fact that it makes TS fail this way is almost certainly TS bug. I am testing with `--noEmit` and it results in heap out of memory:

```
➜  mikro-orm git:(master) ✗ yarn tsc-check-tests

<--- Last few GCs --->

[29318:0x128040000]    72559 ms: Mark-sweep 4042.6 (4136.0) -> 4026.9 (4136.0) MB, 1042.8 / 0.0 ms  (average mu = 0.110, current mu = 0.002) allocation failure; scavenge might not succeed
[29318:0x128040000]    73603 ms: Mark-sweep 4043.0 (4136.3) -> 4026.9 (4136.3) MB, 1041.4 / 0.0 ms  (average mu = 0.059, current mu = 0.002) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100c9c794 node::Abort() [/Users/adamek/Library/Application Support/fnm/node-versions/v18.13.0/installation/bin/node]
 2: 0x100c9c984 node::ModifyCodeGenerationFromStrings(v8::Local<v8::Context>, v8::Local<v8::Value>, bool) [/Users/adamek/Library/Application Support/fnm/node-versions/v18.13.0/installation/bin/node]
 3: 0x100def790 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/adamek/Library/Application Support/fnm/node-versions/v18.13.0/installation/bin/node]
 4: 0x100f9a704 v8::internal::EmbedderStackStateScope::EmbedderStackStateScope(v8::internal::Heap*, v8::internal::EmbedderStackStateScope::Origin, cppgc::EmbedderStackState) [/Users/adamek/Library/Application Support/fnm/node-versions/v18.13.0/installation/bin/node]
 5: 0x100f9e30c v8::internal::Heap::CollectSharedGarbage(v8::internal::GarbageCollectionReason) [/Users/adamek/Library/Application Support/fnm/node-versions/v18.13.0/installation/bin/node]
 6: 0x100f9b300 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [/Users/adamek/Library/Application Support/fnm/node-versions/v18.13.0/installation/bin/node]
 7: 0x100f98758 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/adamek/Library/Application Support/fnm/node-versions/v18.13.0/installation/bin/node]
 8: 0x100f8d490 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/adamek/Library/Application Support/fnm/node-versions/v18.13.0/installation/bin/node]
 9: 0x100f8dcc0 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/adamek/Library/Application Support/fnm/node-versions/v18.13.0/installation/bin/node]
10: 0x100f73af4 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/adamek/Library/Application Support/fnm/node-versions/v18.13.0/installation/bin/node]
11: 0x101303674 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/adamek/Library/Application Support/fnm/node-versions/v18.13.0/installation/bin/node]
12: 0x10164d04c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/adamek/Library/Application Support/fnm/node-versions/v18.13.0/installation/bin/node]
13: 0x10167dc04 Builtins_FastNewFunctionContextFunction [/Users/adamek/Library/Application Support/fnm/node-versions/v18.13.0/installation/bin/node]
14: 0x1070718b0 
15: 0x106cf72ac 
16: 0x10690e054 
17: 0x106eb6008 
18: 0x10691d7e0
...
```

**Comment by AmauryD** [comment]
It's because i have a function that converts a query object to a mikro-orm FindOptions. This function is used at multiples places when fetching data with the ORM using repository.findOne/repository.findAll/repository.findAndCount.

I casted FindOneOptions after the return of the function and it now works.

```
const user = await this.usersRepository.findOne(id, jsonApiQueryToFindOptions(query) as FindOneOptions<UserModel>);
```

Edit: 
This fixes the problem as well:

```
export function jsonApiQueryToFindOptions<T extends object> (jsonApiQuery: JsonApiQuery): FindOptions<T> {
```

_Ahhh these end users, always finding a way to use the library the worst way possible ...._

Thank you for taking your time to look at this bug ! I have plenty of options to get around this bug.
