### ISSUE TITLE
Extra update happens on flush() on entity with nullable json object when forceUndefined: true

### ISSUE THREAD

**Issue by dginzbourg** [mikro-orm/mikro-orm#4262]
**Describe the bug**
It's the same as described and fixed in https://github.com/mikro-orm/mikro-orm/issues/4078, just set `forceUndefined: true`.  

**Stack trace**
```
...
```

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 18.13.0|
| typescript | 4.7|
| mikro-orm | 5.7.0 |
| your-driver | postgresql|

**Comment by B4nan** [comment]
I need a complete reproduction, that issue you linked has a test case, when I enable `forceUndefined` in there, it is still passing.

**Comment by dginzbourg** [comment]
The reproduction is with sqllite drive, I think it's not relevant to specific driver

```
export class ParameterValueDto {
  name!: string;

  value!: string;
}

@Entity()
class ListEntityTest {
  @PrimaryKey({ autoincrement: true })
  id!: string;

  @Property()
  name!: string;

  @Property({ columnType: 'json', type: JsonType, nullable: true })
  params?: ParameterValueDto;
}

export class EntityOperationLogger implements EventSubscriber {
  async afterUpdate<T>(args: EventArgs<T>): Promise<void> {
    console.log('EntityOperationLogger', args);
  }
}

describe('Issue', () => {
  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      metadataProvider: TsMorphMetadataProvider,
      // entities: [EventEntityTest],
      entities: [ListEntityTest],
      dbName: ':memory:',
      driver: SqliteDriver,
      allowGlobalContext: true,
      debug: true,
      forceUtcTimezone: true,
      forceUndefined: true,
      useBatchInserts: true,
      useBatchUpdates: true,
      subscribers: [new EntityOperationLogger()],
    });
    await orm.schema.createSchema();
  });

  afterEach(async () => {
    await orm.schema.clearDatabase();
  });

  afterAll(() => orm.close(true));
}

  test('extra update on json object on flush', async () => {
    const expDto = {
      name: 'xxx',
      // params: { name: 'n', value: 'v' },
    };
    await orm.em.nativeInsert(ListEntityTest, expDto);
    const obj1 = await orm.em.findOne(ListEntityTest, { id: '1' });
    // const event = await orm.em.create(EventEntityTest, { name: 'ev' });
    await orm.em.flush();
  });

});
```

The output I get: 
```
  console.log
    [query] insert into `list_entity_test` (`name`) values ('xxx') returning `id` [took 9 ms]

      at DefaultLogger.log (node_modules/@mikro-orm/core/logging/DefaultLogger.js:31:14)

  console.log
    [query] select `l0`.* from `list_entity_test` as `l0` where `l0`.`id` = '1' limit 1 [took 0 ms]

      at DefaultLogger.log (node_modules/@mikro-orm/core/logging/DefaultLogger.js:31:14)

  console.log
    [query] begin

      at DefaultLogger.log (node_modules/@mikro-orm/core/logging/DefaultLogger.js:31:14)
  
console.log
    [query] update `list_entity_test` set `params` = NULL where `id` = 1 [took 0 ms]

      at DefaultLogger.log (node_modules/@mikro-orm/core/logging/DefaultLogger.js:31:14)

  console.log
    EntityOperationLogger {
      entity: ListEntityTest { id: 1, name: 'xxx', params: undefined },
      em: [EntityManager<1>],
      changeSet: ChangeSet<ListEntityTest> {
        entity: ListEntityTest { id: 1, name: 'xxx', params: undefined },
        type: 'update',
        payload: { params: undefined },
        name: 'ListEntityTest',
        rootName: 'ListEntityTest',
        collection: 'list_entity_test',
        schema: undefined,
        originalEntity: { id: 1, name: 'xxx', params: null },
        primaryKey: 1,
        persisted: true
      }
    }
```
