### ISSUE TITLE
docs: Create blank migration without entities

### ISSUE THREAD

**Issue by varunkamra** [mikro-orm/mikro-orm#4281]
I am using following conifg file:
```
import { Options } from "@mikro-orm/core";
import { constants } from "./constants";
import { PostgreSqlDriver } from "@mikro-orm/postgresql";
import { TSMigrationGenerator } from "@mikro-orm/migrations";

const config: Options = {
  dbName: constants.DB_NAME,
  user: constants.DB_USER,
  password: constants.DB_PASSWORD,
  port: constants.DB_PORT,
  host: constants.DB_HOST,
  entities: [],
  driver: PostgreSqlDriver, 
  migrations: {
    tableName: "mikro_orm_migrations",
    pathTs: "../migrations",
    emit: "ts",
    generator: TSMigrationGenerator,
    transactional: true,
  },
}

export default config;
```

I wish to create a blank migration file which I can use to create the tables before I write the entities. Also, I don't plan to use a schema and put tables directly in the postgres database created. 

I get the following error when I run the command to create a blank migration
```
./node_modules/.bin/mikro-orm migration:create --blank
mikro-orm migration:create

Create new migration with current schema diff

Options:
  -b, --blank    Create blank migration                                [boolean]
  -i, --initial  Create initial migration                              [boolean]
  -d, --dump     Dumps all queries to console                          [boolean]
  -p, --path     Sets path to directory where to save entities          [string]
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]

Error: No entities found, please use `entities` option
    at Configuration.validateOptions (/var/www/node_modules/@mikro-orm/core/utils/Configuration.js:226:19)
    at new Configuration (/var/www/node_modules/@mikro-orm/core/utils/Configuration.js:29:18)
    at Function.getConfiguration (/var/www/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:38:24)
    at async Function.getORM (/var/www/node_modules/@mikro-orm/cli/CLIHelper.js:22:25)
    at async Function.handleMigrationCommand (/var/www/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:73:21)

```

Packages being used:
```
    "@mikro-orm/cli": "^5.7.2",
    "@mikro-orm/core": "^5.7.2",
    "@mikro-orm/migrations": "^5.7.2",
    "@mikro-orm/postgresql": "^5.7.2",
```

**Comment by B4nan** [comment]
You can disable that validation

```ts
MikroORM.init({
  discovery: {
    warnWhenNoEntities: false,
  },
});
```

https://mikro-orm.io/docs/configuration#entity-discovery

**Comment by varunkamra** [comment]
A schema is actually a collection of tables :)

**Comment by varunkamra** [comment]
@B4nan I updated my mikro-orm.config.ts file for the cli to be this:

```
import { constants } from "./constants";
import { MikroORM, PostgreSqlDriver } from "@mikro-orm/postgresql";
import { TSMigrationGenerator } from "@mikro-orm/migrations";

const config = MikroORM.init({
  discovery: {
    warnWhenNoEntities: false,
  },
  dbName: constants.DB_NAME,
  user: constants.DB_USER,
  password: constants.DB_PASSWORD,
  port: constants.DB_PORT,
  host: constants.DB_HOST,
  entities: [],
  driver: PostgreSqlDriver, 
  type: 'postgresql',
  migrations: {
    tableName: "mikro_orm_migrations",
    pathTs: "../migrations",
    emit: "ts",
    generator: TSMigrationGenerator,
    transactional: true,
  },
});

export default config;
```
When I run the migrate create command again I get this error:

```
./node_modules/.bin/mikro-orm migration:create --blank
mikro-orm migration:create

Create new migration with current schema diff

Options:
  -b, --blank    Create blank migration                                [boolean]
  -i, --initial  Create initial migration                              [boolean]
  -d, --dump     Dumps all queries to console                          [boolean]
  -p, --path     Sets path to directory where to save entities          [string]
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]

Error: No platform type specified, please fill in `type` or provide custom driver class in `driver` option. Available platforms types: [
  'mongo',
  'mysql',
  'mariadb',
  'postgresql',
  'sqlite',
  'better-sqlite'
]
    at Configuration.validateOptions (/var/www/node_modules/@mikro-orm/core/utils/Configuration.js:217:19)
    at new Configuration (/var/www/node_modules/@mikro-orm/core/utils/Configuration.js:29:18)
    at Function.getConfiguration (/var/www/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:38:24)
    at async Function.getORM (/var/www/node_modules/@mikro-orm/cli/CLIHelper.js:22:25)
    at async Function.handleMigrationCommand (/var/www/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:73:21)
```

**Comment by varunkamra** [comment]
Oh actually I had to use this in the config file instead:

```
import { Options } from "@mikro-orm/core";
import { constants } from "./constants";
import { PostgreSqlDriver } from "@mikro-orm/postgresql";
import { TSMigrationGenerator } from "@mikro-orm/migrations";

const config: Options = {
  dbName: constants.DB_NAME,
  user: constants.DB_USER,
  password: constants.DB_PASSWORD,
  port: constants.DB_PORT,
  host: constants.DB_HOST,
  entities: [],
  driver: PostgreSqlDriver, 
  migrations: {
    tableName: "mikro_orm_migrations",
    pathTs: "../migrations",
    emit: "ts",
    generator: TSMigrationGenerator,
    transactional: true,
  },
  discovery: {
    warnWhenNoEntities: false,
  },
}

export default config;
```

It worked successfully this time, thank you for your help!
