### ISSUE TITLE
extra update statement on entity with embeddable on persistAndFlush() when cached query is used

### ISSUE THREAD

**Issue by dginzbourg** [mikro-orm/mikro-orm#4295]
**Describe the bug**
extra update statement when query hits the cache and the cached entity has embeddable. 

**Stack trace**
the 2nd call to a.f() produces (snippet only from the 2nd call):
```
 console.log
    [query] begin

      at DefaultLogger.log (node_modules/@mikro-orm/core/logging/DefaultLogger.js:31:14)

  console.log
    [query] insert into `aentity` (`id`, `start_at`) values (5, 1682884980723) returning `id` [took 0 ms]

      at DefaultLogger.log (node_modules/@mikro-orm/core/logging/DefaultLogger.js:31:14)

  console.log
    [query] update `aentity` set `start_at` = 1682884980698 where `id` = 1 [took 0 ms]

      at DefaultLogger.log (node_modules/@mikro-orm/core/logging/DefaultLogger.js:31:14)

EntityOperationLogger {
  entity: AEntity {
    id: 1,
    schedule: RunScheduleEntity { start_at: 2023-04-30T20:03:00.698Z }
  },
  em: [EntityManager<6>],
  changeSet: ChangeSet<AEntity> {
    entity: AEntity { id: 1, schedule: [RunScheduleEntity] },
    type: 'update',
    payload: { schedule: undefined, start_at: 2023-04-30T20:03:00.698Z },
    name: 'AEntity',
    rootName: 'AEntity',
    collection: 'aentity',
    schema: undefined,
    originalEntity: { id: 1, schedule: [Object] },
    primaryKey: 1,
    persisted: true
  }
}
  console.log
    [query] commit

      at DefaultLogger.log (node_modules/@mikro-orm/core/logging/DefaultLogger.js:31:14)

```

**To Reproduce**
```
@Embeddable()
class RunScheduleEntity {
  @Property({ type: Date })
  start_at!: Date;

  @Property({ type: Date, nullable: true })
  end_at?: Date;
}
@Entity()
export class AEntity {
  @PrimaryKey({ autoincrement: true })
  id!: number;

  @Embedded({
    entity: () => RunScheduleEntity,
    prefix: false,
  })
  schedule: RunScheduleEntity;
}

export class EntityOperationLogger implements EventSubscriber {
  async afterUpdate<T>(args: EventArgs<T>): Promise<void> {
    console.log('EntityOperationLogger', args);
  }
}

class Processor {
  private lastId = 4;

  constructor(readonly orm: MikroORM) {}

  @UseRequestContext()
  async f() {
    const em = this.orm.em;

// ---> if you remove "cache" , it works correctly
    await em.findOne(AEntity, { id: 1 }, { cache: 1000 });
    const entity = await em.create(AEntity, { id: this.lastId++, schedule: { start_at: new Date() } });
    await em.persistAndFlush(entity);
  }
}

describe('Issue', () => {
  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      metadataProvider: TsMorphMetadataProvider,
      // entities: [EventEntityTest],
      entities: [AEntity],
      dbName: ':memory:',
      driver: SqliteDriver,
      allowGlobalContext: true,
      debug: true,
      batchSize: 1000,
      forceUtcTimezone: true,
      forceUndefined: true,
      useBatchInserts: true,
      useBatchUpdates: true,
      cache: { options: { cacheDir: 'dist' } },
      subscribers: [new EntityOperationLogger()],
    });
    await orm.schema.createSchema();
  });

  afterEach(async () => {
    await orm.schema.clearDatabase();
  });

  afterAll(() => orm.close(true));

  test('create entity', async () => {
    let entity = await orm.em.create(AEntity, { id: 1, schedule: { start_at: new Date() } });
    await orm.em.persistAndFlush([entity]);
    const a = new Processor(orm);
    await a.f();
    await a.f();
  });
});
```

**Expected behavior**

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 18.3.0|
| typescript | 4.7 |
| mikro-orm | 5.7.3|
| your-driver | NA |

**Comment by dginzbourg** [comment]
Thank you for quick fix :)
