### ISSUE TITLE
Unable to use database provided default value for primary key

### ISSUE THREAD

**Issue by agstrc** [mikro-orm/mikro-orm#4348]
**Describe the bug**
An exception occurs when attempting to create an entity which has a database provided default value for its primary key.

**Stack trace**
```
JIT runtime error: Cannot read properties of undefined (reading 'id')

  function(entity, data, factory, newEntity, convertCustomTypes, schema) {
>   if (typeof data.id !== 'undefined') entity.id = data.id;
                   ^
  }
TypeError: Cannot read properties of undefined (reading 'id')
    at eval (eval at createFunction (/home/davi/globo/colab-v4/campaigns-new/node_modules/@mikro-orm/core/utils/Utils.js:793:20), <anonymous>:6:19)
    at Function.callCompiledFunction (/home/davi/globo/colab-v4/campaigns-new/node_modules/@mikro-orm/core/utils/Utils.js:804:20)
    at ObjectHydrator.hydrate (/home/davi/globo/colab-v4/campaigns-new/node_modules/@mikro-orm/core/hydration/ObjectHydrator.js:28:23)
    at ChangeSetPersister.reloadVersionValues (/home/davi/globo/colab-v4/campaigns-new/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:284:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChangeSetPersister.persistNewEntity (/home/davi/globo/colab-v4/campaigns-new/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:94:13)
    at async ChangeSetPersister.executeInserts (/home/davi/globo/colab-v4/campaigns-new/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:29:13)
    at async ChangeSetPersister.runForEachSchema (/home/davi/globo/colab-v4/campaigns-new/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:68:13)
    at async UnitOfWork.commitCreateChangeSets (/home/davi/globo/colab-v4/campaigns-new/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:722:9)
    at async UnitOfWork.persistToDatabase (/home/davi/globo/colab-v4/campaigns-new/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:688:13)
```

**To Reproduce**
1. Create an entity that uses a `defaultRaw` value for its primary key:
```ts
import { Entity, PrimaryKey, Property } from '@mikro-orm/core';

@Entity()
export class ExampleEntity {
  @PrimaryKey({ type: 'uuid', defaultRaw: '(uuid())' })
  id!: string;

  @Property()
  someField!: string;
}
```
2. Attempt to persist entity
```ts
import { MikroORM } from '@mikro-orm/core';

import { ExampleEntity } from './entity';
import ormConfig from './mikro-orm.config';

void main();

async function main() {
  const orm = await MikroORM.init(ormConfig);
  const em = orm.em.fork();

  const exampleEntity = em.create(ExampleEntity, {
    someField: 'some value',
  });
  await em.persistAndFlush(exampleEntity);
}
```
3. Exception (as described above) occurs

**Expected behavior**
The value should be persisted to the database with its ID defined by the database.

**Additional context**
With debug enabled, the root cause is clear.
```
[info] MikroORM successfully connected to database root on mysql://root:*****@localhost:3306
[query] select 1 from information_schema.schemata where schema_name = 'root' [took 2 ms]
[query] show variables like 'auto_increment_increment' [took 3 ms]
[query] begin
[query] insert into `example_entity` (`some_field`) values ('some value') [took 1 ms]
[query] select `e0`.`id` from `example_entity` as `e0` where `e0`.`id` in (NULL) [took 1 ms]
```
It attempts to query the entity with ID set to null.

The issue is not quite severe, as simply providing a runtime default value is enough to fix it
```ts
import { Entity, PrimaryKey, Property } from '@mikro-orm/core';
import { v1 } from 'uuid';

@Entity()
export class ExampleEntity {
  @PrimaryKey({ type: 'uuid', defaultRaw: '(uuid())' })
  id = v1(); // v1 as that is the same UUID version mysql uses

  @Property()
  someField!: string;
}
```
Although, by doing that, you lose the ability to have database provided default values (which, as previously stated, isn't a _severe_ issue, but I believe it's still a valid use case)

**Versions**

| Dependency | Version |
| - | - |
| node | 18.15.0 |
| typescript | 4.9.5 |
| mikro-orm | 5.7.5 |
| mysql2 | 3.3.0 |

**Comment by B4nan** [comment]
Looks like this won't be possible with mysql at all, so marking it as wontfix. There seems to be no way to get the just-created UUID when it comes from the database default, as there are no returning statements and MySQL will return only auto-increment columns as the insert query result.

https://stackoverflow.com/questions/54289411/nodejs-mysql-results-insertid-always-0-when-the-table-id-is-a-uuid
