### ISSUE TITLE
Inserting a OneToOne relation with composite PK throws an error if the non-owning entity has a DB-default value

### ISSUE THREAD

**Issue by RDSM-CM** [mikro-orm/mikro-orm#4377]
**Describe the bug**
MikroORM throws an error when trying to insert an entity that includes a `@OneToOne` foreign key which is also a composite primary key. The issue seems to occur when MikroORM tries to reload the inserted non-owning entity to hydrate its database-set default values.

This bug appeared in MikroORM 5.7.8 and was not present in MikroORM 5.7.7.

**To Reproduce**

```ts
import {
  Cascade,
  Entity,
  MikroORM,
  OneToOne,
  PrimaryKey,
  PrimaryKeyType,
  Property,
  Ref,
} from "@mikro-orm/core"
import { MySqlDriver } from "@mikro-orm/mysql"
import { randomUUID } from "crypto"

@Entity()
export class NonRoot {
  @PrimaryKey()
  public id!: string

  @OneToOne(() => Root, {
    owner: true,
    primary: true,
    ref: true,
  })
  public root!: Ref<Root>

  public [PrimaryKeyType]?: [string, string]
}

@Entity()
export class Root {
  @PrimaryKey()
  public id!: string

  @Property({
    defaultRaw: "CURRENT_TIMESTAMP",
  })
  public createdAt?: Date

  @OneToOne(() => NonRoot, (nonRoot) => nonRoot.root, {
    cascade: [Cascade.ALL],
  })
  public nonRoot!: NonRoot
}

describe("MikroORM 5.7.8 OneToOne bug reproduction", () => {
  let orm: MikroORM

  before(async () => {
    orm = await MikroORM.init<MySqlDriver>({
      driver: MySqlDriver,
      //... DB connection info
      entities: [Root, NonRoot],
    })

    const gen = orm.getSchemaGenerator()
    await gen.refreshDatabase()
  })

  after(async () => {
    await orm.close(true)
  })

  it("persistAndFlush() should cascade-insert a Root entity and its related NonRoot entity", async () => {
    const nonRoot = new NonRoot()
    nonRoot.id = randomUUID()

    const root = new Root()
    root.id = randomUUID()
    root.nonRoot = nonRoot

    const em = orm.em.fork()

    await em.persistAndFlush(root)
  })
})
```

**Expected behavior**
The entities are inserted into the database.

**Actual behavior**
`em.persistAndFlush()` throws an error:
```
ValidationError: Value for NonRoot.root is required, 'null' found
entity: NonRoot { id: '8af10287-1393-473a-b446-417b89597d71', root: null }
      at Function.propertyRequired (node_modules/@mikro-orm/core/errors.js:68:16)
      at EntityValidator.validateRequired (node_modules/@mikro-orm/core/entity/EntityValidator.js:49:48)
      at ChangeSetPersister.processProperties (node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:82:28)
      at /app/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:26:46
      at Array.forEach (<anonymous>)
      at ChangeSetPersister.executeInserts (node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:26:20)
      at ChangeSetPersister.runForEachSchema (node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:70:48)
      at ChangeSetPersister.executeInserts (node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:21:25)
      at UnitOfWork.commitCreateChangeSets (node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:729:39)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async UnitOfWork.persistToDatabase (node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:695:13)
      at async MySqlConnection.transactional (node_modules/@mikro-orm/knex/AbstractSqlConnection.js:36:25)
      at async UnitOfWork.doCommit (node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:295:17)
      at async UnitOfWork.commit (node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:268:13)
      at async SqlEntityManager.flush (node_modules/@mikro-orm/core/EntityManager.js:998:9)
      at async SqlEntityManager.persistAndFlush (node_modules/@mikro-orm/core/EntityManager.js:943:9)
      at async Context.<anonymous> (src/__unitTests__/mikroOrmTest.spec.ts:79:5)
```

**Additional information**
Removing `primary: true` from the relation decorator of `NonRoot.root` results in successful insertion.

Removing the database-default `defaultRaw: "CURRENT_TIMESTAMP"` from the `Root.createdAt` property (and initializing the property when creating the entity) results in successful insertion even when `NonRoot.root` has `primary: true`.

**Versions**
| Dependency | Version |
|---|---|
| node | 14.17.3
| typescript | 5.0.4
| @mikro-orm/core | 5.7.8
| @mikro-orm/mysql | 5.7.8

**Comment by B4nan** [comment]
An interesting bug that got uncovered by a totally unrelated change, the mapping of results always considered composite FKs as `null` when there is no value, so including cases when the FK wasn't selected. The query that was selecting the default values after insertion was wiping the FK.
