### ISSUE TITLE
insertMany is not reading `schema` option

### ISSUE THREAD

**Issue by wayn3r** [mikro-orm/mikro-orm#4424]
**Describe the bug**
If I try to use `EntityManager.insertMany` method, with `{ schema: "<<runtime calculated valid schema>>" }`, the schema option is ignore

**Stack trace**
```
at PostgreSqlExceptionConverter.convertException ("<base-dir>"\node_modules\.pnpm\@mikro-orm+postgresql@5.7.11_@mikro-orm+core@5.7.11\node_modules\@mikro-orm\postgresql\PostgreSqlExceptionConverter.js:38:24)
    at PostgreSqlDriver.convertException ("<base-dir>"\node_modules\.pnpm\@mikro-orm+core@5.7.11_zmp53sb22yqva5imfl74cthtbm\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:197:54)
    at "<base-dir>"\node_modules\.pnpm\@mikro-orm+core@5.7.11_zmp53sb22yqva5imfl74cthtbm\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:201:24
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PostgreSqlDriver.nativeInsertMany ("<base-dir>"\node_modules\.pnpm\@mikro-orm+knex@5.7.11_timz64mvbvdsmbdwuyrjmo7tfa\node_modules\@mikro-orm\knex\AbstractSqlDriver.js:303:21)
    at ChangeSetPersister.persistNewEntity ("<base-dir>"\node_modules\.pnpm\@mikro-orm+core@5.7.11_zmp53sb22yqva5imfl74cthtbm\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:85:21)
    at ChangeSetPersister.executeInserts ("<base-dir>"\node_modules\.pnpm\@mikro-orm+core@5.7.11_zmp53sb22yqva5imfl74cthtbm\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:29:13)
    at ChangeSetPersister.runForEachSchema ("<base-dir>"\node_modules\.pnpm\@mikro-orm+core@5.7.11_zmp53sb22yqva5imfl74cthtbm\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:68:13)
    at SqlEntityManager.insertMany ("<base-dir>"\node_modules\.pnpm\@mikro-orm+core@5.7.11_zmp53sb22yqva5imfl74cthtbm\node_modules\@mikro-orm\core\EntityManager.js:784:13)
```

**To Reproduce**
1. Create an Entity with the schema set to  `*`, e.g.: `CustomerEntity`
2. Create a list of instances of that entity, e.g.: `const customers = [new CustomerEntity(), new CustomerEntity()]`
3. Use the entity manager to insert them all, `em.insertMany(CustomerEntity, customers, { schema: "<<runtime calculated valid schema>>" })`

**Expected behavior**
This should insert all customers with the given schema

**Versions**

| Dependency | Version |
| ---------------|---------|
| @mikro-orm/core | 5.7.11 |
| @mikro-orm/postgresql | 5.7.11 |
| node | v18.12.1 |
| typescript | 4.9.5 |

**Comment by B4nan** [comment]
The option should be taken into account only for POJOs, so `em.nativeInsert(Entity, [data1, data])`, not for existing instances - for those you need to set them via `wrap(entity).setSchema(schema)` or create the instances via `em.create(Entity, data, { schema })`. But the POJO signature will do that for you in one step:

```ts
await em.nativeInsert(CustomerEntity, [{}, {}]);
```

Let me know if that works.

**Comment by wayn3r** [comment]
@B4nan this didn't work for me, `nativeInsert` doesn't accept an array as second argument it has to be a single entity.
But I solved this with a workaround, I just used `repository.upsertMany` instead. This method does use the `schema`.  I think the `insertMany` should also do it.

**Comment by B4nan** [comment]
Sorry, it's `insertMany`, not `nativeInsert`, I must have copy pasted that from somewhere.

**Comment by wayn3r** [comment]
I tried it today and it worked with plain JS objects. Closing this issue.

**Comment by B4nan** [comment]
I actually changed my mind on this, planing to change this in v6 so the `schema` option will work with entities (that do not have some schema already set) too, so let's keep it open.

**Comment by wayn3r** [comment]
Great

**Comment by B4nan** [comment]
Fixed in v6 via https://github.com/mikro-orm/mikro-orm/commit/e929c306d52cad3197fc313d7f8228f3afc296a3?w=1
