### ISSUE TITLE
Adding a collection before flushing its owner shouldn't lead to find throwing

### ISSUE THREAD

**Issue by darkbasic** [mikro-orm/mikro-orm#4431]
**Describe the bug**
```ts
{
  const authors = [
    new Author('a', 'a@a.com'),
    new Author('b', 'b@b.com'),
    new Author('c', 'c@c.com'),
    new Author('d', 'd@d.com'),
    new Author('e', 'e@e.com'),
  ];

  // This would fix the issue
  // await orm.em.persistAndFlush(authors);

  // This causes the issue
  authors[0].friends.add([authors[1], authors[3]]);
  // These do work though
  // authors[2].friends.add([authors[3]]);
  // authors[3].friends.add([authors[0], authors[2]]);

  orm.em.persist(authors);
  await orm.em.flush();

  const books = [
    new Book('One', authors[0]),
    new Book('Two', authors[0]),
    new Book('Three', authors[1]),
    new Book('Four', authors[2]),
    new Book('Five', authors[2]),
    new Book('Six', authors[2]),
  ];
  orm.em.persist(books);

  await orm.em.flush();
  orm.em.clear();
}
await orm.em.find(Author, {}, { first: 3 }); // Throws
```

**Stack trace**
```ts
  console.error
    JIT runtime error: Cannot read properties of null (reading '__entity')
    
      function(entity, data, factory, newEntity, convertCustomTypes, schema) {
        if (data._id === null) {
          entity._id = null;
        } else if (typeof data._id !== 'undefined') {
          entity._id = data._id;
        }
        if (data.id === null) {
          entity.id = null;
        } else if (typeof data.id !== 'undefined') {
          entity.id = data.id;
        }
        if (data.createdAt === null) {
          entity.createdAt = null;
        } else if (typeof data.createdAt !== 'undefined') {
          if (data.createdAt instanceof Date) {
            entity.createdAt = data.createdAt;
          } else {
            entity.createdAt = new Date(data.createdAt);
          }
        }
        if (data.updatedAt === null) {
          entity.updatedAt = null;
        } else if (typeof data.updatedAt !== 'undefined') {
          if (data.updatedAt instanceof Date) {
            entity.updatedAt = data.updatedAt;
          } else {
            entity.updatedAt = new Date(data.updatedAt);
          }
        }
        if (data.foo === null) {
          entity.foo = null;
        } else if (typeof data.foo !== 'undefined') {
          entity.foo = data.foo;
        }
        if (data.hookTest === null) {
          entity.hookTest = null;
        } else if (typeof data.hookTest !== 'undefined') {
          entity.hookTest = !!data.hookTest;
        }
        if (data.name === null) {
          entity.name = null;
        } else if (typeof data.name !== 'undefined') {
          entity.name = data.name;
        }
        if (data.email === null) {
          entity.email = null;
        } else if (typeof data.email !== 'undefined') {
          entity.email = data.email;
        }
        if (data.age === null) {
          entity.age = null;
        } else if (typeof data.age !== 'undefined') {
          entity.age = data.age;
        }
        if (data.termsAccepted === null) {
          entity.termsAccepted = null;
        } else if (typeof data.termsAccepted !== 'undefined') {
          entity.termsAccepted = !!data.termsAccepted;
        }
        if (data.optional === null) {
          entity.optional = null;
        } else if (typeof data.optional !== 'undefined') {
          entity.optional = !!data.optional;
        }
        if (data.identities === null) {
          entity.identities = null;
        } else if (typeof data.identities !== 'undefined') {
          if (convertCustomTypes) {
            const value = convertToJSValue_identities(data.identities);
            data.identities = convertToDatabaseValue_identities(value);
            entity.identities = value;
          } else {
            entity.identities = data.identities;
          }
        }
        if (data.born === null) {
          entity.born = null;
        } else if (typeof data.born !== 'undefined') {
          if (convertCustomTypes) {
            const value = convertToJSValue_born(data.born);
            entity.born = value;
          } else {
            entity.born = data.born;
          }
        }
        const createCollectionItem_books = (value, entity) => {
          if (isPrimaryKey(value, false)) return factory.createReference('Book', value, { convertCustomTypes, schema, merge: true });
          if (value && value.__entity) return value;
          if (typeof value === 'object' && value?.['author'] == null) {
            value = { ...value, ['author']: Reference.wrapReference(entity, { ref: undefined }) };
          }
          return factory.create('Book', value, { newEntity, convertCustomTypes, schema, merge: true });
        }
        if (data.books && !Array.isArray(data.books) && typeof data.books === 'object') {
          data.books = [data.books];
        }
        if (Array.isArray(data.books)) {
          const items = data.books.map(value => createCollectionItem_books(value, entity));
          const coll = Collection.create(entity, 'books', items, newEntity);
          if (newEntity) {
            coll.setDirty();
          } else {
            coll.takeSnapshot(true);
          }
        } else if (!entity.books && data.books instanceof Collection) {
          entity.books = data.books;
        } else if (!entity.books) {
          const coll = Collection.create(entity, 'books', undefined, !!data.books || newEntity);
          coll.setDirty(false);
        }
        const createCollectionItem_friends = (value, entity) => {
          if (isPrimaryKey(value, false)) return factory.createReference('Author', value, { convertCustomTypes, schema, merge: true });
          if (value && value.__entity) return value;
    >     return factory.create('Author', value, { newEntity, convertCustomTypes, schema, merge: true });
                        ^
        }
        if (data.friends && !Array.isArray(data.friends) && typeof data.friends === 'object') {
          data.friends = [data.friends];
        }
        if (Array.isArray(data.friends)) {
          const items = data.friends.map(value => createCollectionItem_friends(value, entity));
          const coll = Collection.create(entity, 'friends', items, newEntity);
          if (newEntity) {
            coll.setDirty();
          } else {
            coll.takeSnapshot(true);
          }
        } else if (!entity.friends && data.friends instanceof Collection) {
          entity.friends = data.friends;
        } else if (!entity.friends) {
          const coll = Collection.create(entity, 'friends', [], !!data.friends || newEntity);
          coll.setDirty(false);
        }
        if (data.favouriteBook === null) {
          entity.favouriteBook = null;
        } else if (typeof data.favouriteBook !== 'undefined') {
          if (isPrimaryKey(data.favouriteBook, true)) {
            entity.favouriteBook = factory.createReference('Book', data.favouriteBook, { merge: true, convertCustomTypes, schema });
          } else if (data.favouriteBook && typeof data.favouriteBook === 'object') {
            entity.favouriteBook = factory.create('Book', data.favouriteBook, { initialized: true, merge: true, newEntity, convertCustomTypes, schema });
          }
        }
        if (data.favouriteAuthor === null) {
          entity.favouriteAuthor = null;
        } else if (typeof data.favouriteAuthor !== 'undefined') {
          if (isPrimaryKey(data.favouriteAuthor, true)) {
            entity.favouriteAuthor = factory.createReference('Author', data.favouriteAuthor, { merge: true, convertCustomTypes, schema });
          } else if (data.favouriteAuthor && typeof data.favouriteAuthor === 'object') {
            entity.favouriteAuthor = factory.create('Author', data.favouriteAuthor, { initialized: true, merge: true, newEntity, convertCustomTypes, schema });
          }
        }
        if (data.version === null) {
          entity.version = null;
        } else if (typeof data.version !== 'undefined') {
          entity.version = data.version;
        }
        if (data.versionAsString === null) {
          entity.versionAsString = null;
        } else if (typeof data.versionAsString !== 'undefined') {
          entity.versionAsString = data.versionAsString;
        }
        if (data.tenant === null) {
          entity.tenant = null;
        } else if (typeof data.tenant !== 'undefined') {
          entity.tenant = data.tenant;
        }
      }

      1029 |
      1030 |         // eslint-disable-next-line no-console
    > 1031 |         console.error(`JIT runtime error: ${e.message}\n\n${code}`);
           |                 ^
      1032 |       }
      1033 |
      1034 |       throw e;

      at Function.error [as callCompiledFunction] (packages/core/src/utils/Utils.ts:1031:17)
      at ObjectHydrator.callCompiledFunction [as hydrate] (packages/core/src/hydration/ObjectHydrator.ts:29:11)
      at EntityFactory.hydrate (packages/core/src/entity/EntityFactory.ts:277:21)
      at EntityFactory.hydrate [as create] (packages/core/src/entity/EntityFactory.ts:83:10)
      at MongoEntityManager.create [as find] (packages/core/src/EntityManager.ts:194:39)
      at Object.<anonymous> (tests/issues/GH4430.test.ts:48:21)

 FAIL  tests/issues/GH4430.test.ts
  Utils
    ✕ adding a collection before flushing its owner shouldnt lead to find throwing (536 ms)

  ● Utils › adding a collection before flushing its owner shouldnt lead to find throwing

    TypeError: Cannot read properties of null (reading '__entity')

      43 |     options.initialized ??= true;
      44 |
    > 45 |     if ((data as Dictionary).__entity) {
         |                              ^
      46 |       return data as New<T, P>;
      47 |     }
      48 |

      at EntityFactory.__entity [as create] (packages/core/src/entity/EntityFactory.ts:45:30)
      at createCollectionItem_friends (eval at createFunction (packages/core/src/utils/Utils.ts:1001:14), <anonymous>:118:20)
      at eval (eval at createFunction (packages/core/src/utils/Utils.ts:1001:14), <anonymous>:124:45)
          at Array.map (<anonymous>)
      at eval (eval at createFunction (packages/core/src/utils/Utils.ts:1001:14), <anonymous>:124:32)
      at Function.fn [as callCompiledFunction] (packages/core/src/utils/Utils.ts:1012:14)
      at ObjectHydrator.callCompiledFunction [as hydrate] (packages/core/src/hydration/ObjectHydrator.ts:29:11)
      at EntityFactory.hydrate (packages/core/src/entity/EntityFactory.ts:277:21)
      at EntityFactory.hydrate [as create] (packages/core/src/entity/EntityFactory.ts:83:10)
      at MongoEntityManager.create [as find] (packages/core/src/EntityManager.ts:194:39)
      at Object.<anonymous> (tests/issues/GH4430.test.ts:48:21)
...
```

**To Reproduce**
See repro: https://github.com/mikro-orm/mikro-orm/pull/4430

**Expected behavior**
Shouldn't throw.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | v18.16.0 |
| typescript | 5.0.4 |
| mikro-orm | git v6 |
| your-driver | mongo |

**Comment by B4nan** [comment]
This is actually about issuing extra updates for a m:n owner in mongo (as there the m:n is represented as array property on the owner's side). That's indeed not implemented, and mongo only issue.

Maybe the easiest way around this would be to generate the ObjectIds upfront? In the end, that's what the mongo client [already does](https://github.com/mongodb/node-mongodb-native/blob/4e8386fbd14b16071c0f157aab34d7dc06d47c65/src/bulk/common.ts#L1030).
