### ISSUE TITLE
Adding an item to a ManyToMany relationship seems broken

### ISSUE THREAD

**Issue by Juknum** [mikro-orm/mikro-orm#4487]
**Describe the bug**
I have two entities that have a many to many relations between them, when I do `role.users.add(user)` (with users initialized) the collection is updated, but after that, if I interact with the role entity it seems that MikroORM is trying to perform an update request against the users table with invalid data (trying to set a field to NULL while it is non-nullable)

I'm pretty new to MikroORM and this give me headaches ^^" (sorry if its only a bug in my head aha)

**Stack trace**
```
E:\GitHub\AE\api\node_modules\.pnpm\@mikro-orm+postgresql@5.7.12_@mikro-orm+core@5.7.12_@mikro-orm+migrations@5.7.12_@mikro-orm+seeder@5.7.12\node_modules\@mikro-orm\postgresql\PostgreSqlExceptionConverter.js:24 
                return new core_1.NotNullConstraintViolationException(exception);
                       ^
NotNullConstraintViolationException: update "users" set "email" = NULL, "updated_at" = '2023-06-28T00:10:02.435Z' where "id" = 1 - null value in column "email" of relation "users" violates not-null constraint    
    at PostgreSqlExceptionConverter.convertException (E:\GitHub\AE\api\node_modules\.pnpm\@mikro-orm+postgresql@5.7.12_@mikro-orm+core@5.7.12_@mikro-orm+migrations@5.7.12_@mikro-orm+seeder@5.7.12\node_modules\@mikro-orm\postgresql\PostgreSqlExceptionConverter.js:24:24)
    at PostgreSqlDriver.convertException (E:\GitHub\AE\api\node_modules\.pnpm\@mikro-orm+core@5.7.12_@mikro-orm+migrations@5.7.12_@mikro-orm+postgresql@5.7.12_@mikro-orm+seeder@5.7.12\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:197:54)
    at E:\GitHub\AE\api\node_modules\.pnpm\@mikro-orm+core@5.7.12_@mikro-orm+migrations@5.7.12_@mikro-orm+postgresql@5.7.12_@mikro-orm+seeder@5.7.12\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:201:24  
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PostgreSqlDriver.nativeUpdate (E:\GitHub\AE\api\node_modules\.pnpm\@mikro-orm+knex@5.7.12_@mikro-orm+core@5.7.12_@mikro-orm+migrations@5.7.12_pg@8.11.0\node_modules\@mikro-orm\knex\AbstractSqlDriver.js:345:19)
    at ChangeSetPersister.persistManagedEntity (E:\GitHub\AE\api\node_modules\.pnpm\@mikro-orm+core@5.7.12_@mikro-orm+migrations@5.7.12_@mikro-orm+postgresql@5.7.12_@mikro-orm+seeder@5.7.12\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:137:21)
    at ChangeSetPersister.executeUpdates (E:\GitHub\AE\api\node_modules\.pnpm\@mikro-orm+core@5.7.12_@mikro-orm+migrations@5.7.12_@mikro-orm+postgresql@5.7.12_@mikro-orm+seeder@5.7.12\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:42:13)
    at ChangeSetPersister.runForEachSchema (E:\GitHub\AE\api\node_modules\.pnpm\@mikro-orm+core@5.7.12_@mikro-orm+migrations@5.7.12_@mikro-orm+postgresql@5.7.12_@mikro-orm+seeder@5.7.12\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:68:13)
    at UnitOfWork.commitUpdateChangeSets (E:\GitHub\AE\api\node_modules\.pnpm\@mikro-orm+core@5.7.12_@mikro-orm+migrations@5.7.12_@mikro-orm+postgresql@5.7.12_@mikro-orm+seeder@5.7.12\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:789:9)
    at UnitOfWork.persistToDatabase (E:\GitHub\AE\api\node_modules\.pnpm\@mikro-orm+core@5.7.12_@mikro-orm+migrations@5.7.12_@mikro-orm+postgresql@5.7.12_@mikro-orm+seeder@5.7.12\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:707:13)

previous error: update "users" set "email" = NULL, "updated_at" = '2023-06-28T00:10:02.435Z' where "id" = 1 - null value in column "email" of relation "users" violates not-null constraint
    at Parser.parseErrorMessage (E:\GitHub\AE\api\node_modules\.pnpm\pg-protocol@1.6.0\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (E:\GitHub\AE\api\node_modules\.pnpm\pg-protocol@1.6.0\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (E:\GitHub\AE\api\node_modules\.pnpm\pg-protocol@1.6.0\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (E:\GitHub\AE\api\node_modules\.pnpm\pg-protocol@1.6.0\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```

**To Reproduce**
I'm using MikroORM with NestJS and here is the following code I have :
```ts
// Controller
export class RolesController {
	constructor(private readonly rolesService: RolesService) {}

	@Post(':role_id/users/:user_id')
	async addUserToRole(@Param('role_id') role_id: number, @Param('user_id') user_id: number) {
		return this.rolesService.addUser(role_id, user_id);
	}
}
```
```ts
// Service
export class RolesService {
	constructor(private readonly orm: MikroORM) {}

	@UseRequestContext()
	async addUser(role_id: number, user_id: number): Promise<BaseUserResponseDTO[]> {
		const role = await this.orm.em.findOne(Role, { id: role_id });
		if (!role) throw new NotFoundException(`Role with ID ${role_id} not found`);

		const user = await this.orm.em.findOne(User, { id: user_id });
		if (!user) throw new NotFoundException(`User with ID ${user_id} not found`);

		await role.users.init();
		role.users.add(user);
		await this.orm.em.persistAndFlush(role);

		const res: BaseUserResponseDTO[] = [];
		role.users.getItems().forEach((user) =>
			res.push({
				id: user.id,
				updated_at: user.updated_at,
				created_at: user.created_at,
				first_name: user.first_name,
				last_name: user.last_name,
				nickname: user.nickname,
			}),
		);

		return res;
	}
}
```
```ts
@Entity({ tableName: 'users' })
export class User {
	// ...

	@Property({ unique: true })
	email: string;

	/** Linked roles to the user */
	@ManyToMany(() => Role, (role) => role.users)
	roles = new Collection<Role>(this);
}
```
```ts
@Entity({ tableName: 'roles' })
export class Role {
	// ...

	/** Specify to which user the role is attached */
	@ManyToMany(() => User, (user) => user.roles, { owner: true })
	users = new Collection<User>(this);
}
```

Once the `role.users.add()` method has been run, everything seems to be fine in the database (PostgreSQL) : 
![image](https://github.com/mikro-orm/mikro-orm/assets/49886317/78c8376e-37f8-40bd-8173-92a16d8cafe7)

But if I make any request after it, it break and show the stack trace above.

**Expected behavior**
To keep working properly :p

**Additional context**
Here is the screenshot of the debugger when MikroORM is trying to update the user :
![image](https://github.com/mikro-orm/mikro-orm/assets/49886317/4d4fb58d-b0a8-4c90-9858-563269560c41)

**Versions**

| Dependency | Version |
| - | - |
| node | v16.18.1 |
| typescript | 5.0.4 |
| mikro-orm | 5.7.12 |
| your-driver | ? |

**Comment by Juknum** [comment]
I think I got the issue, whenever I flush the `user` entity, MikroORM runs all `onUpdate` methods (but there is no such event on the `user.email` entity field which is kinda weird

**Comment by Juknum** [comment]
Found out it was me, my bad !

I have an interceptor to create a log each time a request is made which used to be like that :
```ts
@Injectable()
export class LoggingInterceptor implements NestInterceptor {
	constructor(private readonly orm: MikroORM) {}

        @UseRequestContext()
	async intercept(context: ExecutionContext, next: CallHandler<unknown>): Promise<Observable<unknown>> {
		const request = context.switchToHttp().getRequest();
		const user_id = request.user ? request.user.id : 'Guest';

		// No need to log guest users
		if (user_id === 'Guest') return next.handle();

		// Create a new log entry
		const user = await this.orm.em.findOne(User, { id: user_id });
		const log = this.orm.em.create(Log, {
			user,
			action: context.getClass().name + '.' + context.getHandler().name,
			ip: context.switchToHttp().getRequest().ip,
			user_agent: context.switchToHttp().getRequest().headers['user-agent'],
			route: context.switchToHttp().getRequest().route.path,
			method: context.switchToHttp().getRequest().method,
			body: context.switchToHttp().getRequest().body,
			query: context.switchToHttp().getRequest().query,
			params: context.switchToHttp().getRequest().params,
			updated_at: undefined,
		});

		await this.orm.em.persistAndFlush(log);

		return next.handle().pipe(
			tap(async () => {
				log.response = context.switchToHttp().getResponse().body;
				log.status_code = context.switchToHttp().getResponse().statusCode;
				log.error = context.switchToHttp().getResponse().error;
				log.error_stack = context.switchToHttp().getResponse().error_stack;
				log.error_message = context.switchToHttp().getResponse().error_message;
				log.updated_at = new Date();

				await this.orm.em.persistAndFlush(log);
			}),
		);
	}
}
```

I had to simply delete the first `persistAndFlush` call and replace the second one with `this.orm.em.persist(log);`

> I do not close this issue by myself as I'm not entirely sure if this behavior was intended or if its just me not knowing what I was doing ^^"

**Comment by Juknum** [comment]
Found out I was just dumb, all I needed was to fork the entity manager using this.orm.em.fork() to create an isolated instance and to not interfere with the request itself ^^"
