### ISSUE TITLE
Many to many collections changing schema name on deletion

### ISSUE THREAD

**Issue by jeroni** [mikro-orm/mikro-orm#4516]
**Describe the bug**
When using schemas on many to many relations with different schema name, deleting objects from the collection changes the relation schema name to the entity schema name.

**Stack trace**
```
TableNotFoundException: delete from "staff"."person_phone" where ("phone_id") in (('11')) and "person_id" = '12' - no existe la relación «staff.person_phone»
    at PostgreSqlExceptionConverter.convertException (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:38:24)
    at PostgreSqlDriver.convertException (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:173:54)
    at /home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:177:24
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PostgreSqlDriver.updateCollectionDiff (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/postgresql/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:560:13)
    at UnitOfWork.persistToDatabase (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:628:13)
    at PostgreSqlConnection.transactional (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/postgresql/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:36:25)
    at UnitOfWork.doCommit (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:254:17)
    at UnitOfWork.commit (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:234:9)
    at SqlEntityManager.flush (/home/jeroni/coding/WebstormProjects/mikro-orm-test/node_modules/@mikro-orm/core/EntityManager.js:603:9)

```

**To Reproduce**
1. Create a ManyToMany relation with a pivot table in a different schema
2. Delete one of the elements from the collection in the owner entity

**Expected behavior**
Delete the relation from the correct pivot table.

**Versions**
node v18.16.0
typescript 4.6.4
mikro-orm 5.7.12 ( and 5.7.13-dev.16 )
postgresql driver

Test case:
```ts
/** SQL
CREATE SCHEMA staff;
CREATE TABLE staff.person
(
    id bigserial primary key,
    name text not null
);

CREATE SCHEMA tic;
CREATE  tic.phone
(
    id bigserial primary key,
    "number" text not null
);

CREATE tic.person_phone
(
    id bigserial primary key,
    person_id bigint NOT NULL,
    phone_id bigint NOT NULL,
    CONSTRAINT person_phone_person_id_fkey FOREIGN KEY (person_id)
        REFERENCES staff.person (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT person_phone_phone_id_fkey FOREIGN KEY (phone_id)
        REFERENCES tic.phone (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
*/


    @Entity({schema: 'staff', tableName: 'person'})
    class Person {
        @PrimaryKey({nullable: true})
        id?: string;

        @Property()
        name!: string;

        @ManyToMany({entity: () => 'Phone', owner: true, pivotTable: 'tic.person_phone', joinColumn: 'person_id', inverseJoinColumn: 'phone_id'})
        phones: Collection<Phone> = new Collection<Phone>(this);
    }

    @Entity({schema: 'tic', tableName: 'phone'})
    class Phone {
        @PrimaryKey({nullable: true})
        id?: string;

        @Property()
        number!: string;

        @ManyToMany({ entity: () => 'Person', mappedBy: (e: Person) => e.phones })
        people: Collection<Person> = new Collection<Person>(this);
    }

    const orm = await MikroORM.init({
        entities: [ Person, Phone ],
        dbName: 'mikro-orm-test',
        type: 'postgresql',
        host: 'localhost',
        port: 5432,
        user: 'postgres',
        password: '',
        debug: true,
        metadataProvider: ReflectMetadataProvider
    });

    const em = orm.em.fork();

    try {
        await em.nativeDelete(Person, {});
        await em.nativeDelete(Phone, {});
        const person = new Person();
        person.name = 'John Wick';
        const phone = new Phone();
        phone.number = '666555444';
        person.phones.add(phone);
        await em.persistAndFlush(person);

        const em2 = orm.em.fork();
        const personLoaded = await em2.findOne(Person, { id: {$gt: '0'} }, {populate: ['phones']});
        personLoaded.phones.remove(personLoaded.phones[0]);
        await em2.persistAndFlush(personLoaded);
    } catch (e) {
        console.error(e);
    } finally {
        await orm.close();
    }
```

**Comment by B4nan** [comment]
Technically the pivot entity is always there, if you don't provide it yourself, it will be generated based on the metadata, so its quite expected those approaches will have the same outcome.

**Comment by jeroni** [comment]
Shouldn't the non-owning side be able to remove the relation too?

```ts
        // Add to the example
        const em3 = orm.em.fork();
        const phone2 = new Phone();
        phone2.number = '666555444';
        personLoaded.phones.add(phone);
        await em3.persistAndFlush(person);

        const em4 = orm.em.fork();
        const phoneLoaded = await em4.findOne(Phone, { id: {$gt: '0'}}, {populate: ['people']});
        console.log(phoneLoaded);
        phoneLoaded.people.remove(phoneLoaded.people[0]);
        console.log(phoneLoaded);
        await em4.persistAndFlush(phoneLoaded);
```
Will not delete the relation, this is the log (for the new part):
```txt
[query] begin
[query] insert into "tic"."person_phone" ("person_id", "phone_id") values ('28', '27') returning "id" [took 0 ms]
[query] commit
[query] select "p0".* from "tic"."phone" as "p0" where "p0"."id" > '0' limit 1 [took 1 ms, 1 result]
[query] select "p0".*, "p1"."person_id" as "fk__person_id", "p1"."phone_id" as "fk__phone_id" from "staff"."person" as "p0" left join "tic"."person_phone" as "p1" on "p0"."id" = "p1"."person_id" where "p1"."phone_id" in ('27') order by "p1"."id" asc [took 1 ms, 1 result]
Phone {
  id: '27',
  number: '666555444',
  people: Collection<Person> {
    '0': Person { id: '28', name: 'John Wick', phones: [Collection<Phone>] },
    initialized: true,
    dirty: false
  }
}
Phone {
  id: '27',
  number: '666555444',
  people: Collection<Person> { initialized: true, dirty: true }
}
```
I've checked the relation is present in the pivot table

**Comment by jeroni** [comment]
It's really working, my mistake to create a new phone.
