### ISSUE TITLE
Saving large (e.g. >=5MB) binary blobs with `BlobType` triggers `DriverException: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by jjhbw** [mikro-orm/mikro-orm#4526]
**Describe the bug**

**Stack trace**
```
[query] rollback
DriverException: Maximum call stack size exceeded
    at SqliteExceptionConverter.convertException (/Users/jur/Desktop/mikro-ORM-repro/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at SqliteExceptionConverter.convertException (/Users/jur/Desktop/mikro-ORM-repro/node_modules/@mikro-orm/sqlite/SqliteExceptionConverter.js:52:22)
    at SqliteDriver.convertException (/Users/jur/Desktop/mikro-ORM-repro/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:197:54)
    at /Users/jur/Desktop/mikro-ORM-repro/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:201:24
    at async SqliteDriver.nativeInsertMany (/Users/jur/Desktop/mikro-ORM-repro/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:303:21)
    at async ChangeSetPersister.persistNewEntity (/Users/jur/Desktop/mikro-ORM-repro/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:85:21)
    at async ChangeSetPersister.executeInserts (/Users/jur/Desktop/mikro-ORM-repro/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:29:13)
    at async ChangeSetPersister.runForEachSchema (/Users/jur/Desktop/mikro-ORM-repro/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:68:13)
    at async UnitOfWork.commitCreateChangeSets (/Users/jur/Desktop/mikro-ORM-repro/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:739:9)
    at async UnitOfWork.persistToDatabase (/Users/jur/Desktop/mikro-ORM-repro/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:703:13)

previous RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at SqliteConnection.getCallMethod (/Users/jur/Desktop/mikro-ORM-repro/node_modules/@mikro-orm/sqlite/SqliteConnection.js:128:52)
    at Client_SQLite3.Sqlite3Dialect._query (/Users/jur/Desktop/mikro-ORM-repro/node_modules/@mikro-orm/sqlite/SqliteConnection.js:72:37)
    at Object.executeQuery (/Users/jur/Desktop/mikro-ORM-repro/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_SQLite3.Client.query (/Users/jur/Desktop/mikro-ORM-repro/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:173:71)
    at /Users/jur/Desktop/mikro-ORM-repro/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_SQLite3.trxClient.query (/Users/jur/Desktop/mikro-ORM-repro/node_modules/knex/lib/execution/transaction.js:358:12)
    at Runner.query (/Users/jur/Desktop/mikro-ORM-repro/node_modules/knex/lib/execution/runner.js:123:36)
    at ensureConnectionCallback (/Users/jur/Desktop/mikro-ORM-repro/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
```

**To Reproduce**
```ts
import { BlobType, Entity, MikroORM, PrimaryKey, Property } from "@mikro-orm/core"

@Entity()
class Something {

    @PrimaryKey()
    id!: number;

    @Property({ type: BlobType })
    file_content!: Buffer
}

const test = async () => {
    const connection = await MikroORM.init({
        entities: [
            Something,
        ],
        dbName: ':memory:',
        type: 'sqlite',
        debug: true,
    })

    const generator = connection.getSchemaGenerator()
    await generator.updateSchema()

    const sth = new Something()
    sth.file_content = Buffer.alloc(5_000_000)

    const em = connection.em.fork()
    await em.persistAndFlush(sth)
}

test().catch(console.log)
```
**Expected behavior**
The `BlobType` used to save just fine.

**Additional context**
We are seeing this since we upgraded mikro-orm from `5.1.3` to `5.7.12`.

**Versions**

| Dependency | Version |
| - | - |
| node | v16.19.1 |
| typescript | 5.1.6 |
| mikro-orm | 5.7.12 |
| your-driver | `@mikro-orm/sqlite@5.7.12` |

**Comment by jjhbw** [comment]
@B4nan thanks a lot for the quick fix, really appreciated! 🎉
