### ISSUE TITLE
ValidationError: Metadata for entity Object not found

### ISSUE THREAD

**Issue by john-yick** [mikro-orm/mikro-orm#461]
**Describe the bug**
Cannot seem to create a new entity using the repository pattern, not matter how much I try to simplify the entities I always seem to hit this error:

`ValidationError: Metadata for entity Object not found`

**Stack trace**
```
Creating user
{ username: 'admin', password: 'XXXXX', id: '0' }
ValidationError: Metadata for entity Object not found
    at Function.missingMetadata (/Users/johnyick/Documents/code/gitlab/nestjs-boilerplate/node_modules/mikro-orm/dist/utils/ValidationError.js:103:16)
    at MetadataStorage.get (/Users/johnyick/Documents/code/gitlab/nestjs-boilerplate/node_modules/mikro-orm/dist/metadata/MetadataStorage.js:26:43)
    at UnitOfWork.cascade (/Users/johnyick/Documents/code/gitlab/nestjs-boilerplate/node_modules/mikro-orm/dist/unit-of-work/UnitOfWork.js:267:36)
    at UnitOfWork.persist (/Users/johnyick/Documents/code/gitlab/nestjs-boilerplate/node_modules/mikro-orm/dist/unit-of-work/UnitOfWork.js:71:14)
    at EntityManager.persistLater (/Users/johnyick/Documents/code/gitlab/nestjs-boilerplate/node_modules/mikro-orm/dist/EntityManager.js:284:34)
    at EntityManager.persist (/Users/johnyick/Documents/code/gitlab/nestjs-boilerplate/node_modules/mikro-orm/dist/EntityManager.js:267:14)
    at EntityRepository.persist (/Users/johnyick/Documents/code/gitlab/nestjs-boilerplate/node_modules/mikro-orm/dist/entity/EntityRepository.js:9:24)
    at UsersService.create (/Users/johnyick/Documents/code/gitlab/nestjs-boilerplate/dist/core/users/users.service.js:24:37)
    at /Users/johnyick/Documents/code/gitlab/nestjs-boilerplate/dist/core/users/users.controller.js:29:35 {
  entity: undefined,
  name: 'ValidationError'
}
```

**To Reproduce**
service.ts
```
    constructor(
        @InjectRepository(User)
        private readonly usersRepository: EntityRepository<User>,
    ) { }

    async create(user: User): Promise<void> {
        return this.usersRepository.persistAndFlush(user);
    }
```
controller.ts (constructor)
```
console.log('Creating user');
console.log(ADMIN_USER)
this.usersService.create(ADMIN_USER).then(res => {
    console.log('Created user')
    console.log(res);
}).catch(err => {
    console.error(err);
});
```

**Expected behavior**
Object to be created as a row within the db table, User. I can see the tables have all created from the migration.

**Versions**
"mikro-orm": "^3.6.2",
"typescript": "^3.7.4",

**Comment by B4nan** [comment]
You are trying to persist POJO, you need to provide instance of the entity.

**Comment by john-yick** [comment]
Thanks worked like a charm, wanted to have the POJO to be held as a constant but initialising the object is fine within the constructor. 
```
  const user = new User(ADMIN_USER.username, ADMIN_USER.password);
                    this.usersService.create(user).then(res => {
                        console.log('Created user')
                        console.log(res);
                    }).catch(err => {
                        console.error(err);
                    });
```

**Comment by B4nan** [comment]
Btw you could also use `em.create(User, payload)` to create the instance.

**Comment by john-yick** [comment]
Gotcha, though I don't want to pass around the em object as I already have the repository exposed at the service level. 

Though good to know that it is their within the em object too.

Thanks

**Comment by B4nan** [comment]
You can use repository too, `repo.create(payload)` is the same.
