### ISSUE TITLE
Upgrade pg module to latest

### ISSUE THREAD

**Issue by elliotttf** [mikro-orm/mikro-orm#4667]
**Describe the bug**
In @mikro-orm/postgresql@5.7.14 the version of pg is pinned at 8.11.1, There was an issue in this version: brianc/node-postgres#2980 that has subsequently been fixed in [pg@8.11.2](https://github.com/brianc/node-postgres/commits/pg%408.11.2) and I see that the mainline branch for mikro is using 8.11.3. Please release a new version of @mikro-orm/postgresql to resolve the issue.

**Stack trace**
```
 SyntaxError: /app/node_modules/pg/lib/crypto/utils.js: 'return' outside of function. (7:2)

       5 |   // We are on an old version of Node.js that requires legacy crypto utilities.
       6 |   module.exports = require('./utils-legacy')
    >  7 |   return
         |   ^
       8 | }
       9 |
      10 | const nodeCrypto = require('crypto')

      64 |     this.migrators = await Promise.all(
      65 |       this.tenantConfigs.map(async tenantConfig => {
    > 66 |         const orm = await MikroORM.init({
         |                     ^
      67 |           entities: this.entities, // todo: figure out entities logic
      68 |           type: 'postgresql',
      69 |           user: tenantConfig.user,

      at instantiate (../node_modules/@babel/parser/src/parse-error/credentials.ts:62:21)
      at instantiate (../node_modules/@babel/parser/src/parse-error.ts:60:12)
      at Parser.toParseError [as raise] (../node_modules/@babel/parser/src/tokenizer/index.ts:1474:19)
      at Parser.raise [as parseReturnStatement] (../node_modules/@babel/parser/src/parser/statement.ts:1008:12)
      at Parser.parseReturnStatement [as parseStatementContent] (../node_modules/@babel/parser/src/parser/statement.ts:478:21)
      at Parser.parseStatementContent [as parseStatementLike] (../node_modules/@babel/parser/src/parser/statement.ts:420:17)
      at Parser.parseStatementLike [as parseStatementListItem] (../node_modules/@babel/parser/src/parser/statement.ts:375:17)
      at Parser.parseStatementListItem [as parseBlockOrModuleBlockBody] (../node_modules/@babel/parser/src/parser/statement.ts:1346:16)
      at Parser.parseBlockOrModuleBlockBody [as parseBlockBody] (../node_modules/@babel/parser/src/parser/statement.ts:1319:10)
      at Parser.parseBlockBody [as parseBlock] (../node_modules/@babel/parser/src/parser/statement.ts:1287:10)
      at Parser.parseBlock [as parseStatementContent] (../node_modules/@babel/parser/src/parser/statement.ts:548:21)
      at Parser.parseStatementContent [as parseStatementLike] (../node_modules/@babel/parser/src/parser/statement.ts:420:17)
      at Parser.parseStatementLike [as parseStatementOrFunctionDeclaration] (../node_modules/@babel/parser/src/parser/statement.ts:386:17)
      at Parser.parseStatementOrFunctionDeclaration [as parseIfStatement] (../node_modules/@babel/parser/src/parser/statement.ts:996:28)
      at Parser.parseIfStatement [as parseStatementContent] (../node_modules/@babel/parser/src/parser/statement.ts:476:21)
      at Parser.parseStatementContent [as parseStatementLike] (../node_modules/@babel/parser/src/parser/statement.ts:420:17)
      at Parser.parseStatementLike [as parseModuleItem] (../node_modules/@babel/parser/src/parser/statement.ts:365:17)
      at Parser.parseModuleItem [as parseBlockOrModuleBlockBody] (../node_modules/@babel/parser/src/parser/statement.ts:1345:16)
      at Parser.parseBlockOrModuleBlockBody [as parseBlockBody] (../node_modules/@babel/parser/src/parser/statement.ts:1319:10)
      at Parser.parseBlockBody [as parseProgram] (../node_modules/@babel/parser/src/parser/statement.ts:226:10)
      at Parser.parseProgram [as parseTopLevel] (../node_modules/@babel/parser/src/parser/statement.ts:208:25)
      at Parser.parseTopLevel [as parse] (../node_modules/@babel/parser/src/parser/index.ts:45:10)
      at parse (../node_modules/@babel/parser/src/index.ts:67:38)
      at parser (../node_modules/@babel/core/src/parser/index.ts:28:19)
          at parser.next (<anonymous>)
      at normalizeFile (../node_modules/@babel/core/src/transformation/normalize-file.ts:52:24)
          at normalizeFile.next (<anonymous>)
      at run (../node_modules/@babel/core/src/transformation/index.ts:38:36)
          at run.next (<anonymous>)
      at transform (../node_modules/@babel/core/src/transform.ts:29:20)
          at transform.next (<anonymous>)
      at evaluateSync (../node_modules/gensync/index.js:251:28)
      at sync (../node_modules/gensync/index.js:89:14)
      at fn (../node_modules/@babel/core/src/errors/rewrite-stack-trace.ts:97:14)
      at transformSync (../node_modules/@babel/core/src/transform.ts:66:52)
      at ScriptTransformer._instrumentFile (../node_modules/@jest/transform/build/ScriptTransformer.js:366:46)
      at ScriptTransformer._buildTransformResult (../node_modules/@jest/transform/build/ScriptTransformer.js:468:33)
      at ScriptTransformer.transformSource (../node_modules/@jest/transform/build/ScriptTransformer.js:528:17)
      at ScriptTransformer._transformAndBuildScript (../node_modules/@jest/transform/build/ScriptTransformer.js:648:40)
      at ScriptTransformer.transform (../node_modules/@jest/transform/build/ScriptTransformer.js:700:19)
      at Object.<anonymous> (../node_modules/pg/lib/crypto/sasl.js:3:16)
      at Object.<anonymous> (../node_modules/pg/lib/client.js:5:12)
      at Object.<anonymous> (../node_modules/pg/lib/index.js:3:14)
      at Object.<anonymous> (../node_modules/@mikro-orm/postgresql/PostgreSqlPlatform.js:7:14)
      at Object.<anonymous> (../node_modules/@mikro-orm/postgresql/PostgreSqlDriver.js:9:30)
      at Object.<anonymous> (../node_modules/@mikro-orm/postgresql/index.js:28:14)
      at module (../node_modules/@mikro-orm/core/utils/Configuration.js:353:19)
      at Configuration.initDriver (../node_modules/@mikro-orm/core/utils/Configuration.js:241:29)
      at new Configuration (../node_modules/@mikro-orm/core/utils/Configuration.js:41:24)
      at new MikroORM (../node_modules/@mikro-orm/core/MikroORM.js:56:21)
      at Function.init (../node_modules/@mikro-orm/core/MikroORM.js:32:17)
      at MigratorManager.ts:66:21
          at async Promise.all (index 0)
      at MigratorManager.initMigrators (MigratorManager.ts:64:22)
      at MigratorManager.init (MigratorManager.ts:59:5)
      at Object.<anonymous> (__tests__/MigrationManager.test.ts:70:5)
```

**Comment by B4nan** [comment]
It is already updated in `master` (by renovate).

https://github.com/mikro-orm/mikro-orm/blob/master/packages/postgresql/package.json#L62

You can use the dev version that includes this change, I will hold the next stable release for a few more days as I am working on one last feature for it.
