### ISSUE TITLE
Cannot read properties of null (reading '__helper')

### ISSUE THREAD

**Issue by sawa-ko** [mikro-orm/mikro-orm#4688]
**Describe the bug**
I have a users entity that references several entities, so what I try to do is to use the fields property of the query to limit which fields to show from the nested properties, but then when I try to limit the properties of the owner field of the projectmembers entity from the project entity then I get the error `Cannot read properties of null (reading '__helper')`.

My project is open source, and you can see who is causing the error here:
https://github.com/kent-0/api/blob/main/src/modules/auth/services/account.service.ts#L126-L174

If you need to run the project, there is an (https://github.com/kent-0/api/blob/main/.env.example) file that you just need to rename to `.env` and set its values.

**Stack trace**
```
[Nest] 18624  - 09/10/2023, 5:27:20 PM   ERROR [ExceptionsHandler] Cannot read properties of null (reading '__helper')
TypeError: Cannot read properties of null (reading '__helper')
    at helper (/home/sawa/personal/backend/api/node_modules/.pnpm/@mikro-orm+core@5.8.0_@mikro-orm+migrations@5.8.0_@mikro-orm+postgresql@5.8.0_@mikro-orm+seeder@5.8.0/node_modules/@mikro-orm/core/entity/wrap.js:21:19)
    at /home/sawa/personal/backend/api/node_modules/.pnpm/@mikro-orm+core@5.8.0_@mikro-orm+migrations@5.8.0_@mikro-orm+postgresql@5.8.0_@mikro-orm+seeder@5.8.0/node_modules/@mikro-orm/core/entity/EntityFactory.js:103:48
    at Array.forEach (<anonymous>)
    at EntityFactory.mergeData (/home/sawa/personal/backend/api/node_modules/.pnpm/@mikro-orm+core@5.8.0_@mikro-orm+migrations@5.8.0_@mikro-orm+postgresql@5.8.0_@mikro-orm+seeder@5.8.0/node_modules/@mikro-orm/core/entity/EntityFactory.js:100:28)
    at EntityFactory.create (/home/sawa/personal/backend/api/node_modules/.pnpm/@mikro-orm+core@5.8.0_@mikro-orm+migrations@5.8.0_@mikro-orm+postgresql@5.8.0_@mikro-orm+seeder@5.8.0/node_modules/@mikro-orm/core/entity/EntityFactory.js:42:18)
    at SqlEntityManager.findOne (/home/sawa/personal/backend/api/node_modules/.pnpm/@mikro-orm+core@5.8.0_@mikro-orm+migrations@5.8.0_@mikro-orm+postgresql@5.8.0_@mikro-orm+seeder@5.8.0/node_modules/@mikro-orm/core/EntityManager.js:372:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AuthAccountService.me (/home/sawa/personal/backend/api/src/modules/auth/services/account.service.ts:128:18)
    at target (/home/sawa/personal/backend/api/node_modules/.pnpm/@nestjs+core@10.2.4_@nestjs+common@10.2.4_@nestjs+platform-express@10.2.4_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/helpers/external-context-creator.js:74:28)
    at Object.accountMe (/home/sawa/personal/backend/api/node_modules/.pnpm/@nestjs+core@10.2.4_@nestjs+common@10.2.4_@nestjs+platform-express@10.2.4_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
```

**To Reproduce**
```ts
const user = await this.usersRespository.findOne(
      {
        id: userId,
      },
      {
        fields: [
          'biography',
          'createdAt',
          'first_name',
          'last_name',
          'username',
          'id',
          'projects.project.description',
          'projects.project.end_date',
          'projects.project.id',
          'projects.project.name',
          'projects.project.owner.id',
          'projects.project.owner.username',
          'projects.project.owner.first_name',
          'projects.project.owner.last_name',
          'projects.project.start_date',
          'projects.roles.id',
          'projects.roles.name',
          'projects.roles.permissions',
          'email.value',
          'email.is_confirmed',
        ],
        populate: [
          'email',
          'projects',
          'projects.project',
          'projects.project.roles',
          'projects.project.owner',
        ],
      },
    );
```

**Expected behavior**
Result of the relationship of the property owner of the entity project members of the entity project resolved correctly with the fields that were set to view.

**Additional context**
I am using mikro-orm with nestjs and I am using postgres as database.

**Versions**

| Dependency | Version |
| - | - |
| node | v20.6.0 |
| typescript | 5.2.2 |
| mikro-orm | 5.8.0 |
| your-driver | postgres |

**Comment by B4nan** [comment]
Can you please provide minimal reproduction? So a script, no additional dependencies, no web servers, no GQL...

**Comment by sawa-ko** [comment]
Hello @B4nan!
I tried to replicate the problem without using graphql but I could not replicate the problem using the nestjs controllers, only using graphql.

**Comment by sawa-ko** [comment]
Problem solved. The problem came from this query:
```ts
	const tokenSession = await this.tokensRepository.findOne({
      revoked: false,
      token_type: TokenType.AUTH,
      token_value: token,
      user: payload.sub,
	});
```

That it was being used in an authentication guard: https://github.com/kent-0/api/blob/main/src/modules/auth/strategy/jwt.strategy.ts?rgh-link-date=2023-09-11T18%3A12%3A13Z#L96-L122

Then changing it to:

```ts
    const tokenSession = await this.em.fork().findOne(AuthTokensEntity, {
      revoked: false,
      token_type: TokenType.AUTH,
      token_value: token,
      user: payload.sub,
    });
```

It has worked correctly now.

**Comment by B4nan** [comment]
So it's about contexts, you apparently have something loaded to the context that affects the following query and hydration. 

Btw I see you have [`forceEntityConstructor`](https://github.com/kent-0/api/blob/main/mikro-orm.config.ts#L15) enabled, may I ask why? I've started to see this flag way too often, and up until now, everyone just misunderstood what it does. I don't see any place in your app that would require it, do you understand that the entities are created with the same class prototype regardless of it? It only controls whether your managed entity (so loaded from he database) fires the constructor or not, there are no other differences (e.g. both ways will support `instanceof` checks, will have the class methods, etc).

**Comment by rubiin** [comment]
Looks more to me like a code issue rather than an orm issue. Since its solved , i think it can be closed
