### ISSUE TITLE
bug: `mikro-orm migration:list` doesn't work with `mongodb` driver (Cannot read properties of undefined (reading 'toISOString'))

### ISSUE THREAD

**Issue by ruscon** [mikro-orm/mikro-orm#4698]
**Describe the bug**
The `cli` package uses `executed_at` property from the migration table
https://github.com/mikro-orm/mikro-orm/blob/v5.8.1/packages/cli/src/commands/MigrationCommandFactory.ts#L150

The `migrations` package creates the `executed_at` property in the migration table
https://github.com/mikro-orm/mikro-orm/blob/v5.8.1/packages/migrations/src/MigrationStorage.ts#L76

But the `migrations-mongodb` package creates the **`created_at`** property in the migration table
https://github.com/mikro-orm/mikro-orm/blame/v5.8.1/packages/migrations-mongodb/src/MigrationStorage.ts#L22

**Stack trace**
```
mikro-orm migration:list
List all executed migrations
Options:
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]
TypeError: Cannot read properties of undefined (reading 'toISOString')
    at /Users/user/projects/company/service/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:126:90
    at Array.map (<anonymous>)
    at Function.handleListCommand (/Users/user/projects/company/service/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:126:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.handleMigrationCommand (/Users/user/projects/company/service/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:83:17)
Warning: run-commands command "npx mikro-orm migration:list" exited with non-zero status code
```

**To Reproduce**
1. Use mongo driver
2. run `npx mikro-orm migration:list`

**Expected behavior**
No errors

**Additional context**

**Versions**

```shell
➜ npx mikro-orm debug
Current MikroORM CLI configuration
 - dependencies:
   - mikro-orm 5.8.1
   - node 18.13.0
   - mongodb 5.8.1
   - typescript 4.9.5
 - package.json found
 - ts-node enabled
 - searched config paths:
   - /Users/user/projects/company/service/apps/api/src/nestjs/data-sources/mongo.ts (found)
   - /Users/user/projects/company/service/dist/apps/api/src/nestjs/data-sources/mongo.js (found)
   - /Users/user/projects/company/service/apps/api/src/mikro-orm.config.ts (not found)
   - /Users/user/projects/company/service/apps/api/mikro-orm.config.ts (not found)
   - /Users/user/projects/company/service/apps/api/src/mikro-orm.config.js (not found)
   - /Users/user/projects/company/service/apps/api/mikro-orm.config.js (not found)
 - configuration found
 - database connection succesful
 - will use `entities` array (contains 4 references and 0 paths)
```

**Comment by ruscon** [comment]
@B4nan 

versions:
```
    "@mikro-orm/cli": "^5.8.2",
    "@mikro-orm/core": "^5.8.2",
    "@mikro-orm/migrations-mongodb": "^5.8.2",
    "@mikro-orm/mongodb": "^5.8.2",
    "@mikro-orm/nestjs": "^5.2.1",
```

error:
```
mikro-orm migration:list
List all executed migrations
Options:
  -v, --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]
TypeError: Cannot read properties of undefined (reading 'length')
    at /Users/user/projects/company/project/node_modules/@mikro-orm/cli/CLIHelper.js:103:60
    at Array.forEach (<anonymous>)
    at /Users/user/projects/company/project/node_modules/@mikro-orm/cli/CLIHelper.js:102:17
    at Array.forEach (<anonymous>)
    at Function.dumpTable (/Users/user/projects/company/project/node_modules/@mikro-orm/cli/CLIHelper.js:101:14)
    at Function.handleListCommand (/Users/user/projects/company/project/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:123:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.handleMigrationCommand (/Users/user/projects/company/project/node_modules/@mikro-orm/cli/commands/MigrationCommandFactory.js:83:17)
```

**Comment by B4nan** [comment]
8ae7eeb should help, please try the next dev version, will be out in ~15 minutes

**Comment by ruscon** [comment]
@B4nan works.
