### ISSUE TITLE
Syntax errors in update queries generated by entity manager if we populate a related entity with a composite key

### ISSUE THREAD

**Issue by lopkol** [mikro-orm/mikro-orm#4720]
**Describe the bug**
I am trying to switch an existing database to MikroORM, and I found three entities that I want to update (using the entity manager), and the generated update query contains a syntax error.

I managed to reproduce the issue on the following small example. 

**Entities**
```TypeScript
@Entity()
export class Parent {
  @PrimaryKey()
  id: number;

  [PrimaryKeyType]?: number;

  @Property()
  @Unique()
  uniqueProp: string;

  @OneToMany({ entity: () => Child, mappedBy: 'parent' })
  children: Collection<Child> = new Collection<Child>(this, [], true);

  @Property()
  data: string;
}
```
```TypeScript
@Entity()
export class Child {
  @ManyToOne({ entity: () => Parent, primary: true })
  parent: Parent;

  @ManyToOne({ entity: () => ChildType, primary: true })
  type: ChildType;

  [PrimaryKeyType]?: [Parent, ChildType];

  @Property()
  data: string;
}
```
```TypeScript
@Entity()
export class ChildType {
  @PrimaryKey()
  foo: string;

  @PrimaryKey()
  boo: string;

  [PrimaryKeyType]?: [string, string];

  @Property()
  data: string;
}
```

**The code that produces the problem**

The issue happens if in the same request we manipulate several things on the same parent and its children, and for this we fetch the entity multiple times from the db. 

```TypeScript
const parent = await this.entityManager.findOneOrFail(Parent, {
  uniqueProp: 'aaa',
});

parent.data = 'pppppppppp';
await this.entityManager.flush();

const sameParent = await this.entityManager.findOneOrFail(
  Parent,
  { uniqueProp: 'aaa' },
  { populate: ['children', 'children.type'] },
);

sameParent.children.getItems()[0].data = 'eeeeeeeeeee';
sameParent.children.getItems()[1].data = 'wwwwwwwwwww';
await this.entityManager.flush();
```
⚠️ Note: The bug doesn't happen if we don't populate `children.type` in the second fetch.

(Of course in a real-life example the different fetches and modifications would happen in different handlers, and we don't want to pass the entity instance between them, that's why I need this to work with several fetches. Also, I need to populate the `type`, since I perform the updates based on what's in the type.)

**The generated queries**
```
[query] select "p0".* from "parent" as "p0" where "p0"."unique_prop" = 'aaa' limit 1 [took 2 ms, 1 result]
[query] begin
[query] update "parent" set "data" = 'pppppppppp' where "id" = 1 [took 1 ms]
[query] commit
[query] select "p0"."id", "p0"."unique_prop", "p0"."data", "c1"."parent_id" as "c1__parent_id", "c1"."type_foo" as "c1__type_foo", "c1"."type_boo" as "c1__type_boo", "c1"."data" as "c1__data", "t2"."foo" as "t2__foo", "t2"."boo" as "t2__boo", "t2"."data" as "t2__data" from "parent" as "p0" left join "child" as "c1" on "p0"."id" = "c1"."parent_id" left join "child_type" as "t2" on "c1"."type_foo" = "t2"."foo" and "c1"."type_boo" = "t2"."boo" where "p0"."unique_prop" = 'aaa' [took 2 ms, 2 results]
[query] begin
[query] update "child" set "type_foo" = case when ("parent_id" = 1 and "type_foo" = 'foo' and "type_boo" = 'boo') then 'foo' when ("parent_id" = 1 and "type_foo" = 'loo' and "type_boo" = 'boo') then 'loo' else "type_foo" end, "type_boo" = case when ("parent_id" = 1 and "type_foo" = 'foo' and "type_boo" = 'boo') then 'boo' when ("parent_id" = 1 and "type_foo" = 'loo' and "type_boo" = 'boo') then 'boo' else "type_boo" end, "data" = case when ("parent_id" = 1 and "type_foo" = 'foo' and "type_boo" = 'boo') then 'eeeeeeeeeee' when ("parent_id" = 1 and "type_foo" = 'loo' and "type_boo" = 'boo') then 'wwwwwwwwwww' else "data" end where ("parent_id", "type_foo", "type_boo") in ((1, '{"foo":"foo","boo":"boo"}', 1), ('{"foo":"loo","boo":"boo"}', NULL, NULL)) [took 1 ms]
[query] rollback
```
The second update has syntax errors in the `where` clause. Also, I find it weird that for the second select it says `2 results`, since I only have one row in that table.

**Stack trace**
```
DriverException: update "child" set "type_foo" = case when ("parent_id" = 1 and "type_foo" = 'foo' and "type_boo" = 'boo') then 'foo' when ("parent_id" = 1 and "type_foo" = 'loo' and "type_boo" = 'boo') then 'loo' else "type_foo" end, "type_boo" = case when ("parent_id" = 1 and "type_foo" = 'foo' and "type_boo" = 'boo') then 'boo' when ("parent_id" = 1 and "type_foo" = 'loo' and "type_boo" = 'boo') then 'boo' else "type_boo" end, "data" = case when ("parent_id" = 1 and "type_foo" = 'foo' and "type_boo" = 'boo') then 'eeeeeeeeeee' when ("parent_id" = 1 and "type_foo" = 'loo' and "type_boo" = 'boo') then 'wwwwwwwwwww' else "data" end where ("parent_id", "type_foo", "type_boo") in ((1, '{"foo":"foo","boo":"boo"}', 1), ('{"foo":"loo","boo":"boo"}', NULL, NULL)) - operator does not exist: character varying = integer
    at PostgreSqlExceptionConverter.convertException (/home/nora/repositories/nest-mikroorm-test/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException (/home/nora/repositories/nest-mikroorm-test/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:42:22)
    at PostgreSqlDriver.convertException (/home/nora/repositories/nest-mikroorm-test/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:197:54)
    at /home/nora/repositories/nest-mikroorm-test/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:201:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PostgreSqlDriver.nativeUpdateMany (/home/nora/repositories/nest-mikroorm-test/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:427:21)
    at ChangeSetPersister.persistManagedEntitiesBatch (/home/nora/repositories/nest-mikroorm-test/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:173:9)
    at ChangeSetPersister.persistManagedEntities (/home/nora/repositories/nest-mikroorm-test/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:146:13)
    at ChangeSetPersister.runForEachSchema (/home/nora/repositories/nest-mikroorm-test/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:68:13)
    at UnitOfWork.commitUpdateChangeSets (/home/nora/repositories/nest-mikroorm-test/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:789:9)
```

**Versions**

| Dependency | Version |
| - | - |
| node | 16.20.2 |
| nestjs | 10.0.0 |
| typescript | 5.1.3 |
| mikro-orm | 5.7.14 |
| pg | 8.11.1 |

It is possible that it's not a bug, maybe I'm just not using the ORM correctly. 🙂 In any case, I'd really appreciate a solution suggestion to do the kind of updates that I'm trying to achieve. (A workaround I can use is of course to write native updates, but I'd prefer to use the entity manager.)

**Comment by B4nan** [comment]
the entity definition looks good, will try to have a look soon, i think i know where the problem is.

> Also, I find it weird that for the second select it says 2 results, since I only have one row in that table.

you join to-many relations, so you get cartesian product as a result - the number is based on what the database returns, not on what will be mapped from it

**Comment by B4nan** [comment]
> mikro-orm | 5.7.14

btw be sure to upgrade first, there were many fixes in v5.8

**Comment by B4nan** [comment]
You forgot to mention one important thing, you are using the joined strategy. With the default select-in strategy things work just fine.

Here is a complete failing repro:

```ts
import {
  Collection,
  Entity,
  LoadStrategy,
  ManyToOne,
  OneToMany,
  PrimaryKey,
  PrimaryKeyProp,
  PrimaryKeyType,
  Property,
  Unique,
} from '@mikro-orm/core';
import { MikroORM } from '@mikro-orm/postgresql';

@Entity()
class Parent {

  @PrimaryKey()
  id!: number;

  @Property()
  @Unique()
  uniqueProp!: string;

  @OneToMany({ entity: () => Child, mappedBy: 'parent' })
  children: Collection<Child> = new Collection<Child>(this);

  @Property()
  data!: string;

}
@Entity()
class ChildType {

  [PrimaryKeyProp]?: 'foo' | 'boo';
  [PrimaryKeyType]?: [string, string];

  @PrimaryKey()
  foo!: string;

  @PrimaryKey()
  boo!: string;

  @Property()
  data!: string;

}

@Entity()
class Child {

  [PrimaryKeyProp]?: 'parent' | 'type';
  [PrimaryKeyType]?: [number, [string, string]];

  @ManyToOne({ entity: () => Parent, primary: true })
  parent!: Parent;

  @ManyToOne({ entity: () => ChildType, primary: true })
  type!: ChildType;

  @Property()
  data!: string;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [Parent],
    dbName: '4720',
    debug: true,
    loadStrategy: LoadStrategy.JOINED,
  });
  await orm.schema.refreshDatabase();
});

afterAll(() => orm.close(true));

test('cascade persist with pre-filled PK and with cycles', async () => {
  const parent = await orm.em.insert(Parent, {
    uniqueProp: 'aaa',
    data: '123',
  });
  await orm.em.insertMany(ChildType, [
    { foo: 'f1', boo: 'b1', data: '456' },
    { foo: 'f2', boo: 'b2', data: '789' },
  ]);
  await orm.em.insertMany(Child, [
    { parent, type: ['f1', 'b1'], data: '111' },
    { parent, type: ['f2', 'b2'], data: '222' },
  ]);

  const p = await orm.em.findOneOrFail(Parent, {
    uniqueProp: 'aaa',
  });

  p.data = 'pppppppppp';
  await orm.em.flush();

  const sameParent = await orm.em.findOneOrFail(
    Parent,
    { uniqueProp: 'aaa' },
    { populate: ['children', 'children.type'] },
  );

  sameParent.children[0].data = 'eeeeeeeeeee';
  sameParent.children[1].data = 'wwwwwwwwwww';
  await orm.em.flush();
});
```

**Comment by lopkol** [comment]
> You forgot to mention one important thing, you are using the joined strategy. With the default select-in strategy things work just fine.

Yes, you're completely right! I'm sorry, I forgot about that 🤦 

Thanks a lot for the reactivity!
