### ISSUE TITLE
validation error when persisting entity from parent constructor

### ISSUE THREAD

**Issue by JulianCissen** [mikro-orm/mikro-orm#4781]
**Describe the bug**
When creating an entity and assigning a related entity as relation in it's constructor, an issue occurs persisting the related entity.

**Stack trace**
```
C:\sources\mikro-orm-sandbox\node_modules\@mikro-orm\core\errors.js:68
        return new ValidationError(`Value for ${entityName}.${property.name} is required, '${entity[property.name]}' found\nentity: ${(0, util_1.inspect)(entity)}`, entity);               ^
ValidationError: Value for Book.author is required, 'undefined' found
entity: Book {
  id: 'acc9d787-abbc-469e-b8cf-1560a2ede99a',
  releaseDate: 2023-10-04T10:12:08.773Z,
  name: 'My first book'
}
    at Function.propertyRequired (C:\sources\mikro-orm-sandbox\node_modules\@mikro-orm\core\errors.js:68:16)
    at EntityValidator.validateRequired (C:\sources\mikro-orm-sandbox\node_modules\@mikro-orm\core\entity\EntityValidator.js:49:48)
    at ChangeSetPersister.processProperties (C:\sources\mikro-orm-sandbox\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:77:28)
    at C:\sources\mikro-orm-sandbox\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:24:46
    at Array.forEach (<anonymous>)
    at ChangeSetPersister.executeInserts (C:\sources\mikro-orm-sandbox\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:24:20)
    at ChangeSetPersister.runForEachSchema (C:\sources\mikro-orm-sandbox\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:68:31)
    at ChangeSetPersister.executeInserts (C:\sources\mikro-orm-sandbox\node_modules\@mikro-orm\core\unit-of-work\ChangeSetPersister.js:21:25)
    at UnitOfWork.commitCreateChangeSets (C:\sources\mikro-orm-sandbox\node_modules\@mikro-orm\core\unit-of-work\UnitOfWork.js:741:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  entity: Book {
    id: 'acc9d787-abbc-469e-b8cf-1560a2ede99a',
    releaseDate: [Getter/Setter],
    name: [Getter/Setter]
  }
}
```

**To Reproduce**
1. Run the following code:
```typescript
import { Entity, Property, PrimaryKey, OneToOne, OneToMany, ManyToOne, Collection, Ref, DateType, ref } from "@mikro-orm/core";
import { MikroORM } from "@mikro-orm/postgresql";
import { v4 } from "uuid";

@Entity()
export class Author {
  @PrimaryKey()
  id = v4();

  @Property()
  name!: string

  @OneToMany({
    entity: () => Book,
    mappedBy: 'author',
  })
  books = new Collection<Book>(this);

  @OneToOne({
    entity: () => Book,
    ref: true,
    formula: (alias) =>
      `(select "b"."id"
      from (
        select "b"."author_id", min("b"."release_date") "release_date"
        from "book" "b"
        where "b"."author_id" = ${alias}."id"
        group by "b"."author_id"
      ) "s1"
      join "book" "b"
      on "b"."author_id" = "s1"."author_id"
      and "b"."release_date" = "s1"."release_date")`,
  })
  firstBook!: Ref<Book>;

  constructor(name: string) {
    this.name = name;
    const myFirstBook = new Book(new Date(), 'My first book', this);
    this.books.add(myFirstBook)
    this.firstBook = ref(myFirstBook)
  }
}

@Entity()
export class Book {
  @PrimaryKey()
  id = v4();

  @Property({ type: DateType })
  releaseDate!: Date;

  @Property()
  name!: string;

  @ManyToOne({
    entity: () => Author,
    ref: true,
    inversedBy: 'books',
  })
  author!: Ref<Author>;

  constructor(releaseDate: Date = new Date(), name: string, author: Author) {
    this.releaseDate = releaseDate;
    this.name = name;
    this.author = ref((author));
  }
}

const start = async () => {
  const db = await MikroORM.init({
      entities: [Book, Author],
      type: 'postgresql',
      dbName: 'debug',
      host: 'localhost',
      port: 5432,
      user: 'postgres',
      password: 'postgres',
      debug: true,
  });

  let em = db.em.fork();

  const author = new Author('John');

  em.persistAndFlush([author]);
}

start();
```

**Expected behavior**
The newly constructed entities are persisted properly.

**Additional context**
Relates to #4759. Based on the resolution of that issue I assume that using virtual relations this way is fine (I understand that it hasn't been tested much, but that's something I can live with).

This issue only seems to occur when initializing the parent entity (Author) at the same time as the related entity (Book). If the parent entity already exists and has been retrieved from EM, and then the book is added as shown in the constructor (initialize the entity, relate it to the normal and the virtual relations), it seems like this issue doesn't occur.

Similarly, the issue does not occur when only the actual relation is set, not the virtual relation. My use case however requires me to make the virtual relation (firstBook) required (mostly due to backwards compatibility), and the virtual relation itself is needed to be able to query on a specific (most recent) entry of the collection (books).

**Versions**

| Dependency | Version |
| - | - |
| node | 18.18.0 |
| typescript | 5.1.6 |
| mikro-orm | 5.8.5 |
| your-driver | 5.8.5 |

**Comment by B4nan** [comment]
FYI you can disable this validation for now via `validateRequired: false` in the ORM config. But if it's triggered, it really means the value is not there, and a following insert query would fail on the database level, so its probably not gonna help.

**Comment by B4nan** [comment]
Making the property is actually all you need to work this around, as that way the commit order calculator will know its fine to not provide a value for it.
