### ISSUE TITLE
Error: createSchema is not supported for this dialect (only PostgreSQL supports it currently).

### ISSUE THREAD

**Issue by NomadInsurance** [mikro-orm/mikro-orm#4792]
**Describe the bug**
Migrations fail with error when running `npx mikro-orm migration:create --initial` and `npx mikro-orm migration:up` with Mysql

**Stack trace**
```
Error: createSchema is not supported for this dialect (only PostgreSQL supports it currently).
    at throwOnlyPGError (/Users/michael/Repos/addam/node_modules/.pnpm/knex@2.5.1_mysql2@3.6.1/node_modules/knex/lib/schema/compiler.js:182:9)
    at SchemaCompiler_MySQL.createSchema (/Users/michael/Repos/addam/node_modules/.pnpm/knex@2.5.1_mysql2@3.6.1/node_modules/knex/lib/schema/compiler.js:25:5)
    at SchemaCompiler_MySQL.toSQL (/Users/michael/Repos/addam/node_modules/.pnpm/knex@2.5.1_mysql2@3.6.1/node_modules/knex/lib/schema/compiler.js:97:26)
    at SchemaBuilder.toSQL (/Users/michael/Repos/addam/node_modules/.pnpm/knex@2.5.1_mysql2@3.6.1/node_modules/knex/lib/schema/builder.js:36:45)
    at ensureConnectionCallback (/Users/michael/Repos/addam/node_modules/.pnpm/knex@2.5.1_mysql2@3.6.1/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
    at Runner.ensureConnection (/Users/michael/Repos/addam/node_modules/.pnpm/knex@2.5.1_mysql2@3.6.1/node_modules/knex/lib/execution/runner.js:318:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Runner.run (/Users/michael/Repos/addam/node_modules/.pnpm/knex@2.5.1_mysql2@3.6.1/node_modules/knex/lib/execution/runner.js:30:19)
    at async MigrationStorage.ensureTable (/Users/michael/Repos/addam/node_modules/.pnpm/@mikro-orm+migrations@5.8.7_@mikro-orm+core@5.8.7_@mikro-orm+entity-generator@5.8.7/node_modules/@mikro-orm/migrations/MigrationStorage.js:76:13)
    at async Migrator.ensureDatabase (/Users/michael/Repos/addam/node_modules/.pnpm/@mikro-orm+migrations@5.8.7_@mikro-orm+core@5.8.7_@mikro-orm+entity-generator@5.8.7/node_modules/@mikro-orm/migrations/Migrator.js:162:9)
```

**To Reproduce**
1. Setup project with Mysql
2. Run migrator
3. See error

**Expected behavior**
Migrations should succeed 

**Additional context**
Using Plantscale.

When I remove the `schema` option from the config it progresses but then errors with `"VT05003: unknown database 'public' in vschema`.  The `mikro_orm_migrations` table is created though.

**Versions**

| Dependency | Version |
| - | - |
| node | v20.5.0 |
| mikro-orm | 5.8.6 |

**Comment by B4nan** [comment]
As the error says, mysql does not support this feature.
