### ISSUE TITLE
Issue with createMigration(path?: string, blank?: boolean, initial?: boolean): Promise<MigrationResult>;

### ISSUE THREAD

**Issue by tiaanvow** [mikro-orm/mikro-orm#4902]
**Describe the bug**
When trying to run the `orm.createMigration()` there is a failure in `@mikro-orm/knex/schema/SchemaGenerator.js` where it is unable to find an index name. 

**Stack trace**
```
~/node_modules/@mikro-orm/knex/schema/SchemaHelper.js:88
        return `${tableName}_${columns.join('_')}_${type}`;
                                       ^
TypeError: Cannot read properties of undefined (reading 'join')
    at PostgreSqlSchemaHelper.getIndexName (~/node_modules/@mikro-orm/knex/schema/SchemaHelper.js:88:40)
    at idxName (~/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:440:69)
    at ~/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:460:30
    at Array.forEach (<anonymous>)
    at SchemaGenerator.findIndexDifference (~/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:455:20)
    at SchemaGenerator.computeTableDifference (~/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:243:46)
    at SchemaGenerator.updateTable (~/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:210:57)
    at SchemaGenerator.getUpdateTableSQL (~/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:127:21)
    at SchemaGenerator.getUpdateSchemaSQL (~/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:85:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Migrator.getSchemaDiff (~/node_modules/@mikro-orm/migrations/Migrator.js:163:26)
    at Migrator.createMigration (~/node_modules/@mikro-orm/migrations/Migrator.js:60:22)
```

**To Reproduce**
This is quite difficult for me to reproduce. I have narrowed it down as occuring in `findIndexDifference`. The following line:
```
if (prop.index) {
    const name = idxName(prop.index, prop.fieldNames, 'index');
    expectIndex(name, prop.fieldNames, false, prop.reference === core_1.ReferenceType.SCALAR);
} 
```
Appears to be the one that fails, where the `prop` is:
```
prop {
  name: 'toMeasures',
  reference: '1:m',
  cascade: [ 'all' ],
  entity: [Function: entity],
  mappedBy: 'measureGroup',
  type: 'Measurement',
  columnTypes: [ 'int4' ],
  unsigned: undefined,
  joinColumns: [ 'to_measures_id' ],
  referencedColumnNames: [ 'id' ],
  referencedPKs: [ 'id' ],
  targetMeta: <ref *1> EntityMetadata {
    propertyOrder: Map(9) {
      ...
      'measureGroup' => 9
    },
    properties: {
      ...
      measureGroup: [Object]
    },
    props: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    primaryKeys: [ 'id' ],
    filters: { softDelete: [Object] },
    hooks: {},
    indexes: [ [Object] ],
    uniques: [],
    className: 'Measurement',
    path: './Measurement.ts',
    class: [class Measurement],
    name: 'Measurement',
    abstract: false,
    prototype: {
      toJSON: [Function (anonymous)],
      [Symbol(nodejs.util.inspect.custom)]: [Function (anonymous)]
    },
    constructorParams: [...],
    toJsonParams: [],
    extends: undefined,
    useCache: false,
    compositePK: false,
    relations: [ [Object], [Object], [Object] ],
    collection: 'measurement',
    root: [Circular *1],
    tableName: 'measurement',
    forceConstructor: false,
    serializedPrimaryKey: 'id',
    comparableProps: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    hydrateProps: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    selfReferencing: false
  },
  index: true
}
```

As you can see, there is no `fieldnames` property as part of this `prop`. This is the actual entity definition which defines this relation:
```
export class MeasureGroup {
...
@OneToMany({ entity: () => Measurement, mappedBy: 'measureGroup', cascade: [Cascade.ALL] })
  @Index()
  toMeasures = new Collection<Measurement>(this);
}

export class Measurement {
@ManyToOne({ entity: () => MeasureGroup, cascade: [Cascade.MERGE], nullable: true })
  @Index()
  measureGroup?: MeasureGroup;
}
```

And this was the generated migration which is related:

```
this.addSql('alter table "measurement" add column "measure_group_id" int4 null;');
    this.addSql(
      'create index "measurement_measure_group_id_index" on "measurement" ("measure_group_id");',
    );

    this.addSql(
      'alter table "measurement" add constraint "measurement_measure_group_id_foreign" foreign key ("measure_group_id") references "measure_group" ("id") on delete set null;',
    );
```

**Expected behavior**
Before running this migration our `createMigration` API call worked fine, and I have even tested it that if I create a DB and dont run this migration, the `createMigration` call works fine. 

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 18.17.0|
| typescript | 3.9.10 |
| mikro-orm |4.5.7 |
| your-driver | Postgres |

**Comment by B4nan** [comment]
v4 is no longer supported, please try upgrading

**Comment by tiaanvow** [comment]
@B4nan Do you know at all what might be causing this issue? Is it something in the entity definition ?

**Comment by B4nan** [comment]
Drop the `@Index` decorator from 1:m relation, that does not make much sense, it does not represent any database column, its inverse side.

**Comment by tiaanvow** [comment]
You saved me! thanks a lot @B4nan

**Comment by B4nan** [comment]
Just curious, what holds you from upgrading? You are missing out _a lot_.
