### ISSUE TITLE
Turning validate off on EntityManager Population should not trigger invalidPropertyName Error

### ISSUE THREAD

**Issue by ThatOneAwkwardGuy** [mikro-orm/mikro-orm#5043]
### Describe the bug

I have a polymorphic schema, which may or may not have a property i'd like to be populated. I've turned validation off when using `this.em.populate` however I'm still receiving invalidPropertyName errors.

### Reproduction

```
@Entity({
  discriminatorColumn: 'type',
  abstract: true,
  discriminatorMap: {
	'child1': 'Child1',
	'child2': 'Child2'
  },
})
export abstract class Base  {
  @Property({ nullable: true })
  type? string;
}

export class Child1 extends Base {
  @Property()
  type: "child1";
}

export class Child2 extends Base {
  @Property()
  type: "child2";

  @ManyToOne(() => BankingAccount, { ref: true })
  account: Ref<BankingAccount>;	
}

// This will throw a invalidPropertyName error even though the entity could have account as a property. 
// I think it's fine that it does this and will prevent others making mistakes, but I need a way to turn it off.

await this.em.populate(entity, ["account"], {validate: false})

```

### What driver are you using?

@mikro-orm/mongodb

### MikroORM version

6.0.0-dev.284

### Node.js version

20

### Operating system

Mac

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
> await this.em.populate(entity, ["account"], {validate: false})

What is `entity` here? What error do you get? Include the stack trace so it's clear where it's thrown from.

My guess is its coming from the EM, not entity loader. FWIW this options is rather internal.

**Comment by ThatOneAwkwardGuy** [comment]
Actual stack trace
```
[2] [0] [Nest] 71051  - 22/12/2023, 18:11:41   ERROR [ExceptionsHandler] Entity 'BusinessAssetManualOther' does not have property 'ticker'
[2] [0] ValidationError: Entity 'BusinessAssetManualOther' does not have property 'ticker'
[2] [0]     at Function.invalidPropertyName (test/node_modules/.pnpm/@mikro-orm+core@6.0.0-dev.284_patch_hash=pip6vhquwj3ln44si6axk5oway/node_modules/@mikro-orm/core/errors.js:58:16)
[2] [0]     at MongoEntityManager.preparePopulate (test/node_modules/.pnpm/@mikro-orm+core@6.0.0-dev.284_patch_hash=pip6vhquwj3ln44si6axk5oway/node_modules/@mikro-orm/core/EntityManager.js:1517:44)
[2] [0]     at MongoEntityManager.populate (test/node_modules/.pnpm/@mikro-orm+core@6.0.0-dev.284_patch_hash=pip6vhquwj3ln44si6axk5oway/node_modules/@mikro-orm/core/EntityManager.js:1303:37)
[2] [0]     at test/dist/apps/api/main.js:48434:81
[2] [0]     at Array.map (<anonymous>)
[2] [0]     at AssetService.getPopulatedAssets (test/dist/apps/api/main.js:48434:58)
[2] [0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2] [0]     at AssetController.getAssets (test/dist/apps/api/main.js:48238:24)
[2] [0]
```

modified to suite example:
```
[2] [0] [Nest] 71051  - 22/12/2023, 18:11:41   ERROR [ExceptionsHandler] Entity 'Child1' does not have property 'ticker'
[2] [0] ValidationError: Entity 'Child1' does not have property 'account'
[2] [0]     at Function.invalidPropertyName (test/node_modules/.pnpm/@mikro-orm+core@6.0.0-dev.284_patch_hash=pip6vhquwj3ln44si6axk5oway/node_modules/@mikro-orm/core/errors.js:58:16)
[2] [0]     at MongoEntityManager.preparePopulate (test/node_modules/.pnpm/@mikro-orm+core@6.0.0-dev.284_patch_hash=pip6vhquwj3ln44si6axk5oway/node_modules/@mikro-orm/core/EntityManager.js:1517:44)
[2] [0]     at MongoEntityManager.populate (test/node_modules/.pnpm/@mikro-orm+core@6.0.0-dev.284_patch_hash=pip6vhquwj3ln44si6axk5oway/node_modules/@mikro-orm/core/EntityManager.js:1303:37)
[2] [0]     at test/dist/apps/api/main.js:48434:81
[2] [0]     at Array.map (<anonymous>)
[2] [0]     at AssetService.getPopulatedAssets (test/dist/apps/api/main.js:48434:58)
[2] [0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2] [0]     at AssetController.getAssets (test/dist/apps/api/main.js:48238:24)
[2] [0]
```

**Comment by ThatOneAwkwardGuy** [comment]
Sorry, i also realised i forgot to answer what entity would be. entity could be either Child1 or Child2

**Comment by B4nan** [comment]
Got it, I think we could allow that in general even without the flag, it's just about checking the root entity metadata in there.

**Comment by ThatOneAwkwardGuy** [comment]
> Got it, I think we could allow that in general even without the flag, it's just about checking the root entity metadata in there.

As in expanding the names it checks for by starting from the Base entity getting all possible property names?
