### ISSUE TITLE
Nestjs Cache

### ISSUE THREAD

**Issue by wujingquan** [mikro-orm/mikro-orm#505]
**Describe the bug**

**Stack trace**
```
Error: Collection BookTag[] of entity Book[1] not initialized
    at Collection.checkInitialized (C:\Users\github\workspace\nestjs-example-app\node_modules\mikro-orm\dist\entity\Collection.js:132:19)
    at Collection.count (C:\Users\github\workspace\nestjs-example-app\node_modules\mikro-orm\dist\entity\Collection.js:49:14)
    at Collection.get length [as length] (C:\Users\github\workspace\nestjs-example-app\node_modules\mikro-orm\dist\entity\ArrayCollection.js:70:21)
    at isArrayLike (C:\Users\github\workspace\nestjs-example-app\node_modules\lodash.clonedeep\index.js:1513:42)
    at keys (C:\Users\github\workspace\nestjs-example-app\node_modules\lodash.clonedeep\index.js:1706:10)
    at baseGetAllKeys (C:\Users\github\workspace\nestjs-example-app\node_modules\lodash.clonedeep\index.js:926:16)
    at getAllKeys (C:\Users\github\workspace\nestjs-example-app\node_modules\lodash.clonedeep\index.js:1152:10)
    at baseClone (C:\Users\github\workspace\nestjs-example-app\node_modules\lodash.clonedeep\index.js:889:26)
    at C:\Users\github\workspace\nestjs-example-app\node_modules\lodash.clonedeep\index.js:897:30
    at arrayEach (C:\Users\github\workspace\nestjs-example-app\node_modules\lodash.clonedeep\index.js:140:9)
    at baseClone (C:\Users\github\workspace\nestjs-example-app\node_modules\lodash.clonedeep\index.js:891:3)
    at C:\Users\github\workspace\nestjs-example-app\node_modules\lodash.clonedeep\index.js:897:30
    at arrayEach (C:\Users\github\workspace\nestjs-example-app\node_modules\lodash.clonedeep\index.js:140:9)
    at baseClone (C:\Users\github\workspace\nestjs-example-app\node_modules\lodash.clonedeep\index.js:891:3)
    at C:\Users\github\workspace\nestjs-example-app\node_modules\lodash.clonedeep\index.js:897:30
    at arrayEach (C:\Users\github\workspace\nestjs-example-app\node_modules\lodash.clonedeep\index.js:140:9)
```

**To Reproduce**
Based on [nestjs-example-app](https://github.com/mikro-orm/nestjs-example-app) and [NestJS Cacheing](https://docs.nestjs.com/techniques/caching)

1. install require.
```
npm install --save cache-manager
```
2. import CachaModule and register it.
```
// modules/author/author.module.ts

import { Module, CacheModule } from '@nestjs/common';
import { AuthorController } from './author.controller';
import { OrmModule } from '../orm/orm.module';

@Module({
  imports: [
    OrmModule,
    CacheModule.register({
      ttl: 100
    })],
  controllers: [AuthorController],
  providers: [],
})
export class AuthorModule { }


```
3. Use CacheInterceptor in author controller.

```
import { Get, Controller, Post, Put, HttpStatus, HttpException, Param, Body, UseInterceptors, CacheInterceptor } from '@nestjs/common';
import { EntityRepository, QueryOrder, wrap } from 'mikro-orm';
import { InjectRepository } from 'nestjs-mikro-orm';
import { Author } from '../../entities';

@UseInterceptors(CacheInterceptor)
@Controller('author')
export class AuthorController {

  constructor(@InjectRepository(Author) private readonly authorRepository: EntityRepository<Author>) { }

  @Get()
  async find() {
    return await this.authorRepository.findAll(['books'], { name: QueryOrder.DESC }, 20);
  }

  @Get(':id')
  async findOne(@Param() id: string) {
    const author = await this.authorRepository.findOne(+id, ['books']);

    if (!author) {
      throw new HttpException('Author not found', HttpStatus.NOT_FOUND);
    }

    return author;
  }

  @Post()
  async create(@Body() body: any) {
    if (!body.name || !body.email) {
      throw new HttpException('One of `name, email` is missing', HttpStatus.BAD_REQUEST);
    }

    const author = new Author(body.name, body.email);
    wrap(author).assign(body);
    await this.authorRepository.persist(author);

    return author;
  }

  @Put(':id')
  async update(@Param() id: string, @Body() body: any) {
    const author = await this.authorRepository.findOne(+id);

    if (!author) {
      throw new HttpException('Author not found', HttpStatus.NOT_FOUND);
    }

    wrap(author).assign(body);
    await this.authorRepository.persist(author);

    return author;
  }

}

```

4. create author and book via author and book api.
5. request http://127.0.0.1:3000/author via GET method.

**Expected behavior**

**Additional context**

**Versions**

| Dependency | Version |
Current MikroORM CLI configuration
 - dependencies:
   - mikro-orm 3.0.0-rc
   - node 10.16.0
   - knex 0.20.8
   - mysql2 2.1.0
   - typescript 3.7.5
 - package.json found
 - ts-node enabled
 - searched config paths:
   - C:/Users/github/workspace/nestjs-example-app/src/mikro-orm.config.ts (found)
   - C:/Users/github/workspace/nestjs-example-app/dist/mikro-orm.config.js (not found)
   - C:/Users/github/workspace/nestjs-example-app/mikro-orm.config.ts (not found)
   - C:/Users/github/workspace/nestjs-example-app/mikro-orm.config.js (not found)
 - configuration found
 - will use `entities` array (contains 5 items)

**Comment by wujingquan** [comment]
if use JSON.stringify is success.
```
// modules/author/author.controller.ts

  @Get()
  async find() {
    const result = await this.authorRepository.findAll(['books'], { name: QueryOrder.DESC }, 20);
    return JSON.parse(JSON.stringify(result))
  }
```

**Comment by B4nan** [comment]
Are you really submitting bug from 3.0.0-rc? Also this looks more like something you should report to nestjs, the error is a validation, not a bug. You can't read anything from collections that are not initialized.

**Comment by B4nan** [comment]
If I understand this correctly, nest will cache the return value of your handler, which is here the entity (e.g. `author`). Entities cannot be cached like this, you need to serialise them first.

If you return `wrap(author).toJSON()` instead, it should work.

**Comment by wujingquan** [comment]
thank you very musch.
