### ISSUE TITLE
`raw` helper with named bindings doesn't work when used in filter and orderBy simultaneously 

### ISSUE THREAD

**Issue by ahtcx** [mikro-orm/mikro-orm#5129]
### Describe the bug

I have this code to filter Stop entities by distance from a provided location.

```ts
const query = raw(
  (alias) =>
    `ST_Distance(${alias}.location_coordinates, ST_MakePoint(:longitude, :latitude)::geography)`,
  options
);

const [items, count] = await this.em.findAndCount(
  Stop,
  { [query]: { $lte: NEARBY_STOPS_MAX_DISTANCE_IN_METERS } },
  { orderBy: { [query]: "ASC" } }
);
```

It throws ` Error: Expected 0 bindings, saw 2`, here is the full stacktrace:

<details><summary>Full Stacktrace</summary>

```
DriverException: Expected 0 bindings, saw 2
    at PostgreSqlExceptionConverter.convertException (path/node_modules/.pnpm/@mikro-orm+core@6.0.3/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException (path/node_modules/.pnpm/@mikro-orm+postgresql@6.0.3_@mikro-orm+core@6.0.3/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:42:22)
    at PostgreSqlDriver.convertException (path/node_modules/.pnpm/@mikro-orm+core@6.0.3/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:326:54)
    at path/node_modules/.pnpm/@mikro-orm+core@6.0.3/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:330:24
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PostgreSqlDriver.find (path/node_modules/.pnpm/@mikro-orm+knex@6.0.3_@mikro-orm+core@6.0.3_pg@8.11.3/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:67:24)
    at SqlEntityManager.find (path/node_modules/.pnpm/@mikro-orm+core@6.0.3/node_modules/@mikro-orm/core/EntityManager.js:144:25)
    at async Promise.all (index 0)
    at SqlEntityManager.findAndCount (path/node_modules/.pnpm/@mikro-orm+core@6.0.3/node_modules/@mikro-orm/core/EntityManager.js:380:35)
    at Stop_Service.get_paginated_by_location (path/services/api/dist/modules/stop/stop.service.js:50:32)

previous Error: Expected 0 bindings, saw 2
    at replaceRawArrBindings (path/node_modules/.pnpm/knex@3.1.0_pg@8.11.3/node_modules/knex/lib/formatter/rawFormatter.js:27:11)
    at Ref.toSQL (path/node_modules/.pnpm/knex@3.1.0_pg@8.11.3/node_modules/knex/lib/raw.js:77:13)
    at Ref.toSQL (path/node_modules/.pnpm/knex@3.1.0_pg@8.11.3/node_modules/knex/lib/ref.js:35:18)
    at Ref.Target.toQuery (path/node_modules/.pnpm/knex@3.1.0_pg@8.11.3/node_modules/knex/lib/builder-interface-augmenter.js:9:21)
    at Ref.toString (path/node_modules/.pnpm/knex@3.1.0_pg@8.11.3/node_modules/knex/lib/raw.js:70:17)
    at QueryBuilder.wrapPaginateSubQuery (path/node_modules/.pnpm/@mikro-orm+knex@6.0.3_@mikro-orm+core@6.0.3_pg@8.11.3/node_modules/@mikro-orm/knex/query/QueryBuilder.js:1164:66)
    at QueryBuilder.finalize (path/node_modules/.pnpm/@mikro-orm+knex@6.0.3_@mikro-orm+core@6.0.3_pg@8.11.3/node_modules/@mikro-orm/knex/query/QueryBuilder.js:1089:18)
    at QueryBuilder.getKnexQuery (path/node_modules/.pnpm/@mikro-orm+knex@6.0.3_@mikro-orm+core@6.0.3_pg@8.11.3/node_modules/@mikro-orm/knex/query/QueryBuilder.js:462:14)
    at QueryBuilder.execute (path/node_modules/.pnpm/@mikro-orm+knex@6.0.3_@mikro-orm+core@6.0.3_pg@8.11.3/node_modules/@mikro-orm/knex/query/QueryBuilder.js:594:28)
    at PostgreSqlDriver.find (path/node_modules/.pnpm/@mikro-orm+knex@6.0.3_@mikro-orm+core@6.0.3_pg@8.11.3/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:67:46)
```

</details> 

The raw helper works fine when used in the filter of in `orderBy` seperately, but not when they're in at the same time. I'm using v6.0.3, migrating from v5 with which I used `expr` and `em.raw` which worked fine with my implementation.

### Reproduction

https://github.com/ahtcx/mikro-orm-bug

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.0.3

### Node.js version

20.10.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
This is a wrong usage, you need separate instances for each place (for usage in object keys, as that gets serialized into string first), e.g.:

```ts
const query = () => raw(
  (alias) =>
    `ST_Distance(${alias}.location_coordinates, ST_MakePoint(:longitude, :latitude)::geography)`,
  options
);

const [items, count] = await this.em.findAndCount(
  Stop,
  { [query()]: { $lte: NEARBY_STOPS_MAX_DISTANCE_IN_METERS } },
  { orderBy: { [query()]: "ASC" } }
);
```

**Comment by B4nan** [comment]
Thinking about this a bit more, maybe we could find a way around it, by having some counters on the serialized fragments cache, so we only remove them on the last usage. It would be great to lift this restriction.

**Comment by B4nan** [comment]
Hmm, this is not just about that apparently.

**Comment by B4nan** [comment]
> edit: oh but only if you dont use the parameter from the options, this repro works as expected:

This part is a wontfix to me, your query simply has more values than parameters, and that itself is something to fix in your code. I'll try to resolve the other problem with sharing single raw fragment instance in multiple keys.

**Comment by B4nan** [comment]
All right, this was actually pretty simple.

**Comment by ahtcx** [comment]
Thanks for the explanation on what was going on and the quick resolution!
