### ISSUE TITLE
Using findAndCount causes DriverException: aborted

### ISSUE THREAD

**Issue by NeelDigonto** [mikro-orm/mikro-orm#5175]
### Describe the bug

Calling `find` or `count` solely on a UoW works fine.

But if we call them both at the same time in any order we run into this error.
Also calling just `findAndCount` results in such an error.
Even calling `find` twice or `count` twice in a row results in the same error.

```sh
[query] select "t0".* from "Tenant" as "t0" where "t0"."fts" @@ plainto_tsquery('english', 'org') [took 5 ms, 7 results]
[query] select count(*) as "count" from "Tenant" as "t0" where "t0"."fts" @@ plainto_tsquery('english', 'org') [took 9 ms]
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

DriverException: aborted
    at PostgreSqlExceptionConverter.convertException (/home/fathomless/repo/hashpoint/server/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
    at PostgreSqlExceptionConverter.convertException (/home/fathomless/repo/hashpoint/server/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:42:22)
    at PostgreSqlDriver.convertException (/home/fathomless/repo/hashpoint/server/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:326:54)
    at /home/fathomless/repo/hashpoint/server/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:330:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SqlEntityManager.count (/home/fathomless/repo/hashpoint/server/node_modules/@mikro-orm/core/EntityManager.js:1219:23)
    at async findTenantByFTS (/home/fathomless/repo/hashpoint/server/dist/modules/Tenant/handler.js:58:5)

previous Error: aborted
    at PendingOperation.abort (/home/fathomless/repo/hashpoint/server/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /home/fathomless/repo/hashpoint/server/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /home/fathomless/repo/hashpoint/server/node_modules/tarn/dist/Pool.js:207:53
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client_PG.destroy (/home/fathomless/repo/hashpoint/server/node_modules/knex/lib/client.js:358:9)
    at async PostgreSqlConnection.close (/home/fathomless/repo/hashpoint/server/node_modules/@mikro-orm/knex/AbstractSqlConnection.js:34:9)
    at async PostgreSqlDriver.close (/home/fathomless/repo/hashpoint/server/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:88:9)
    at async MikroORM.close (/home/fathomless/repo/hashpoint/server/node_modules/@mikro-orm/core/MikroORM.js:144:13) {
  code: undefined,
  errno: undefined,
  sqlState: undefined,
  sqlMessage: undefined,
  errmsg: undefined
}

Node.js v20.11.0
```

Running both the queries on the DB manually works fine.

### Reproduction

```ts
import { Entity, PrimaryKey, Property, Index } from '@mikro-orm/core';
import { FullTextType, WeightedFullTextValue } from '@mikro-orm/postgresql';

@Entity()
export class Tenant {
  @PrimaryKey({ type: 'integer' })
  id!: number;

  @Property({ type: 'text' })
  name: string = '';

  @Property({ type: 'text' })
  description = '';

  @Property({ type: 'integer' })
  maxActiveUsers = 20;

  @Property({ type: 'timestamptz' })
  createdAt = new Date();

  @Property({ type: 'timestamptz', onUpdate: () => new Date() })
  updatedAt = new Date();

  @Index({ type: "fulltext" })
  @Property({
    type: new FullTextType('english'),
    nullable: true,
    onCreate: (tenant: Tenant) => ({ A: tenant.name, B: tenant.description }),
    onUpdate: (tenant: Tenant) => ({ A: tenant.name, B: tenant.description })
  })
  fts!: string;

}
```

```ts
await orm.em.find(Tenant, {
        fts: { $fulltext: 'sample' }
    })

await orm.em.count(Tenant, {
        fts: { $fulltext: 'sample' }
    })
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.0.5

### Node.js version

Node 20 LTS

### Operating system

Ubuntu 23.04

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NeelDigonto** [comment]
Ahh, I didn't await the `RequestContext.create()` call, awaiting it seems to fix the issue.
