### ISSUE TITLE
Validation Error for enum with default value

### ISSUE THREAD

**Issue by sualko** [mikro-orm/mikro-orm#5185]
### Describe the bug

Hi everyone,

I think I discovered a bug introduced in v6. If you have an entity with an enum field and a default value, you will get an validation error if you try to use the query builder.

https://github.com/mikro-orm/mikro-orm/issues/5120 has a similar error message for doubles, so I hope no full blown reproduction example is needed. If desired, I can create one.

### Reproduction

```
export enum OrderState {
  NEW = 'new',
  IN_PROGRESS = 'inProgress',
  CLOSED = 'closed',
}

export class Order extends BaseEntity {
  ...

  @Enum({items: () => OrderState})
  state: Opt<OrderState> = OrderState.NEW;
}
```

```
await em.createQueryBuilder(Order).limit(10, 0).getResult();
```

will throw

```
ValidationError: Trying to set Order.state of type 'OrderState' to 'inProgress' of type 'string'
    at Function.fromWrongPropertyType (/usr/src/app/node_modules/@mikro-orm/core/errors.js:23:16)
    at EntityValidator.validateProperty (/usr/src/app/node_modules/@mikro-orm/core/entity/EntityValidator.js:67:44)
    at /usr/src/app/node_modules/@mikro-orm/core/entity/EntityValidator.js:25:35\n    at Array.forEach (<anonymous>)
    at EntityValidator.validate (/usr/src/app/node_modules/@mikro-orm/core/entity/EntityValidator.js:14:20)
    at SqlEntityManager.merge (/usr/src/app/node_modules/@mikro-orm/core/EntityManager.js:1144:22)
    at SqlEntityManager.map (/usr/src/app/node_modules/@mikro-orm/core/EntityManager.js:1120:21)
    at QueryBuilder.getResultList (/usr/src/app/node_modules/@mikro-orm/knex/query/QueryBuilder.js:664:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

If I remove the default value or use `find`, no error occurs. We use ts-morph and a custom naming strategy. 

### What driver are you using?

MySQL

### MikroORM version

6.0.5 and 6.0.6

### Node.js version

18.13.0

### Operating system

Ubuntu 22.04

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sualko** [comment]
Once again, it works like a charm :tada:
