### ISSUE TITLE
qb.getResultAndCount() fails on execution, if Entity field type uses TS allias 

### ISSUE THREAD

**Issue by DenisLutsky** [mikro-orm/mikro-orm#5221]
### Describe the bug

```
...
const qb = this.orm.em.createQueryBuilder(UserEntity, 'user');
const [items, count] = await qb.select('*').getResultAndCount();
...
```

Code like this example will fail with the exception posted below if field of entity using named [type alias](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-aliases) instead of notation with a pipe.

```
type Nullable<T> = T | null;

@Property({ columnType: 'varchar', length: 50, nullable: true })
public firstName!: string | null; // works fine

@Property({ columnType: 'varchar', length: 50, nullable: true })
public firstName!: Nullable<string>; // fails and fails only with QB, em.find working fine
```

```
ValidationError: Trying to set UserEntity.firstName of type 'object' to 'John' of type 'string'
    at Function.fromWrongPropertyType (C:\projects\ChatlynAI\node_modules\@mikro-orm\core\errors.js:23:16)
    at EntityValidator.validateProperty (C:\projects\ChatlynAI\node_modules\@mikro-orm\core\entity\EntityValidator.js:73:48)
    at C:\projects\ChatlynAI\node_modules\@mikro-orm\core\entity\EntityValidator.js:25:35
    at Array.forEach (<anonymous>)
    at EntityValidator.validate (C:\projects\ChatlynAI\node_modules\@mikro-orm\core\entity\EntityValidator.js:14:20)
    at SqlEntityManager.merge (C:\projects\ChatlynAI\node_modules\@mikro-orm\core\EntityManager.js:1147:22)
    at SqlEntityManager.map (C:\projects\ChatlynAI\node_modules\@mikro-orm\core\EntityManager.js:1123:21)
    at QueryBuilder.getResultList (C:\projects\ChatlynAI\node_modules\@mikro-orm\knex\query\QueryBuilder.js:664:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0) - [32/14]
```
    
The problem appeared after updating mikro-orm to version 6.x, on previous (4, 5) there were no problems with that

### Reproduction

1. Setup NestJS application
2. Create TS type alias `type Nullable<T> = T | null;`
3. Create entity class 
eg.
```
@Entity({ tableName: 'users' })
export class UserEntity extends BaseEntity {
  @PrimaryKey()
  public userId!: number;

  @Property({ columnType: 'varchar', length: 50, nullable: true })
  public firstName!: Nullable<string>;

  @Property({ columnType: 'varchar', length: 50, nullable: true })
  public lastName!: Nullable<string>;

  @Property({ columnType: 'varchar', length: 320, unique: true })
  public email!: string;

  @Property({ columnType: 'text' })
  public password!: string;

  @Property({ columnType: 'bool', default: false })
  public isDeleted!: boolean;

  @Property({ columnType: 'timestamp', defaultRaw: 'current_timestamp' })
  public createdAt!: Date;

  @Property({ columnType: 'timestamp', defaultRaw: 'current_timestamp', onUpdate: () => new Date() })
  public updatedAt!: Date;

  public [OptionalProps]?: 'userId' | 'isDeleted' | 'createdAt' | 'updatedAt';
}

```
3. Inject MikroORM instanc with PG driver using `public constructor(private readonly orm: MikroORM<PostgreSqlDriver>) {}`
4. Build query builder request 
e.g.
```
...
const qb = this.orm.em.createQueryBuilder(UserEntity, 'user');
const [items, count] = await qb.select('*').getResultAndCount();
...
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.1.0

### Node.js version

node v20.10.0, npm 10.2.3

### Operating system

Windows 11

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Using ts-morph I guess? That's the important part here that you skipped from the report.

> Setup NestJS application

If this is your first step to set up a minimal repro, you don't understand what a minimal repro means :] You don't need web server to reproduce anything.

**Comment by B4nan** [comment]
What TS version are you using? I am not able to reproduce this with 5.3. On the other hand, I know quite well what's happening and I can fix that, it's just not reproducible on my end.

**Comment by DenisLutsky** [comment]
Thank you for fix.

I'm sorry for bad repro steps.

No, I don't use `ts-morph`
TS version `"typescript": "^5.3.3"`

**Comment by B4nan** [comment]
Hmm, then it needs to be caused by SWC, their reflect-metadata support is pretty broken, so many differences...

Anyway, the fix I did should cover this too, the property type validation is now limited only to a set of known types, and those don't include `object`.

You can also get around such problems by specifying the `type` explicitly:

```ts
@Property({ type: 'string', length: 50, nullable: true }) // strings are by default mapped to varchar
public firstName!: Nullable<string>;
```

And one more note - your entity definition is a bit wrong, since you use `columnType` and `length` next to each other - the length has no effect there, you need to include it in the `columnType` as that is always used as is, without any postprocessing.

```ts
@Property({ columnType: 'varchar(50)', nullable: true })
public firstName!: Nullable<string>;
```
