### ISSUE TITLE
Enum requires 'type' field with reflect-metadata

### ISSUE THREAD

**Issue by NeelDigonto** [mikro-orm/mikro-orm#5255]
### Describe the bug

https://mikro-orm.io/docs/defining-entities#enums

I tried to use enums like above, and do a initial migration with `orm.schema.getUpdateSchemaSQL();` but won't work.
See error below.

I have `import 'reflect-metadata';` at the top of mikro-orm init file, so that isn't the problem and, other stuff like `OneToMany` and `ManyToOne` works fine.

### Reproduction

```ts
@Entity()
export class Log {
  @PrimaryKey({ type: 'int' })
  id!: number;

  @Enum({
    type: () => LogLevel,
  })
  level: LogLevel;
}
```
Will work

```ts
@Entity()
export class Log {
  @PrimaryKey({ type: 'int' })
  id!: number;

  @Enum(() => LogLevel)
  level: LogLevel;
}
```
But this won't, and errors out with

```sh
Error: Please provide either 'type' or 'entity' attribute in Log.level. If you are using decorators, ensure you have 'emitDecoratorMetadata' enabled in your tsconfig.json.
    at ReflectMetadataProvider.initPropertyType (/home/fathomless/repo/redacted/gateway/node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:30:19)
    at ReflectMetadataProvider.initProperties (/home/fathomless/repo/redacted/gateway/node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:23:22)
    at ReflectMetadataProvider.loadEntityMetadata (/home/fathomless/repo/redacted/gateway/node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:10:14)
    at MetadataDiscovery.discoverEntity (/home/fathomless/repo/redacted/gateway/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:284:31)
    at MetadataDiscovery.discoverReferences (/home/fathomless/repo/redacted/gateway/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:220:18)
    at MetadataDiscovery.findEntities (/home/fathomless/repo/redacted/gateway/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:139:14)
    at MetadataDiscovery.discover (/home/fathomless/repo/redacted/gateway/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:43:20)
    at MikroORM.discoverEntities (/home/fathomless/repo/redacted/gateway/node_modules/@mikro-orm/core/MikroORM.js:164:46)
    at PostgreSqlMikroORM.init (/home/fathomless/repo/redacted/gateway/node_modules/@mikro-orm/core/MikroORM.js:40:19)
    at async initORM (/home/fathomless/repo/redacted/gateway/dist/db/db.js:23:17)
```

`mikro-orm.config.ts`
```ts
const config: Options = {
  driver: PostgreSqlDriver,
  dbName: vtEnv.pgDB,
  user: vtEnv.pgUser,
  password: vtEnv.pgPassword,
  host: vtEnv.pgHost,
  port: vtEnv.pgPort,
  //entities: ['dist/**/*.entity.js'],
  //entitiesTs: ['src/**/*.entity.ts'],
  entities: [Log, KiteAccount, KiteSession, KiteInstrumentSync, KiteInstrument],
  metadataProvider: ReflectMetadataProvider,
  // enable debug mode to log SQL queries and discovery information
  namingStrategy: EntityCaseNamingStrategy,
  debug: false,
  extensions: [Migrator],
};

export default config;
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.1.4

### Node.js version

20.11.1 LTS

### Operating system

Ubuntu 23.04

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Also how does your enum look like? And whats your tsconfig?

**Comment by B4nan** [comment]
I'd still like to see a complete repro as this is not reproducible with the setup in this repository, but the fix should cover it most probably.

**Comment by NeelDigonto** [comment]
@B4nan I am using swc to compile my TS files.

`tsconfig.json`
```ts
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "allowJs": false,
    "removeComments": true,
    "resolveJsonModule": true,
    "typeRoots": ["./node_modules/@types"],
    "sourceMap": true,
    "outDir": "dist",
    "strict": true,
    "lib": ["DOM", "ESNext"],
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declaration": true,
    "moduleResolution": "Node",
    "skipLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["src/**/*", "__tests__/**/*"],
  "exclude": ["node_modules"]
}

```

I compile to cjs

LogLevel defination 
```ts
export enum LogLevel {
  FATAL = 'fatal',
  ERROR = 'error',
  WARN = 'warn',
  INFO = 'info',
  DEBUG = 'debug',
  TRACE = 'trace',
}

```

The output files without explicit `type`.
```js
_ts_decorate([
    (0, _postgresql.PrimaryKey)({
        type: 'int'
    })
], Log.prototype, "id", void 0);
_ts_decorate([
    (0, _postgresql.Enum)(()=>LogLevel)
], Log.prototype, "level", void 0);
```

And with explicit `type` specified
```js
_ts_decorate([
    (0, _postgresql.PrimaryKey)({
        type: 'int'
    })
], Log.prototype, "id", void 0);
_ts_decorate([
    (0, _postgresql.Enum)({
        type: ()=>LogLevel
    })
], Log.prototype, "level", void 0);
```

**Comment by NeelDigonto** [comment]
@boenrobot I have tested it.

I didn't need the `"legacyDecorator": true`, the `"decoratorMetadata": true` was enough.

Also with and without the `"legacyDecorator": true`, it produced the same build output.
