### ISSUE TITLE
Add support for entities without primary key

### ISSUE THREAD

**Issue by Loown** [mikro-orm/mikro-orm#562]
### Bug
Happens when you want to create a entity without primaryKey using type `AnyEntity`

### Error

> TypeError: Cannot read property 'forEach' of undefined
>     at MetadataDiscovery.initColumnType (/home/lown/validi/api/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:432:26)
>     at /home/lown/validi/api/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:41:86
>     at Array.forEach (<anonymous>)
>     at /home/lown/validi/api/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:41:65
>     at Array.forEach (<anonymous>)
>     at MetadataDiscovery.discover (/home/lown/validi/api/node_modules/mikro-orm/dist/metadata/MetadataDiscovery.js:41:18)
>     at async Function.init (/home/lown/validi/api/node_modules/mikro-orm/dist/MikroORM.js:45:24)
>     at async Injector.instantiateClass (/home/lown/validi/api/node_modules/@nestjs/core/injector/injector.js:293:37)
>     at async callback (/home/lown/validi/api/node_modules/@nestjs/core/injector/injector.js:76:30)
>     at async Injector.resolveConstructorParams (/home/lown/validi/api/node_modules/@nestjs/core/injector/injector.js:117:24)
>     at async Injector.loadInstance (/home/lown/validi/api/node_modules/@nestjs/core/injector/injector.js:80:9)
>     at async Injector.loadProvider (/home/lown/validi/api/node_modules/@nestjs/core/injector/injector.js:37:9)
>     at async Promise.all (index 4)
>     at async InstanceLoader.createInstancesOfProviders (/home/lown/validi/api/node_modules/@nestjs/core/injector/instance-loader.js:42:9)
>     at async /home/lown/validi/api/node_modules/@nestjs/core/injector/instance-loader.js:27:13
>     at async Promise.all (index 3)

### Reproduce
Create an entity without primaryKey

I'm using NestJS

**Comment by B4nan** [comment]
This particular error is fixed in v4. But generally, entities without PK are not supported, you would still get a validation error.

**Comment by Loown** [comment]
OK thanks !

**Comment by B4nan** [comment]
What do you need this for?

**Comment by B4nan** [comment]
Closing due to inactivity.

**Comment by mikey0000** [comment]
Hi I'd like this feature as I'm working with the Google GTFS specification and a number of tables don't have primary keys. The tables themselves are read only.

**Comment by mikey0000** [comment]
I'll also add I'm using the entities to represent materialized views as well

**Comment by B4nan** [comment]
Without a PK you can't load an entity to identity map, that is the biggest blocker - it would require lots of (rather small) changes pretty much everywhere. 

Still a table without PK seems very weird to me, you really don't have any naturaly unique column in there? How do you even use such table if there is nothing unique you could use to filter?

**Comment by mikey0000** [comment]
Just peeking at the gtfs spec again and there are a lot of ids that are externally referenced(to other tables). Looks like I'd need to spend a bit more time adjusting the entities. I'd love to know if that's what I'm missing. See developers.google.com/transit/gtfs/reference#calendar_dates

Im very new to mikro, but so far loving it.

**Comment by B4nan** [comment]
Btw as a last resort, you can still use the driver to load any database table (without entity mapping).

**Comment by mikey0000** [comment]
Do you have an example? Also can you add into the docs about using driverOptions for ssl, I figured it out but it took me a little bit I'm sure others will get stuck on it.

8/04/2021 8:19:43 pm Martin Adámek ***@***.***>:

**Comment by B4nan** [comment]
> Do you have an example? 

Just get the driver and use the same API as with EM, e.g. `em.getDriver().find('table_name', { ...conds })`. Check the [`IDatabaseDriver`](https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/drivers/IDatabaseDriver.ts) interface to see the methods. 

> Also can you add into the docs about using driverOptions for ssl, I figured it out but it took me a little bit I'm sure others will get stuck on it.

Sure.

**Comment by mikey0000** [comment]
Ahh I see.

Thanks

8/04/2021 9:58:26 pm Martin Adámek ***@***.***>:
