### ISSUE TITLE
Wrong migration schema generated when use EntityCaseNamingStrategy

### ISSUE THREAD

**Issue by triadium** [mikro-orm/mikro-orm#5681]
### Describe the bug

We use EntitySchema to define entities for our system and EntityCaseNamingStrategy
We get an error during the schema update
```
D:\modyno\node_modules\@mikro-orm\postgresql\PostgreSqlExceptionConverter.js:42
                return new core_1.InvalidFieldNameException(exception);
                       ^
InvalidFieldNameException: alter table "some_schema"."EntityOne" add column "auxField3" varchar(255) not null default 'Sambook AUX data';
alter table "some_schema"."EntityOne" rename column "auxfield2" to "auxField3"; - column "auxfield2" does not exist
    at PostgreSqlExceptionConverter.convertException (D:\modyno\node_modules\@mikro-orm\postgresql\PostgreSqlExceptionConverter.js:42:24)
    at PostgreSqlDriver.convertException (D:\modyno\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:344:54)
    at D:\modyno\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:348:24
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SqlSchemaGenerator.execute (D:\modyno\node_modules\@mikro-orm\knex\schema\SqlSchemaGenerator.js:467:17)
    at SqlSchemaGenerator.updateSchema (D:\modyno\node_modules\@mikro-orm\knex\schema\SqlSchemaGenerator.js:155:9)
    at AppService.onApplicationBootstrap (D:\modyno\src\app.service.ts:77:5)
    at async Promise.all (index 0)
    at callModuleBootstrapHook (D:\modyno\node_modules\@nestjs\core\hooks\on-app-bootstrap.hook.js:43:5)
    at NestApplication.callBootstrapHook (D:\modyno\node_modules\@nestjs\core\nest-application-context.js:243:13)

    at Parser.parseErrorMessage (D:\modyno\node_modules\pg-protocol\src\parser.ts:369:69)
    at Parser.handlePacket (D:\modyno\node_modules\pg-protocol\src\parser.ts:188:21)
    at Parser.parse (D:\modyno\node_modules\pg-protocol\src\parser.ts:103:30)
    at Socket.<anonymous> (D:\modyno\node_modules\pg-protocol\src\index.ts:7:48)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Socket.Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I see two errors:
1. The field was renamed but there is generated the drop-add column statements, not only a rename statement
2. The "auxField2" field is used in lowercase

We would like a more predictable behavior when updating the schema. For example, add an option that will indicate that these fields are new, you do not need to search for renaming them, and then the choice between the two options will be obvious.

### Reproduction

```
const MikroOrmConfig: Options = {
      dbName: configService.get('MODYNO_POSTGRES_DB'),
      driver: PostgreSqlDriver,
      namingStrategy: EntityCaseNamingStrategy,  
      entities: [],  
      host: configService.get('MODYNO_POSTGRES_HOST'),      
      password: configService.get('MODYNO_POSTGRES_PASSWORD'),
      port: configService.get('MODYNO_POSTGRES_PORT'),      
      user: configService.get('MODYNO_POSTGRES_USER'),
      metadataCache: {
        enabled: false
      },
      debug: true,
    }

// auxField2 is renamed to auxField3
const sambookSchema = new EntitySchema<ICmsObject>({
      name: 'EntityOne',
      schema: 'some_schema',
      properties: {
        id: { type: 'uuid', defaultRaw: 'gen_random_uuid()', primary: true },        
        domainId: { type: 'string', formula: "'some_schema'", default: 'some_schema' },
        entityId: { type: 'string', formula: "'Sambook'", default: 'Sambook' },
        title: { type: 'string', returning: true, nullable: true },        
        // auxField2: { type: 'string', default: "Sambook AUX data" },
        auxField3: { type: 'string', default: "Sambook AUX data" },
      },
    });

MikroOrmConfig.entities.push(sambookSchema);
const orm1 = await MikroORM.init(MikroOrmConfig)    

const sqlUpdateSchema = await orm1.getSchemaGenerator().getUpdateSchemaSQL()
console.log('======================== UPDATE =====================');    
console.log(sqlUpdateSchema);
```

```
======================== UPDATE =====================
set names 'utf8';
set session_replication_role = 'replica';

alter table "some_schema"."EntityOne" drop column "auxField2";

alter table "some_schema"."EntityOne" add column "auxField3" varchar(255) not null default 'Sambook AUX data';
alter table "some_schema"."EntityOne" rename column "auxfield2" to "auxField3";

set session_replication_role = 'origin';
```

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.2.8

### Node.js version

v20.11.1

### Operating system

Windows 11

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by triadium** [comment]
Sorry, I just saw that a new version has recently been released in which this bug does not repdroduced itself. We will try to use version 6.2.9 on our system. It doesn't have this bug, but we may run into other problems. After regression testing, I will open a new door if necessary.
