### ISSUE TITLE
Index Creation Query is Generated Twice When Using Schema Generator in SQLite Driver Environment

### ISSUE THREAD

**Issue by myuoong** [mikro-orm/mikro-orm#5725]
### Describe the bug

This issue occurs only when there are relational columns present.

### Reproduction

``` ts
import { ManyToOne, MikroORM, raw, Ref } from '@mikro-orm/sqlite';
import { Entity, Index, PrimaryKey, Property } from '@mikro-orm/core';

@Entity()
@Index({ properties: ['age'] }) //it works
class User {
  @PrimaryKey()
  id!: number;

  @Property()
  age!: number;
}

@Entity()
@Index({ properties: ['user'] }) //it not works
class Apartment {
  @PrimaryKey()
  id!: number;

  @ManyToOne(() => User, {
    fieldName: 'ref_user_id',
    referenceColumnName: 'id',
    ref: true,
  })
  user: Ref<User>;
}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ':memory:',
    entities: [User, Apartment],
    debug: ['query', 'query-params'],
    logger: console.log.bind(console),
    allowGlobalContext: true, // only for testing
  });
  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close(true);
});
```

Logs
```
  console.log
    [query] create table `user` (`id` integer not null primary key autoincrement, `age` integer not null); [took 0 ms, 0 results]

      at DefaultLogger.log (../../node_modules/.pnpm/nexus.tosspayments.bz+@mikro-orm+core@6.2.9/node_modules/@mikro-orm/core/logging/DefaultLogger.js:38:14)

  console.log
    [query] create index `user_age_index` on `user` (`age`); [took 0 ms, 0 results]

      at DefaultLogger.log (../../node_modules/.pnpm/nexus.tosspayments.bz+@mikro-orm+core@6.2.9/node_modules/@mikro-orm/core/logging/DefaultLogger.js:38:14)

  console.log
    [query] create table `apartment` (`id` integer not null primary key autoincrement, `ref_user_id` integer not null, constraint `apartment_ref_user_id_foreign` foreign key(`ref_user_id`) references `user`(`id`) on update cascade); [took 0 ms, 0 results]

      at DefaultLogger.log (../../node_modules/.pnpm/nexus.tosspayments.bz+@mikro-orm+core@6.2.9/node_modules/@mikro-orm/core/logging/DefaultLogger.js:38:14)

  console.log
    [query] create index `apartment_ref_user_id_index` on `apartment` (`ref_user_id`); [took 0 ms, 0 results]

      at DefaultLogger.log (../../node_modules/.pnpm/nexus.tosspayments.bz+@mikro-orm+core@6.2.9/node_modules/@mikro-orm/core/logging/DefaultLogger.js:38:14)

  console.log
    [query] create index `apartment_ref_user_id_index` on `apartment` (`ref_user_id`); [took 1 ms]

      at DefaultLogger.log (../../node_modules/.pnpm/nexus.tosspayments.bz+@mikro-orm+core@6.2.9/node_modules/@mikro-orm/core/logging/DefaultLogger.js:38:14)


create index `apartment_ref_user_id_index` on `apartment` (`ref_user_id`); - SQLITE_ERROR: index apartment_ref_user_id_index already exists
TableExistsException: create index `apartment_ref_user_id_index` on `apartment` (`ref_user_id`); - SQLITE_ERROR: index apartment_ref_user_id_index already exists
```

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.2.9

### Node.js version

18

### Operating system

mac os

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Slack](https://join.slack.com/t/mikroorm/shared_invite/enQtNTM1ODYzMzM4MDk3LWM4ZDExMjU5ZDhmNjA2MmM3MWMwZmExNjhhNDdiYTMwNWM0MGY5ZTE3ZjkyZTMzOWExNDgyYmMzNDE1NDI5NjA).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
FYI foreign keys are all indexed (in SQLite and MySQL), it's you who creates the duplicity, not the ORM. We can surely deal with this automatically.
