### ISSUE TITLE
Incorrect key when filtering on relations

### ISSUE THREAD

**Issue by Webbly25** [mikro-orm/mikro-orm#5989]
### Describe the bug

When getting a relation the incorrect key is being used. The default `id` field is being used instead of the desired `document_id`.

I have three entities: `Document`, `DocumentVersion`, and `DocumentVersionReview`.
`Document` has many `DocumentVersion`s, and `DocumentVersion` has many `DocumentVersionReview`s.

When I filter versions (for example to get only approved reviews):
``` typescript
const doc = await documentRepo.findOneOrFail({ id: 1 });
const version = await doc.versions
	.loadItems({
		where: { reviews: { $every: { approved: true } } },
		orderBy: { versionNumber: 'DESC' }
	})
	.then(res => (res.length ? res[0] : null));
```

I get the following error:
```
InvalidFieldNameException: select `t0`.* from `document_version` as `t0` where `t0`.`document_id` in (1) and `t0`.`id` not in (select `t0`.`id` from `document_version` as `t0` inner join `document_version_review` as `d1` on `t0`.`document_id` = `d1`.`document_version_document_id` and `t0`.`version_number` = `d1`.`document_version_version_number` where not (`d1`.`approved` = true)) order by `t0`.`version_number` desc - SQLITE_ERROR: no such column: t0.id
    at SqliteExceptionConverter.convertException (C:\Users\Ryan\Documents\Projects\Misc\mikroorm-relation-issue\node_modules\@mikro-orm\sqlite\SqliteExceptionConverter.js:35:20)
    at SqliteDriver.convertException (C:\Users\Ryan\Documents\Projects\Misc\mikroorm-relation-issue\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:345:54)
    at C:\Users\Ryan\Documents\Projects\Misc\mikroorm-relation-issue\node_modules\@mikro-orm\core\drivers\DatabaseDriver.js:349:24
    at async SqliteDriver.find (C:\Users\Ryan\Documents\Projects\Misc\mikroorm-relation-issue\node_modules\@mikro-orm\knex\AbstractSqlDriver.js:68:24)
    at async SqlEntityManager.find (C:\Users\Ryan\Documents\Projects\Misc\mikroorm-relation-issue\node_modules\@mikro-orm\core\EntityManager.js:144:25)
    at async EntityLoader.findChildren (C:\Users\Ryan\Documents\Projects\Misc\mikroorm-relation-issue\node_modules\@mikro-orm\core\entity\EntityLoader.js:242:23)
    at async EntityLoader.populateMany (C:\Users\Ryan\Documents\Projects\Misc\mikroorm-relation-issue\node_modules\@mikro-orm\core\entity\EntityLoader.js:148:22)
    at async EntityLoader.populateField (C:\Users\Ryan\Documents\Projects\Misc\mikroorm-relation-issue\node_modules\@mikro-orm\core\entity\EntityLoader.js:274:27)
    at async EntityLoader.populate (C:\Users\Ryan\Documents\Projects\Misc\mikroorm-relation-issue\node_modules\@mikro-orm\core\entity\EntityLoader.js:53:13)
    at async SqlEntityManager.populate (C:\Users\Ryan\Documents\Projects\Misc\mikroorm-relation-issue\node_modules\@mikro-orm\core\EntityManager.js:1361:9)
```

DocumentVersion.entity.ts
``` typescript
@Entity({
	discriminatorColumn: 'type',
	discriminatorMap: {
		[DocumentType.TRAINING_DOCUMENT]: 'TrainingDocument',
		[DocumentType.FORM]: 'Form',
		[DocumentType.GENERATED_RECORD]: 'GeneratedRecord'
	}
})
export abstract class DocumentVersion {
	[PrimaryKeyProp]?: ['document', 'versionNumber'];

	@ManyToOne(() => Document, { primary: true })
	document: Ref<Document>;

	@PrimaryKey()
	versionNumber: number;

	@Enum()
	type: DocumentType;

	@OneToMany(() => DocumentVersionReview, review => review.documentVersion)
	reviews = new Collection<DocumentVersionReview>(this);
}

// ...
```

DocumentVersionReview.entity.ts
``` typescript
@Entity()
export class DocumentVersionReview {
	@PrimaryKey()
	id: number;

	@ManyToOne()
	documentVersion: Ref<DocumentVersion>;

	@Property()
	approved: boolean;
}

```

It could be because the entities are all using single table inheritance.
My main project is using Postgres, but the reproduction is using SQLite and still has the issue.

### Reproduction

[Reproduction](https://github.com/Webbly25/mikroorm-relation-issue)

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.3.7

### Node.js version

Node v20.14.0, typescript@5.5.4

### Operating system

Windows 11

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Can you please simplify the reproduction and move everything into a single file? It's quite huge now, also please remove usage of seeder and ts-morph provider.

**Comment by Webbly25** [comment]
I have updated the repository as per your request
