### ISSUE TITLE
Failed to update all child entities of a STI at once using flush

### ISSUE THREAD

**Issue by enjoykcc456** [mikro-orm/mikro-orm#6069]
### Describe the bug

Hi, I have this entity structure.

```
@Entity({
  tableName: 'appointment-sti',
  repository: () => AppointmentStiRepository,
})
export class AppointmentStiEntity {
  @PrimaryKey({ unique: true })
  id: string = nanoid();

  @OneToMany(() => VenueStiEntity, (venue) => venue.appointment)
  venues = new Collection<VenueStiEntity>(this);
}

@Entity({
  tableName: 'venue-sti',
  discriminatorColumn: 'type',
  discriminatorValue: 'Venue',
  repository: () => VenueStiRepository,
})
export abstract class VenueStiEntity extends AuditableEntity {
  [EntityRepositoryType]?: VenueRepository;

  @PrimaryKey({ unique: true })
  id: string = nanoid();

  @Property()
  name: string;

  @Enum(() => VenueType)
  type: VenueType; // discriminator for polymorphic behavior

  @Property({ persist: false }) // This will not be persisted in the database
  get appointmentId(): string {
    return this.appointment ? this.appointment.id : null;
  }

  @ManyToOne(() => AppointmentStiEntity)
  appointment: AppointmentStiEntity;
}

@Entity({
  discriminatorValue: VenueType.Physical,
  repository: () => PhysicalVenueStiRepository,
})
export class PhysicalVenueStiEntity extends VenueStiEntity {
  @Property()
  street: string;

  @Property()
  block: string;
}

@Entity({
  discriminatorValue: VenueType.Virtual,
  repository: () => VirtualVenueStiRepository,
})
export class VirtualVenueStiEntity extends VenueStiEntity {
  @Property()
  meetingLink: string;

  @Property()
  passcode: string;
}
```

Repositories
```
export class VenueStiRepository extends EntityRepository<VenueStiEntity> {}
export class PhysicalVenueStiRepository extends EntityRepository<PhysicalVenueStiEntity> {}
export class VirtualVenueStiRepository extends EntityRepository<VirtualVenueStiEntity> {}
```

Then, when i created physical venue and virtual venue, did a findAll with the venue repository and try to make changes to the venues based on the type.

```
    const appointment = this.appointmentStiRepository.create({});

    const physicalVenue = new PhysicalVenueStiEntity();
    physicalVenue.name = 'Venue 1';
    physicalVenue.street = 'Street 1';
    physicalVenue.block = 'Block 1';
    physicalVenue.appointment = appointment;

    const virtualVenue = new VirtualVenueStiEntity();
    virtualVenue.name = 'Venue 2';
    virtualVenue.meetingLink = 'Link 1';
    virtualVenue.passcode = 'Passcode 1';
    virtualVenue.appointment = appointment;

    this.venueStiRepository
      .getEntityManager()
      .persistAndFlush([physicalVenue, virtualVenue]);

    const venues = await this.venueStiRepository.findAll();
    console.log({ venues });

    // random update
    for (const venue of venues) {
      if (venue instanceof PhysicalVenueStiEntity) {
        venue.block = `Block ${Math.random()}`;
      }

      if (venue instanceof VirtualVenueStiEntity) {
        venue.passcode = `Passcode ${Math.random()}`;
      }
    }

    await this.em.flush();
```

I got this error 
```
TypeError: Cannot read properties of undefined (reading 'fieldNames')
    at /Users/enjoy/Desktop/postgresql-orm/node_modules/.pnpm/@mikro-orm+knex@6.3.8_@mikro-orm+core@6.3.8_pg@8.12.0/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:572:18
    at Set.forEach (<anonymous>)
    at PostgreSqlDriver.nativeUpdateMany (/Users/enjoy/Desktop/postgresql-orm/node_modules/.pnpm/@mikro-orm+knex@6.3.8_@mikro-orm+core@6.3.8_pg@8.12.0/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:569:14)
    at ChangeSetPersister.persistManagedEntitiesBatch (/Users/enjoy/Desktop/postgresql-orm/node_modules/.pnpm/@mikro-orm+core@6.3.8/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:190:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ChangeSetPersister.persistManagedEntities (/Users/enjoy/Desktop/postgresql-orm/node_modules/.pnpm/@mikro-orm+core@6.3.8/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:161:13)
```

When i put some logs at the nativeUpdateMany, this is what i got. Realised that the error happened because failed to find passcode from the PhysicalVenueStiEntity. 
```
{
  changeSets: [
    ChangeSet<PhysicalVenueStiEntity> {
      entity: [PhysicalVenueStiEntity],
      type: 'update',
      payload: [Object],
      primaryKey: undefined,
      name: 'PhysicalVenueStiEntity',
      rootName: 'VenueStiEntity',
      collection: 'venue-sti',
      schema: undefined,
      originalEntity: [Object]
    },
    ChangeSet<VirtualVenueStiEntity> {
      entity: [VirtualVenueStiEntity],
      type: 'update',
      payload: [Object],
      primaryKey: undefined,
      name: 'VirtualVenueStiEntity',
      rootName: 'VenueStiEntity',
      collection: 'venue-sti',
      schema: undefined,
      originalEntity: [Object]
    }
  ]
}
{ entityName: 'PhysicalVenueStiEntity' }
{
  data: [
    {
      block: 'Block 0.18024144130084618',
      updatedAt: 2024-09-25T09:17:07.932Z
    },
    {
      passcode: 'Passcode 0.4463114972170372',
      updatedAt: 2024-09-25T09:17:07.932Z
    }
  ]
}
{ keys: Set(3) { 'block', 'updatedAt', 'passcode' } }
```
When i do updates on only one type of the venues then everything works fine. Hence, would like to check did i do something wrong? What i want to achieve is to make changes to all the retrieved venues (both physical and virtual venue) and update them at one shot in one transaction using flush. 

### Reproduction

-

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

6.3.7

### Node.js version

18.16.0

### Operating system

Mac 14.6.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Please provide a [complete reproduction](https://github.com/mikro-orm/reproduction), a script I can run to see this.

    this.venueStiRepository
      .getEntityManager()
      .persistAndFlush([physicalVenue, virtualVenue]);

Note that you are missing an await here.

**Comment by enjoykcc456** [comment]
Hi @B4nan . Thanks for the reply. Please find the reproduction [here](https://github.com/enjoykcc456/reproduction).
