### ISSUE TITLE
Cannot initialize unidirectional M:N relations using  `loadItems` in mongo

### ISSUE THREAD

**Issue by snigdha920** [mikro-orm/mikro-orm#6079]
### Describe the bug

Sometimes, we get a `Collection of entity not initialized` error when loading the collection using `loadItems`

```
Error: Collection<Workspace> of entity QuorumQBFTBlockchainNetwork[66e18d930cc3ee508ce796dd] not initialized
    at Collection.checkInitialized (/app/node_modules/@mikro-orm/core/entity/Collection.js:327:19)
    at Collection.getItems (/app/node_modules/@mikro-orm/core/entity/Collection.js:108:18)
    at /app/node_modules/@mikro-orm/core/entity/EntityLoader.js:454:40
    at Array.reduce (<anonymous>)
    at EntityLoader.getChildReferences (/app/node_modules/@mikro-orm/core/entity/EntityLoader.js:453:39)
    at EntityLoader.findChildren (/app/node_modules/@mikro-orm/core/entity/EntityLoader.js:211:31)
    at EntityLoader.populateMany (/app/node_modules/@mikro-orm/core/entity/EntityLoader.js:150:33)
    at processTicksAndRejections (/Users/snigdhasingh/Development/btp/apps/api/lib/internal/process/task_queues.js:95:5)
    at EntityLoader.populateField (/app/node_modules/@mikro-orm/core/entity/EntityLoader.js:287:27)
    at EntityLoader.populate (/app/node_modules/@mikro-orm/core/entity/EntityLoader.js:57:13)
    at MongoEntityManager.populate (/app/node_modules/@mikro-orm/core/EntityManager.js:1367:9)
    at Collection.init (/app/node_modules/@mikro-orm/core/entity/Collection.js:248:9)
    at Collection.load (/app/node_modules/@mikro-orm/core/entity/Collection.js:43:13)
    at Collection.loadItems (/app/node_modules/@mikro-orm/core/entity/Collection.js:58:9)
    at BlockchainNetworkResolver.canInviteWorkspaces (/app/src/modules/blockchain/api/lib/resolvers/blockchain-network.resolver.ts:106:14) {stack: 'Error: Collection<Workspace> of entity Quorum…olvers/blockchain-network.resolver.ts:106:14)', message: 'Collection<Workspace> of entity QuorumQBFTBl…rk[66e18d930cc3ee508ce796dd] not initialized'}

```

### Reproduction

```ts
import {
  Collection,
  Entity,
  ManyToMany,
  MikroORM,
  PrimaryKey,
  Property,
  ObjectId,
} from '@mikro-orm/mongodb';

@Entity()
class Manager {

  @PrimaryKey()
  _id!: ObjectId;

  @ManyToMany({
    entity: 'Task',
    lazy: true,
  })
  tasks = new Collection<Task>(this);

}

@Entity()
class Task {

  @PrimaryKey()
  _id!: ObjectId;

  @Property()
  name!: string;

}

describe('GH issue 6079', () => {
  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [Manager, Task],
      dbName: ':memory:',
    });
    await orm.schema.createSchema();

    const task = new Task();
    task.name = 'task';

    const manager = new Manager();
    manager.tasks.set([task]);

    await orm.em.persistAndFlush(manager);
    orm.em.clear();
  });

  afterAll(() => orm.close(true));

  test('owning side can intialize collections using loadItems', async () => {
    const [manager] = await orm.em.findAll(Manager);
    expect(manager.tasks.isInitialized()).toBe(false);

    await manager.tasks.loadItems();
    expect(manager.tasks.isInitialized()).toBe(true);
    expect(manager.tasks).toHaveLength(1);
  });
});
```

### What driver are you using?

@mikro-orm/mongodb

### MikroORM version

6.3.11

### Node.js version

22.9.0

### Operating system

MacOS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
> Enough info in the ticket along with a proposed fix, let me know if a repro is needed

I don't know what you mean by this. Repro is always needed, please provide one.

**Comment by snigdha920** [comment]
```
import {
  Collection,
  Entity,
  ManyToMany,
  MikroORM,
  PrimaryKey,
  Property,
  ObjectId,
} from "@mikro-orm/mongodb";

@Entity({
  discriminatorColumn: "type",
  abstract: true,
})
@Entity()
class Manager {
  @PrimaryKey()
  _id!: ObjectId;

  @ManyToMany({
    entity: "Task",
    lazy: true,
  })
  tasks = new Collection<Task>(this);
}

@Entity()
class Task {
  @PrimaryKey()
  _id!: ObjectId;

  @Property()
  name!: string;
}

describe("GH issue 4423", () => {
  let orm: MikroORM;

  beforeAll(async () => {
    orm = await MikroORM.init({
      entities: [Manager, Task],
      dbName: ":memory:",
    });
    await orm.schema.createSchema();

    const task = new Task();
    task.name = "task";

    const manager = new Manager();
    manager.tasks.set([task]);

    await orm.em.persistAndFlush(manager);
    orm.em.clear();
  });

  afterAll(() => orm.close(true));

  test("owning side can intialize collections using loadItems", async () => {
    const manager = (await orm.em.findAll(Manager))[0];
    expect(manager).not.toBeNull();
    expect(manager.tasks.isInitialized()).toBe(false);

    const tasks = await manager?.tasks.loadItems();
    expect(tasks).not.toBeNull();
    expect(manager.tasks.isInitialized()).toBe(true);
  });
});

```

**Comment by B4nan** [comment]
I see, M:N with `lazy: true`, we surely have no tests for that, first time seeing this. This is why I am always asking for reproductions, you haven't mentioned anything like that in your issue 🙃

**Comment by snigdha920** [comment]
I want to add a unit test for this in my codebase too, where I fetch an entity and ensure a collection on it is not initialised without adding the `lazy` property on the collection (because i don't want my property to actually be lazy loaded, just want to test loadItems on un-initialized collections). Now, when I'm fetching entities from the db, the collection is always initialised, is there a way I can ensure a collection remains uninitialised without adding the `lazy` property?  

It's important for me to have this unit test also in my codebase because when this doesn't work, authorisation logic fails and blank pages are rendered in production for all users, which is obviously a huge issue for us

**Comment by B4nan** [comment]
your test works fine if i use a regular db name instead of `:memory:` which is sqlite specific. except the second assertion which is wrong, the `completedTasks` is not lazy, so it will be (partially) initialized even without any population.

this is passing:

```ts
import { Collection, Entity, ManyToMany, MikroORM, PrimaryKey, Property, ObjectId } from '@mikro-orm/mongodb';

@Entity()
class Manager {

  @PrimaryKey()
  _id!: ObjectId;

  @ManyToMany({ entity: () => Task, lazy: true })
  pendingTasks = new Collection<Task>(this);

  @ManyToMany({ entity: () => Task })
  completedTasks = new Collection<Task>(this);

}

@Entity()
class Task {

  @PrimaryKey()
  _id!: ObjectId;

  @Property()
  name!: string;

}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    entities: [Manager, Task],
    dbName: '6079',
  });
  await orm.schema.refreshDatabase();

  const pendingTask = new Task();
  pendingTask.name = 'pending task';

  const manager = new Manager();
  manager.pendingTasks.set([pendingTask]);

  await orm.em.persistAndFlush(manager);
  orm.em.clear();
});

afterAll(() => orm.close(true));

test('owning side can intialize collections using loadItems', async () => {
  const [manager] = await orm.em.findAll(Manager);
  expect(manager.pendingTasks.isInitialized()).toBe(false);
  // expect(manager.completedTasks.isInitialized()).toBe(false);

  await manager.pendingTasks.loadItems();
  await manager.completedTasks.loadItems();

  expect(manager.pendingTasks).toHaveLength(1);
  expect(manager.pendingTasks.isInitialized(true)).toBe(true);

  expect(manager.completedTasks).toHaveLength(0);
});
```
