### ISSUE TITLE
Issue with bigint primary key and forceEntityConstructor

### ISSUE THREAD

**Issue by petergledhillinclusive** [mikro-orm/mikro-orm#6092]
### Describe the bug

There appears to be an issue when using forceEntityConstructor on entities which have collections that use bigint for their primary key.

The issue happens when retrieving the parent object and loading it's collection.  It seems like each object in the collection is trying to be parsed as a bigint and this caues the error:

```js
 SyntaxError: Cannot convert [object Object] to a BigInt
        at BigInt (<anonymous>)

      at BigIntType.convertToJSValue (node_modules/@mikro-orm/core/types/BigIntType.js:32:24)
      at node_modules/@mikro-orm/core/entity/EntityFactory.js:308:62
          at Array.map (<anonymous>)
      at EntityFactory.extractConstructorParams (node_modules/@mikro-orm/core/entity/EntityFactory.js:278:39)
      at EntityFactory.createEntity (node_modules/@mikro-orm/core/entity/EntityFactory.js:193:33)
      at EntityFactory.create (node_modules/@mikro-orm/core/entity/EntityFactory.js:58:39)
      at SqlEntityManager.find (node_modules/@mikro-orm/core/EntityManager.js:152:45)
      at Object.<anonymous> (src/example.test.ts:75:17)
```

Outline of the reproduction 

```ts
@Entity()
export class User {
  // Unrealistic example, but it's just to show use case of forceEntityConstructor
  private role = "ADMIN";

  @PrimaryKey()
  id!: bigint;

  @Enum()
  name!: string;

  @OneToMany(() => UserComments, (x) => x.user)
  comments = new Collection<UserComments>(this);

  constructor(props: Pick<User, "name">) {
    this.name = props.name;
  }

  getRole() {
    return this.role;
  }
}

@Entity()
export class UserComments {
  @PrimaryKey()
  id!: bigint; // change to number to fix the issue

  @ManyToOne(() => User)
  user!: User;

  @Property()
  text!: string;
}

let orm: MikroORM;

beforeAll(async () => {
  orm = await MikroORM.init({
    dbName: ":memory:",
    entities: [User, UserComments],
    debug: ["query", "query-params"],
    forceEntityConstructor: true,
    allowGlobalContext: true,
  });
  await orm.schema.refreshDatabase();
});

afterAll(async () => {
  await orm.close(true);
});

test("can load entity with bigint pk and access private variables", async () => {
  const user = new User({ name: "John Doe" });

  const comment = new UserComments();
  comment.text = "a comment";
  user.comments.add(comment);

  await orm.em.persistAndFlush(user);
  orm.em.clear();

  // error : SyntaxError: Cannot convert [object Object] to a BigInt
  const users = await orm.em.findAll(User, { populate: ["comments"] });
  expect(users[0].getRole()).toBe("ADMIN");
});

```

### Reproduction

https://github.com/cpt-pete/mikro-orm-bigint-bug/

### What driver are you using?

@mikro-orm/sqlite

### MikroORM version

6.3.11

### Node.js version

20

### Operating system

macos

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by petergledhillinclusive** [comment]
Speedy work! Thanks
