### ISSUE TITLE
SQLite generated migrations depend on correct column ordering

### ISSUE THREAD

**Issue by chrisbenincasa** [mikro-orm/mikro-orm#6145]
### Describe the bug

There are some sqlite migrations that require creating a temp table with the new definition, copying all data into the temp table, dropping the prev, and renaming the new one.

mikro-orm [generates the copy step with a statement like](https://github.com/mikro-orm/mikro-orm/blob/742c2eeb02bf4083377777061371677e02cb9e80/packages/knex/src/dialects/sqlite/BaseSqliteSchemaHelper.ts#L220):
```
insert into X__temp_alter select * from X;
```

The problem here seems to be that the columns in the new table definition are not always aligned with whatever the current schema is defined as. I'm guessing that the column ordering pulled from knex is not always stable (or perhaps can change between versions or something). Without explicitly specifying the columns and their mappings between the two tables during this step, we can either run into exceptions in the migration or mismatched column data altogether.

I haven't found a solid set of migration steps that produce column reordering, but have attached a repro where I was able to make this happen after a few migrations below.

### Reproduction

https://github.com/chrisbenincasa/reproduction-populate-hint/pull/new/migration-example

In this example, if you insert a test value into the initial table, before running the final migration:
```
insert into channel (number, stream_mode) values (1, 'hls');
```

and then run through...

<details>
<summary>The exception this particular example produces</summary>

```
MigrationError: Migration Migration20241015141952 (up) failed: Original error: insert into `channel__temp_alter` select * from
 `channel`; - SQLITE_CONSTRAINT: CHECK constraint failed: stream_mode
    at /home/christian/Code/oss/reproduction-populate-hint/node_modules/umzug/src/umzug.ts:261:17
    at async Umzug.runCommand (/home/christian/Code/oss/reproduction-populate-hint/node_modules/umzug/src/umzug.ts:210:14)
    at async Migrator.runInTransaction (/home/christian/Code/oss/reproduction-populate-hint/node_modules/@mikro-orm/migrations
/Migrator.js:313:21)      
    at async SqliteConnection.transactional (/home/christian/Code/oss/reproduction-populate-hint/node_modules/@mikro-orm/knex/
AbstractSqlConnection.js:58:25)                                
    at async Function.handleUpDownCommand (/home/christian/Code/oss/reproduction-populate-hint/node_modules/@mikro-orm/cli/com
mands/MigrationCommandFactory.js:119:9)                        
    at async Function.handleMigrationCommand (/home/christian/Code/oss/reproduction-populate-hint/node_modules/@mikro-orm/cli/
commands/MigrationCommandFactory.js:100:17) {                                                                                 
  cause: CheckConstraintViolationException: insert into `channel__temp_alter` select * from `channel`; - SQLITE_CONSTRAINT: CH
ECK constraint failed: stream_mode                             
      at SqliteExceptionConverter.convertException (/home/christian/Code/oss/reproduction-populate-hint/node_modules/@mikro-or
m/sqlite/SqliteExceptionConverter.js:26:20)                                                                                   
      at SqliteDriver.convertException (/home/christian/Code/oss/reproduction-populate-hint/node_modules/@mikro-orm/core/drive
rs/DatabaseDriver.js:345:54)  
      at /home/christian/Code/oss/reproduction-populate-hint/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:349:24
      at async Function.runSerial (/home/christian/Code/oss/reproduction-populate-hint/node_modules/@mikro-orm/core/utils/Util
s.js:712:22)                                                   
      at async connection.transactional.ctx (/home/christian/Code/oss/reproduction-populate-hint/node_modules/@mikro-orm/migra
tions/MigrationRunner.js:29:17)                                
      at async SqliteConnection.transactional (/home/christian/Code/oss/reproduction-populate-hint/node_modules/@mikro-orm/kne
x/AbstractSqlConnection.js:58:25)                                                                                             
      at async MigrationRunner.run (/home/christian/Code/oss/reproduction-populate-hint/node_modules/@mikro-orm/migrations/Mig
rationRunner.js:26:13)                                                                                                        
      at async createMigrationHandler (/home/christian/Code/oss/reproduction-populate-hint/node_modules/@mikro-orm/migrations/
Migrator.js:202:13)                                                                                                           
      at async /home/christian/Code/oss/reproduction-populate-hint/node_modules/umzug/src/umzug.ts:259:11                     
      at async Umzug.runCommand (/home/christian/Code/oss/reproduction-populate-hint/node_modules/umzug/src/umzug.ts:210:14)                                             
```
</details>

Issue here is that the temp table change after adding a new column produces columns in a different order. Original order was `(id, number, stream_mode)` and new order is `(id, number, new_field, stream_mode)`

### What driver are you using?

None

### MikroORM version

6.3.13

### Node.js version

20.11.1

### Operating system

Ubuntu 24.04.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
This is a knex bug technically, we won't get around this unless we reimplement the schema diffing completely in the ORM (which I would like to do for v7, but it will be quite a lot of work).

**Comment by chrisbenincasa** [comment]
Yea that's what I figured. Though I thought that maybe just sorting the columns alphanumerically for this type of migration might be a quick workaround?

**Comment by B4nan** [comment]
Feel free to explore that. I am personally not interested in spending more time on hacking knex, I will rather spend the time on getting rid of it. But I will be happy to accept a PR doing that.

**Comment by chrisbenincasa** [comment]
Makes sense - thanks!
