### ISSUE TITLE
column reference "<x>" is ambiguous, when saving entity, part of a single table inheritance (postgres)

### ISSUE THREAD

**Issue by quiquelhappy** [mikro-orm/mikro-orm#6203]
### Describe the bug

When trying to save an 'Item' object (see below), which is part of a STI with class 'Sku', I get the following **postgres** error:
```sql
insert into "sku" ("category_id", "created", "id", "img", "name", "sku_type") values ('ZZeP1oUrprl6CpKfDnF20', '2024-10-31T12:13:44.870Z', 'hHPwlMvgkJn0362ZT65bN', NULL, 'v', 'item') on conflict ("id") do update set "sku_type" = excluded."sku_type", "created" = excluded."created", "name" = excluded."name", "category_id" = excluded."category_id", "img" = excluded."img" where "sku_type" = 'item' 
- column reference "sku_type" is ambiguous
```

the 'child' class of the STI
```ts
@Entity({ discriminatorValue: 'item' })
export default class Item extends Sku {

    @OneToMany({ mappedBy: 'item', eager: true })
    perks = new Collection<ItemPerkUsage>(this);

}
```

the root abstract class of the STI
```ts
@Entity({
    discriminatorColumn: 'skuType',
    abstract: true,
})
export default abstract class Sku extends E {

    @Property()
    name: string

    @ManyToOne()
    category: StoreCategory

    @Enum()
    skuType!: SkuType

    @OneToMany({ mappedBy: 'sku' })
    prices = new Collection<SkuPrice>(this)

    @Property({
        nullable: true
    })
    img: string | null

}
```

my base entity class
```ts
export default abstract class E extends BaseEntity {

    @PrimaryKey()
    id: string
    @Property()
    created = new Date()

    constructor(id: string = nanoid()) {
        super()
        this.id = id
    }

    async save(): Promise<this> {
        if (!db) return this
        return db.em.getRepository(this.constructor).upsert(this);
    }

}
```

### Reproduction

the code is fairly simple, its just an STI + base entity class

### What driver are you using?

None

### MikroORM version

@mikro-orm/core 6.3.13 @mikro-orm/postgresql 6.3.13 @mikro-orm/reflection 6.3.13 @mikro-orm/sql-highlighter 1.0.1

### Node.js version

v20.18.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
Please provide a [complete reproduction](https://github.com/mikro-orm/reproduction), something I can run myself to see the problem.

**Comment by quiquelhappy** [comment]
I dont have time to make one right now. **STI just doesn't work on postgres on the latest version. Adding this to the end of the query fixes it:**

```sql
WHERE "abstract_class"."discriminator_column" = 'discriminator_value';
```

the current release does this instead:
```sql
WHERE "discriminator_column" = 'discriminator_value';
```

example query + stacktrace:
```
NonUniqueFieldNameException: insert into "checkout_gateway" ("checkout_id", "customer_id", "id", "payment_intent", "service") values ('1B9RBsQkbhee8vxMj2Ltq', NULL, 'mOmLACQsZb6ZCX4V2DEtq', 'pi_3QGpQFCoP2Uu5XHy0KtcJTFd', 'stripe') on conflict ("id") do update set "service" = excluded."service", "checkout_id" = excluded."checkout_id", "payment_intent" = excluded."payment_intent", "customer_id" = excluded."customer_id" where "service" = 'stripe' - column reference "service" is ambiguous
    at PostgreSqlExceptionConverter.convertException (/app/node_modules/.pnpm/@mikro-orm+postgresql@6.3.13_@mikro-orm+core@6.3.13/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:40:24)
    at PostgreSqlDriver.convertException (/app/node_modules/.pnpm/@mikro-orm+core@6.3.13/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:345:54)                                                             
    at /app/node_modules/.pnpm/@mikro-orm+core@6.3.13/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:349:24                                                                                                 
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                                                                   
    at async PostgreSqlDriver.nativeUpdate (/app/node_modules/.pnpm/@mikro-orm+knex@6.3.13_@mikro-orm+core@6.3.13_pg@8.13.0/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:510:19)                               
    at async SqlEntityManager.upsert (/app/node_modules/.pnpm/@mikro-orm+core@6.3.13/node_modules/@mikro-orm/core/EntityManager.js:666:21)
    at async Promise.all (index 0)                                                                                                                                                                                  
    at async Checkout.create (file:///app/dist/src/checkout/Checkout.e.js:61:31)                                                                                                                                    
    at async StoreCheckout.create (file:///app/dist/src/community/store/StoreCheckout.e.js:40:26)                                                                                                                   
    at async Object.handler (file:///app/dist/src/lib/interface/Endpoint.js:332:36)                                                                                                                                 
                                                                                                                                                                                                                    
    at Parser.parseErrorMessage (/app/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:283:98)                                                                                          
    at Parser.handlePacket (/app/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:122:29)                                                                                               
    at Parser.parse (/app/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/parser.js:35:38)                                                                                                       
    at Socket.<anonymous> (/app/node_modules/.pnpm/pg-protocol@1.7.0/node_modules/pg-protocol/dist/index.js:11:42)                                                                                                  
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)                                                                                                                                                                             
    at addChunk (node:internal/streams/readable:559:12)                                                                                                                                                             
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)                                                                                                                                          
    at Readable.push (node:internal/streams/readable:390:5)                                                                                                                                                         
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23) {                                                                                                                                                
  code: '42702',                                                                                                                                                                                                    
  errno: undefined,                                                                                                                                                                                                 
  sqlState: undefined,                                                                                                                                                                                              
  sqlMessage: undefined,                                                                                                                                                                                            
  errmsg: undefined,
  length: 109,                                                                                                                                                                                                      
  severity: 'ERROR',                                                                                                                                                                                                
  detail: undefined,                                                                                                                                                                                                
  hint: undefined,                                                                                                                                                                                                  
  position: '399',                                                                                                                                                                                                  
  internalPosition: undefined,                                                                                                                                                                                      
  internalQuery: undefined,                                                                                                                                                                                         
  where: undefined,                                                                                                                                                                                                 
  schema: undefined,                                                                                                                                                                                                
  table: undefined,
  column: undefined,                                                                                                                                                                                                
  dataType: undefined,                                                                                                                                                                                              
  constraint: undefined,                                                                                                                                                                                            
  file: 'parse_relation.c',                                                                                                                                                                                         
  line: '913',                                                                                                                                                                                                      
  routine: 'colNameToVar'                                                                                                                                                                                           
}
```

**Comment by B4nan** [comment]
It would most likely take you less time than writing the message above 🤷

**Comment by B4nan** [comment]
It's yet another unresolved knex bug.

https://github.com/knex/knex/issues/5257

**Comment by quiquelhappy** [comment]
> Here, took me less than 10 minutes, this is all I was asking you for. I guess you must be a really busy person 🤣
> 
> ```ts
> import { Entity, Enum, MikroORM, Opt, PrimaryKey, Property } from '@mikro-orm/postgresql';
> import { v4 } from 'uuid';
> 
> @Entity({
>   discriminatorColumn: 'skuType',
>   abstract: true,
> })
> abstract class Sku {
> 
>   @PrimaryKey()
>   id = v4();
> 
>   @Property()
>   created: Date & Opt = new Date();
> 
>   @Property()
>   name!: string;
> 
>   @Enum()
>   skuType!: string & Opt;
> 
> }
> 
> @Entity({ discriminatorValue: 'item' })
> class Item extends Sku {
> 
> }
> 
> let orm: MikroORM;
> 
> beforeAll(async () => {
>   orm = await MikroORM.init({
>     dbName: '6203',
>     entities: [Sku, Item],
>     debug: true,
>   });
>   await orm.schema.refreshDatabase();
> });
> 
> afterAll(async () => {
>   await orm.close(true);
> });
> 
> test('6203', async () => {
>   const item1 = orm.em.create(Item, { name: 'name 1' });
>   await orm.em.upsert(item1);
> 
>   const item2 = orm.em.create(Item, { name: 'name 2' });
>   await orm.em.upsertMany([item2]);
> });
> ```
> 
> You say repro is not needed because it's so simple and whatnot. That is completely irrelevant, repro is always needed before we can fix anything, I am not interested in sending random patches without seeing they actually solve something, or breaking stuff again just because we didn't have a regression test.
> 
> It's yet another unresolved knex bug.
> 
> [knex/knex#5257](https://github.com/knex/knex/issues/5257)

I sincerely apologize. I am indeed a busy person, and I thought directly showing the issue would be more effective. I understand why you’d want a complete example, and I’ll keep it in mind when opening new issues. I appreciate your quick response and your work on maintaining the repo.

ps. the issue might need to be marked as bug
