### ISSUE TITLE
Entity discovery fails when running built app (v6.4.1)

### ISSUE THREAD

**Issue by Robert-Schirmer** [mikro-orm/mikro-orm#6297]
### Describe the bug

In v6.4.1 when running a built version of a NestJS app entity discovery fails using `TsMorphMetadataProvider`
```
[Nest] 1  - 12/13/2024, 5:43:18 PM   ERROR [ExceptionHandler] Source file './dist/shared/crud/base.entity.ts' not found. Check your 'entitiesTs' option and verify you have 'compilerOptions.declaration' enabled in your 'tsconfig.json'. If you are using webpack, see https://bit.ly/35pPDNn
MetadataError: Source file './dist/shared/crud/base.entity.ts' not found. Check your 'entitiesTs' option and verify you have 'compilerOptions.declaration' enabled in your 'tsconfig.json'. If you are using webpack, see https://bit.ly/35pPDNn
    at TsMorphMetadataProvider.getSourceFile (/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:134:19)
    at TsMorphMetadataProvider.getExistingSourceFile (/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:23:21)
    at TsMorphMetadataProvider.getExistingSourceFile (/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:20:77)
    at TsMorphMetadataProvider.readTypeFromSource (/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:79:29)
    at TsMorphMetadataProvider.initPropertyType (/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:62:50)
    at TsMorphMetadataProvider.initProperties (/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:30:22)
    at TsMorphMetadataProvider.loadEntityMetadata (/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:16:14)
    at MetadataDiscovery.discoverEntity (/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:301:31)
    at MetadataDiscovery.discoverDirectories (/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:215:18)
    at async MetadataDiscovery.discover (/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:43:9)
```

Previously it worked with v6.3.11

### Reproduction

https://github.com/Robert-Schirmer/mikro-orm-nestjs-bug-reproduction

### What driver are you using?

@mikro-orm/postgresql

### MikroORM version

v6.4.1

### Node.js version

v20.17.0

### Operating system

Docker

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/mikro-orm/mikro-orm/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://mikro-orm.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/mikro-orm/mikro-orm/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mikro-orm/mikro-orm/discussions) or join our [Discord](https://discord.gg/w8bjxFHS7X).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by B4nan** [comment]
If you cannot reproduce this outside of docker container, it only confirms its an issue with how you build it. My guess is its because you don't have the ts-node installed inside it (since its a dev dep and you use `--only=production`).

Note that you should be creating the metadata cache as part of your docker build, then there wont be such problems and you will also cut down the startup time. Even better, you should be using the `GeneratedCacheAdapter` so you don't have to bring TS as your production dependency (now you still have it there since its a transitive dep of the reflection package).

https://mikro-orm.io/docs/deployment#deploy-pre-built-cache

**Comment by B4nan** [comment]
This is apparently caused by the upgrade to ts-morph v24, you can enforce the previous version via NPM overrides, v23 works fine.
