### ISSUE TITLE
(v4) Metadata cache generation doesn't discover entities

### ISSUE THREAD

**Issue by thekevinbrown** [mikro-orm/mikro-orm#659]
**Describe the bug**
I run 
```
$ mikro-orm cache:generate
```

and get

```
MetadataError: No entities were discovered
    at Function.noEntityDiscovered ([project dir]/node_modules/@mikro-orm/core/utils/errors.js:121:16)
    at MetadataValidator.validateDiscovered ([project dir]/node_modules/@mikro-orm/core/metadata/MetadataValidator.js:28:41)
    at MetadataDiscovery.findEntities ([project dir]/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:67:24)
    at async MetadataDiscovery.discover ([project dir]/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:32:9)
    at async Object.handler ([project dir]/node_modules/@mikro-orm/cli/commands/GenerateCacheCommand.js:23:9) {
  entity: undefined,
  name: 'MetadataError'
}
```

My config looks pretty simple:

```javascript
module.exports = {
	entitiesDirsTs: ['./src/entities'],
	entitiesDirs: ['./lib/entities'],
	dbName: 'temp',
	type: 'postgresql',
};
```

The entities are indeed in ./src/entities, and Typescript builds them out to lib.

**To Reproduce**
I can create a reproduction if needed, but I suspect the docs need updating because the config option is now `entitiesTs`, no?

Either way, if I omit those config options it still doesn't discover the entities.

**Expected behavior**
Expected entity discovery to succeed.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.16.1 |
| typescript | 3.9.5 |
| mikro-orm | "@mikro-orm/core": "4.0.0-alpha.5", "@mikro-orm/postgresql": "4.0.0-alpha.5", "@mikro-orm/cli": "4.0.0-alpha.5", |
| your-driver | Postgresql |

**Comment by B4nan** [comment]
Create repro. Live docs are for v3.

**Comment by thekevinbrown** [comment]
Here's a minimal repro: https://github.com/thekevinbrown/mikro-659

**Comment by B4nan** [comment]
All docs are generated from master, so v4 will be there once we merge #527 (which for me means first RC release).

And as you mentioned, in v4 its `entities` and `entitiesTs`, so that will be probably why its not working for you. `entitiesDirs` and `entitiesDirsTs` are no longer there.

**Comment by thekevinbrown** [comment]
Now I'm getting

```
MetadataError: Entity 'MikroOrm' not found in ./lib/mikro-orm.config.js
    at Function.entityNotFound (/Users/kevin/development/mikro-659/node_modules/@mikro-orm/core/utils/errors.js:105:16)
    at MetadataDiscovery.getEntityClassOrSchema (/Users/kevin/development/mikro-659/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:620:41)
    at MetadataDiscovery.discoverDirectories (/Users/kevin/development/mikro-659/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:90:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async MetadataDiscovery.findEntities (/Users/kevin/development/mikro-659/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:65:9)
    at async MetadataDiscovery.discover (/Users/kevin/development/mikro-659/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:32:9)
    at async Object.handler (/Users/kevin/development/mikro-659/node_modules/@mikro-orm/cli/commands/GenerateCacheCommand.js:23:9) {
  entity: undefined,
  name: 'MetadataError'
}
```

I've updated the repo.

**Comment by thekevinbrown** [comment]
Ok, it discovers the entities now, but says:

```
$ mikro-orm cache:generate
Metadata cache was successfully generated
✨  Done in 3.96s.
```

But there's no `./temp` that's created.

**Comment by B4nan** [comment]
Because it thinks that your orm config is an entity...

**Comment by B4nan** [comment]
Caching is disabled by default in v4.

**Comment by thekevinbrown** [comment]
Ah, well it probably shouldn't say "Metadata cache was successfully generated" if the cache is disabled and it didn't actually generate it.

I'll do a PR for this.
