### ISSUE TITLE
Circular dependency in v4 causes problems with Webpack

### ISSUE THREAD

**Issue by thekevinbrown** [mikro-orm/mikro-orm#676]
**Describe the bug**

[Reference requires wrap](https://github.com/mikro-orm/mikro-orm/blob/dev/packages/core/src/entity/Reference.ts#L2), then [wrap immediately requires Reference](https://github.com/mikro-orm/mikro-orm/blob/dev/packages/core/src/entity/wrap.ts#L3).

This is a circular dependency, which is undefined behaviour.

This seems to work on vanilla Node, but in a Webpack context, Reference doesn't correctly get set to the same object everywhere, resulting in `TypeError: Cannot read property '__meta' of undefined`. This is because wrap doesn't see that the entity is an `instanceof Reference`, resulting in it falling through wrap without doing what's intended.

I added this to wrap:

```typescript
    console.log('entity: ', entity);
    console.log('entity instanceof Reference_1.Reference', entity instanceof Reference_1.Reference);
    console.trace();
    console.log('--------------------');
```

Then called `findAndCount` once. Both the successful output and the error output happen from the same call to `findAndCount`.

Successful output:
```
entity:  Reference { entity: Location { id: '4' } }
entity instanceof Reference_1.Reference true
Trace: 
    at Object.wrap (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/wrap.js?:17:13)
    at Function.autoWireOneToOne (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/EntityAssigner.js?:65:30)
    at ObjectHydrator.hydrateManyToOne (webpack:///[project dir]/node_modules/@mikro-orm/core/hydration/ObjectHydrator.js?:79:37)
    at ObjectHydrator.hydrateProperty (webpack:///[project dir]/node_modules/@mikro-orm/core/hydration/ObjectHydrator.js?:10:18)
    at ObjectHydrator.hydrate (webpack:///[project dir]/node_modules/@mikro-orm/core/hydration/Hydrator.js?:20:18)
    at EntityFactory.create ([project dir]/node_modules/@mikro-orm/core/entity/EntityFactory.js:27:27)
    at SqlEntityManager.merge ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:258:80)
    at SqlEntityManager.find ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:78:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at SqlEntityManager.findAndCount ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:133:35)
(our code)
--------------------
```

Unsuccessful output:
```
entity:  Reference { entity: Organisation { id: '2' } }
entity instanceof Reference_1.Reference false
Trace: 
    at Object.wrap (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/wrap.js?:17:13)
    at new Reference (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/Reference.js?:9:32)
    at Function.create (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/Reference.js?:29:16)
    at Function.wrapReference (webpack:///[project dir]/node_modules/@mikro-orm/core/utils/Utils.js?:409:39)
    at Shop.set [as organisation] (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/EntityHelper.js?:99:56)
    at Function.assignReference ([project dir]/node_modules/@mikro-orm/core/entity/EntityAssigner.js:89:31)
    at [project dir]/node_modules/@mikro-orm/core/entity/EntityAssigner.js:33:39
    at Array.forEach (<anonymous>)
    at Function.assign ([project dir]/node_modules/@mikro-orm/core/entity/EntityAssigner.js:20:27)
    at SqlEntityManager.merge ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:261:33)
    at SqlEntityManager.find ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:78:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at SqlEntityManager.findAndCount ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:133:35)
(our code)
--------------------
```

**Stack trace**
```
TypeError: Cannot read property '__meta' of undefined
    at new Reference (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/Reference.js?:10:17)
    at Function.create (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/Reference.js?:29:16)
    at Function.wrapReference (webpack:///[project dir]/node_modules/@mikro-orm/core/utils/Utils.js?:409:39)
    at Shop.set [as organisation] (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/EntityHelper.js?:99:56)
    at Function.assignReference ([project dir]/node_modules/@mikro-orm/core/entity/EntityAssigner.js:89:31)
    at [project dir]/node_modules/@mikro-orm/core/entity/EntityAssigner.js:33:39
    at Array.forEach (<anonymous>)
    at Function.assign ([project dir]/node_modules/@mikro-orm/core/entity/EntityAssigner.js:20:27)
    at SqlEntityManager.merge ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:261:33)
    at SqlEntityManager.find ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:78:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at SqlEntityManager.findAndCount ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:133:35)
(our code)
```

**To Reproduce**

I will provide a reproduction case, but I haven't had time to yet and wanted to get the issue some visibility so we can work towards eliminating circular dependencies in the project in general.

**Expected behavior**

Expected no circular dependency to exist as it's undefined behaviour.

**Versions**

| Dependency | Version |
| - | - |
| node | 12 |
| typescript | 3.9.5 |
| mikro-orm | 4.0.0-alpha.6 |
| your-driver | Postgresql |

**Comment by thekevinbrown** [comment]
I should note that this might not be caused by the circular reference itself, it might actually be because in one we're in the middle of a constructor, while in the other the Reference is already created. Either way it'd be a good idea to avoid circular dependencies.

**Comment by B4nan** [comment]
We can remove the condition in `wrap` as `unwrapReference` is already taking care of that.

**Comment by B4nan** [comment]
Can you verify it helps?

Btw I am quite sure the reason is that `Reference_1.Reference` is actually undefined when it fails.

**Comment by thekevinbrown** [comment]
Yeah, I suspect you're right, I'll give the latest a shot. There's still a cycle (Reference -> wrap -> Utils -> Reference) so it might not make much difference, but will verify before we worry about changing things.

(Note for later, if the change above doesn't fix it, could wrapReference and unwrapReference actually go on the Reference class? That should fix the cycles.)

**Comment by B4nan** [comment]
Try alpha 7, that condition is now gone.

> (Note for later, if the change above doesn't fix it, could wrapReference and unwrapReference actually go on the Reference class? That should fix the cycles.)

Yeah sure, makes sense.

**Comment by B4nan** [comment]
FYI if we move the methods to `Reference` wrapper, we will still have `Reference` imported in `wrap` and vice versa. 

What we could do is to define a `__helper` getter on `Reference` class so we do not have to do this at all (we can then remove the `unwrapReference` from `wrap`). This way we can even remove the usage of `Reference` from `Utils`, as we could use this fact to verify if given object is entity.

Overall the circular dependencies are haunting me from the very beginning :] 

I guess I will do that right ahead, it makes sense.

**Comment by thekevinbrown** [comment]
Same result in alpha 7 unfortunately:

```
TypeError: Cannot read property '__meta' of undefined
    at new Reference (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/Reference.js?:10:17)
    at Function.create (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/Reference.js?:29:16)
    at Function.wrapReference (webpack:///[project dir]/node_modules/@mikro-orm/core/utils/Utils.js?:409:39)
    at Shop.set [as organisation] (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/EntityHelper.js?:99:56)
    at Function.assignReference ([project dir]/node_modules/@mikro-orm/core/entity/EntityAssigner.js:89:31)
    at [project dir]/node_modules/@mikro-orm/core/entity/EntityAssigner.js:33:39
    at Array.forEach (<anonymous>)
    at Function.assign ([project dir]/node_modules/@mikro-orm/core/entity/EntityAssigner.js:20:27)
    at SqlEntityManager.merge ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:261:33)
    at SqlEntityManager.find ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:78:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at SqlEntityManager.findAndCount ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:133:35)
(our code)
```

I made Utils.unwrapReference look like this:
```javascript
    static unwrapReference(ref) {
        console.log('ref: ', ref);
        console.log('entity_1.Reference: ', entity_1.Reference);
        console.log('ref instanceof entity_1.Reference', ref instanceof entity_1.Reference);
        console.trace();
        console.log('--------------------');

        return Utils.isReference(ref) ? ref.unwrap() : ref;
    }
```

It showed the same behaviour in that if it comes from `ObjectHydrator` it works, but if it comes from `new Reference` it doesn't. `entity_1.Reference` is definitely initialised to something at that point:

```
ref:  Reference { entity: Organisation { id: '2' } }
entity_1.Reference:  [Function: Reference]
ref instanceof entity_1.Reference false
Trace: 
    at Function.unwrapReference (webpack:///[project dir]/node_modules/@mikro-orm/core/utils/Utils.js?:328:17)
    at Object.wrap (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/wrap.js?:18:26)
    at new Reference (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/Reference.js?:9:32)
    at Function.create (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/Reference.js?:29:16)
    at Function.wrapReference (webpack:///[project dir]/node_modules/@mikro-orm/core/utils/Utils.js?:415:39)
    at Shop.set [as organisation] (webpack:///[project dir]/node_modules/@mikro-orm/core/entity/EntityHelper.js?:99:56)
    at Function.assignReference ([project dir]/node_modules/@mikro-orm/core/entity/EntityAssigner.js:89:31)
    at [project dir]/node_modules/@mikro-orm/core/entity/EntityAssigner.js:33:39
    at Array.forEach (<anonymous>)
    at Function.assign ([project dir]/node_modules/@mikro-orm/core/entity/EntityAssigner.js:20:27)
    at SqlEntityManager.merge ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:261:33)
    at SqlEntityManager.find ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:78:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at SqlEntityManager.findAndCount ([project dir]/node_modules/@mikro-orm/core/EntityManager.js:133:35)
(our code)
```

I then used `yarn link` to try latest dev and got:

```
MetadataError: Metadata for entity Reference not found
    at Function.missingMetadata (webpack:////Users/kevin/development/mikro-orm/packages/core/dist/utils/errors.js?:133:16)
    at MetadataStorage.get (webpack:////Users/kevin/development/mikro-orm/packages/core/dist/metadata/MetadataStorage.js?:37:41)
    at UnitOfWork.cascade (/Users/kevin/development/mikro-orm/packages/core/dist/unit-of-work/UnitOfWork.js:319:36)
    at UnitOfWork.cascadeReference (/Users/kevin/development/mikro-orm/packages/core/dist/unit-of-work/UnitOfWork.js:331:25)
    at UnitOfWork.cascade (/Users/kevin/development/mikro-orm/packages/core/dist/unit-of-work/UnitOfWork.js:321:18)
    at UnitOfWork.merge (/Users/kevin/development/mikro-orm/packages/core/dist/unit-of-work/UnitOfWork.js:42:14)
    at SqlEntityManager.merge (/Users/kevin/development/mikro-orm/packages/core/dist/EntityManager.js:262:30)
    at SqlEntityManager.find (/Users/kevin/development/mikro-orm/packages/core/dist/EntityManager.js:78:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at SqlEntityManager.findAndCount (/Users/kevin/development/mikro-orm/packages/core/dist/EntityManager.js:133:35)
(our code)
```
(We have no entity called Reference.)

I'll create a reproduction so you can run this locally.

**Comment by thekevinbrown** [comment]
Ok, here's the reproduction: https://github.com/thekevinbrown/mikro-676

It looks like it actually reproduces two things:

1. The __meta issue.
2. But also the long time for `MikroORM.init()` to run. With two entities that have 2 or 3 properties each, using `ReflectMetadataProvider`, `init()` is taking more than a second to run on my relatively modern MacBook Air, which feels like it's longer than it should be to me.

**Comment by thekevinbrown** [comment]
I added profiling to the reproduction. It looks like about half of the time in init is spent in highlight.js, the other half is spent in postgres getting a connection, and the rest is super tiny. You can see a flamegraph on the repo, or can generate one locally with `yarn profile` now.

**Comment by B4nan** [comment]
Regarding the coloring, it is just about the highlighting, right? Not about the chalk usage I hope (now replaced with ansi-colors that should be much faster). It can be already disabled via configuration (from the very beginning of this addition), does that help? You can also disable coloring via `process.env.FORCE_COLOR = 0`.

**Comment by B4nan** [comment]
So closing this as #679 is merged. Let's continue the coloring discussion in #658.
