### ISSUE TITLE
BigInt primary key resulting in missing key length

### ISSUE THREAD

**Issue by hydroper** [mikro-orm/mikro-orm#715]
**Describe the bug**

Generating schema with the MikroORM using MySQL driver results in query missing [key length](https://dev.mysql.com/doc/refman/8.0/en/string-type-syntax.html) of a text.

On running `mikro-orm schema:create`, I get:

```
Error: alter table `user` add primary key `user_pkey`(`numeric_id`); - BLOB/TEXT column 'numeric_id' used in key specification without a key length
```

**Stack trace**
```
    at Packet.asError (C:\Users\Padrão\Documents\com.recoyx\sapper-template\server\node_modules\mysql2\lib\packets\packet.js:712:17)
    at Query.execute (C:\Users\Padrão\Documents\com.recoyx\sapper-template\server\node_modules\mysql2\lib\commands\command.js:28:26)
    at Connection.handlePacket (C:\Users\Padrão\Documents\com.recoyx\sapper-template\server\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (C:\Users\Padrão\Documents\com.recoyx\sapper-template\server\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (C:\Users\Padrão\Documents\com.recoyx\sapper-template\server\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\Padrão\Documents\com.recoyx\sapper-template\server\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**To Reproduce**
1. Write this entity:

```typescript
import { Entity, PrimaryKey, BigIntType } from "mikro-orm";

@Entity()
export class User {
    @PrimaryKey({ type: BigIntType })
    numericId: string;
}
```
2. Run `npx mikro-orm schema:create -r`

**Expected behavior**
Succesful schema generation.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 12.18.1 |
| typescript | 3.7.4 |
| mikro-orm | 3.6.15 |
| your-driver | 2.1.0 |

**Comment by B4nan** [comment]
The error is from alter statement - how does the (original) table definition look like?

**Comment by hydroper** [comment]
Entirety:

```sql
set names utf8mb4;
set foreign_key_checks = 0;

create table `user` (`numeric_id` json not null, `network_id` varchar(255) not null, `email` varchar(255) not null, `password_hash` varchar(255) not null, `created_at` datetime not null, `updated_at` datetime not null) default character set utf8mb4 engine = InnoDB;
alter table `user` add primary key `user_pkey`(`numeric_id`);
alter table `user` add unique `user_network_id_unique`(`network_id`);
alter table `user` add unique `user_email_unique`(`email`);

set foreign_key_checks = 1;
```

**Comment by hydroper** [comment]
With PostgreSQL driver I instead get `data type json has no default operator class for access method btree` on the `numericId` property.

**Comment by B4nan** [comment]
Yeah, because you can't change JSON values into bigints (or numbers in general), the database does not understand it. 

You can get around this by first dropping the column.

**Comment by hydroper** [comment]
So BigIntType isn't supported exactly? Number's range would not be an issue... the problem though is it'd be slower than an integer, it's good to get a benefit.

**Comment by B4nan** [comment]
Ah sorry I though you are using `schema:update`. This is weird, big ints work fine in the tests, for MySQL as well as for postgres. 

As you can see it tries to create JSON column instead of bigint, and that is not a valid primary key type.

**Comment by B4nan** [comment]
Maybe you omitted something important from the reproduction? Because I am sure this works fine if you just use `schema:create`, you can see the entity in tests and the dump it generates:

https://github.com/mikro-orm/mikro-orm/blob/master/tests/entities-sql/BookTag2.ts#L7
https://github.com/mikro-orm/mikro-orm/blob/master/tests/__snapshots__/SchemaGenerator.test.ts.snap

**Comment by hydroper** [comment]
Sorry, I think I forgot something on the build. I think I should have used `ts-node`. It looks like a `schema:drop`-`schema:create` resolved the issue now, but I believe I had already trying first dropping yesterday.
