### ISSUE TITLE
TsMorphMetadataProvider doesn't find source file

### ISSUE THREAD

**Issue by oliversalzburg** [mikro-orm/mikro-orm#727]
**Describe the bug**
When using `TsMorphMetadataProvider`, my application no longer starts because some source file is apparently missing.

**Stack trace**
```
(node:14672) UnhandledPromiseRejectionWarning: Error: Source file for entity './dist/entities/CoreEntity.js' not found, check your 'entitiesTs' option. If you are using webpack, see https://bit.ly/35pPDNn
    at TsMorphMetadataProvider.getSourceFile (/home/oliver/fairmanager/backend/core-web3/.yarn/$$virtual/@mikro-orm-reflection-virtual-84f2ec7642/0/cache/@mikro-orm-reflection-npm-4.0.0-rc.0-d5f10a9522-1e54d859bc.zip/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:80:19)
    at TsMorphMetadataProvider.getExistingSourceFile (/home/oliver/fairmanager/backend/core-web3/.yarn/$$virtual/@mikro-orm-reflection-virtual-84f2ec7642/0/cache/@mikro-orm-reflection-npm-4.0.0-rc.0-d5f10a9522-1e54d859bc.zip/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:26:28)
    at TsMorphMetadataProvider.getExistingSourceFile (/home/oliver/fairmanager/backend/core-web3/.yarn/$$virtual/@mikro-orm-reflection-virtual-84f2ec7642/0/cache/@mikro-orm-reflection-npm-4.0.0-rc.0-d5f10a9522-1e54d859bc.zip/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:23:89)
    at async TsMorphMetadataProvider.readTypeFromSource (/home/oliver/fairmanager/backend/core-web3/.yarn/$$virtual/@mikro-orm-reflection-virtual-84f2ec7642/0/cache/@mikro-orm-reflection-npm-4.0.0-rc.0-d5f10a9522-1e54d859bc.zip/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:58:24)
    at async TsMorphMetadataProvider.initPropertyType (/home/oliver/fairmanager/backend/core-web3/.yarn/$$virtual/@mikro-orm-reflection-virtual-84f2ec7642/0/cache/@mikro-orm-reflection-npm-4.0.0-rc.0-d5f10a9522-1e54d859bc.zip/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:48:36)
    at async TsMorphMetadataProvider.initProperties (/home/oliver/fairmanager/backend/core-web3/.yarn/$$virtual/@mikro-orm-reflection-virtual-84f2ec7642/0/cache/@mikro-orm-reflection-npm-4.0.0-rc.0-d5f10a9522-1e54d859bc.zip/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:33:17)
    at async TsMorphMetadataProvider.loadEntityMetadata (/home/oliver/fairmanager/backend/core-web3/.yarn/$$virtual/@mikro-orm-reflection-virtual-84f2ec7642/0/cache/@mikro-orm-reflection-npm-4.0.0-rc.0-d5f10a9522-1e54d859bc.zip/node_modules/@mikro-orm/reflection/TsMorphMetadataProvider.js:19:9)
    at async MetadataDiscovery.discoverEntity (/home/oliver/fairmanager/backend/core-web3/.yarn/$$virtual/@mikro-orm-core-virtual-3ad60f3fc1/0/cache/@mikro-orm-core-npm-4.0.0-rc.0-779fca6c16-4355f3c4f9.zip/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:164:13)
    at async MetadataDiscovery.discoverDirectories (/home/oliver/fairmanager/backend/core-web3/.yarn/$$virtual/@mikro-orm-core-virtual-3ad60f3fc1/0/cache/@mikro-orm-core-npm-4.0.0-rc.0-779fca6c16-4355f3c4f9.zip/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:103:13)
    at async MetadataDiscovery.findEntities (/home/oliver/fairmanager/backend/core-web3/.yarn/$$virtual/@mikro-orm-core-virtual-3ad60f3fc1/0/cache/@mikro-orm-core-npm-4.0.0-rc.0-779fca6c16-4355f3c4f9.zip/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:65:9)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**To Reproduce**
1. Switch from `ReflectMetadataProvider` to `TsMorphMetadataProvider`?

**Expected behavior**
My application starts as before when using the `ReflectMetadataProvider`.

**Additional context**
The directory for `entitesTs` is properly declared as far as I can tell. The class being complained about here is an abstract base class for other entities.

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 3 |
| mikro-orm | 4 |
| your-driver | ? |

**Comment by B4nan** [comment]
So how do you define entities and entitiesTs? How do you run the project? Node or ts-node? Do you have declaration files enabled?

**Comment by oliversalzburg** [comment]
I'm defining them as:
```typescript
this.orm = await MikroORM.init({
	debug: true,
	baseDir: __dirname + "/..",
	entities: ["./dist/entities"],
	entitiesTs: ["./src/entities"],
});
```

I'm running the project through node with `/usr/bin/node --unhandled-rejections=strict --require /home/oliver/fairmanager/backend/core-web3/.pnp.js /home/oliver/fairmanager/backend/core-web3/dist/app.js`.

I don't have declaration files enabled unless they are enabled by default. I'm not sure what the term is referring to in this context.

**Comment by B4nan** [comment]
In v4 you need to have them, its the .d.ts files, next to the compiled js files. Enable them in your tsconfig.json.

**Comment by oliversalzburg** [comment]
Ah, yes. Now I see. I also started stepping into the implementation and saw it is looking for `'/home/oliver/fairmanager/backend/core-web3/dist/entities/CoreEntity.d.ts'`. I'll see what I can do. Thanks

**Comment by B4nan** [comment]
Yeah this has changed, in v3 the real TS source files were used, now it uses the .d.ts files. Will improve the error message.

**Comment by oliversalzburg** [comment]
Awesome. That was it. How would you feel about a note regarding this TS compiler setting around https://mikro-orm.io/docs/next/installation#entity-discovery-in-typescript or https://mikro-orm.io/docs/next/metadata-providers/#tsmorphmetadataprovider ?

**Comment by B4nan** [comment]
Yeah I would say both places should have a note about this.
