### ISSUE TITLE
Monorepo packaging: dependencies must be peers

### ISSUE THREAD

**Issue by dfee** [mikro-orm/mikro-orm#733]
**Describe the bug**
I'm using MikroORM in a monorepo, so my database occupies it's own package. I noticed that MikroORM was throwing weird errors related ... somehow related to to the order dependencies created in a many-to-one relationship.

What solved the error (after much debugging) was copying over all the `@mikro-orm/*` dependencies from `@mymonorepo/db` to `@mymonorepo/app`. (well, all except `@mikro-orm/cli` which is apparently not needed).

To be clear these were the dependencies I needed to copy over (and without any one of them, there were problems):
```
    "@mikro-orm/core": "^4.0.0-rc.1",
    "@mikro-orm/entity-generator": "^4.0.0-rc.1",
    "@mikro-orm/knex": "^4.0.0-rc.1",
    "@mikro-orm/nestjs": "~4.0.0-alpha.2",
    "@mikro-orm/migrations": "^4.0.0-rc.1",
    "@mikro-orm/postgresql": "^4.0.0-rc.1",
```

It's a bit weird that I can't rely on normal NodeJS resolutions, but need to include those again in every package I use my db code in.

To be clear, without those, this line of code fails: https://github.com/mikro-orm/mikro-orm/blob/443c5ab20a42eb7d7a8ef9614f063ff7a464a9a9/packages/core/src/entity/wrap.ts#L24

which was called during propagation: https://github.com/mikro-orm/mikro-orm/blob/443c5ab20a42eb7d7a8ef9614f063ff7a464a9a9/packages/core/src/entity/EntityHelper.ts#L141

**Stack trace**
```
            "TypeError: Cannot read property 'isInitialized' of undefined",
            "    at Function.propagate (/Users/dfee/code/experiment/common/temp/node_modules/.pnpm/@mikro-orm/core@4.0.0-rc.1_1d751e5dc421b2a6ee0c06e1755c2352/node_modules/@mikro-orm/core/entity/EntityHelper.js:116:106)",
            "    at LoginEntity.set [as user] (/Users/dfee/code/experiment/common/temp/node_modules/.pnpm/@mikro-orm/core@4.0.0-rc.1_1d751e5dc421b2a6ee0c06e1755c2352/node_modules/@mikro-orm/core/entity/EntityHelper.js:107:30)",
            "    at Function.defineReferenceProperty (/Users/dfee/code/experiment/common/temp/node_modules/.pnpm/@mikro-orm/core@4.0.0-rc.1_1d751e5dc421b2a6ee0c06e1755c2352/node_modules/@mikro-orm/core/entity/EntityHelper.js:112:24)",
            "    at LoginEntity.set (/Users/dfee/code/experiment/common/temp/node_modules/.pnpm/@mikro-orm/core@4.0.0-rc.1_1d751e5dc421b2a6ee0c06e1755c2352/node_modules/@mikro-orm/core/entity/EntityHelper.js:85:34)",
            "    at new LoginEntity (/Users/dfee/code/experiment/db/db-experiment-2/src/entities/login.entity.ts:54:16)",
            "    at AuthService.register (/Users/dfee/code/experiment/services/service-api/src/auth/auth.service.ts:68:19)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
            "    at AuthResolver.register (/Users/dfee/code/experiment/services/service-api/src/auth/auth.resolver.ts:70:18)"
```

**To Reproduce**
1. separate your db into a separate package
2. install the package as a dependency
3. play around with M:1 relationships

**Expected behavior**
I should only need to install used dependencies. 

**Additional context**
Using pnpm (5.4.6) and rush (5.30.1)
**Versions**

| Dependency | Version |
| - | - |
| node | 12.16.3 |
| typescript | 3.9.7 |
| mikro-orm | (as above) |
| your-driver | postgresql |

**Comment by B4nan** [comment]
Do you have a reproduction? Peer dependencies are correctly defined, and v4 is compatible with yarn pnp, so I'd expect pnpm to be fine too. I don't think there is much we can do from the ORM point of view, this sounds more like bad configuration of your project (as you ended up with multiple copies of `@mikro-orm/core` - that is what causes the failure). 

I saw the issue with `instanceof` when the meta package `mikro-orm` was used instead of `@mikro-orm/core` for entity definition. 

cc @merceyz

**Comment by B4nan** [comment]
Any updates on this one? As I said, for me the dependencies are defined correctly, so without a reproduction I don't see anything we can do.

**Comment by merceyz** [comment]
I'm not using all of the mentioned packages but across my projects i'm using these under strict PnP and they all work, granted they're not a monorepo.
```
@mikro-orm/core
@mikro-orm/reflection
@mikro-orm/sqlite
@mikro-orm/mysql
```
Without a reproduction it's hard to say

**Comment by B4nan** [comment]
Closing due to inactivity, will be happy to reopen if you provide reproduction repository.
