### ISSUE TITLE
PostGIS: parse error - invalid geometry

### ISSUE THREAD

**Issue by iabtyagi** [mikro-orm/mikro-orm#749]
I am using MikroORM with PostGIS. And trying to run a basic query of finding entities within a given radius, using query builder.
The query runs fine when I use the following format for the where clause:
```JS
where(`ST_DWithin(geog, \'SRID=4326;POINT(${req.query.longitude} ${req.query.latitude})\'::geography, 1000)`)
```
However I am getting `parse error - invalid geometry` when I use this format:
```JS
where('ST_DWithin(geog, \'SRID=4326;POINT(? ?)\'::geography, 1000)', [77.612, 12.9922])
```
I am not sure if I am using this correctly or if this is a bug.

Here is how the model is defined:
```JS
@Entity()
export class Business extends BaseEntity {

    @Property({columnType: 'double precision'})
    latitude: number;

    @Property({columnType: 'double precision'})
    longitude: number;

    @Index({type:"GIST"})
    @Property({ columnType: 'GEOGRAPHY(POINT)' })
    geog: string // = "POINT(77.6668863 12.918725)"

    @BeforeCreate()
    async doStuffBeforeCreate() {
        this.geog = `POINT(${this.longitude} ${this.latitude})`
    }
    @BeforeUpdate()
    async doStuffBeforeUpdate() {
        this.geog = `POINT(${this.longitude} ${this.latitude})`
    }
}
```
And, here is the code that queries:
```JS
const qb = DI.orm.em.createQueryBuilder(Business)
// const nearby = await qb.select('*').where(`ST_DWithin(geog, \'SRID=4326;POINT(${req.query.longitude} ${req.query.latitude})\'::geography, 1000)`).getResult()
const nearby = await qb.select('*')
                       .where('ST_DWithin(geog, \'SRID=4326;POINT(? ?)\'::geography, 1000)', [77.612, 12.9922])
                       .limit(10)
                       .getResult()
console.log(nearby)
res.json(nearby)
```

**Stack trace**
```
[query] select "e0".* from "business" as "e0" where (ST_DWithin(geog, 'SRID=4326;POINT(77.612 12.9922)'::geography, 1000)) limit 10 [took 31 ms]
error: select "e0".* from "business" as "e0" where (ST_DWithin(geog, 'SRID=4326;POINT($1 $2)'::geography, 1000)) limit $3 - parse error - invalid geometry
    at Parser.parseErrorMessage (..../node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (..../node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (..../node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (..../node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 168,
  severity: 'ERROR',
  code: 'XX000',
  detail: undefined,
  hint: '"SRID=4326;POINT($1" <-- parse error at position 18 within geometry',
  position: '68',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'lwgeom_pg.c',
  line: '171',
  routine: 'pg_parser_errhint'
}
```

node: v13.13.0
typescript: 3.9.7
mikro-orm: 3.6.15

**Comment by B4nan** [comment]
I am not a postgis user, but I believe postgis works based on WKT - well known text. So it is not a standard query, where you could interpolate your parameters as usual, the whole postgis bit needs to be a string. 

You could try this to verify if it works with knex itself:

```
const res = await qb.getKnexQuery().where('ST_DWithin(geog, \'SRID=4326;POINT(? ?)\'::geography, 1000)', [77.612, 12.9922]);
```

My bet is it won't. 

Here is a related SO question (although about C++ but that is not really important I believe): 

https://stackoverflow.com/questions/25296942/c-postgis-prepared-statement-failing-invalid-geometry

**Comment by iabtyagi** [comment]
I see. Yes, PostGIS works on WKT. 

> the whole postgis bit needs to be a string

That's right. I forgot about that and was looking at it differently.

> My bet is it won't.

It doesn't. Although the error is something else:
```
TypeError: (value || "").toLowerCase is not a function
    at Formatter.operator (.../node_modules/knex/lib/formatter.js:201:46)
```
It's ok. I will use the first syntax, that works fine. I just wanted to know if I am doing something wrong or if it's small bug maybe I can submit a fix.
Thanks a lot, closing it for now.
