### ISSUE TITLE
CLI: Only abstract entities were discovered + Cannot use 'in' operator to search for 'schema'

### ISSUE THREAD

**Issue by quinnturner** [mikro-orm/mikro-orm#759]
**Describe the bug**

Please review the demo: https://github.com/quinnturner/mikro-orm-cli-issue

When using the following config:

```ts
const config: MikroOrmModuleOptions<PostgreSqlDriver> = {
  entities: [EmailIdentity],
  metadataProvider: TsMorphMetadataProvider,
  dbName: process.env.PHOENIX_DATABASE_NAME,
  host: process.env.PHOENIX_DATABASE_HOST,
  password: process.env.PHOENIX_DATABASE_PASSWORD,
  user: process.env.PHOENIX_DATABASE_USER,
  port: process.env.PHOENIX_DATABASE_PORT
    ? parseInt(process.env.PHOENIX_DATABASE_PORT, 10)
    : 5432,
  type: 'postgresql',
  debug: true,
};
```

I receive:

**Stack trace**
```
ValidationError: Only abstract entities were discovered, maybe you forgot to use @Entity() decorator?
    at Function.onlyAbstractEntitiesDiscovered (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/src/utils/ValidationError.ts:120:12)
    at MetadataValidator.validateDiscovered (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/src/metadata/MetadataValidator.ts:43:29)
    at MetadataDiscovery.findEntities (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/src/metadata/MetadataDiscovery.ts:77:20)
    at MetadataDiscovery.discover (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/src/metadata/MetadataDiscovery.ts:31:5)
    at Function.init (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/src/MikroORM.ts:32:20)
    at Function.handleMigrationCommand (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/src/commands/MigrationCommandFactory.ts:77:17) {
  entity: undefined
}
```

Also, just as importantly, when I use the following config:

```

  entities: ['./dist/**/*.entity.js'],
  entitiesTs: ['./src/**/*.entity.ts'],
```

I receive this stack trace when performing:

`npx mikro-orm migration:create -b`

```
TypeError: Cannot use 'in' operator to search for 'schema' in ./dist/**/*.entity.js
    at MetadataDiscovery.prepare (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/src/metadata/MetadataDiscovery.ts:115:17)
    at MetadataDiscovery.discoverEntity (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/src/metadata/MetadataDiscovery.ts:151:19)
    at /Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/src/metadata/MetadataDiscovery.ts:70:73
    at Function.runSerial (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/src/utils/Utils.ts:507:22)
    at MetadataDiscovery.findEntities (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/src/metadata/MetadataDiscovery.ts:70:19)
    at MetadataDiscovery.discover (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/src/metadata/MetadataDiscovery.ts:31:16)
    at Function.init (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/node_modules/@mikro-orm/core/src/MikroORM.ts:32:36)
    at Function.getORM (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/src/CLIHelper.ts:35:21)
    at Function.handleMigrationCommand (/Users/quinn/Dev/Phoenix/packages/server/node_modules/@mikro-orm/cli/src/commands/MigrationCommandFactory.ts:77:17)
```

**To Reproduce**
1. Demo project: https://github.com/quinnturner/mikro-orm-cli-issue
1. `npx mikro-orm schema:generate -d`
OR
1. `npx mikro-orm migration:create -b`

**Expected behavior**
Either generate the schema or create the blank migration file.

**Additional context**

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 3.9 |
    "@mikro-orm/cli": "^4.0.0-alpha.0",
    "@mikro-orm/core": "^4.0.0-rc.1",
    "@mikro-orm/entity-generator": "^4.0.0-alpha.0",
    "@mikro-orm/migrations": "^4.0.0-alpha.0",
    "@mikro-orm/nestjs": "^4.0.0-alpha.3",
    "@mikro-orm/postgresql": "^4.0.0-rc.1",
    "@mikro-orm/reflection": "^4.0.0-rc.1",
    "reflect-metadata": "^0.1.13",
    "ts-loader": "^8.0.2",
    "ts-node": "^8.10.2",
    "tsconfig-paths": "^3.9.0"

**Comment by quinnturner** [comment]
Note, I have successfully `.findOne` data from the database using the schema.

**Comment by B4nan** [comment]
CLI works fine for me, all I did was to align the dependencies. You have `alpha.0` of few packages, while some at `rc.1`.

**Comment by B4nan** [comment]
You were basically testing the very fast alpha version in the CLI. 

Btw you don't need to install entity generator and migrations explicitly, they are part of the CLI package.
