### ISSUE TITLE
"Only abstract entities were discovered, maybe you forgot to use @Entity() decorator?" even though I copy pasted it from website

### ISSUE THREAD

**Issue by divakaivan** [mikro-orm/mikro-orm#777]
Here is a link to my repo: https://github.com/divakaivan/my-reddit-server

I copied the code from a youtube video(posted last week) repo where it works, but for me I get: 

### Only abstract entities were discovered, maybe you forgot to use @Entity() decorator?

Full: 
`
ValidationError: Only abstract entities were discovered, maybe you forgot to use @Entity() decorator?
    at Function.onlyAbstractEntitiesDiscovered (D:\Dev\Code\my-reddit-server\node_modules\mikro-orm\dist\utils\ValidationError.js:91:16)   
    at MetadataValidator.validateDiscovered (D:\Dev\Code\my-reddit-server\node_modules\mikro-orm\dist\metadata\MetadataValidator.js:33:43) 
    at MetadataDiscovery.findEntities (D:\Dev\Code\my-reddit-server\node_modules\mikro-orm\dist\metadata\MetadataDiscovery.js:68:24)       
    at MetadataDiscovery.discover (D:\Dev\Code\my-reddit-server\node_modules\mikro-orm\dist\metadata\MetadataDiscovery.js:31:9)
    at Function.init (D:\Dev\Code\my-reddit-server\node_modules\mikro-orm\dist\MikroORM.js:45:24)
    at Function.handleMigrationCommand (D:\Dev\Code\my-reddit-server\node_modules\mikro-orm\dist\cli\MigrationCommandFactory.js:63:21) {   
  entity: undefined
`

when I run `npx mikro-orm migration:create`

**Comment by B4nan** [comment]
upgrade your project, latest version is `4.0.0-rc.3`, you are using the very first alpha build.

**Comment by divakaivan** [comment]
This is the version that was installed minutes ago from npm install *... mikro orm packages*. Will try it now

**Comment by B4nan** [comment]
You need to install `@next`, not stable.

**Comment by B4nan** [comment]
Also remove the `mikro-orm` metapackage, use `@mikro-orm/core` instead. 

![image](https://user-images.githubusercontent.com/615580/91160213-683f1100-e6c9-11ea-90a9-96f7d0624ed3.png)

**Comment by divakaivan** [comment]
its 4.0.0-rc.3 for all four packages in your above pic ?

**Comment by B4nan** [comment]
Yes, all packages are released together

**Comment by divakaivan** [comment]
ok. this issue has appeared. I get an auth error but this is on my end. Thanks!

**Comment by B4nan** [comment]
One thing to note - you always need to setup the request context (or use manual forking). I haven't watched the tutorial yet, but it feels like Ben did totally ignore this crucial bit. Without that, you might face weird issues.

https://mikro-orm.io/docs/next/installation#request-context
https://mikro-orm.io/docs/next/identity-map#why-is-request-context-needed
