### ISSUE TITLE
MetadataError: Metadata for entity not found

### ISSUE THREAD

**Issue by darkadept** [mikro-orm/mikro-orm#806]
I'm using webpack and babel-typescript to create a bundle of my app. I have a basic entity defined and I'm trying to create a new instance and persist and flush it to the database.

I'm using the directly defined `entities` in the configuration and disabling dynamic file access.

MikroORM seems to detect the entities during discovery, but when I try to get a repository from the entity manager it fails saying the Metadata for my entity was not found.

**Stack trace**
```
$ NODE_ENV=production node dist/index.js
[discovery] ORM entity discovery started, using ReflectMetadataProvider
[discovery] - processing entity MyEnt
[discovery] - processing entity MyPkgEnt
[discovery] - entity discovery finished, found 2 entities, took 9 ms
[info] MikroORM successfully connected to database motest on postgres://postgres:*****@localhost:5432
(node:29751) UnhandledPromiseRejectionWarning: MetadataError: Metadata for entity MyEnt not found
    at Function.missingMetadata (/home/mike/dev/motest/node_modules/@mikro-orm/core/utils/errors.js:139:16)
    at MetadataStorage.get (/home/mike/dev/motest/node_modules/@mikro-orm/core/metadata/MetadataStorage.js:38:41)
    at SqlEntityManager.getRepository (/home/mike/dev/motest/node_modules/@mikro-orm/core/EntityManager.js:48:40)
    at SqlEntityManager.getRepository (/home/mike/dev/motest/node_modules/@mikro-orm/knex/SqlEntityManager.js:24:22)
    at main (/home/mike/dev/motest/packages/app/dist/index.js:233:27)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:29751) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29751) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
Repository here: https://github.com/darkadept/mikro-orm-test

This is from the README.md file in that repo:
1. Install modules: `yarn install`.
2. Copy the `packages/app/default.env` file to `packages/app/.env` and edit it with your database user/pass.
3. Build the `entities` library with `cd packages/entities && yarn build`.
4. Build the `app` with `cd packages/app && yarn build`.
5. Run the app with `cd packages/app && yarn start`.

**Expected behavior**
I expect the 2 entities to be inserted in the database.

**Additional context**
I have my test repo set up to test entities in a separate webpack package, but that is not relevant to this issue. I have 2 entities defined, one directly in my app, the other imported from this separate package. The error occurs in the entity directly defined in the app.

**Versions**

| Dependency | Version |
| - | - |
| node | 12.7.0 |
| typescript | 3.9.7 |
| mikro-orm | 4.0.0-rc.5 |
| @mikro-orm/postgresql | 4.0.0-rc.5 |

**Comment by B4nan** [comment]
> I have my test repo set up to test entities in a separate webpack package, but that is not relevant to this issue.

Actually this is almost certainly the reason why it fails. I see you have `@mikro-orm/core` as a regular dependency in that `entities` packages, but I believe you need to use peer dependency there. You need to make sure there exists only one (shared) installation of `@mikro-orm/core`, without that there will be multiple metadata storages.

**Comment by B4nan** [comment]
Ok, I managed to run it, the issue is connected to the "paths from decorators" thing, the metadata for `MyEnt` were gathered under wrong key. 

```
[discovery] ORM entity discovery started, using ReflectMetadataProvider
[discovery] - processing entity MyEnt
[discovery] - processing entity MyPkgEnt
[discovery] - entity discovery finished, found 2 entities, took 10 ms
[info] MikroORM successfully connected to database ./test.db
[query] begin
[query] insert into `my_pkg_ent` (`id`, `name`) values ('0affe6f9-6d1f-498e-8783-94c169b21aa9', 'Entity 2,') [took 1 ms]
[query] insert into `my_ent` (`id`, `name`) values ('b1810114-6056-4af5-bbd9-75a717f6f7a1', 'Entity 1') [took 0 ms]
[query] commit
Application complete
```

Will be fixed in `rc.7`.
