### ISSUE TITLE
 Please provide either 'type' or 'entity' attribute in Payment.id

### ISSUE THREAD

**Issue by VictorKoenders** [mikro-orm/mikro-orm#841]
**Describe the bug**

After updating to mikro-orm 4.0.0, I keep getting the following runtime error:
`Please provide either 'type' or 'entity' attribute in Payment.id`

Whenever I give that field a type, it will go onto the next field. It seems like this happens to every field of every object I have.

I'm not sure if this is a breaking change on 4.0.0 or an actual bug, but I cannot find any documentation on what to do to fix this issue.

**Stack trace**
```
    Please provide either 'type' or 'entity' attribute in Payment.id

      113 |     }
      114 |
    > 115 |     const orm = await MikroORM.init(config);
          |                 ^
      116 |
      117 |     DI.orm = orm;
      118 |     DI.em = DI.orm.em;

      at ReflectMetadataProvider.initPropertyType (node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:14:19)
      at node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:9:54
      at ReflectMetadataProvider.initProperties (node_modules/@mikro-orm/core/metadata/MetadataProvider.js:26:23)
      at ReflectMetadataProvider.loadEntityMetadata (node_modules/@mikro-orm/core/metadata/ReflectMetadataProvider.js:9:20)
      at MetadataDiscovery.discoverEntity (node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:165:41)
      at MetadataDiscovery.discoverReferences (node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:116:24)
      at MetadataDiscovery.findEntities (node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:67:20)
      at MetadataDiscovery.discover (node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:33:9)
      at Function.init (node_modules/@mikro-orm/core/MikroORM.js:40:24)
      at Object.configure (src/database.ts:115:14)
      at Object.<anonymous> (src/api/users.test.ts:90:2)
```

**To Reproduce**
See the build logs at https://github.com/pixelbar/pixelbank/pull/37/checks?check_run_id=1100262152
The source code is at:
- https://github.com/pixelbar/pixelbank/blob/master/server/src/database.ts#L83
- https://github.com/pixelbar/pixelbank/blob/master/server/src/models/payment.ts

**Versions**

| Dependency | Version |
| - | - |
| node | v14.9.0 |
| typescript | 4.0.2, or whatever is installed on github actions |
| mikro-orm | 4.0.0 through 4.0.3 |
| your-driver | sqlite |

**Comment by B4nan** [comment]
Sounds like you are missing the reflect metadata import, but that will help only with scalars, not relations. 

Or use ts-morph, default metadata provider changed in v4.

**Comment by VictorKoenders** [comment]
That was indeed what was wrong.

For anyone running into this issue, this is the relevant chapter in the documentation: https://mikro-orm.io/docs/installation/#entity-discovery-in-typescript

You need to install `@mikro-orm/reflection` and add this to your init:
```javascript
import { TsMorphMetadataProvider } from '@mikro-orm/reflection';

const orm = await MikroORM.init({
  metadataProvider: TsMorphMetadataProvider,
  // ...
});
```

**Comment by patarapolw** [comment]
But I want to use `ReflectMetadataProvider`.

Though, it throws no error with `TsMorphMetadataProvider `.

Of course, I didn't forget to import `reflect-metadata`.
