### ISSUE TITLE
Compound (unique) indices on foreign key (generated column names) result in error

### ISSUE THREAD

**Issue by patarapolw** [mikro-orm/mikro-orm#850]
**Describe the bug**

I have no idea how to declare an entity like this (which doesn't work).

```ts
@Entity()
@Unique({ properties: ['user', 'note', 'template'] })
class Quiz {
  @ManyToOne({ nullable: false })
  user!: User

  @ManyToOne({ nullable: false })
  note!: Note

  @ManyToOne({ nullable: false })
  template!: Template
}
```

**Expected behavior**

It should somehow works.

**Suggested feature, if possible**

Maybe you would create something like

```ts
@CompoundUnique<Quiz>({ properties: ['user', 'note', 'template'] /* (keyof Quiz)[] */ })
```

which is typesafe.

**Versions**

| Dependency | Version |
| - | - |
| node | v12.16.3 |
| typescript | 4.0.2 |
| mikro-orm | 4.0.3 |
| your-driver | both mongodb and SQLite (I am trying to make dual server / Electron) |

However, I am currently testing on SQLite, which is much more strict.

**Comment by B4nan** [comment]
Uh, what? Can you at least say what is not working for you? Your entity has no PK, otherwise it looks valid. The unique key definition like this is supported.

**Comment by B4nan** [comment]
Schema diffing does not support compound indexes/uniques, so that is probably what you are talking about. But you failed to mention that you are actually using schema diffing or migrations, you just state "its not working" 🤷

**Comment by patarapolw** [comment]
I create a new SQLite database using `await orm.getSchemaGenerator().createSchema()`, not really via CLI, so that might satisfy as migration.

I created [a minimal producible repo](https://github.com/patarapolw/mikro-compound), and [this file](https://github.com/patarapolw/mikro-compound/blob/master/src/schema/NoteAttr.ts) is the culprit.

```ts
import { Entity, ManyToOne, PrimaryKey, Property, Unique } from '@mikro-orm/core'

import { Note } from './Note'

export interface INoteAttr {
  key: string
  value: string
  note: Note
}

@Entity()
@Unique({ properties: ['key', 'note'] })
export class NoteAttr implements INoteAttr {
  @PrimaryKey()
  id!: number

  @Property({ nullable: false })
  key!: string

  @Property({ nullable: false })
  value!: string

  @ManyToOne({ nullable: false })
  note!: Note

  constructor (d: INoteAttr) {
    Object.assign(this, d)
  }
}
```

The error is

```
yarn run v1.22.5
$ ts-node src/index.ts
InvalidFieldNameException: create unique index `note_attr_key_note_id_unique` on `note_attr` (`key`, `note_id`); - SQLITE_ERROR: no such column: note_id
    at SqliteExceptionConverter.convertException (/Users/patarapolw/projects/mikro-compound/node_modules/@mikro-orm/sqlite/SqliteExceptionConverter.js:32:20)
    at SqliteDriver.convertException (/Users/patarapolw/projects/mikro-compound/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:168:54)
    at /Users/patarapolw/projects/mikro-compound/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:172:24
    at SchemaGenerator.execute (/Users/patarapolw/projects/mikro-compound/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:108:13)
    at SchemaGenerator.createSchema (/Users/patarapolw/projects/mikro-compound/node_modules/@mikro-orm/knex/schema/SchemaGenerator.js:27:9)
    at initDatabase (/Users/patarapolw/projects/mikro-compound/src/index.ts:23:5)
    at main (/Users/patarapolw/projects/mikro-compound/src/index.ts:32:3)

previous Error: create unique index `note_attr_key_note_id_unique` on `note_attr` (`key`, `note_id`); - SQLITE_ERROR: no such column: note_id {
  errno: 1,
  code: 'SQLITE_ERROR'
}
```

I can see that it tried to use `note_id` instead of `note`, but unsuccessfully.

**Comment by patarapolw** [comment]
So, I `console.log(await gen.generate())`, and got unexpected orders (and also drop tables when I actually want to create tables if not exist).

```ts
    const gen = orm.getSchemaGenerator()
    console.log(await gen.generate())
    await gen.createSchema()
```

```sql
pragma foreign_keys = off;

drop table if exists `deck`;
drop table if exists `user_notes`;
drop table if exists `quiz`;
drop table if exists `note_attr`;
drop table if exists `note`;
drop table if exists `user_templates`;
drop table if exists `template`;
drop table if exists `user`;

create table `user` (`id` varchar not null, `name` varchar not null, `email` varchar not null, `api_key` varchar not null, primary key (`id`));
create unique index `user_email_unique` on `user` (`email`);

create table `template` (`id` varchar not null, `name` varchar not null, `description` varchar null, `front` varchar not null, `back` varchar null, primary key (`id`));
create index `template_name_index` on `template` (`name`);

create table `user_templates` (`user_id` varchar not null, `template_id` varchar not null, primary key (`user_id`, `template_id`));
create index `user_templates_user_id_index` on `user_templates` (`user_id`);
create index `user_templates_template_id_index` on `user_templates` (`template_id`);

create table `note` (`id` varchar not null, primary key (`id`));

create table `note_attr` (`id` varchar not null, `key` varchar not null, `value` varchar not null, primary key (`id`));
create unique index `note_attr_key_note_id_unique` on `note_attr` (`key`, `note_id`);

create table `quiz` (`id` varchar not null, `front` varchar null, `back` varchar null, `mnemonic` varchar null, `srs_level` integer null, `next_review` DATE(undefined) null, `right_streak` integer null, `wrong_streak` integer null, `max_right` integer null, `max_wrong` integer null, `last_right` DATE(undefined) null, `last_wrong` DATE(undefined) null, primary key (`id`));
create index `quiz_srs_level_index` on `quiz` (`srs_level`);
create index `quiz_next_review_index` on `quiz` (`next_review`);
create index `quiz_wrong_streak_index` on `quiz` (`wrong_streak`);
create index `quiz_max_wrong_index` on `quiz` (`max_wrong`);
create index `quiz_last_wrong_index` on `quiz` (`last_wrong`);
create unique index `quiz_user_id_note_id_template_id_unique` on `quiz` (`user_id`, `note_id`, `template_id`);

create table `user_notes` (`user_id` varchar not null, `note_id` varchar not null, primary key (`user_id`, `note_id`));
create index `user_notes_user_id_index` on `user_notes` (`user_id`);
create index `user_notes_note_id_index` on `user_notes` (`note_id`);

create table `deck` (`id` varchar not null, `name` TEXT not null, primary key (`id`));
create unique index `deck_name_unique` on `deck` (`name`);

alter table `note_attr` add column `note_id` varchar null;
create index `note_attr_note_id_index` on `note_attr` (`note_id`);

alter table `quiz` add column `user_id` varchar null;
alter table `quiz` add column `note_id` varchar null;
alter table `quiz` add column `template_id` varchar null;
create index `quiz_user_id_index` on `quiz` (`user_id`);
create index `quiz_note_id_index` on `quiz` (`note_id`);
create index `quiz_template_id_index` on `quiz` (`template_id`);

pragma foreign_keys = on;
```

**Comment by B4nan** [comment]
`generate()` is an alias for `drop + create`. Order of processed entities is based on the relations.

Ok I see, so the issue is that the index query comes before the column is created.

**Comment by patarapolw** [comment]
For quickfix, I will take a peek at `gen.getCreateSchemaSQL()`, and edit it, so it will become,

```ts
  const gen = orm.getSchemaGenerator()

  try {
    if (isMongo) {
      await gen.createSchema()
    } else {
      await gen.execute('...')
    }
  } catch (_) {}
```

Is there a better way to ensure indices in Mongo, and ensure tables with constraints in SQLite?

**Comment by B4nan** [comment]
SchemaGenerator is SQL only thing, there is support for mongo.

**Comment by patarapolw** [comment]
I identified two more errors.

First one is, what is the proper way to do SQL parsing? Only removing the commented lines will clear the errors.

```ts
  const isExists = type === 'sqlite' ? fs.existsSync(dbString) : true
  const orm = await MikroORM.init(opts)

  if (type === 'sqlite') {
    if (!isExists) {
      const gen = orm.getSchemaGenerator()
      // console.log(await gen.getCreateSchemaSQL())
      await gen
        .execute(
          fs.readFileSync(path.resolve(__dirname, './schema/sqlite.sql'), 'utf8')
          // .replace(/\n/g, ' ')
          // .replace(/;/g, ';\n')
        )
    }
  }
```

Second one is an issue with circular references. I cannot find a way around it.

```ts
import crypto from 'crypto'

import { Collection, Entity, ManyToMany, MikroORM, PrimaryKey, Property, Unique } from '@mikro-orm/core'
import { Ulid } from 'id128'

import { Note } from './Note'
// import { Quiz } from './Quiz'
import { Template } from './Template'

export interface IUser {
  name: string
  email: string
}

@Entity()
export class User implements IUser {
  @PrimaryKey()
  _id: string = Ulid.generate().toCanonical()

  @Property({ nullable: false })
  name!: string

  @Property({ nullable: false })
  @Unique()
  email!: string

  @ManyToMany({ entity: () => Note, inversedBy: 'users' })
  notes = new Collection(Note)

  // @OneToMany(() => Quiz, (q) => q.user)
  // quizzes = new Collection(Quiz)

  @ManyToMany({ entity: () => Template, inversedBy: 'users' })
  templates = new Collection(Template)

  constructor (d: IUser) {
    Object.assign(this, d)
  }
}
```

**Comment by patarapolw** [comment]
> it should be `notes = new Collection(this)`

Thanks, it works now.
