### ISSUE TITLE
Migration ORM init requires passing entities

### ISSUE THREAD

**Issue by lewispham** [mikro-orm/mikro-orm#875]
**Describe the bug**
I'm trying to run some migrations completely via SQL scripts passing into method `addSql`. But initializing the connection to database requires having options `entities` passed into `orm.init`. I think it's a bit redundant.

**Stack trace**
```
(node:34) UnhandledPromiseRejectionWarning: Error: No entities found, please use `entities` option
    at Configuration.validateOptions (/app/node_modules/@mikro-orm/core/utils/Configuration.js:134:19)
    at new Configuration (/app/node_modules/@mikro-orm/core/utils/Configuration.js:21:18)
    at new MikroORM (/app/node_modules/@mikro-orm/core/MikroORM.js:20:27)
    at Function.init (/app/node_modules/@mikro-orm/core/MikroORM.js:38:21)
    at Migrations.start (/app/src/components/apps/migrations/Migrations.ts:17:36)
    at /app/src/app.ts:15:8
    at Object.<anonymous> (/app/src/app.ts:21:3)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Module._compile (/app/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-4195075166508704.js:57:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-4195075166508704.js:59:20)
    at Object.nodeDevHook [as .ts] (/app/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19)
```

**To Reproduce**
```
        const orm = await MikroORM.init({
            migrations: {
                tableName: "migrations", // name of database table with log of executed transactions
                transactional: true, // wrap each migration in a transaction
                disableForeignKeys: true, // wrap statements with `set foreign_key_checks = 0` or equivalent
                allOrNothing: true, // wrap all migrations in master transaction
                dropTables: true, // allow to disable table dropping
                safe: false, // allow to disable table and column dropping
                emit: "ts", // migration generation mode,
                migrationsList
            },
            type: "mariadb",
            dbName: "main",
            host: "localhost",
            port: 3306,
            user: "root",
            password: "12345678"
        });
        const migrator = orm.getMigrator();
        await migrator.up();
        await orm.close(true);
```
**Expected behavior**
no error happens

**Versions**
4.0.7

**Comment by B4nan** [comment]
You can disable that validation via `discovery: { warnWhenNoEntities: false }`.

> I think it's a bit redundant.

It is there because there were quite a lot of people who had the folder based discovery set up wrongly, and without debug mode enabled you would not see what is wrong, but doing anything with entities would cause "Metadata for entity abc ... found".

**Comment by lewispham** [comment]
ah ok. I guess it only happens when they're using 1 single orm instance for both migrations and API db queries. I think in the case of running migrations, entities shouldn't be involved. I'm actual using 2 separated orm instances. One for running migrations, the other for handling db queries from API server. I also prefer not to use ORM style for db migrations since SQL scripts for DDL a bit more readable and debuggable IMHO. Thanks for the hint Martin.
