### ISSUE TITLE
Metadata discovery with glob can't find entity with class name of "BaseEntity"

### ISSUE THREAD

**Issue by squareloop1** [mikro-orm/mikro-orm#897]
**Describe the bug**
When using glob for the metadata discovery like this
```
entities: ['dist/**/*.entity.js'],
entitiesTs: ['src/**/*.entity.ts'],
```
the following error is thrown: `MetadataError: Entity 'Base' not found in ./dist/common/base.entity.js`
The class name of the base entity is `BaseEntity`. When renaming the class to just `Base` it is working without any errors.

**Stack trace**
```
MetadataError: Entity 'Base' not found in ./dist/common/base.entity.js
    at Function.entityNotFound (/home/redacted/server/node_modules/@mikro-orm/core/errors.js:108:16)
    at MetadataDiscovery.getEntityClassOrSchema (/home/redacted/server/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:634:42)
    at MetadataDiscovery.discoverDirectories (/home/redacted/server/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:98:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async MetadataDiscovery.findEntities (/home/redacted/server/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:73:9)
    at async MetadataDiscovery.discover (/home/redacted/server/node_modules/@mikro-orm/core/metadata/MetadataDiscovery.js:34:9)
    at async Function.init (/home/redacted/server/node_modules/@mikro-orm/core/MikroORM.js:40:24)
    at async Injector.instantiateClass (/home/redacted/server/node_modules/@nestjs/core/injector/injector.js:294:37)
    at async callback (/home/redacted/server/node_modules/@nestjs/core/injector/injector.js:77:30)
    at async Injector.resolveConstructorParams (/home/redacted/server/node_modules/@nestjs/core/injector/injector.js:118:24)
```

**To Reproduce**
1. Have a base entity `base.entity.ts` with the class name `BaseEntity` and extend an entity with it.
2. Start app
3. See error in the console

**Expected behavior**
Metadata discovery should be able to find the class.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.11.0 |
| typescript | 4.0.2 |
| mikro-orm | 4.0.7 |
| your-driver | postgresql |

**Comment by royalcala** [comment]
hello @squareloop1, did you check defining baseDir?, maybe your path is pointing at node_modules at the package of the mikro-orm:
```
entities: ['dist/**/*.entity.js'],
   baseDir: __dirname,
```

**Comment by B4nan** [comment]
This is actually correct/expected/documented behaviour. Everything after the first dot is ignored from the file name. If your entity is called `BaseEntity`, your file name should be one of:

- `BaseEntity.ts`
- `base-entity.ts`
- `base-entity.entity.ts`
- `base-entity.*.ts`
- ...

You can override how this works via custom naming strategy.

We could probably to get around this limitation and base the entity name only on the usage of `@Entity` decorator, but that would require new decorator on base entities, which would be a breaking change, so no plans to change that now.

**Comment by squareloop1** [comment]
Alright, I'm fine if it can be customized in the naming strategy. Thanks for the information.
