### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by 0ttik** [mikro-orm/mikro-orm#899]
**Describe the bug**
Neither it builds schema with the cli nor inializes MirkroOrm.init() in code. 

**Stack trace**
```
[1601824873062] ERROR (3448 on DESKTOP-6MRTK56): Cannot read property 'length' of undefined
    TypeError: Cannot read property 'length' of undefined
        at MetadataDiscovery.initIndexes (C:\Users\username\Desktop\projectname_backend_v3\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:616:38)
        at C:\Users\username\Desktop\projectname_backend_v3\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:55:45
        at Array.forEach (<anonymous>)
        at C:\Users\username\Desktop\projectname_backend_v3\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:55:24
        at Array.forEach (<anonymous>)
        at MetadataDiscovery.discover (C:\Users\username\Desktop\projectname_backend_v3\node_modules\@mikro-orm\core\metadata\MetadataDiscovery.js:50:25)
        at async Function.init (C:\Users\username\Desktop\projectname_backend_v3\node_modules\@mikro-orm\core\MikroORM.js:40:24)
        at async C:\Users\username\Desktop\projectname_backend_v3\dist\plugins\mikro-orm-init.js:10:17

```

**To Reproduce**
1. go to repo https://github.com/0ttik/mikro-orm-error-repoduction
2. run `npx mikro-orm schema:create -d` or `npm run debug`
3. get the error

**Expected behavior**
If it is something up with my entitiy definition, it would be better to get more instuctive error message. 

**Additional context**
My guess is it some internal error since it asks an undefined property at MetadataDiscovery.js but I have 0 clue what is going on inside tho. 

**Versions**

| Dependency | Version |
| - | - |
| node | 12 LTS - last release |
| typescript | look ex. |
| mikro-orm | since 4.0.5 (4.0.4  does not have this error) |
| your-driver | mysql |

**Comment by 0ttik** [comment]
oh, god. I'm omega sorry for that I've just written `Entity()` instead of `@Entity()` before class declaration such a shame
