### ISSUE TITLE
Enum issue with Postgres

### ISSUE THREAD

**Issue by michaelkimball** [mikro-orm/mikro-orm#904]
**Describe the bug**
When creating a migration with an enum type on my entity it adds a strange constraint that causes all `persist()` calls to fail. This is the constraint that is added to Postgres:
```
Check constraints:
    "oas_type_check" CHECK (type = ''::text)
```

**Stack trace**
```
docserver_1     | [query] insert into "oas" ("created_at", "iteration", "major_version", "name", "type", "url_retrieved_from") values ('2020-10-06 16:43:48.668', 1, 0, '****', 1, 'https://****') returning "id" [took 2 ms]
docserver_1     | [query] rollback
docserver_1     | {"length":295,"name":"DriverException","severity":"ERROR","code":"23514","detail":"Failing row contains (1, 2020-10-06 16:43:49+00, ****, 1, 0, 1, https://****).","schema":"public","table":"oas","constraint":"oas_type_check","file":"execMain.c","line":"2009","routine":"ExecConstraints","level":"error"}
docserver_1     | (node:59) UnhandledPromiseRejectionWarning: DriverException: insert into "oas" ("created_at", "iteration", "major_version", "name", "type", "url_retrieved_from") values ($1, $2, $3, $4, $5, $6) returning "id" - new row for relation "oas" violates check constraint "oas_type_check"
docserver_1     |     at PostgreSqlExceptionConverter.convertException (/home/node/node_modules/@mikro-orm/core/platforms/ExceptionConverter.js:8:16)
docserver_1     |     at PostgreSqlExceptionConverter.convertException (/home/node/node_modules/@mikro-orm/postgresql/PostgreSqlExceptionConverter.js:40:22)
docserver_1     |     at PostgreSqlDriver.convertException (/home/node/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:168:54)
docserver_1     |     at /home/node/node_modules/@mikro-orm/core/drivers/DatabaseDriver.js:172:24
docserver_1     |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
docserver_1     |     at PostgreSqlDriver.nativeInsert (/home/node/node_modules/@mikro-orm/knex/AbstractSqlDriver.js:144:21)
docserver_1     |     at ChangeSetPersister.persistNewEntity (/home/node/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:52:21)
docserver_1     |     at ChangeSetPersister.executeInserts (/home/node/node_modules/@mikro-orm/core/unit-of-work/ChangeSetPersister.js:23:13)
docserver_1     |     at UnitOfWork.commitCreateChangeSets (/home/node/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:440:9)
docserver_1     |     at UnitOfWork.persistToDatabase (/home/node/node_modules/@mikro-orm/core/unit-of-work/UnitOfWork.js:403:13)
docserver_1     | 
docserver_1     | previous error: insert into "oas" ("created_at", "iteration", "major_version", "name", "type", "url_retrieved_from") values ($1, $2, $3, $4, $5, $6) returning "id" - new row for relation "oas" violates check constraint "oas_type_check"
docserver_1     |     at Parser.parseErrorMessage (/home/node/node_modules/pg-protocol/src/parser.ts:357:11)
docserver_1     |     at Parser.handlePacket (/home/node/node_modules/pg-protocol/src/parser.ts:186:21)
docserver_1     |     at Parser.parse (/home/node/node_modules/pg-protocol/src/parser.ts:101:30)
docserver_1     |     at Socket.<anonymous> (/home/node/node_modules/pg-protocol/src/index.ts:7:48)
docserver_1     |     at Socket.emit (events.js:315:20)
docserver_1     |     at Socket.EventEmitter.emit (domain.js:483:12)
docserver_1     |     at addChunk (_stream_readable.js:295:12)
docserver_1     |     at readableAddChunk (_stream_readable.js:271:9)
docserver_1     |     at Socket.Readable.push (_stream_readable.js:212:10)
docserver_1     |     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
docserver_1     | (node:59) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**To Reproduce**
1. Create an entity with an enum connected to Postgres
2. Try to persist that entity
3. Receive error

**Expected behavior**
I expect the entity to persist

**Additional context**

Here is my enum:
```
export enum OASType {
  ORIGINAL,
  TRANSFORMED,
}
```
This is how I reference it in my entity class:
```
  @Enum()
  type!: OASType;
```
It is in the same file.

**Versions**

| Dependency | Version |
| - | - |
| node | 14.7.0 |
| typescript | 4.0.3 |
| mikro-orm | 4.0.7 |
| @mikro-orm/postgresql | 4.0.7 |

**Comment by B4nan** [comment]
You need to define the enum like this:

```ts
  @Enum(() => OASType)
  type!: OASType;
```

Btw the enum like this is numeric, not sure what you want, but this would be stored as number. 

Or use ts-morph provider that can handle it automatically. 

You will also need to fix your schema.
