### ISSUE TITLE
JSON.stringify gives __meta error when entitiy has relation that references its parent

### ISSUE THREAD

**Issue by Langstra** [mikro-orm/mikro-orm#956]
**Describe the bug**
Organization has Teams (1:m), and a Team has an ORganization (m:1). When fetching an organization, then loading the teams, then JSON.stringify(organization) gives an error.

**Stack trace**
```
[Nest] 181203   - 10/23/2020, 5:28:09 PM   [ExceptionsHandler] Cannot read property '__meta' of undefined +4975ms
TypeError: Cannot read property '__meta' of undefined
    at Collection.getIdentifiers (/home/langstra/Documents/mikro-orm-issue/node_modules/@mikro-orm/core/entity/ArrayCollection.js:42:78)
    at Function.processCollection (/home/langstra/Documents/mikro-orm-issue/node_modules/@mikro-orm/core/entity/EntityTransformer.js:175:24)
    at Function.processProperty (/home/langstra/Documents/mikro-orm-issue/node_modules/@mikro-orm/core/entity/EntityTransformer.js:148:38)
    at /home/langstra/Documents/mikro-orm-issue/node_modules/@mikro-orm/core/entity/EntityTransformer.js:108:43
    at Array.map (<anonymous>)
    at Function.toObject (/home/langstra/Documents/mikro-orm-issue/node_modules/@mikro-orm/core/entity/EntityTransformer.js:103:14)
    at Organization.prototype.toJSON (/home/langstra/Documents/mikro-orm-issue/node_modules/@mikro-orm/core/entity/EntityHelper.js:27:62)
    at JSON.stringify (<anonymous>)
    at stringify (/home/langstra/Documents/mikro-orm-issue/node_modules/express/lib/response.js:1123:12)

```

**To Reproduce**
1. git clone https://github.com/RiskChallenger/mikro-orm-meta-error
2. yarn
3. yarn start
4. Go to http://localhost:3000

**Versions**

| Dependency | Version |
| - | - |
| node | 14 |
| typescript | 3.9.7 |
| mikro-orm | 4.2.2 |
| sqlite | 5.0.0 |
| nestjs | 7 |

**Comment by B4nan** [comment]
Workaround is to use `populate` instead of `init`: 

```ts
const org = await this.organizationRepository.findById(1);
await this.organizationRepository.populate(org, ['teams']);
return org;
```

It's probably also closer to what you want, as calling `coll.init()` would not make any difference on the serialized response of your API - that just loads the collection, without making it populated (and therefore part of the response). You would have to call `coll.populated()` to make it part of the response.

**Comment by B4nan** [comment]
> It's probably also closer to what you want, as calling coll.init() would not make any difference on the serialized response of your API - that just loads the collection, without making it populated (and therefore part of the response). You would have to call coll.populated() to make it part of the response.

Sorry for confusion, this is not 100% correct. The collection will be represented as array of PKs if you uses `init`, to have array of DTOs it is needed to use the `populated()` method or `em.populate()`.
