### ISSUE TITLE
ValidationError: Child2.rel is not initialized, define it as 'rel = new Collection<Child1Specific>(this);' when using STI and 'problematic' relation is defined on other child

### ISSUE THREAD

**Issue by whocaresk** [mikro-orm/mikro-orm#997]
**Describe the bug**
When querying table, that uses STI, with `QueryBuilder` things broke up and orm starts complaining about uninitialized relation, although it is initialized and defined, but on other children 

**Stack trace**
```
ValidationError: Child2.rel is not initialized, define it as 'rel = new Collection<Child1Specific>(this);'

    at Function.fromCollectionNotInitialized (/home/k/WebstormProjects/mikro-orm/packages/core/src/errors.ts:32:12)
    at EntityValidator.validateCollection (/home/k/WebstormProjects/mikro-orm/packages/core/src/entity/EntityValidator.ts:106:29)
    at /home/k/WebstormProjects/mikro-orm/packages/core/src/entity/EntityValidator.ts:13:14
    at Array.forEach (<anonymous>)
    at EntityValidator.validate (/home/k/WebstormProjects/mikro-orm/packages/core/src/entity/EntityValidator.ts:11:16)
    at SqlEntityManager.merge (/home/k/WebstormProjects/mikro-orm/packages/core/src/EntityManager.ts:479:20)
    at SqlEntityManager.map (/home/k/WebstormProjects/mikro-orm/packages/core/src/EntityManager.ts:446:17)
    at /home/k/WebstormProjects/mikro-orm/packages/knex/src/query/QueryBuilder.ts:389:34
    at Array.map (<anonymous>)
    at QueryBuilder.getResultList (/home/k/WebstormProjects/mikro-orm/packages/knex/src/query/QueryBuilder.ts:389:16)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.<anonymous> (/home/k/WebstormProjects/mikro-orm/tests/issues/GH8455.test.ts:93:21)
```

**To Reproduce**
1. Run test case GH997.test.ts

**Expected behavior**
Should work like it works without `QueryBuilder`

**Versions**

| Dependency | Version |
| - | - |
| node | v12.14.1 |
| typescript | 4.0.5 |
| mikro-orm | 4.2 |
| mysql | dunno |

**Comment by B4nan** [comment]
You can test it before the actual release via `4.2.4-dev.71` (playing around with nightlies curretly, in future this will be shipped around 6 am, but now you are lucky enough to have it right after build :P).

**Comment by whocaresk** [comment]
> You can test it before the actual release via `4.2.4-dev.71` (playing around with nightlies curretly, in future this will be shipped around 6 am, but now you are lucky enough to have it right after build :P).

Great! I'll check it later today :)
